CREATE TABLE K7_LK.ABONENT_ADD_INFO (
  CONTRACT_ID INTEGER CONSTRAINT PK_ABONENT_ADD_INFO PRIMARY KEY,
  Name varchar2(100 char) not null, 
  EMAIL varchar2(100 char),
  BirthDay date,
  PASSPORT varchar2(250 char),
  KeyWORD varchar2(250 char)
);
/
COMMENT ON TABLE K7_LK.ABONENT_ADD_INFO IS 'Дополнительная информация абонента';
/
COMMENT ON COLUMN K7_LK.ABONENT_ADD_INFO.CONTRACT_ID IS 'Ид контракта';
/
COMMENT ON COLUMN K7_LK.ABONENT_ADD_INFO.Name IS 'Имя абонента';
/
COMMENT ON COLUMN K7_LK.ABONENT_ADD_INFO.EMAIL IS 'Email';
/
COMMENT ON COLUMN K7_LK.ABONENT_ADD_INFO.BirthDay IS 'Дата рождения';
/
COMMENT ON COLUMN K7_LK.ABONENT_ADD_INFO.PASSPORT IS 'Паспортные данные';
/
COMMENT ON COLUMN K7_LK.ABONENT_ADD_INFO.KeyWORD IS 'Кодовое слово';
/
