CREATE TABLE K7_LK.PASSWORD_RESET_LOGS
(
  ID               NUMBER(38)                   NOT NULL PRIMARY KEY, 
  USER_ID          NUMBER(38),
  SMS_SEND_RESULT  VARCHAR2(250 CHAR),
  CREATED_AT       DATE                         NOT NULL,
  UPDATED_AT       DATE                         NOT NULL
);
/

CREATE INDEX K7_LK.I_PAS_RES_LOG_USE_ID_CRE_AT ON K7_LK.PASSWORD_RESET_LOGS (USER_ID, CREATED_AT);
/

COMMENT ON TABLE K7_LK.PASSWORD_RESET_LOGS IS 'Лог сброса паролей';
/
COMMENT ON COLUMN K7_LK.PASSWORD_RESET_LOGS.ID IS 'Ид записи';
/
COMMENT ON COLUMN K7_LK.PASSWORD_RESET_LOGS.USER_ID IS 'Ид пользователя';
/
COMMENT ON COLUMN K7_LK.PASSWORD_RESET_LOGS.SMS_SEND_RESULT IS 'Результат отправки смс';
/
COMMENT ON COLUMN K7_LK.PASSWORD_RESET_LOGS.CREATED_AT IS 'Дата создания';
/
COMMENT ON COLUMN K7_LK.PASSWORD_RESET_LOGS.UPDATED_AT IS 'Дата обновления';
/
CREATE SEQUENCE K7_LK.PASSWORD_RESET_LOGS_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
