CREATE TABLE K7_LK.SIMPLE_CAPTCHA_DATA
(
  ID          NUMBER(38)                        NOT NULL PRIMARY KEY,
  KEY         VARCHAR2(40 CHAR),
  VALUE       VARCHAR2(6 CHAR),
  CREATED_AT  DATE                              NOT NULL,
  UPDATED_AT  DATE                              NOT NULL
);
/

CREATE INDEX K7_LK.IDX_KEY ON K7_LK.SIMPLE_CAPTCHA_DATA(KEY);
/

COMMENT ON TABLE K7_LK.SIMPLE_CAPTCHA_DATA IS 'Таблицы для работы с капчей';
/

COMMENT ON COLUMN K7_LK.SIMPLE_CAPTCHA_DATA.ID IS 'Ид записи';
/
COMMENT ON COLUMN K7_LK.SIMPLE_CAPTCHA_DATA.KEY IS 'хэшь';
/
COMMENT ON COLUMN K7_LK.SIMPLE_CAPTCHA_DATA.VALUE IS 'Значение капчи';
/
COMMENT ON COLUMN K7_LK.SIMPLE_CAPTCHA_DATA.CREATED_AT IS 'дата создания';
/
COMMENT ON COLUMN K7_LK.SIMPLE_CAPTCHA_DATA.UPDATED_AT IS 'дата обновления';
/
CREATE SEQUENCE K7_LK.SIMPLE_CAPTCHA_DATA_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
