CREATE TABLE K7_LK.TARIFF_OPTION_ADD_INFO (
  TARIFF_OPTION_ID INTEGER CONSTRAINT PK_TARIFF_OPTION_ADD_INFO PRIMARY KEY,
  CATEGORY_NAME VARCHAR2(100 CHAR),
  DESCRIPTION  VARCHAR2(4000 CHAR)
);
/
COMMENT ON TABLE K7_LK.TARIFF_OPTION_ADD_INFO IS 'Дополнительная информация об услугах';
/
COMMENT ON COLUMN K7_LK.TARIFF_OPTION_ADD_INFO.TARIFF_OPTION_ID IS 'Ид опции из таблици CORP_MOBILE.TARIFF_OPRIONS';
/
COMMENT ON COLUMN K7_LK.TARIFF_OPTION_ADD_INFO.CATEGORY_NAME IS 'Название категории';
/
COMMENT ON COLUMN K7_LK.TARIFF_OPTION_ADD_INFO.DESCRIPTION IS 'Расшифровка';
/