CREATE TYPE TARIFF_REST_ROW_TYPE AS OBJECT
(
  PHONE_NUMBER VARCHAR2(10 CHAR)
 ,UNIT_TYPE    VARCHAR2(50 CHAR)
 ,REST_TYPE    VARCHAR2(50 CHAR)
 ,INITIAL_SIZE NUMBER(18,2)
 ,CURR_VALUE   NUMBER(18,2)
 ,NEXT_VALUE   NUMBER(18,2)
 ,FREQUENCY    VARCHAR2(16 CHAR)
 ,SOC          VARCHAR2(16 CHAR)
 ,SOC_NAME     VARCHAR2(1024 CHAR)
 ,REST_NAME    VARCHAR2(2048 CHAR)
);
/

CREATE OR REPLACE TYPE TARIFF_REST_ROW_TAB AS TABLE OF TARIFF_REST_ROW_TYPE;
/