ALTER TABLE IVIDEON.ABONENT_BLOCK_UNLOCK
 DROP PRIMARY KEY CASCADE;

DROP TABLE IVIDEON.ABONENT_BLOCK_UNLOCK CASCADE CONSTRAINTS;

CREATE TABLE IVIDEON.ABONENT_BLOCK_UNLOCK
(
  ABONENT_ID         INTEGER                    NOT NULL,
  ABONENT_IS_ACTIVE  INTEGER                    NOT NULL,
  BALANCE            NUMBER(10,2)               DEFAULT 0                     NOT NULL,
  USER_CREATED       VARCHAR2(30 BYTE)          NOT NULL,
  DATE_CREATED       DATE                       NOT NULL,
  USER_LAST_UPDATED  VARCHAR2(30 BYTE)          NOT NULL,
  DATE_LAST_UPDATED  DATE                       NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE IVIDEON.ABONENT_BLOCK_UNLOCK IS 'Текущий статус абонента';

COMMENT ON COLUMN IVIDEON.ABONENT_BLOCK_UNLOCK.ABONENT_ID IS 'Идентификатор пользователя системы IVIDEON_ABONENTS.ABONENTN_ID';

COMMENT ON COLUMN ABONENT_BLOCK_UNLOCK.ABONENT_IS_ACTIVE IS 'Статус абонента: 1 - Активный, 0 - Заблокирован';

COMMENT ON COLUMN IVIDEON.ABONENT_BLOCK_UNLOCK.BALANCE IS 'Баланс';

COMMENT ON COLUMN IVIDEON.ABONENT_BLOCK_UNLOCK.USER_CREATED IS 'Создавший пользователь';

COMMENT ON COLUMN IVIDEON.ABONENT_BLOCK_UNLOCK.DATE_CREATED IS 'Дата создания записи';

COMMENT ON COLUMN IVIDEON.ABONENT_BLOCK_UNLOCK.USER_LAST_UPDATED IS 'Изменившый запись';

COMMENT ON COLUMN IVIDEON.ABONENT_BLOCK_UNLOCK.DATE_LAST_UPDATED IS 'Дата изменения записи';



--  There is no statement for index IVIDEON.SYS_C0019531.
--  The object is created when the parent object is created.

CREATE OR REPLACE TRIGGER IVIDEON.TI_ABONENT_BLK_UNLOCK_ID
  BEFORE INSERT OR UPDATE ON IVIDEON.ABONENT_BLOCK_UNLOCK
  REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
BEGIN
  
  IF INSERTING THEN   
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
    :NEW.USER_LAST_UPDATED := USER;
    :NEW.DATE_LAST_UPDATED := SYSDATE;
  END IF;
  
  IF UPDATING THEN
    :NEW.USER_LAST_UPDATED := USER;
    :NEW.DATE_LAST_UPDATED := SYSDATE;
  END IF; 
END;
/


ALTER TABLE IVIDEON.ABONENT_BLOCK_UNLOCK ADD (
  PRIMARY KEY
  (ABONENT_ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MAXSIZE          UNLIMITED
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE IVIDEON.ABONENT_BLOCK_UNLOCK ADD (
  CONSTRAINT FK_ABONENT_ACTIVE_ID 
  FOREIGN KEY (ABONENT_ID) 
  REFERENCES IVIDEON.IVIDEON_ABONENTS (ABONENT_ID)
  ENABLE VALIDATE);

ALTER TABLE IVIDEON.ABONENT_BLOCK_UNLOCK ADD (
  CONSTRAINT FK_ACTIVE_TYPE_ID 
  FOREIGN KEY (ABONENT_IS_ACTIVE) 
  REFERENCES IVIDEON.ACTIVE_TYPE (ACTIVE_TYPE_ID)
  ENABLE VALIDATE); 
