CREATE TABLE ABONENT_BLOCK_UNLOCK_HISTORY(
  ABONENT_BLOCK_UNLOCK_HIS_ID Integer NOT NULL PRIMARY KEY,
  ABONENT_ID Integer NOT NULL,
  ACTION_TYPE_ID Integer NOT NULL,
  HISTORY_DATE Date NOT NULL,
  ANSWER Varchar2(100 ),
  USER_CREATED Varchar2(30 ) NOT NULL,
  DATE_CREATED Date NOT NULL
)
/


-- Table and Columns comments section
  
COMMENT ON TABLE ABONENT_BLOCK_UNLOCK_HISTORY IS 'История заявок на блок/разблок абонентов'
/
COMMENT ON COLUMN ABONENT_BLOCK_UNLOCK_HISTORY.ABONENT_BLOCK_UNLOCK_HIS_ID IS 'Идентификатор записи'
/
COMMENT ON COLUMN ABONENT_BLOCK_UNLOCK_HISTORY.ABONENT_ID IS 'Идентификатор пользователя системы IVIDEON_ABONENTS.ABONENTN_ID'
/
COMMENT ON COLUMN ABONENT_BLOCK_UNLOCK_HISTORY.ACTION_TYPE_ID IS 'Идентификатор типа действия'
/
COMMENT ON COLUMN ABONENT_BLOCK_UNLOCK_HISTORY.HISTORY_DATE IS 'Дата запроса'
/
COMMENT ON COLUMN ABONENT_BLOCK_UNLOCK_HISTORY.ANSWER IS 'Текст ответа'
/
COMMENT ON COLUMN ABONENT_BLOCK_UNLOCK_HISTORY.USER_CREATED IS 'Создавший пользователь'
/
COMMENT ON COLUMN ABONENT_BLOCK_UNLOCK_HISTORY.DATE_CREATED IS 'Дата создания записи'
/
CREATE SEQUENCE S_ABONENT_BLOCK_UNLOCK_HIS_ID
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1;
  
CREATE OR REPLACE TRIGGER TI_ABONENT_BLK_UNLOCK_HIS_ID
  BEFORE INSERT ON ABONENT_BLOCK_UNLOCK_HISTORY
  REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
BEGIN
  
  IF INSERTING THEN
    if nvl(:new.ABONENT_BLOCK_UNLOCK_HIS_ID, 0) = 0 then
      :new.ABONENT_BLOCK_UNLOCK_HIS_ID := S_ABONENT_BLOCK_UNLOCK_HIS_ID.NEXTVAL;
    END IF;
    
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
END;
/  

  
ALTER TABLE ABONENT_BLOCK_UNLOCK_HISTORY ADD (
  CONSTRAINT FK_ABON_BL_UNLOCK_HIST_TYPE_ID
  FOREIGN KEY (ACTION_TYPE_ID) 
  REFERENCES ACTION_TYPE (ACTION_TYPE_ID)
  );  
  
ALTER TABLE ABONENT_BLOCK_UNLOCK_HISTORY ADD (
  CONSTRAINT FK_BL_ABONENT_ID
  FOREIGN KEY (ABONENT_ID) 
  REFERENCES IVIDEON_ABONENTS (ABONENT_ID)
  );  

ALTER TABLE ABONENT_BLOCK_UNLOCK_HISTORY
     ADD BALANCE NUMBER(10,2) DEFAULT 0 NOT NULL;

COMMENT ON COLUMN ABONENT_BLOCK_UNLOCK_HISTORY.BALANCE IS 'Баланс';
