CREATE TABLE CONSTANTS(
  CONSTANT_ID Integer NOT NULL primary key,
  NAME Varchar2(30 ) NOT NULL UNIQUE,
  VALUE Varchar2(150 ),
  CONSTANT_TYPE Varchar2(1 CHAR) NOT NULL,
  DESCRIPTION Varchar2(100 ) NOT NULL
)
/

-- Table and Columns comments section
  
COMMENT ON TABLE CONSTANTS IS 'Таблица с константами'
/
COMMENT ON COLUMN CONSTANTS.CONSTANT_ID IS 'Идентификатор записи'
/
COMMENT ON COLUMN CONSTANTS.NAME IS 'Имя константы'
/
COMMENT ON COLUMN CONSTANTS.VALUE IS 'Значение константы'
/
COMMENT ON COLUMN CONSTANTS.CONSTANT_TYPE IS 'Тип константы (S- СТРОКА, N - ЧИСЛОВОЙ ТИП и т.д.)'
/
COMMENT ON COLUMN CONSTANTS.DESCRIPTION IS 'Комментарий к константе'
/
CREATE SEQUENCE S_CONSTANT_ID
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1;
  
CREATE OR REPLACE TRIGGER TI_CONSTANTS
  BEFORE INSERT ON CONSTANTS
  REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
BEGIN
  
  if nvl(:new.CONSTANT_ID, 0) = 0 then
    :new.CONSTANT_ID := S_CONSTANT_ID.NEXTVAL;
  END IF;

END;
/  

Insert into CONSTANTS
   (NAME, VALUE, CONSTANT_TYPE, DESCRIPTION)
 Values
   ( 'START_TIME_JOB_AFTER_STOP', NULL, 'D', 'Время запуска job после их остановки');
COMMIT;
