CREATE TABLE SERVICE_TYPES(
  SERVICE_TYPE_ID Integer NOT NULL primary key,
  SERVICE_TYPE_NAME Varchar2(100 CHAR) NOT NULL UNIQUE
)
/

  
COMMENT ON TABLE SERVICE_TYPES IS 'Типы списаниия'
/
COMMENT ON COLUMN SERVICE_TYPES.SERVICE_TYPE_ID IS 'Идентификатор записи'
/
COMMENT ON COLUMN SERVICE_TYPES.SERVICE_TYPE_NAME IS 'Название услуги'
/

CREATE SEQUENCE S_SERVICE_TYPE_ID
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1;
  
CREATE OR REPLACE TRIGGER TI_SERVICE_TYPES
  BEFORE INSERT ON SERVICE_TYPES
  REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
BEGIN
  
  if nvl(:new.SERVICE_TYPE_ID, 0) = 0 then
    :new.SERVICE_TYPE_ID := S_SERVICE_TYPE_ID.NEXTVAL;
  END IF;
END;
/  

SET DEFINE OFF;
Insert into SERVICE_TYPES
   (SERVICE_TYPE_ID, SERVICE_TYPE_NAME)
 Values
   (1, 'Платеж абонента');
Insert into SERVICE_TYPES
   (SERVICE_TYPE_ID, SERVICE_TYPE_NAME)
 Values
   (2, 'Списание абон.платы за тариф "%TARIFF_NAME%"');
COMMIT;
