CREATE TABLE TARIFF_ON_OFF_HISTORY(
  TARIFF_ON_OFF_HISTORY_ID Integer NOT NULL PRIMARY KEY,
  TARIFF_ID Integer NOT NULL,
  ACTION_TYPE_ID Integer NOT NULL,
  DATE_CREATED Date NOT NULL,
  USER_CREATED Varchar2(30 ) NOT NULL,
  USER_LAST_UPDATED Varchar2(30 ),
  DATE_LAST_UPDATED Date,
  ABONENT_ID Integer NOT NULL
)
/  
COMMENT ON TABLE TARIFF_ON_OFF_HISTORY IS 'История подключения/ отключения тарифов'
/
COMMENT ON COLUMN TARIFF_ON_OFF_HISTORY.TARIFF_ON_OFF_HISTORY_ID IS 'Идентификатор записи'
/
COMMENT ON COLUMN TARIFF_ON_OFF_HISTORY.TARIFF_ID IS 'Идентификатор тарифного плана'
/
COMMENT ON COLUMN TARIFF_ON_OFF_HISTORY.ACTION_TYPE_ID IS 'Идентификатор действия'
/
COMMENT ON COLUMN TARIFF_ON_OFF_HISTORY.DATE_CREATED IS 'Дата создания'
/
COMMENT ON COLUMN TARIFF_ON_OFF_HISTORY.USER_CREATED IS 'Создавший пользователь'
/
COMMENT ON COLUMN TARIFF_ON_OFF_HISTORY.USER_LAST_UPDATED IS 'Последний обновивший пользователь'
/
COMMENT ON COLUMN TARIFF_ON_OFF_HISTORY.DATE_LAST_UPDATED IS 'Дата послденего обновления'
/
COMMENT ON COLUMN TARIFF_ON_OFF_HISTORY.ABONENT_ID IS 'Идентификатор пользователя системы IVIDEON_ABONENTS.ABONENTN_ID'
/

CREATE SEQUENCE S_TARIFF_ON_OFF_HISTORY_ID
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1;
  
CREATE OR REPLACE TRIGGER TIU_TARIFF_ON_OFF_HISTORY
  BEFORE INSERT OR UPDATE ON TARIFF_ON_OFF_HISTORY
  REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
BEGIN
  
  IF INSERTING THEN
    if nvl(:new.TARIFF_ON_OFF_HISTORY_ID, 0) = 0 then
      :new.TARIFF_ON_OFF_HISTORY_ID := S_TARIFF_ON_OFF_HISTORY_ID.NEXTVAL;
    END IF;
    
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  
  IF UPDATING THEN
    :NEW.USER_LAST_UPDATED := USER;
    :NEW.DATE_LAST_UPDATED := SYSDATE;
  END IF;
END;
/  

ALTER TABLE TARIFF_ON_OFF_HISTORY ADD (
  CONSTRAINT FK_TARIFF_ID
  FOREIGN KEY (TARIFF_ID) 
  REFERENCES TARIFFS (TARIFF_ID)
  );
  
ALTER TABLE TARIFF_ON_OFF_HISTORY ADD (
  CONSTRAINT FK_ACTION_TYPE_ID
  FOREIGN KEY (ACTION_TYPE_ID) 
  REFERENCES ACTION_TYPE (ACTION_TYPE_ID)
  );  