-- Журнал блокировок
TRUNCATE TABLE AUTO_BLOCKED_PHONE;

-- Журнал разблокировок
TRUNCATE TABLE AUTO_UNBLOCKED_PHONE;

--
TRUNCATE TABLE BLOCK_SEND_SMS;


-- Журнал загрузок с сайта
TRUNCATE TABLE ACCOUNT_LOAD_LOGS;


TRUNCATE TABLE DB_LOADER_ACCOUNT_PHONE_HISTS;
TRUNCATE TABLE DB_LOADER_ACCOUNT_PHONE_OPTS;
TRUNCATE TABLE DB_LOADER_ACCOUNT_PHONES;
TRUNCATE TABLE DB_LOADER_BILLS;
TRUNCATE TABLE DB_LOADER_PAYMENTS;
TRUNCATE TABLE DB_LOADER_PHONE_STAT;

-- Лицевые счета
DELETE FROM ACCOUNTS;

-- Договора
TRUNCATE TABLE PHONE_BALANCES;

TRUNCATE TABLE CONTRACT_BALANCES;

TRUNCATE TABLE CONTRACT_CANCELS;

TRUNCATE TABLE CONTRACT_CHANGES;

TRUNCATE TABLE RECEIVED_PAYMENTS;

TRUNCATE TABLE SMS_SEND_PARAMETRS;

DELETE FROM CONTRACTS;

-- Абоненты (ФИО)
DELETE FROM ABONENTS;

-- Нумерация догвооров
UPDATE AUTO_NUMERATION2_SEQUENCES SET LAST_VALUE=1 WHERE SEQUENCE_NAME='CONTRACT_NUM';

DELETE FROM AUTO_NUMERATION2_FREE_VALUES;


--
TRUNCATE TABLE USER_NAMES;

DELETE FROM FILIALS;

COMMIT;
