CREATE SYNONYM SIM_TRADE_USER1.ABONENTS FOR SIM_TRADE.ABONENTS;
--абоненты

CREATE SYNONYM SIM_TRADE_USER1.ACCOUNT_LOAD_LOGS FOR SIM_TRADE.ACCOUNT_LOAD_LOGS;
--логи загрузок

CREATE SYNONYM SIM_TRADE_USER1.AUTO_BLOCKED_PHONE FOR SIM_TRADE.AUTO_BLOCKED_PHONE;
--номера бывшие автозаблокированными

CREATE SYNONYM SIM_TRADE_USER1.AUTO_UNBLOCKED_PHONE FOR SIM_TRADE.AUTO_UNBLOCKED_PHONE;
--авторазблокированные номера

CREATE SYNONYM SIM_TRADE_USER1.DB_LOADER_ACCOUNT_PHONE_HISTS FOR SIM_TRADE.DB_LOADER_ACCOUNT_PHONE_HISTS;

CREATE SYNONYM SIM_TRADE_USER1.DB_LOADER_ACCOUNT_PHONE_OPTS FOR SIM_TRADE.DB_LOADER_ACCOUNT_PHONE_OPTS;
--загруженные списки подключенных опций

CREATE SYNONYM SIM_TRADE_USER1.DB_LOADER_ACCOUNT_PHONES FOR SIM_TRADE.DB_LOADER_ACCOUNT_PHONES;

CREATE SYNONYM SIM_TRADE_USER1.DB_LOADER_BILLS FOR SIM_TRADE.DB_LOADER_BILLS;
--загруженные счета оператора

CREATE SYNONYM SIM_TRADE_USER1.DB_LOADER_PAYMENTS FOR SIM_TRADE.DB_LOADER_PAYMENTS;
--загруженные платежи опратору

CREATE SYNONYM SIM_TRADE_USER1.DB_LOADER_REPORT_DATA FOR SIM_TRADE.DB_LOADER_REPORT_DATA;
--загруженные отчеты о начислениях оператора

CREATE SYNONYM SIM_TRADE_USER1.OPERATORS FOR SIM_TRADE.OPERATORS;
--СПИСОК ОПЕРАТОРОВ

CREATE SYNONYM SIM_TRADE_USER1.TARIFFS FOR SIM_TRADE.TARIFFS;
--СПИСОК ТАРИФОВ 

CREATE SYNONYM SIM_TRADE_USER1.V_ABON_PAYMENT_BY_PHONES_YEAR2 FOR SIM_TRADE.V_ABON_PAYMENT_BY_PHONES_YEAR2;
--отчет по абон плате

CREATE SYNONYM SIM_TRADE_USER1.V_ABONENT_BALANCES FOR SIM_TRADE.V_ABONENT_BALANCES;
--текущие балансы телефонов

CREATE SYNONYM SIM_TRADE_USER1.V_ACTIVE_NUMBERS_OUT_CONTRACTS FOR SIM_TRADE.V_ACTIVE_NUMBERS_OUT_CONTRACTS;
--активные номера без контракта

CREATE SYNONYM SIM_TRADE_USER1.V_BILL_FOR_CLIENT FOR SIM_TRADE.V_BILL_FOR_CLIENT;
--СЧЕТА ДЛЯ КЛИЕНТОВ

CREATE SYNONYM SIM_TRADE_USER1.V_PAYMENTS_WITHOUT_TRAFFIC FOR SIM_TRADE.V_PAYMENTS_WITHOUT_TRAFFIC;
--номера с начил абонплаты, но без активности

CREATE SYNONYM SIM_TRADE_USER1.V_PHONE_NUMBER_VIOLATIONS FOR SIM_TRADE.V_PHONE_NUMBER_VIOLATIONS;
--номера с любой активностью без контрактов

CREATE SYNONYM SIM_TRADE_USER1.V_PROFIT_BY_PHONES_YEAR FOR SIM_TRADE.V_PROFIT_BY_PHONES_YEAR;
--отчет о доходности

CREATE SYNONYM SIM_TRADE_USER1.V_REPORT_PHONE_STAT FOR SIM_TRADE.V_REPORT_PHONE_STAT;
--отчет по детализациям

CREATE SYNONYM SIM_TRADE_USER1.V_REPORT_SUMMARY_MINUTES FOR SIM_TRADE.V_REPORT_SUMMARY_MINUTES;
--отчет кол-ва беспл минут

CREATE SYNONYM SIM_TRADE_USER1.V_TARIFF_VIOLATIONS FOR SIM_TRADE.V_TARIFF_VIOLATIONS;
--нарушения с тарифами