CREATE USER BUSINESS_COMM_LK IDENTIFIED BY "UOCM_NMOLS"
 DEFAULT TABLESPACE USERS
 TEMPORARY TABLESPACE TEMP
 QUOTA UNLIMITED ON USERS;
 
  GRANT BUSINESS_COMM_ROLE TO BUSINESS_COMM_LK;
  ALTER USER BUSINESS_COMM_LK DEFAULT ROLE ALL;
  -- 1 System Privilege for BUSINESS_COMM_LK 
  GRANT CREATE SESSION TO BUSINESS_COMM_LK;