DROP ROLE BUSINESS_COMM_ROLE;

CREATE ROLE BUSINESS_COMM_ROLE NOT IDENTIFIED;

-- System privileges granted to BUSINESS_COMM_ROLE
GRANT CREATE SESSION TO BUSINESS_COMM_ROLE;

-- Grantees of BUSINESS_COMM_ROLE
GRANT BUSINESS_COMM_ROLE TO BUSINESS_COMM WITH ADMIN OPTION;
