CREATE USER BUSINESS_COMM IDENTIFIED BY "BUSINESS_COMM-112"
 DEFAULT TABLESPACE USERS
 TEMPORARY TABLESPACE TEMP
 QUOTA UNLIMITED ON USERS;

GRANT ADMINISTER ANY SQL TUNING SET TO BUSINESS_COMM;

GRANT ADMINISTER DATABASE TRIGGER TO BUSINESS_COMM;

BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'BUSINESS_COMM', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/

GRANT ADMINISTER SQL MANAGEMENT OBJECT TO BUSINESS_COMM;

GRANT ADMINISTER SQL TUNING SET TO BUSINESS_COMM;

GRANT ADVISOR TO BUSINESS_COMM;

GRANT ALTER ANY ASSEMBLY TO BUSINESS_COMM;

GRANT ALTER ANY CLUSTER TO BUSINESS_COMM;

GRANT ALTER ANY CUBE TO BUSINESS_COMM;

GRANT ALTER ANY CUBE DIMENSION TO BUSINESS_COMM;

GRANT ALTER ANY DIMENSION TO BUSINESS_COMM;

GRANT ALTER ANY EDITION TO BUSINESS_COMM;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'BUSINESS_COMM',
  GRANT_OPTION => FALSE);
END;
/

GRANT ALTER ANY INDEX TO BUSINESS_COMM;

GRANT ALTER ANY INDEXTYPE TO BUSINESS_COMM;

GRANT ALTER ANY LIBRARY TO BUSINESS_COMM;

GRANT ALTER ANY MATERIALIZED VIEW TO BUSINESS_COMM;

GRANT ALTER ANY MINING MODEL TO BUSINESS_COMM;

GRANT ALTER ANY OPERATOR TO BUSINESS_COMM;

GRANT ALTER ANY OUTLINE TO BUSINESS_COMM;

GRANT ALTER ANY PROCEDURE TO BUSINESS_COMM;

GRANT ALTER ANY ROLE TO BUSINESS_COMM;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'BUSINESS_COMM',
  GRANT_OPTION => FALSE);
END;
/

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'BUSINESS_COMM',
  GRANT_OPTION => FALSE);
END;
/

GRANT ALTER ANY SEQUENCE TO BUSINESS_COMM;

GRANT ALTER ANY SQL PROFILE TO BUSINESS_COMM;

GRANT ALTER ANY TABLE TO BUSINESS_COMM;

GRANT ALTER ANY TRIGGER TO BUSINESS_COMM;

GRANT ALTER ANY TYPE TO BUSINESS_COMM;

GRANT ALTER DATABASE TO BUSINESS_COMM;

GRANT ALTER DATABASE LINK TO BUSINESS_COMM;

GRANT ALTER PROFILE TO BUSINESS_COMM;

GRANT ALTER PUBLIC DATABASE LINK TO BUSINESS_COMM;

GRANT ALTER RESOURCE COST TO BUSINESS_COMM;

GRANT ALTER ROLLBACK SEGMENT TO BUSINESS_COMM;

GRANT ALTER SESSION TO BUSINESS_COMM;

GRANT ALTER SYSTEM TO BUSINESS_COMM;

GRANT ALTER TABLESPACE TO BUSINESS_COMM;

GRANT ALTER USER TO BUSINESS_COMM;

GRANT ANALYZE ANY TO BUSINESS_COMM;

GRANT ANALYZE ANY DICTIONARY TO BUSINESS_COMM;

GRANT AUDIT ANY TO BUSINESS_COMM;

GRANT AUDIT SYSTEM TO BUSINESS_COMM;

GRANT BACKUP ANY TABLE TO BUSINESS_COMM;

GRANT BECOME USER TO BUSINESS_COMM;

GRANT CHANGE NOTIFICATION TO BUSINESS_COMM;

GRANT COMMENT ANY MINING MODEL TO BUSINESS_COMM;

GRANT COMMENT ANY TABLE TO BUSINESS_COMM;

GRANT CREATE ANY ASSEMBLY TO BUSINESS_COMM;

GRANT CREATE ANY CLUSTER TO BUSINESS_COMM;

GRANT CREATE ANY CONTEXT TO BUSINESS_COMM;

GRANT CREATE ANY CUBE TO BUSINESS_COMM;

GRANT CREATE ANY CUBE BUILD PROCESS TO BUSINESS_COMM;

GRANT CREATE ANY CUBE DIMENSION TO BUSINESS_COMM;

GRANT CREATE ANY DIMENSION TO BUSINESS_COMM;

GRANT CREATE ANY DIRECTORY TO BUSINESS_COMM;

GRANT CREATE ANY EDITION TO BUSINESS_COMM;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'BUSINESS_COMM',
  GRANT_OPTION => FALSE);
END;
/

GRANT CREATE ANY INDEX TO BUSINESS_COMM;

GRANT CREATE ANY INDEXTYPE TO BUSINESS_COMM;

GRANT CREATE ANY JOB TO BUSINESS_COMM;

GRANT CREATE ANY LIBRARY TO BUSINESS_COMM;

GRANT CREATE ANY MATERIALIZED VIEW TO BUSINESS_COMM;

GRANT CREATE ANY MEASURE FOLDER TO BUSINESS_COMM;

GRANT CREATE ANY MINING MODEL TO BUSINESS_COMM;

GRANT CREATE ANY OPERATOR TO BUSINESS_COMM;

GRANT CREATE ANY OUTLINE TO BUSINESS_COMM;

GRANT CREATE ANY PROCEDURE TO BUSINESS_COMM;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'BUSINESS_COMM',
  GRANT_OPTION => FALSE);
END;
/

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'BUSINESS_COMM',
  GRANT_OPTION => FALSE);
END;
/

GRANT CREATE ANY SEQUENCE TO BUSINESS_COMM;

GRANT CREATE ANY SQL PROFILE TO BUSINESS_COMM;

GRANT CREATE ANY SYNONYM TO BUSINESS_COMM;

GRANT CREATE ANY TABLE TO BUSINESS_COMM;

GRANT CREATE ANY TRIGGER TO BUSINESS_COMM;

GRANT CREATE ANY TYPE TO BUSINESS_COMM;

GRANT CREATE ANY VIEW TO BUSINESS_COMM;

GRANT CREATE ASSEMBLY TO BUSINESS_COMM;

GRANT CREATE CLUSTER TO BUSINESS_COMM;

GRANT CREATE CUBE TO BUSINESS_COMM;

GRANT CREATE CUBE BUILD PROCESS TO BUSINESS_COMM;

GRANT CREATE CUBE DIMENSION TO BUSINESS_COMM;

GRANT CREATE DATABASE LINK TO BUSINESS_COMM;

GRANT CREATE DIMENSION TO BUSINESS_COMM;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'BUSINESS_COMM',
  GRANT_OPTION => FALSE);
END;
/

GRANT CREATE EXTERNAL JOB TO BUSINESS_COMM;

GRANT CREATE INDEXTYPE TO BUSINESS_COMM;

GRANT CREATE JOB TO BUSINESS_COMM;

GRANT CREATE LIBRARY TO BUSINESS_COMM;

GRANT CREATE MATERIALIZED VIEW TO BUSINESS_COMM;

GRANT CREATE MEASURE FOLDER TO BUSINESS_COMM;

GRANT CREATE MINING MODEL TO BUSINESS_COMM;

GRANT CREATE OPERATOR TO BUSINESS_COMM;

GRANT CREATE PROCEDURE TO BUSINESS_COMM;

GRANT CREATE PROFILE TO BUSINESS_COMM;

GRANT CREATE PUBLIC DATABASE LINK TO BUSINESS_COMM;

GRANT CREATE PUBLIC SYNONYM TO BUSINESS_COMM;

GRANT CREATE ROLE TO BUSINESS_COMM;

GRANT CREATE ROLLBACK SEGMENT TO BUSINESS_COMM;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'BUSINESS_COMM',
  GRANT_OPTION => FALSE);
END;
/

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'BUSINESS_COMM',
  GRANT_OPTION => FALSE);
END;
/

GRANT CREATE SEQUENCE TO BUSINESS_COMM;

GRANT CREATE SESSION TO BUSINESS_COMM;

GRANT CREATE SYNONYM TO BUSINESS_COMM;

GRANT CREATE TABLE TO BUSINESS_COMM;

GRANT CREATE TABLESPACE TO BUSINESS_COMM;

GRANT CREATE TRIGGER TO BUSINESS_COMM;

GRANT CREATE TYPE TO BUSINESS_COMM;

GRANT CREATE USER TO BUSINESS_COMM;

GRANT CREATE VIEW TO BUSINESS_COMM;

GRANT DEBUG ANY PROCEDURE TO BUSINESS_COMM;

GRANT DEBUG CONNECT SESSION TO BUSINESS_COMM;

GRANT DELETE ANY CUBE DIMENSION TO BUSINESS_COMM;

GRANT DELETE ANY MEASURE FOLDER TO BUSINESS_COMM;

GRANT DELETE ANY TABLE TO BUSINESS_COMM;

BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'BUSINESS_COMM',
  ADMIN_OPTION => FALSE);
END;
/

GRANT DROP ANY ASSEMBLY TO BUSINESS_COMM;

GRANT DROP ANY CLUSTER TO BUSINESS_COMM;

GRANT DROP ANY CONTEXT TO BUSINESS_COMM;

GRANT DROP ANY CUBE TO BUSINESS_COMM;

GRANT DROP ANY CUBE BUILD PROCESS TO BUSINESS_COMM;

GRANT DROP ANY CUBE DIMENSION TO BUSINESS_COMM;

GRANT DROP ANY DIMENSION TO BUSINESS_COMM;

GRANT DROP ANY DIRECTORY TO BUSINESS_COMM;

GRANT DROP ANY EDITION TO BUSINESS_COMM;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'BUSINESS_COMM',
  GRANT_OPTION => FALSE);
END;
/

GRANT DROP ANY INDEX TO BUSINESS_COMM;

GRANT DROP ANY INDEXTYPE TO BUSINESS_COMM;

GRANT DROP ANY LIBRARY TO BUSINESS_COMM;

GRANT DROP ANY MATERIALIZED VIEW TO BUSINESS_COMM;

GRANT DROP ANY MEASURE FOLDER TO BUSINESS_COMM;

GRANT DROP ANY MINING MODEL TO BUSINESS_COMM;

GRANT DROP ANY OPERATOR TO BUSINESS_COMM;

GRANT DROP ANY OUTLINE TO BUSINESS_COMM;

GRANT DROP ANY PROCEDURE TO BUSINESS_COMM;

GRANT DROP ANY ROLE TO BUSINESS_COMM;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'BUSINESS_COMM',
  GRANT_OPTION => FALSE);
END;
/

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'BUSINESS_COMM',
  GRANT_OPTION => FALSE);
END;
/

GRANT DROP ANY SEQUENCE TO BUSINESS_COMM;

GRANT DROP ANY SQL PROFILE TO BUSINESS_COMM;

GRANT DROP ANY SYNONYM TO BUSINESS_COMM;

GRANT DROP ANY TABLE TO BUSINESS_COMM;

GRANT DROP ANY TRIGGER TO BUSINESS_COMM;

GRANT DROP ANY TYPE TO BUSINESS_COMM;

GRANT DROP ANY VIEW TO BUSINESS_COMM;

GRANT DROP PROFILE TO BUSINESS_COMM;

GRANT DROP PUBLIC DATABASE LINK TO BUSINESS_COMM;

GRANT DROP PUBLIC SYNONYM TO BUSINESS_COMM;

GRANT DROP ROLLBACK SEGMENT TO BUSINESS_COMM;

GRANT DROP TABLESPACE TO BUSINESS_COMM;

GRANT DROP USER TO BUSINESS_COMM;

BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'BUSINESS_COMM',
  ADMIN_OPTION => FALSE);
END;
/

GRANT EXECUTE ANY ASSEMBLY TO BUSINESS_COMM;

GRANT EXECUTE ANY CLASS TO BUSINESS_COMM;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'BUSINESS_COMM',
  GRANT_OPTION => FALSE);
END;
/

GRANT EXECUTE ANY INDEXTYPE TO BUSINESS_COMM;

GRANT EXECUTE ANY LIBRARY TO BUSINESS_COMM;

GRANT EXECUTE ANY OPERATOR TO BUSINESS_COMM;

GRANT EXECUTE ANY PROCEDURE TO BUSINESS_COMM;

GRANT EXECUTE ANY PROGRAM TO BUSINESS_COMM;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'BUSINESS_COMM',
  GRANT_OPTION => FALSE);
END;
/

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'BUSINESS_COMM',
  GRANT_OPTION => FALSE);
END;
/

GRANT EXECUTE ANY TYPE TO BUSINESS_COMM;

GRANT EXECUTE ASSEMBLY TO BUSINESS_COMM;

GRANT EXEMPT ACCESS POLICY TO BUSINESS_COMM;

GRANT EXEMPT IDENTITY POLICY TO BUSINESS_COMM;

GRANT EXPORT FULL DATABASE TO BUSINESS_COMM;

GRANT FLASHBACK ANY TABLE TO BUSINESS_COMM;

GRANT FLASHBACK ARCHIVE ADMINISTER TO BUSINESS_COMM;

GRANT FORCE ANY TRANSACTION TO BUSINESS_COMM;

GRANT FORCE TRANSACTION TO BUSINESS_COMM;

GRANT GLOBAL QUERY REWRITE TO BUSINESS_COMM;

GRANT GRANT ANY OBJECT PRIVILEGE TO BUSINESS_COMM;

GRANT GRANT ANY PRIVILEGE TO BUSINESS_COMM;

GRANT GRANT ANY ROLE TO BUSINESS_COMM;

GRANT IMPORT FULL DATABASE TO BUSINESS_COMM;

GRANT INSERT ANY CUBE DIMENSION TO BUSINESS_COMM;

GRANT INSERT ANY MEASURE FOLDER TO BUSINESS_COMM;

GRANT INSERT ANY TABLE TO BUSINESS_COMM;

GRANT LOCK ANY TABLE TO BUSINESS_COMM;

GRANT MANAGE ANY FILE GROUP TO BUSINESS_COMM;

BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'BUSINESS_COMM',
  ADMIN_OPTION => FALSE);
END;
/

GRANT MANAGE FILE GROUP TO BUSINESS_COMM;

GRANT MANAGE SCHEDULER TO BUSINESS_COMM;

GRANT MANAGE TABLESPACE TO BUSINESS_COMM;

GRANT MERGE ANY VIEW TO BUSINESS_COMM;

GRANT ON COMMIT REFRESH TO BUSINESS_COMM;

GRANT QUERY REWRITE TO BUSINESS_COMM;

GRANT READ ANY FILE GROUP TO BUSINESS_COMM;

GRANT RESTRICTED SESSION TO BUSINESS_COMM;

GRANT RESUMABLE TO BUSINESS_COMM;

GRANT SELECT ANY CUBE TO BUSINESS_COMM;

GRANT SELECT ANY CUBE DIMENSION TO BUSINESS_COMM;

GRANT SELECT ANY DICTIONARY TO BUSINESS_COMM;

GRANT SELECT ANY MINING MODEL TO BUSINESS_COMM;

GRANT SELECT ANY SEQUENCE TO BUSINESS_COMM;

GRANT SELECT ANY TABLE TO BUSINESS_COMM;

GRANT SELECT ANY TRANSACTION TO BUSINESS_COMM;

GRANT UNDER ANY TABLE TO BUSINESS_COMM;

GRANT UNDER ANY VIEW TO BUSINESS_COMM;

GRANT UNLIMITED TABLESPACE TO BUSINESS_COMM WITH ADMIN OPTION;

GRANT UPDATE ANY CUBE TO BUSINESS_COMM;

GRANT UPDATE ANY CUBE BUILD PROCESS TO BUSINESS_COMM;

GRANT UPDATE ANY CUBE DIMENSION TO BUSINESS_COMM;

GRANT UPDATE ANY TABLE TO BUSINESS_COMM;


GRANT "DBA" TO BUSINESS_COMM WITH ADMIN OPTION;
ALTER USER BUSINESS_COMM DEFAULT ROLE "DBA";

