DROP ROLE BUSINESS_COMM_ROLE_RO;

CREATE ROLE BUSINESS_COMM_ROLE_RO NOT IDENTIFIED;

-- System privileges granted to BUSINESS_COMM_ROLE_RO
GRANT CREATE SESSION TO BUSINESS_COMM_ROLE_RO;

-- Grantees of BUSINESS_COMM_ROLE_RO
GRANT BUSINESS_COMM_ROLE_RO TO BUSINESS_COMM WITH ADMIN OPTION;
