CREATE TABLE ACCOUNT_INFO_HISTORY
(
  ID_ACCOUNT_INFO_HISTORY  INTEGER              NOT NULL,
  ACCOUNT_ID               INTEGER              NOT NULL,
  BALANCE                  NUMBER(15,2),
  COUNT_PHONE              INTEGER,
  USER_UPDATE              VARCHAR2(30 CHAR),
  DATE_UPDATE              DATE
)
;

CREATE UNIQUE INDEX ACCOUNT_INFO_HISTORY_PK ON ACCOUNT_INFO_HISTORY
(ID_ACCOUNT_INFO_HISTORY);


ALTER TABLE ACCOUNT_INFO_HISTORY ADD (
  CONSTRAINT ACCOUNT_INFO_HISTORY_PK
  PRIMARY KEY
  (ID_ACCOUNT_INFO_HISTORY)
  USING INDEX ACCOUNT_INFO_HISTORY_PK
  ENABLE VALIDATE);

COMMENT ON TABLE ACCOUNT_INFO_HISTORY is 'История изменений баланса лицевых счетов';
COMMENT ON COLUMN ACCOUNT_INFO_HISTORY.ID_ACCOUNT_INFO_HISTORY IS 'Код изменения';
COMMENT ON COLUMN ACCOUNT_INFO_HISTORY.ACCOUNT_ID IS 'Код лицевого счёта';
COMMENT ON COLUMN ACCOUNT_INFO_HISTORY.BALANCE IS 'Баланс л/с';
COMMENT ON COLUMN ACCOUNT_INFO_HISTORY.COUNT_PHONE IS 'Кол-во номеров телефонов л/с';
COMMENT ON COLUMN ACCOUNT_INFO_HISTORY.USER_UPDATE IS 'Пользователь, изменивший баланс';
COMMENT ON COLUMN ACCOUNT_INFO_HISTORY.DATE_UPDATE IS 'Дата изменения балланса';

GRANT DELETE, INSERT, SELECT, UPDATE ON ACCOUNT_INFO_HISTORY TO CORP_MOBILE_ROLE;

CREATE SEQUENCE S_NEW_ID_ACCOUNT_INFO_HISTORY
  START WITH 12
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  CREATE OR REPLACE TRIGGER TI_ACCOUNT_INFO_HISTORY
  before insert on ACCOUNT_INFO_HISTORY  
  for each row

begin
    :new.ID_ACCOUNT_INFO_HISTORY := S_NEW_ID_ACCOUNT_INFO_HISTORY.nextval;
END;    