CREATE TABLE ALL_PHONE_STAT
(
  ALL_PHONE_STAT_ID      NUMBER(38),
  PHONE              VARCHAR2(10 CHAR),
  PCKG_CODE        VARCHAR2(30 CHAR),
  UNITTYPE VARCHAR2(100 char),
  INITVALUE          NUMBER(18),
  CURRVALUE          NUMBER(18),
  CURR_CHECK_DATE    TIMESTAMP(6),
  NEXT_CHECK_DATE    TIMESTAMP(6),
  CTRL_PNT           NUMBER(12)                  DEFAULT 0,
  IS_CHECKED         NUMBER(12)                 DEFAULT 0,
  ALL_PHONE_TURN_LOG_ID  NUMBER(28)   DEFAULT 0
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ALL_PHONE_STAT IS 'Статистики по пакетам по всем номерам абонентов, кроме безлимитов и драйвов';

COMMENT ON COLUMN ALL_PHONE_STAT.ALL_PHONE_STAT_ID IS 'Первичный ключ';

COMMENT ON COLUMN ALL_PHONE_STAT.PHONE IS 'Номер телефона';

COMMENT ON COLUMN ALL_PHONE_STAT.PCKG_CODE IS 'Код пакета';

COMMENT ON COLUMN ALL_PHONE_STAT.UNITTYPE IS 'Тип данных: звонки, смс и ммс, интернет';

COMMENT ON COLUMN ALL_PHONE_STAT.INITVALUE IS 'Объём трафика при инициализации';

COMMENT ON COLUMN ALL_PHONE_STAT.CURRVALUE IS 'Текущий доступный трафик';

COMMENT ON COLUMN ALL_PHONE_STAT.CURR_CHECK_DATE IS 'Дата-время текущей проверки';

COMMENT ON COLUMN ALL_PHONE_STAT.NEXT_CHECK_DATE IS 'Дата-время следующей проверки';

COMMENT ON COLUMN ALL_PHONE_STAT.CTRL_PNT IS 'Метка опорной точки, по опорным точкам строится прогноз времени следующей проверки';

COMMENT ON COLUMN ALL_PHONE_STAT.IS_CHECKED IS 'Метка обработки записи';

COMMENT ON COLUMN ALL_PHONE_STAT.ALL_PHONE_TURN_LOG_ID IS 'Ид. записи в логе ALL_PHONE_TURN_LOG';

CREATE INDEX I_ALL_PHONE__STAT_PHN ON ALL_PHONE_STAT
(PHONE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
COMPRESS 1;

CREATE UNIQUE INDEX PK_ALL_PHONE_STAT ON ALL_PHONE_STAT
(ALL_PHONE_STAT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE ALL_PHONE_STAT ADD (
  CONSTRAINT PK_ALL_PHONE_STAT
  PRIMARY KEY
  (ALL_PHONE_STAT_ID)
  USING INDEX PK_ALL_PHONE_STAT);

GRANT SELECT ON ALL_PHONE_STAT TO CORP_MOBILE_ROLE;

GRANT SELECT ON ALL_PHONE_STAT TO CORP_MOBILE_ROLE_RO;