CREATE TABLE API_GET_UNBILLED_CALLS_LOG(
  PHONE_NUMBER VARCHAR2(10 CHAR),
  DATE_INSERT DATE,
  ERROR_TEXT VARCHAR2(500 CHAR)
  );

COMMENT ON TABLE API_GET_UNBILLED_CALLS_LOG IS 'Таблица с логами ошибок по загрузке из API'; 
COMMENT ON COLUMN API_GET_UNBILLED_CALLS_LOG.PHONE_NUMBER IS 'Номер телефона';
COMMENT ON COLUMN API_GET_UNBILLED_CALLS_LOG.DATE_INSERT IS 'Дата вставки';
COMMENT ON COLUMN API_GET_UNBILLED_CALLS_LOG.ERROR_TEXT IS 'Текст ошибки';

create index I_API_GET_UNB_CAL_LOG_PHN on API_GET_UNBILLED_CALLS_LOG(PHONE_NUMBER);


--GRANT SELECT, INSERT, UPDATE, DELETE ON API_GET_CTN_INFO_LIST TO CORP_MOBILE_ROLE;

--GRANT SELECT, INSERT, UPDATE, DELETE ON API_GET_CTN_INFO_LIST TO LONTANA_ROLE;

--GRANT SELECT, INSERT, UPDATE, DELETE ON API_GET_UNBILLED_CALLS_LOG TO SIM_TRADE_ROLE;