CREATE GLOBAL TEMPORARY TABLE API_GET_UNBILLED_CALLS_LIST(
  callDate VARCHAR2(25 CHAR),
  callNumber VARCHAR2(20 CHAR),
  callToNumber VARCHAR2(30 CHAR),
  serviceName VARCHAR2(120 CHAR),
  callType VARCHAR2(120 CHAR),
  dataVolume VARCHAR2(15 CHAR),
  callAmt VARCHAR2(15 CHAR),
  callDuration VARCHAR2(15 CHAR)
  ) ON COMMIT PRESERVE ROWS;
  
COMMENT ON TABLE API_GET_UNBILLED_CALLS_LIST IS 'Временная таблица для загрузки API.getUnbilledCallsList'; 
COMMENT ON COLUMN API_GET_UNBILLED_CALLS_LIST.callDate IS 'Дата звонка';
COMMENT ON COLUMN API_GET_UNBILLED_CALLS_LIST.callNumber IS 'Инициатор звонка';
COMMENT ON COLUMN API_GET_UNBILLED_CALLS_LIST.callToNumber IS 'Принявший звонок';
COMMENT ON COLUMN API_GET_UNBILLED_CALLS_LIST.serviceName IS 'Название услуги';
COMMENT ON COLUMN API_GET_UNBILLED_CALLS_LIST.callType IS 'Тип звонка';
COMMENT ON COLUMN API_GET_UNBILLED_CALLS_LIST.dataVolume IS 'Дата посл активности';
COMMENT ON COLUMN API_GET_UNBILLED_CALLS_LIST.callAmt IS 'Стоимость';
COMMENT ON COLUMN API_GET_UNBILLED_CALLS_LIST.callDuration IS 'Длительность';


CREATE INDEX I_API_GET_U_C_LIST_CALL_TYPE ON API_GET_UNBILLED_CALLS_LIST
  (serviceName, callType);

--GRANT SELECT, INSERT, UPDATE, DELETE ON API_GET_CTN_INFO_LIST TO CORP_MOBILE_ROLE;

--GRANT SELECT, INSERT, UPDATE, DELETE ON API_GET_CTN_INFO_LIST TO LONTANA_ROLE;

--GRANT SELECT, INSERT, UPDATE, DELETE ON API_GET_CTN_INFO_LIST TO SIM_TRADE_ROLE;