CREATE TABLE ARCHIVE_API_GET_PAYMENT_LIST(
  BAN NUMBER(10),
  ctn VARCHAR2(15 CHAR),
  paymentDate VARCHAR2(25 char),
  paymentStatus VARCHAR2(200 CHAR),
  paymentType VARCHAR2(200 char),
  paymentOriginalAmt VARCHAR2(15 CHAR),
  paymentCurrentAmt VARCHAR2(15 char),
  bankPaymentID VARCHAR2(30 CHAR),
  paymentActivateDate VARCHAR2(25 char),
  BEGIN_DATE DATE,
  END_DATE DATE,
  LAST_CHECK_DATE DATE
  ) TABLESPACE TS_ARCHIVE;
  
COMMENT ON TABLE ARCHIVE_API_GET_PAYMENT_LIST IS 'Архив платежей по АПИ'; 
COMMENT ON COLUMN ARCHIVE_API_GET_PAYMENT_LIST.BAN IS 'Лицевой счет';
COMMENT ON COLUMN ARCHIVE_API_GET_PAYMENT_LIST.ctn IS 'Номер телефона';
COMMENT ON COLUMN ARCHIVE_API_GET_PAYMENT_LIST.paymentDate IS 'Дата платежа';
COMMENT ON COLUMN ARCHIVE_API_GET_PAYMENT_LIST.paymentStatus IS 'Статус платежа';
COMMENT ON COLUMN ARCHIVE_API_GET_PAYMENT_LIST.paymentType IS 'Тип платежа';
COMMENT ON COLUMN ARCHIVE_API_GET_PAYMENT_LIST.paymentOriginalAmt IS 'Сумма платежа (внесенная)';
COMMENT ON COLUMN ARCHIVE_API_GET_PAYMENT_LIST.paymentCurrentAmt IS 'Сумма платежа (зачисленная)';
COMMENT ON COLUMN ARCHIVE_API_GET_PAYMENT_LIST.bankPaymentID IS 'ID платежа';
COMMENT ON COLUMN ARCHIVE_API_GET_PAYMENT_LIST.paymentActivateDate IS 'Дата активации платежа';
COMMENT ON COLUMN ARCHIVE_API_GET_PAYMENT_LIST.BEGIN_DATE IS 'Дата начала'; 
COMMENT ON COLUMN ARCHIVE_API_GET_PAYMENT_LIST.END_DATE IS 'Дата конца'; 
COMMENT ON COLUMN ARCHIVE_API_GET_PAYMENT_LIST.LAST_CHECK_DATE IS 'Дата посл проверки'; 

CREATE INDEX I_ARCHIVE_API_GPL 
  ON ARCHIVE_API_GET_PAYMENT_LIST(BAN, ctn, bankPaymentID, END_DATE)
  TABLESPACE TS_ARCHIVE;
