CREATE TABLE AUTO_LOAD_CONTRACTS_LOG
(
  AUTO_LOAD_CONTRACTS_LOG_ID  INTEGER,
  CONTRACT_LINE               VARCHAR2(1000 BYTE),
  USER_CREATED                VARCHAR2(50 BYTE) DEFAULT USER,
  DATE_CREATED                DATE              DEFAULT SYSDATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE AUTO_LOAD_CONTRACTS_LOG IS 'Лог загрузки контратков в автомате. Таблица очищается в 00:00:00 каждый день';

COMMENT ON COLUMN AUTO_LOAD_CONTRACTS_LOG.AUTO_LOAD_CONTRACTS_LOG_ID IS 'Иденитификатор записи';

COMMENT ON COLUMN AUTO_LOAD_CONTRACTS_LOG.CONTRACT_LINE IS 'Строка с контрактом';

COMMENT ON COLUMN AUTO_LOAD_CONTRACTS_LOG.USER_CREATED IS 'Создавший пользователь';

COMMENT ON COLUMN AUTO_LOAD_CONTRACTS_LOG.DATE_CREATED IS 'Дата создания';



CREATE OR REPLACE TRIGGER TBI_AUTO_LOAD_CONTRACTS_LOG
--#Version=1
  BEFORE INSERT ON AUTO_LOAD_CONTRACTS_LOG
  FOR EACH ROW
BEGIN
  IF NVL(:NEW.AUTO_LOAD_CONTRACTS_LOG_ID, 0) = 0 then
    :NEW.AUTO_LOAD_CONTRACTS_LOG_ID := S_AUTO_LOAD_CONTRACTS_LOG_ID.NEXTVAL;
  END IF;
END;
/
