create table AUTO_BLOCKED_PHONE
(
         phone_number  varchar2(50),
         Client_name varchar2(50),
         Client_Surname varchar2(50),
         Ballance     number,
         Date_of_block varchar2(50),
         Time_of_block varchar2(50),
         Note   varchar2(300 CHAR)
); 

ALTER TABLE AUTO_BLOCKED_PHONE ADD BLOCK_DATE_TIME  DATE;


UPDATE AUTO_BLOCKED_PHONE
 SET BLOCK_DATE_TIME=TO_DATE(DATE_OF_BLOCK || ' ' || Time_of_block, 'MM/DD/YYYY HH24:MI')
 WHERE BLOCK_DATE_TIME IS NULL;
 
ALTER TABLE AUTO_BLOCKED_PHONE ADD (MANUAL_BLOCK  NUMBER   DEFAULT 0);

ALTER TABLE AUTO_BLOCKED_PHONE ADD USER_NAME  VARCHAR2(30 CHAR);

ALTER TABLE AUTO_BLOCKED_PHONE ADD ABONENT_FIO  VARCHAR2(100 CHAR);

UPDATE AUTO_BLOCKED_PHONE
 SET ABONENT_FIO=CLIENT_SURNAME || ' ' || CLIENT_NAME
 WHERE ABONENT_FIO IS NULL;
 
CREATE INDEX I_AUTO_BLOCKED_PHONE ON AUTO_BLOCKED_PHONE
(PHONE_NUMBER,BLOCK_DATE_TIME)
LOGGING
NOPARALLEL;
