CREATE TABLE AUTO_BLOCKED_PHONE_NO_CONTRACT(
  PHONE_NUMBER VARCHAR2(10 CHAR) NOT NULL,
  ACCOUNT_NUMBER NUMBER,
  BLOCK_DATE_TIME DATE NOT NULL,
  MANUAL_BLOCK INTEGER DEFAULT 0,
  USER_NAME VARCHAR2(30 CHAR),
  NOTE VARCHAR2(300 CHAR)
  );
  
  -- ’з, что с индексом, но вроде сильно не нужен
CREATE INDEX I_AUTO_BLOCKED_PHONE_NO_CL ON AUTO_BLOCKED_PHONE(
  PHONE_NUMBER,
  BLOCK_DATE_TIME)
  LOGGING
  NOPARALLEL;  
  
--GRANT SELECT, INSERT, DELETE, UPDATE ON AUTO_BLOCKED_PHONE_NO_CONTRACT TO SIM_TRADE_ROLE;  
  
--GRANT SELECT, INSERT, DELETE, UPDATE ON AUTO_BLOCKED_PHONE_NO_CONTRACT TO CORP_MOBILE_ROLE;  

--GRANT SELECT ON AUTO_BLOCKED_PHONE_NO_CONTRACT TO CORP_MOBILE_ROLE_RO;  