CREATE TABLE BALANCE_DATA_LOG(
  BALANCE_ROW_ID INTEGER,
  PHONE_NUMBER NUMBER(10),
  YEAR_MONTH INTEGER,
  CHARGES_TYPE_ID INTEGER,
  CHARGES_DATE DATE,
  CHARGES_SUMM NUMBER(15, 4),
  CHARGES_COMMENT VARCHAR2(150 CHAR), 
  CONTRACT_ID INTEGER,
  DATE_CREATED DATE,
  USER_CREATED VARCHAR2(30 CHAR),
  ACTION_TYPE VARCHAR2(10 CHAR),
  IS_ACTIVE INT,
  TARIFF_ID INT,
  CONSTRAINT FK_BALANCE_DATA_TARIFF_ID
    FOREIGN KEY (TARIFF_ID)
    REFERENCES TARIFFS(TARIFF_ID),
  CONSTRAINT FK_BALANCE_LOG_CHARGES_TYPE_ID
    FOREIGN KEY(CHARGES_TYPE_ID)
    REFERENCES BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID)
  );

COMMENT ON TABLE BALANCE_DATA_LOG IS 'Архив с данными по балансу "НЕ УДАЛЯТЬ"'; 
COMMENT ON COLUMN BALANCE_DATA_LOG.BALANCE_ROW_ID IS 'ИД строки-начисления';
COMMENT ON COLUMN BALANCE_DATA_LOG.PHONE_NUMBER IS 'Телефон';
COMMENT ON COLUMN BALANCE_DATA_LOG.YEAR_MONTH IS 'Год и месяц начисления';
COMMENT ON COLUMN BALANCE_DATA_LOG.CHARGES_TYPE_ID IS 'Тип начисления';
COMMENT ON COLUMN BALANCE_DATA_LOG.CHARGES_DATE IS 'Дата начисления';
COMMENT ON COLUMN BALANCE_DATA_LOG.CHARGES_SUMM IS 'Сумма начисления';
COMMENT ON COLUMN BALANCE_DATA_LOG.CHARGES_COMMENT IS 'Примечание';
COMMENT ON COLUMN BALANCE_DATA_LOG.CONTRACT_ID IS 'ИД договора';
COMMENT ON COLUMN BALANCE_DATA_LOG.DATE_CREATED IS 'Дата создания';
COMMENT ON COLUMN BALANCE_DATA_LOG.USER_CREATED IS 'Имя создателя';
COMMENT ON COLUMN BALANCE_DATA_LOG.ACTION_TYPE IS 'Тип действия';
COMMENT ON COLUMN BALANCE_DATA_LOG.IS_ACTIVE IS 'Акт/Бл';
COMMENT ON COLUMN BALANCE_DATA_LOG.TARIFF_ID IS 'ИД тарифа';

CREATE OR REPLACE TRIGGER TIU_BALANCE_DATA_LOG
  BEFORE INSERT OR UPDATE ON BALANCE_DATA_LOG FOR EACH ROW
-- Version = 1  
BEGIN
  IF :NEW.DATE_CREATED IS NULL THEN
    :NEW.DATE_CREATED:=SYSDATE; 
  END IF;
  IF :NEW.USER_CREATED IS NULL THEN
    :NEW.USER_CREATED:=USER; 
  END IF;
END;
/

CREATE INDEX I_BALANCE_DATA_LOG_PN ON BALANCE_DATA_LOG(PHONE_NUMBER);

GRANT SELECT, INSERT, UPDATE, DELETE ON BALANCE_DATA_LOG TO CORP_MOBILE_ROLE;

GRANT SELECT ON BALANCE_DATA_LOG TO CORP_MOBILE_ROLE_RO;