CREATE TABLE BALANCE_DATA_DAILY_CHARGES(
  PHONE_NUMBER NUMBER(10),
  CHARGES_TYPE_ID INTEGER,
  CHARGES_DATE DATE,
  CHARGES_SUMM NUMBER(15, 4),
  CHARGES_COMMENT VARCHAR2(150 CHAR), 
  CONTRACT_ID INTEGER,
  IS_ACTIVE INT,
  TARIFF_ID INT,
  CONSTRAINT FK_BALANCE_DATA_D_C_TYPE_ID
    FOREIGN KEY (CHARGES_TYPE_ID)
    REFERENCES BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID),
  CONSTRAINT FK_BALANCE_DATA_D_C_TARIFF_ID
    FOREIGN KEY (TARIFF_ID)
    REFERENCES TARIFFS(TARIFF_ID)
  );

COMMENT ON TABLE BALANCE_DATA_DAILY_CHARGES IS 'Таблица с данными по балансу за посл сутки "НЕ УДАЛЯТЬ"'; 
COMMENT ON COLUMN BALANCE_DATA_DAILY_CHARGES.PHONE_NUMBER IS 'Телефон';
COMMENT ON COLUMN BALANCE_DATA_DAILY_CHARGES.CHARGES_TYPE_ID IS 'Тип начисления';
COMMENT ON COLUMN BALANCE_DATA_DAILY_CHARGES.CHARGES_DATE IS 'Дата начисления';
COMMENT ON COLUMN BALANCE_DATA_DAILY_CHARGES.CHARGES_SUMM IS 'Сумма начисления';
COMMENT ON COLUMN BALANCE_DATA_DAILY_CHARGES.CHARGES_COMMENT IS 'Примечание';
COMMENT ON COLUMN BALANCE_DATA_DAILY_CHARGES.CONTRACT_ID IS 'ИД договора';
COMMENT ON COLUMN BALANCE_DATA_DAILY_CHARGES.IS_ACTIVE IS 'Акт/Бл';
COMMENT ON COLUMN BALANCE_DATA_DAILY_CHARGES.TARIFF_ID IS 'ИД тарифа';

CREATE INDEX I_BALANCE_DATA_D_C_PN ON BALANCE_DATA_DAILY_CHARGES(PHONE_NUMBER);

CREATE INDEX I_BALANCE_DATA_D_C_CTID ON BALANCE_DATA_DAILY_CHARGES(CHARGES_TYPE_ID);