CREATE TABLE BALANCE_CHARGES_TYPES(
  CHARGES_TYPE_ID INTEGER PRIMARY KEY,
  TYPE_NAME VARCHAR2(50 CHAR),
  CREDIT_ALLOWED INTEGER DEFAULT 0
  );

COMMENT ON TABLE BALANCE_CHARGES_TYPES IS 'Таблица с типами данных по балансу "НЕ УДАЛЯТЬ"'; 
COMMENT ON COLUMN BALANCE_CHARGES_TYPES.CHARGES_TYPE_ID IS 'Тип начисления';
COMMENT ON COLUMN BALANCE_CHARGES_TYPES.TYPE_NAME IS 'Название';

GRANT SELECT, INSERT, UPDATE, DELETE ON BALANCE_CHARGES_TYPES TO CORP_MOBILE_ROLE;

GRANT SELECT ON BALANCE_CHARGES_TYPES TO CORP_MOBILE_ROLE_RO;

INSERT INTO BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID, TYPE_NAME)
  VALUES(-1, 'Тип неопределен');

INSERT INTO BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID, TYPE_NAME)
  VALUES(1, 'Абоненская плата за тарифный план');

INSERT INTO BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID, TYPE_NAME)
  VALUES(2, 'Абоненская плата за услугу');

INSERT INTO BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID, TYPE_NAME)
  VALUES(3, 'Сумма звонков по отчету о тек. начислениях');

INSERT INTO BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID, TYPE_NAME)
  VALUES(4, 'Сумма звонков по детализации');

INSERT INTO BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID, TYPE_NAME)
  VALUES(5, 'Плата за подключение услуги');

INSERT INTO BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID, TYPE_NAME)
  VALUES(6, 'Рассрочка для абонента');

INSERT INTO BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID, TYPE_NAME)
  VALUES(7, 'Депозит абонента');

INSERT INTO BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID, TYPE_NAME)
  VALUES(10, 'Счет абонента');

INSERT INTO BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID, TYPE_NAME)
  VALUES(11, 'Платеж: Стартовый баланс');

INSERT INTO BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID, TYPE_NAME)
  VALUES(12, 'Платеж: Регистрация в офисе');

INSERT INTO BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID, TYPE_NAME)
  VALUES(13, 'Платеж: Компенсация');

INSERT INTO BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID, TYPE_NAME)
  VALUES(20, 'Платеж: денежный перевод');

INSERT INTO BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID, TYPE_NAME)
  VALUES(8, 'Абоненская плата за тарифный план(дискретно)');

INSERT INTO BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID, TYPE_NAME)
  VALUES(9, 'Абоненская плата за услугу(дискретно)');

INSERT INTO BALANCE_CHARGES_TYPES(CHARGES_TYPE_ID, TYPE_NAME)
  VALUES(21, 'Абонентская плата за доп. статус');
  