CREATE TABLE BEELINE_OPTION_CODE(
  OPTION_ID INTEGER PRIMARY KEY,
  OPTION_CODE VARCHAR2(30 CHAR),
  OPTION_NAME VARCHAR2(200 CHAR),
  SINGLE_MAIN NUMBER(15,4) DEFAULT 0,
  ABON_MAIN NUMBER(15,4) DEFAULT 0,
  ENABLED NUMBER(1) DEFAULT 0,
  DISCR_SPISANIE NUMBER(1) DEFAULT 0,
  DILER_KOEFF NUMBER(1) DEFAULT 0
  );

COMMENT ON COLUMN BEELINE_OPTION_CODE.OPTION_ID IS 'ИД опции/пакета'; 
COMMENT ON COLUMN BEELINE_OPTION_CODE.OPTION_CODE IS 'Код опции';
COMMENT ON COLUMN BEELINE_OPTION_CODE.OPTION_NAME IS 'Название опции';     
COMMENT ON COLUMN BEELINE_OPTION_CODE.SINGLE_MAIN IS 'Подключение';
COMMENT ON COLUMN BEELINE_OPTION_CODE.ABON_MAIN IS 'Абон. плата';     
COMMENT ON COLUMN BEELINE_OPTION_CODE.ENABLED IS 'Включенали';     
COMMENT ON COLUMN BEELINE_OPTION_CODE.DISCR_SPISANIE IS 'Дискретное списание'; 
COMMENT ON COLUMN BEELINE_OPTION_CODE.DILER_KOEFF IS 'Коэффициент для дилеров'; 

CREATE UNIQUE INDEX I_BEELINE_OPTION_CODE_OPT_CODE 
  ON BEELINE_OPTION_CODE(OPTION_CODE);