CREATE TABLE BEELINE_BS_ZONES
(
  BEELINE_BS_ZONE_ID INTEGER,
  ZONE_NAME          VARCHAR2(30 CHAR),
  USER_CREATED       VARCHAR2(30 CHAR),
  DATE_CREATED       DATE,
  USER_LAST_UPDATED  VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED  DATE
);

ALTER TABLE BEELINE_BS_ZONES ADD CONSTRAINT PK_BEELINE_BS_ZONES PRIMARY KEY (BEELINE_BS_ZONE_ID);

CREATE OR REPLACE TRIGGER TIU_BEELINE_BS_ZONES
  BEFORE INSERT OR UPDATE ON BEELINE_BS_ZONES FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/

 

COMMENT ON TABLE BEELINE_BS_ZONES IS 'Тарифные зоны базовых станций Билайн';

COMMENT ON COLUMN BEELINE_BS_ZONES.BEELINE_BS_ZONE_ID IS 'Код (номер) базовой станции';

COMMENT ON COLUMN BEELINE_BS_ZONES.ZONE_NAME IS 'Название тарифной зоны';

COMMENT ON COLUMN BEELINE_BS_ZONES.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN BEELINE_BS_ZONES.DATE_CREATED IS 'Дата/время создания записи';

COMMENT ON COLUMN BEELINE_BS_ZONES.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';

COMMENT ON COLUMN BEELINE_BS_ZONES.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';
 
CREATE SYNONYM DB_LOADER.BEELINE_BS_ZONES FOR BEELINE_BS_ZONES;

GRANT SELECT ON BEELINE_BS_ZONES TO DB_LOADER;
