CREATE TABLE BEELINE_STATUS_CODE(
  STATUS_ID INTEGER PRIMARY KEY,
  STATUS_CODE VARCHAR2(20 CHAR) NOT NULL,
  IS_ACTIVE INTEGER NOT NULL,
  IS_CONSERVATION INTEGER NOT NULL,
  IS_SYSTEM_BLOCK INTEGER NOT NULL,
  ACCESS_BLOCK INTEGER NOT NULL,
  ACCESS_UNLOCK INTEGER NOT NULL,
  COMMENT_BEELINE VARCHAR2(1000 CHAR),
  COMMENT_CLENT VARCHAR2(1000 CHAR),
  INFO_COLOR VARCHAR2(30 CHAR)
  );
    
COMMENT ON TABLE BEELINE_STATUS_CODE IS 'Коды статусов номеров в АПИ Билайн';
COMMENT ON COLUMN BEELINE_STATUS_CODE.STATUS_CODE IS 'Код статуса';
COMMENT ON COLUMN BEELINE_STATUS_CODE.IS_ACTIVE IS 'Номер активен';
COMMENT ON COLUMN BEELINE_STATUS_CODE.IS_CONSERVATION IS 'Номер на сохранении';
COMMENT ON COLUMN BEELINE_STATUS_CODE.IS_SYSTEM_BLOCK IS 'Номер в системном блоке';
COMMENT ON COLUMN BEELINE_STATUS_CODE.ACCESS_BLOCK IS 'Доступна блокировка';
COMMENT ON COLUMN BEELINE_STATUS_CODE.ACCESS_UNLOCK IS 'Доступна разблокировка';
COMMENT ON COLUMN BEELINE_STATUS_CODE.COMMENT_BEELINE IS 'Комментарий Билайна';
COMMENT ON COLUMN BEELINE_STATUS_CODE.COMMENT_CLENT IS 'Комментарий Клиента';
COMMENT ON COLUMN BEELINE_STATUS_CODE.INFO_COLOR IS 'Цвет статуса';

CREATE SEQUENCE S_NEW_STATUS_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE OR REPLACE FUNCTION NEW_STATUS_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_STATUS_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;

CREATE OR REPLACE TRIGGER TIU_BEELINE_STATUS_CODE
  BEFORE INSERT OR UPDATE ON BEELINE_STATUS_CODE FOR EACH ROW 
--#Version=1
BEGIN 
  IF INSERTING THEN 
    IF NVL(:NEW.STATUS_ID, 0) = 0 then 
      :NEW.STATUS_ID := NEW_STATUS_ID; 
    END IF; 
  END IF;
END;
/

INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('ATNO', 1, 0, 0, 1, 0, 'Move-Переоформление','Активен: Переоформление','Green');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('BDB', 0, 1, 1, 0, 0, 'Suspend-Долг на постпейд BAN (полная)','Блокирован: Долг на постпейд BAN (полная)','Red');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('BLB', 0, 1, 1, 0, 0, 'Suspend-Black List (полная)','Блокирован: Black List (полная)','Red');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('BLI', 0, 1, 1, 0, 0, 'Suspend-Identification (полная)','Блокирован до идентификации абонента (полная)','Red');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('BSB', 0, 1, 1, 0, 0, 'Suspend-Мошенничество(согл.п.4.1 д-ра)','Блокирован: Мошенничество(согл.п.4.1 д-ра)','Purple');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('COL', 1, 0, 0, 1, 0, 'Restore-Подтверждение платежа(полная)','Активен: Подтверждение платежа(полная)','Green');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('COO', 1, 0, 0, 1, 0, 'Restore-Подтверждение платежа(исходящ)','Активен: Подтверждение платежа(исходящ)','Green');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('DOSS', 0, 1, 1, 0, 0, 'Suspend-DoS (Корпор. Безопасность) SUS','Блокирован: DoS (Корпор. Безопасность)','Purple');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('DUF', 0, 1, 1, 0, 0, 'Suspend-По фроду(ДУФиГД)','Блокирован: По фроду(ДУФиГД)','Purple');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('F1B', 0, 1, 1, 0, 0, 'Suspend-По финансам (полная)','Блокирован: По финансам (полная)','Red');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('F1O', 0, 1, 1, 0, 0, 'Suspend-По финансам (исходящая)','Блокирован: По финансам (исходящая)','Red');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('FAB', 0, 1, 1, 0, 0, 'Suspend-Достижение неснижаемого порога','Блокирован: Достижение неснижаемого порога','Red');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('FOUT', 0, 1, 1, 0, 0, 'Suspend-По фроду-исх.связь (ДУФиГД)SUS','Блокирован: По фроду-исх.связь (ДУФиГД)SUS','Purple');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('GFA', 1, 0, 0, 1, 0, 'Restore-GPRS','Активен: GPRS','Green');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('GSMG', 0, 1, 1, 0, 0, 'Suspend-GSM шлюз (ДУФиГД)-полная SUS','Блокирован: GSM шлюз (ДУФиГД)-полная','Purple');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('LOB', 0, 1, 0, 0, 0, 'Suspend-Limit Option расторжение','Блокирован: Limit Option расторжение','Red');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('NCTN', 1, 0, 0, 1, 0, 'Activate-New CTN','Активен: Активация номера','Green');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('NR', 1, 0, 0, 1, 0, 'Restore-По желанию (полная)','Активен','Green');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('OTB', 0, 1, 0, 0, 0, 'Suspend-Другое (полная)','Блокирован: Другое (полная)','Red');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('PORT', 1, 0, 0, 1, 0, 'Change-Port IN','Активен: Портация номера','Green');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('RCTC', 1, 0, 0, 1, 0, 'Resume-Technical','Активен: Возврат из тех. Расторжения','Green');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('RLE', 0, 1, 1, 0, 0, 'Suspend-Запрос правоохранительных орга','Блокирован: Запрос правоохр. Органов','Purple');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('RMB', 0, 1, 1, 0, 0, 'Suspend-По роумингу (полная)','Блокирован: По роумингу (полная)','Red');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('RS1B', 1, 0, 0, 1, 0, 'Restore-Сохранение (полная)','Активен','Green');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('RSB', 1, 0, 0, 1, 0, 'Restore-Другое (полная)','Активен','Green');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('RSBI', 1, 0, 0, 1, 0, 'Restore-Identification (полная)','Активен: после идентификации абонента (полная)','Green');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('RSBO', 1, 0, 0, 1, 0, 'Restore-По желанию (полная)','Активен','Green');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('RSOT', 1, 0, 0, 1, 0, 'Restore-По желанию (исходящая)','Активен','Green');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('S1B', 0, 1, 0, 0, 1, 'Suspend-Сохранение (полная)','Блокирован по сохранению','Red');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('SMB', 0, 1, 1, 0, 0, 'Suspend-Продажа через супермаркет','Блокирован: Продажа через супермаркет','Purple');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('SOD', 0, 1, 1, 0, 0, 'Suspend-Долг у опер.-донора полная SUS','Блокирован: Долг у опер.-донора полная SUS','Purple');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('SPAM', 0, 1, 1, 0, 0, 'Suspend-СПАМ (ДУФиГД) - полная SUS','Блокирован: СПАМ (ДУФиГД) - полная','Purple');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('STB', 0, 1, 0, 0, 1, 'Suspend-По утере/краже (полная)','Блокирован: По утере/краже (полная)','Red');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('STO', 0, 1, 0, 0, 1, 'Suspend-По утере/краже (исходящая)','Блокирован: По утере/краже (исходящая)','Red');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('USB', 0, 1, 1, 0, 0, 'Suspend-По трафику (полная)','Блокирован: По трафику (полная)','Purple');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('USO', 0, 1, 1, 0, 0, 'Suspend-По трафику (исходящая)','Блокирован: По трафику (исходящая)','Purple');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('WIO', 0, 0, 0, 0, 1, 'Suspend-По желанию (исходящая)','Блокирована исходящая связь','Yellow');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('WIB', 0, 0, 0, 0, 1, 'Suspend-По желанию (полная)','Блокирован по желанию: полная','Yellow');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('ZGSM', 0, 1, 1, 0, 0, 'Suspend-GSM шлюз (ДУФиГД)-полная SUS','Блокирован: GSM шлюз (ДУФиГД)-полная SUS','Purple');
INSERT INTO BEELINE_STATUS_CODE(STATUS_CODE,IS_ACTIVE,IS_CONSERVATION,IS_SYSTEM_BLOCK,ACCESS_BLOCK,ACCESS_UNLOCK,COMMENT_BEELINE,COMMENT_CLENT, INFO_COLOR)
  VALUES('ZSPA', 0, 1, 1, 0, 0, 'Suspend-СПАМ (ДУФиГД) - полная SUS','Блокирован: СПАМ (ДУФиГД) - полная','Purple');
   
CREATE UNIQUE INDEX I_BEELINE_STATUS_CODE_ID_CODE
ON BEELINE_STATUS_CODE(STATUS_ID, STATUS_CODE);

CREATE UNIQUE INDEX I_BEELINE_STATUS_CODE_CODE
ON BEELINE_STATUS_CODE(STATUS_CODE);

CREATE UNIQUE INDEX I_BEELINE_STATUS_CODE_S_DATA
ON BEELINE_STATUS_CODE(STATUS_ID, STATUS_CODE, IS_ACTIVE, IS_CONSERVATION, IS_SYSTEM_BLOCK);
                           
--GRANT SELECT, INSERT, DELETE, UPDATE ON BEELINE_STATUS_CODE TO CORP_MOBILE_ROLE;    

--GRANT SELECT ON BEELINE_STATUS_CODE TO CORP_MOBILE_ROLE_RO;
                           
--GRANT SELECT, INSERT, DELETE, UPDATE ON BEELINE_STATUS_CODE TO LONTANA_ROLE;  
                           
--GRANT SELECT, INSERT, DELETE, UPDATE ON BEELINE_STATUS_CODE TO SIM_TRADE_ROLE;    