CREATE TABLE BILL_FOR_CLIENTS_SAVED(
  ACCOUNT_ID INTEGER NOT NULL, 
  YEAR_MONTH INTEGER NOT NULL, 
  PHONE_NUMBER VARCHAR2(10 CHAR) NOT NULL, 
  DATE_BEGIN DATE NOT NULL,
  DATE_END DATE NOT NULL, 
  DISCOUNT_VALUE NUMBER(15, 2) NOT NULL,
  SUBSCRIBER_PAYMENT_COEF NUMBER(15, 9) NOT NULL,
  OPTION_CORRECT_SUM NUMBER(15, 2), 
  BILL_SUM_ORIGIN NUMBER(15, 2),
  BILL_SUM NUMBER(15, 2) NOT NULL,
  SUBSCRIBER_PAYMENT_NEW NUMBER(15, 2),
  SUBSCRIBER_PAYMENT_OLD NUMBER(15, 2),
  TARIFF_ID INTEGER NOT NULL,
  SUBSCRIBER_PAYMENT_ADD_OLD NUMBER(15, 2),  
  SUBSCRIBER_PAYMENT_ADD_VOZVRAT NUMBER(15, 2),
  BILL_CHECKED INTEGER,
  USER_CREATED VARCHAR2(30 CHAR),
  DATE_CREATED DATE,
  USER_LAST_UPDATED VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED DATE
  );

CREATE OR REPLACE TRIGGER TIU_BILL_FOR_CLIENTS_SAVED
  BEFORE INSERT OR UPDATE ON BILL_FOR_CLIENTS_SAVED FOR EACH ROW
  --Version=1
BEGIN
  IF INSERTING THEN
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;  
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/

CREATE INDEX I_BILL_FOR_CLIENTS_SAVED_DATE ON BILL_FOR_CLIENTS_SAVED
(PHONE_NUMBER, ACCOUNT_ID, YEAR_MONTH, DATE_END, BILL_CHECKED)
LOGGING
NOPARALLEL;  


CREATE INDEX I_BILL_FOR_CLIENTS_SAVED ON BILL_FOR_CLIENTS_SAVED
(PHONE_NUMBER, ACCOUNT_ID, YEAR_MONTH)
LOGGING
NOPARALLEL; 

GRANT INSERT, SELECT, UPDATE, DELETE ON BILL_FOR_CLIENTS_SAVED TO LONTANA_ROLE;

--GRANT INSERT, SELECT, UPDATE, DELETE ON BILL_FOR_CLIENTS_SAVED TO CORP_MOBILE_ROLE;