CREATE TABLE BILL_RECALC_ADD_COST(
  ACCOUNT_ID INTEGER NOT NULL,
  YEAR_MONTH INTEGER NOT NULL,
  PHONE_NUMBER VARCHAR2(10 CHAR) NOT NULL,
  CALLS_ALL NUMBER(15, 4) NOT NULL,
  CALLS NUMBER(15, 4) NOT NULL,
  SMS NUMBER(15, 4) NOT NULL,
  DATE_CHECK DATE
  ); 
    
CREATE UNIQUE INDEX UNIQUE_BILL_ADD_COST_AD_YM_PH ON BILL_RECALC_ADD_COST
(ACCOUNT_ID, YEAR_MONTH, PHONE_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE TRIGGER TIU_BILL_RECALC_ADD_COST
  BEFORE INSERT OR UPDATE ON BILL_RECALC_ADD_COST FOR EACH ROW
--#Version=1
BEGIN
  IF UPDATING THEN
    IF (:NEW.CALLS_ALL < :OLD.CALLS_ALL) OR (:NEW.CALLS < :OLD.CALLS) OR (:NEW.SMS < :OLD.SMS) THEN
      :NEW.CALLS_ALL := :OLD.CALLS_ALL;
      :NEW.CALLS := :OLD.CALLS;
      :NEW.SMS := :OLD.SMS;
    END IF;
  END IF;
  :NEW.DATE_CHECK := SYSDATE;
END;