/*CREATE TABLE CALL_2015_11_KOK(
SUBSCR_NO NUMBER(11),
START_TIME DATE,
AT_FT_CODE VARCHAR2(6 Byte),
DBF_ID NUMBER(12),
CALL_COST NUMBER,
COSTNOVAT NUMBER,
DUR NUMBER,
IMEI NUMBER(15),
SERVICETYPE VARCHAR2(1 Byte),
SERVICEDIRECTION NUMBER(1),
DURATION VARCHAR2(8 Byte),
DIALED_DIG VARCHAR2(21 Byte),
CALLING_NO VARCHAR2(21 Byte),
AT_CHG_AMT NUMBER,
DATA_VOL NUMBER,
CELL_ID NUMBER(6),
MN_UNLIM NUMBER(1),
INSERT_DATE DATE,
COST_CHNG NUMBER,
ROAMING_PROVIDER_ID INTEGER
);*/

BEGIN
  INSERT INTO CALL_2015_11_KOK(SUBSCR_NO, START_TIME, AT_FT_CODE, DBF_ID,
                               CALL_COST, COSTNOVAT, DUR, IMEI,
                               SERVICETYPE, SERVICEDIRECTION, DURATION, DIALED_DIG,
                               CALLING_NO, AT_CHG_AMT, DATA_VOL, CELL_ID,
                               MN_UNLIM, INSERT_DATE, COST_CHNG, ROAMING_PROVIDER_ID)
    SELECT TO_NUMBER(SUBSCR_NO), START_TIME, CASE WHEN DBF_ID = 7529 THEN '7529' ELSE AT_FT_CODE END AT_FT_CODE, DBF_ID,
           CALL_COST, COSTNOVAT, DUR, TO_NUMBER(IMEI),
           SERVICETYPE, SERVICEDIRECTION, DURATION, DIALED_DIG,
           CALLING_NO, TO_NUMBER(AT_CHG_AMT), TO_NUMBER(DATA_VOL), TO_NUMBER(CELL_ID),
           MN_UNLIM, INSERT_DATE, COST_CHNG, ROAMING_PROVIDER_ID
      FROM CALL_2015_11_KOK2;                                
  COMMIT;
END;  
