CREATE TABLE COLLECTOR_BILL_XML(
  FILE_ID INTEGER,
  YEAR_MONTH INTEGER,
  FILE_NAME VARCHAR2(500 CHAR),
  XML_TXT CLOB,
  DATE_INSERT DATE,
  XML_CHECKED INTEGER
  );
  
CREATE SEQUENCE S_NEW_COLL_BILL_FILE_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;  
  
CREATE OR REPLACE FUNCTION NEW_BILL_FILE_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_COLL_BILL_FILE_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;  
  
CREATE OR REPLACE TRIGGER TIU_COLLECTOR_BILL_XML
  BEFORE INSERT OR UPDATE ON COLLECTOR_BILL_XML FOR EACH ROW
DECLARE
vXML XMLTYPE;
vYM INTEGER;
BEGIN
  IF INSERTING THEN
    :NEW.DATE_INSERT:=SYSDATE;
    :NEW.FILE_ID:=NEW_BILL_FILE_ID;
    :NEW.XML_CHECKED:=0;
  END IF; 
  IF (INSERTING) 
      OR ((UPDATING) AND (:NEW.XML_CHECKED = :OLD.XML_CHECKED) AND (:NEW.BAN = :OLD.BAN) AND (:NEW.ACCOUNT_ID = :OLD.ACCOUNT_ID)) THEN
    SELECT TO_CHAR(TO_DATE(extractVALUE(xmltype(:NEW.XML_TXT),'XML_BILL/ECare_Corporate_Str/ECare_Corporate_Info/BILL_prd_cvrg_end_date'), 'DD/MM/YYYY'), 'YYYYMM'),
           TO_NUMBER(extractVALUE(xmltype(:NEW.XML_TXT),'XML_BILL/ECare_Corporate_Str/ECare_Corporate_Info/BILL_ban'))
      INTO :NEW.YEAR_MONTH, :NEW.BAN
      FROM DUAL;
  END IF; 
END;
/


CREATE OR REPLACE TRIGGER TIU_COLLECTOR_BILL_XML
  BEFORE INSERT OR UPDATE ON COLLECTOR_BILL_XML FOR EACH ROW
DECLARE
vXML XMLTYPE;
vYM INTEGER;
vACC varchar2(30 char);
BEGIN
  IF INSERTING THEN
    :NEW.DATE_INSERT:=SYSDATE;
    :NEW.FILE_ID:=NEW_BILL_FILE_ID;
    IF NVL(:NEW.XML_CHECKED, 0) <> -1 THEN
      :NEW.XML_CHECKED:=0;
    END IF;
  END IF; 
  IF ((INSERTING) and (:NEW.XML_CHECKED <> -1)) 
      OR ((UPDATING) AND (:NEW.XML_CHECKED = :OLD.XML_CHECKED) AND (:NEW.BAN = :OLD.BAN) AND (:NEW.ACCOUNT_ID = :OLD.ACCOUNT_ID))
      OR ((UPDATING) AND (:NEW.XML_CHECKED = 0) AND (:OLD.XML_CHECKED = -1)) THEN
    SELECT TO_CHAR(TO_DATE(extractVALUE(xmltype(:NEW.XML_TXT),'XML_BILL/ECare_Corporate_Str/ECare_Corporate_Info/BILL_prd_cvrg_end_date'), 'DD/MM/YYYY'), 'YYYYMM'),
           TO_NUMBER(extractVALUE(xmltype(:NEW.XML_TXT),'XML_BILL/ECare_Corporate_Str/ECare_Corporate_Info/BILL_ban')),
           TO_NUMBER(extractVALUE(xmltype(:NEW.XML_TXT),'XML_BILL/ECare_Corporate_Str/ECare_Corporate_Info/WORK_corporate_id'))
      INTO :NEW.YEAR_MONTH, :NEW.BAN, vACC
      FROM DUAL;
    :NEW.ACCOUNT_ID:=CASE
                       WHEN vACC = 4582633 THEN 93
                       WHEN vACC = 4965132 THEN 99
                       when vACC = 7040749 THEN 128
                       ELSE 930
                     END;
  END IF; 
END;
/