--DROP TABLE CONGR_TARIF CASCADE CONSTRAINTS;

CREATE TABLE CONGR_TARIF
(
  TARIFFS_ATTRIBUTES_ID  INTEGER                NOT NULL,
  TARIFF_ID              INTEGER                NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
/

COMMENT ON TABLE CONGR_TARIF IS 'Таблица соответствий тарифов и их атрибутов';

COMMENT ON COLUMN CONGR_TARIF.TARIFFS_ATTRIBUTES_ID IS 'Ссылка на таблицу TARIFFS_ATTRS';
/
COMMENT ON COLUMN CONGR_TARIF.TARIFF_ID IS 'Ссылка на таблицу TARIFFS';
/


ALTER TABLE CONGR_TARIF ADD (
  FOREIGN KEY (TARIFFS_ATTRIBUTES_ID) 
  REFERENCES TARIFFS_ATTRS (TARIFFS_ATTRIBUTES_ID)
  DEFERRABLE INITIALLY IMMEDIATE
  ENABLE NOVALIDATE);
/

--
begin
  for rec in (
                select *
                from tariffs
                order by tariff_id
              )
  loop
    INSERT INTO CONGR_TARIF(TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
        VALUES (7, rec.tariff_id);
  end loop;     
  commit;        
end;

--схемы подкл. пакетов
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (224, 2060);
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (224, 2061);
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (224, 2254);
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (224, 2255);		
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (225, 2062);
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (232, 2256);
--доступные опции по тарифу 2060
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (230, 2060);
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (229, 2060);
--доступные опции по тарифу 2061
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (230, 2061);
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (229, 2061);
--доступные опции по тарифу 2254
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (230, 2254);
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (229, 2254);
--доступные опции по тарифу 2255	
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (230, 2255);
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (229, 2255);
--доступные опции по тарифу 2062	
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (227, 2062);
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (228, 2062);	
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (229, 2062);
--доступные опции по тарифу 2062	
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (231, 2256);
INSERT INTO CONGR_TARIF (TARIFFS_ATTRIBUTES_ID, TARIFF_ID) 
    VALUES (229, 2256);	
	
commit;