CREATE TABLE CONTRACT_DOP_STATUSES
(
  DOP_STATUS_ID      NUMBER NOT NULL,
  DOP_STATUS_NAME    VARCHAR2(100 CHAR),
  USER_CREATED       VARCHAR2(30 CHAR),
  DATE_CREATED       DATE,
  USER_LAST_UPDATED  VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CONTRACT_DOP_STATUSES IS 'Доп. статусы контрактов';

COMMENT ON COLUMN CONTRACT_DOP_STATUSES.DOP_STATUS_ID IS 'Первичный ключ';

COMMENT ON COLUMN CONTRACT_DOP_STATUSES.DOP_STATUS_NAME IS 'Наименование доп.статуса';

COMMENT ON COLUMN CONTRACT_DOP_STATUSES.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN CONTRACT_DOP_STATUSES.DATE_CREATED IS 'Дата/время создания записи';

COMMENT ON COLUMN CONTRACT_DOP_STATUSES.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';

COMMENT ON COLUMN CONTRACT_DOP_STATUSES.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';

CREATE UNIQUE INDEX PK_DOP_STATIS_ID ON CONTRACT_DOP_STATUSES
(DOP_STATUS_ID)
LOGGING
NOPARALLEL;

alter table CONTRACT_DOP_STATUSES
  add constraint PK_DOP_ST_KEY primary key (DOP_STATUS_ID);


CREATE SEQUENCE S_NEW_DOP_STATUS_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
  

CREATE OR REPLACE FUNCTION NEW_DOP_STATUS_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_DOP_STATUS_ID.NEXTVAL
    INTO vRES
    FROM DUAL;
  RETURN vRES;
END;

CREATE OR REPLACE TRIGGER TIU_CONTRACT_DOP_STATUSES
  BEFORE INSERT OR UPDATE ON CONTRACT_DOP_STATUSES FOR EACH ROW
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.DOP_STATUS_ID, 0) = 0 THEN
      :NEW.DOP_STATUS_ID := NEW_DOP_STATUS_ID;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/


/*GRANT DELETE, INSERT, SELECT, UPDATE ON CONTRACT_DOP_STATUSES TO CORP_MOBILE_ROLE;
GRANT SELECT ON CONTRACT_DOP_STATUSES TO CORP_MOBILE_ROLE_RO;
GRANT SELECT ON S_NEW_DOP_STATUS_ID TO CORP_MOBILE_ROLE;
GRANT SELECT ON S_NEW_DOP_STATUS_ID TO CORP_MOBILE_ROLE_RO;
GRANT EXECUTE ON NEW_DOP_STATUS_ID TO CORP_MOBILE_ROLE;
GRANT EXECUTE ON NEW_DOP_STATUS_ID TO CORP_MOBILE_ROLE_RO;*/

/*GRANT DELETE, INSERT, SELECT, UPDATE ON CONTRACT_DOP_STATUSES TO SIM_TRADE_ROLE;
GRANT SELECT ON S_NEW_DOP_STATUS_ID TO SIM_TRADE_ROLE;
GRANT EXECUTE ON NEW_DOP_STATUS_ID TO SIM_TRADE_ROLE;*/

--#if not ColumnExists("CONTRACT_DOP_STATUSES.DO_BLOCK_PHONE")
ALTER TABLE CONTRACT_DOP_STATUSES ADD DO_BLOCK_PHONE NUMBER(1);
COMMENT ON COLUMN CONTRACT_DOP_STATUSES.DO_BLOCK_PHONE IS 'Выполнять блокировку номеров по сохранению с данным доп. статусом';
--#end if