--DROP TABLE CONTRACT_BALANCES;

CREATE SEQUENCE S_NEW_CONTRACT_BALANCE_ID;

CREATE TABLE CONTRACT_BALANCES (
  CONTRACT_BALANCE_ID      INTEGER 
    CONSTRAINT PK_CONTRACT_BALANCE_ID PRIMARY KEY,
  CONTRACT_ID           INTEGER 
    CONSTRAINT FK_CONTRACT_BALANCE_CONTRACT REFERENCES CONTRACTS
    CONSTRAINT NN_CONTRACT_BALANCE_CONTRACT NOT NULL,
  BALANCE_DATE          DATE CONSTRAINT NN_CONTRACT_BALANCE_DATE NOT NULL,
  BALANCE_VALUE         NUMBER(15, 2) NOT NULL,
  USER_CREATED          VARCHAR2(30 CHAR),
  DATE_CREATED          DATE,
  USER_LAST_UPDATED     VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED     DATE
);

ALTER TABLE CONTRACT_BALANCES
ADD PHONE_NUMBER VARCHAR2(10 CHAR);

UPDATE CONTRACT_BALANCES 
SET 
  PHONE_NUMBER=
    (SELECT PHONE_NUMBER_FEDERAL FROM CONTRACTS WHERE CONTRACTS.CONTRACT_ID=CONTRACT_BALANCES.CONTRACT_ID);
    

COMMENT ON TABLE CONTRACT_BALANCES IS 'Баланс по договору';

COMMENT ON COLUMN CONTRACT_BALANCES.CONTRACT_BALANCE_ID IS 'Первичный ключ';

COMMENT ON COLUMN CONTRACT_BALANCES.BALANCE_VALUE  IS 'Оплаченная сумма';

COMMENT ON COLUMN CONTRACT_BALANCES.BALANCE_DATE IS 'Дата и время платежа';

COMMENT ON COLUMN RECEIVED_PAYMENTS.CONTRACT_ID  IS 'Код договора';

-- Уникальность позволяет сделать только одну запись для договора на дату
CREATE UNIQUE INDEX UQ_CONTRACT_BALANCE_CONTR_DATE ON CONTRACT_BALANCES (
  CONTRACT_ID, 
  BALANCE_DATE
  );

CREATE OR REPLACE FUNCTION NEW_CONTRACT_BALANCE_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_CONTRACT_BALANCE_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;
/

SHOW ERRORS;


CREATE OR REPLACE TRIGGER TIU_CONTRACT_BALANCES
  BEFORE INSERT OR UPDATE ON CONTRACT_BALANCES FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.CONTRACT_BALANCE_ID, 0) = 0 then
      :NEW.CONTRACT_BALANCE_ID := NEW_CONTRACT_BALANCE_ID;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/
SHOW ERRORS;

