CREATE TABLE CRM_UNBLOCK_PHONE_LOG
(
  PHONE_NUMBER      VARCHAR2(10 CHAR),
  BALANCE           INTEGER,
  DATE_INSERT       DATE,
  ERROR_TEXT        VARCHAR2(2000 CHAR),
  CRM_MESSAGE_TYPE  INTEGER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE CRM_UNBLOCK_PHONE_LOG ADD DOP_STATUS_ID INTEGER;

COMMENT ON COLUMN CRM_UNBLOCK_PHONE_LOG.DOP_STATUS_ID IS 'ÍÀﬁ◊ Õ¿ ƒŒœ —“¿“”— ƒŒ√Œ¬Œ–¿';

ALTER TABLE CRM_UNBLOCK_PHONE_LOG 
  ADD CONSTRAINT FK_CRM_UNBLOCK_LOG_D_STATUS_ID
  FOREIGN KEY (DOP_STATUS_ID) REFERENCES CONTRACT_DOP_STATUSES(DOP_STATUS_ID);

ALTER TABLE CRM_UNBLOCK_PHONE_LOG 
  ADD CONSTRAINT FK_CRM_UNBLOCK_LOG_D_CRM_M_T
  FOREIGN KEY (CRM_MESSAGE_TYPE) REFERENCES CRM_UNBLOCK_PHONE_TYPE(CUP_ID);