CREATE TABLE DB_LOADER_ABONENT_PERIODS(
  YEAR_MONTH INTEGER,
  PHONE_NUMBER VARCHAR2(10 CHAR),
  BEGIN_DATE DATE,
  END_DATE DATE,
  TARIFF_CODE VARCHAR2(10 CHAR),
  IS_ACTIVE INTEGER,
  TARIFF_ID INTEGER,
  check_date date
  );
  
CREATE INDEX I_DB_L_ABON_PER_PH_YM ON DB_LOADER_ABONENT_PERIODS(YEAR_MONTH, PHONE_NUMBER);