CREATE SEQUENCE DB_LOADER_RESTS_ID
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE TABLE DB_LOADER_RESTS
(
  RESTS_ID     NUMBER(38),
  LOAD_DATE    TIMESTAMP(6),
  PHONE        VARCHAR2(10 CHAR),
  UNITTYPE     VARCHAR2(32 CHAR),
  RESTTYPE     VARCHAR2(16 CHAR),
  INITIALSIZE  NUMBER(18,2),
  CURRVALUE    NUMBER(18,2),
  NEXTVALUE    NUMBER(18,2),
  FREQUENCY    VARCHAR2(16 CHAR),
  SOC          VARCHAR2(16 CHAR),
  SOCNAME      VARCHAR2(1024 CHAR),
  RESTNAME     VARCHAR2(2048 CHAR)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE OR REPLACE FUNCTION NEW_LOADER_RESTS_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT DB_LOADER_RESTS_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;

ALTER TABLE DB_LOADER_RESTS ADD (
  CONSTRAINT PK_DB_LOADER_RESTS
 PRIMARY KEY
 (RESTS_ID));

COMMENT ON TABLE DB_LOADER_RESTS IS 'Загруженные сообщения об остатках - метод REST';

COMMENT ON COLUMN DB_LOADER_RESTS.LOAD_DATE IS 'Дата/время загрузки';

COMMENT ON COLUMN DB_LOADER_RESTS.PHONE IS 'Номер телефона';

COMMENT ON COLUMN DB_LOADER_RESTS.UNITTYPE IS 'Тип данных (звонки, мобильный интернет, SMS/MMS, MONET(рубли))';

COMMENT ON COLUMN DB_LOADER_RESTS.RESTTYPE IS 'Тип остатка (AL, AS, PK, MONET)';

COMMENT ON COLUMN DB_LOADER_RESTS.INITIALSIZE IS 'Начальный размер пакета';

COMMENT ON COLUMN DB_LOADER_RESTS.CURRVALUE IS 'Текущий остаток';

COMMENT ON COLUMN DB_LOADER_RESTS.NEXTVALUE IS 'Кол-во которое будет предоставлено на следующий период (для остатков с типами AL, AS)';

COMMENT ON COLUMN DB_LOADER_RESTS.FREQUENCY IS 'Периодичность (в день, в месяц)';

COMMENT ON COLUMN DB_LOADER_RESTS.SOC IS 'Тариф/услуга/agreement, к которой привязан остаток';

COMMENT ON COLUMN DB_LOADER_RESTS.SOCNAME IS 'Коммерческое наименование тарифа/услуги/agreement';

COMMENT ON COLUMN DB_LOADER_RESTS.RESTNAME IS 'Коммерческое название пакета';
