CREATE TABLE DB_LOADER_ACCOUNT_BAN_LIST
(
  ACCOUNT_ID     INTEGER NOT NULL,
  BAN NUMBER,
  BAN_NAME VARCHAR2(250),
  MARKET_CODE VARCHAR2(10),
  BAN_CURRENCY_IND VARCHAR2(3),
  DATE_CREATED  DATE,
  DATE_UPDATED   DATE,
  DATE_LAST_LOAD_STATUS DATE
);

COMMENT ON TABLE DB_LOADER_ACCOUNT_BAN_LIST IS 'Список подбанов на счетах';

COMMENT ON COLUMN DB_LOADER_ACCOUNT_BAN_LIST.ACCOUNT_ID IS 'ИД счета из табилцы ACCOUNTS';

COMMENT ON COLUMN DB_LOADER_ACCOUNT_BAN_LIST.BAN IS 'Номер бана';

COMMENT ON COLUMN DB_LOADER_ACCOUNT_BAN_LIST.BAN_NAME IS 'Имя бана';

COMMENT ON COLUMN DB_LOADER_ACCOUNT_BAN_LIST.MARKET_CODE IS 'Код региона';

COMMENT ON COLUMN DB_LOADER_ACCOUNT_BAN_LIST.BAN_CURRENCY_IND IS 'Код валюты бана ("P" - рубль,"D" - доллар)';

COMMENT ON COLUMN DB_LOADER_ACCOUNT_BAN_LIST.DATE_CREATED IS 'Дата создания';

COMMENT ON COLUMN DB_LOADER_ACCOUNT_BAN_LIST.DATE_UPDATED IS 'Дата обновления';

COMMENT ON COLUMN DB_LOADER_ACCOUNT_BAN_LIST.DATE_LAST_LOAD_STATUS IS 'Дата последней загрузки статуса';
