CREATE TABLE DB_LOADER_ACCOUNT_PHONES_PERI(
  YEAR_MONTH INTEGER,
  PHONE_NUMBER VARCHAR2(10 CHAR),
  DATE_INSERT DATE
  );
  
CREATE UNIQUE INDEX UNIQUE_DB_L_A_P_P_YM_PHONE ON DB_LOADER_ACCOUNT_PHONES_PERI
(YEAR_MONTH, PHONE_NUMBER);
