CREATE TABLE DB_LOADER_PAYMENT_TRANSFERS(
  ACCOUNT_ID INTEGER,
  PHONE_NUMBER VARCHAR2(15 CHAR),
  PAYMENT_DATE DATE,
  PAYMENT_STATUS VARCHAR2(200 CHAR),
  PAYMENT_TYPE VARCHAR2(200 CHAR),
  PAYMENT_ORIGINAL_AMT VARCHAR2(30 CHAR),
  PAYMENT_CURRENT_AMT VARCHAR2(30 CHAR),
  BANK_PAYMENT_ID VARCHAR2(30 CHAR),
  PAYMENT_ACTIVATE_DATE DATE
  );
  
  
  
COMMENT ON TABLE DB_LOADER_PAYMENT_TRANSFERS IS 'Временная таблица для загрузки API.getPaymentList';

COMMENT ON COLUMN DB_LOADER_PAYMENT_TRANSFERS.ACCOUNT_ID IS 'ID счета';

COMMENT ON COLUMN DB_LOADER_PAYMENT_TRANSFERS.PAYMENT_DATE IS 'Номер телефона';

COMMENT ON COLUMN DB_LOADER_PAYMENT_TRANSFERS.PAYMENT_DATE IS 'Дата платежа';

COMMENT ON COLUMN DB_LOADER_PAYMENT_TRANSFERS.PAYMENT_STATUS IS 'Статус платежа';

COMMENT ON COLUMN DB_LOADER_PAYMENT_TRANSFERS.PAYMENT_TYPE IS 'Тип платежа';

COMMENT ON COLUMN DB_LOADER_PAYMENT_TRANSFERS.PAYMENT_ORIGINAL_AMT IS 'Сумма платежа (внесенная)';

COMMENT ON COLUMN DB_LOADER_PAYMENT_TRANSFERS.PAYMENT_CURRENT_AMT IS 'Сумма платежа (зачисленная)';

COMMENT ON COLUMN DB_LOADER_PAYMENT_TRANSFERS.BANK_PAYMENT_ID IS 'ID платежа';

COMMENT ON COLUMN DB_LOADER_PAYMENT_TRANSFERS.PAYMENT_ACTIVATE_DATE IS 'Дата активации платежа';

GRANT SELECT ON DB_LOADER_PAYMENT_TRANSFERS TO CORP_MOBILE_ROLE;
GRANT SELECT ON DB_LOADER_PAYMENT_TRANSFERS TO CORP_MOBILE_ROLE_RO;