CREATE SEQUENCE DB_LOADER_SUBS_ID
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE TABLE DB_LOADER_SUBS
(
  SUBS_ID           NUMBER(10),
  LOAD_DATE         TIMESTAMP(6),
  PHONE             VARCHAR2(10 BYTE),
  ID                VARCHAR2(32 BYTE),
  NAME              VARCHAR2(64 BYTE),
  TRY_PRICE         NUMBER(12,2),
  BUY_PRICE         NUMBER(12,2),
  BUY_PRICE_PERIOD  NUMBER(10),
  START_DATE        VARCHAR2(32 BYTE),
  END_FREE_DATE     VARCHAR2(32 BYTE),
  END_DATE          VARCHAR2(32 BYTE),
  TRY_BUY_MODE      VARCHAR2(16 BYTE),
  PROVIDER_NAME     VARCHAR2(128 BYTE),
  PROVIDER_CONTACT  VARCHAR2(128 BYTE),
  CATEGORY          VARCHAR2(64 BYTE),
  TYPE              VARCHAR2(8 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE OR REPLACE FUNCTION NEW_LOADER_SUBS_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT DB_LOADER_SUBS_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;

ALTER TABLE DB_LOADER_SUBS ADD (
  CONSTRAINT PK_DB_LOADER_SUBS
 PRIMARY KEY
 (SUBS_ID));

COMMENT ON TABLE DB_LOADER_SUBS IS 'Загруженные сообщения о подписках методом REST';

COMMENT ON COLUMN DB_LOADER_SUBS.SUBS_ID IS 'Первичный ключ';

COMMENT ON COLUMN DB_LOADER_SUBS.LOAD_DATE IS 'Дата/время загрузки';

COMMENT ON COLUMN DB_LOADER_SUBS.PHONE IS 'Номер телефона';

COMMENT ON COLUMN DB_LOADER_SUBS.ID IS 'Идентификатор подписки';

COMMENT ON COLUMN DB_LOADER_SUBS.NAME IS 'Название подписки';

COMMENT ON COLUMN DB_LOADER_SUBS.TRY_PRICE IS 'Абоненская плата на периоде TRY';

COMMENT ON COLUMN DB_LOADER_SUBS.BUY_PRICE IS 'Абоненская плата в Buy';

COMMENT ON COLUMN DB_LOADER_SUBS.BUY_PRICE_PERIOD IS 'Периодичность в Buy (в днях; 0 - если ежемесячно)';

COMMENT ON COLUMN DB_LOADER_SUBS.START_DATE IS 'Дата подключения подписки';

COMMENT ON COLUMN DB_LOADER_SUBS.END_FREE_DATE IS 'Дата окончания бесплатного периода';

COMMENT ON COLUMN DB_LOADER_SUBS.END_DATE IS 'Дата отключения подписки, если не указана, то подписка считается безсрочной';

COMMENT ON COLUMN DB_LOADER_SUBS.TRY_BUY_MODE IS 'Определяется режим подписки (TRY, BUY - для CDP; UNKNOWN - для всех подписок по CPA, т.к. по ним пока не получаем признаков try)';

COMMENT ON COLUMN DB_LOADER_SUBS.PROVIDER_NAME IS 'Наименование провайдера (для CPA)';

COMMENT ON COLUMN DB_LOADER_SUBS.PROVIDER_CONTACT IS 'Контакты провайдера (для CPA)';

COMMENT ON COLUMN DB_LOADER_SUBS.CATEGORY IS 'Категория подписки (для CPA)';

COMMENT ON COLUMN DB_LOADER_SUBS.TYPE IS 'Тип подписки: CPA, CDP';

