CREATE TABLE DETAILS_INFO(
  DETAIL_INFO_ID INTEGER PRIMARY KEY,
  ACCOUNT_ID NUMBER(13) NOT NULL,
  YEAR_MONTH INTEGER NOT NULL,
  PHONE_NUMBER VARCHAR2(10 CHAR) NOT NULL
  );
 
CREATE SEQUENCE S_NEW_DETAIL_INFO_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;  
  
CREATE OR REPLACE FUNCTION NEW_DETAIL_INFO_ID RETURN INTEGER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_DETAIL_INFO_ID.NEXTVAL
    INTO vRES
    FROM DUAL;
  RETURN vRES;
END;  

CREATE OR REPLACE TRIGGER TIU_DETAILS_INFO
  BEFORE INSERT OR UPDATE ON DETAILS_INFO FOR EACH ROW
--#Version=1
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.DETAIL_INFO_ID, 0)=0 THEN
      :NEW.DETAIL_INFO_ID:=NEW_DETAIL_INFO_ID;
    END IF;
  END IF;
END;
/ 
  
CREATE INDEX I_DETAILS_INFO_ACCOUNT_ID ON DETAILS_INFO
  (ACCOUNT_ID)
  LOGGING
  NOPARALLEL;
  
CREATE INDEX I_DETAILS_INFO_YEAR_MONTH ON DETAILS_INFO
  (YEAR_MONTH)
  LOGGING
  NOPARALLEL;
  
CREATE INDEX I_DETAILS_INFO_PHONE_NUMBER ON DETAILS_INFO
  (PHONE_NUMBER)
  LOGGING
  NOPARALLEL;  
  
--GRANT DELETE, INSERT, SELECT, UPDATE ON DETAILS_INFO TO CORP_MOBILE_ROLE;

--GRANT SELECT ON DETAILS_INFO TO CORP_MOBILE_ROLE_RO;   