CREATE TABLE GPRS_PHONE_LIMIT
(
  YEAR_MONTH    NUMBER(38),
  PHONE_NUMBER  VARCHAR2(10 CHAR),
  DATE_CREATED  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          9M
            NEXT             8K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE GPRS_PHONE_LIMIT IS 'Номера, по которым включаем ограничения по автоподключению пакетов';

COMMENT ON COLUMN GPRS_PHONE_LIMIT.YEAR_MONTH IS 'Год/месяц';

COMMENT ON COLUMN GPRS_PHONE_LIMIT.PHONE_NUMBER IS 'Номер';

COMMENT ON COLUMN GPRS_PHONE_LIMIT.DATE_CREATED IS 'Дата создания записи';

ALTER TABLE GPRS_PHONE_LIMIT ADD CONTRACT_ID INTEGER;
COMMENT ON COLUMN GPRS_PHONE_LIMIT.CONTRACT_ID IS 'ID контракта';

CREATE UNIQUE INDEX I_PHONE_YEAR_MONTH_LT ON GPRS_PHONE_LIMIT
(PHONE_NUMBER, YEAR_MONTH)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          4M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
COMPRESS 1;

CREATE OR REPLACE TRIGGER TI_GPRS_PHONE_LIMIT
BEFORE DELETE OR INSERT
ON GPRS_PHONE_LIMIT 
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :NEW.YEAR_MONTH := TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMM'));
    :NEW.DATE_CREATED := SYSDATE;
  ELSIF DELETING THEN  --если удаление
    INSERT INTO GPRS_PHONE_LIMIT_LOG 
    (
       YEAR_MONTH, 
       PHONE_NUMBER, 
       DATE_CREATED, 
       DATE_DELETE, 
       CONTRACT_ID
    ) 
    VALUES 
    (
       :OLD.YEAR_MONTH,
       :OLD.PHONE_NUMBER, 
       :OLD.DATE_CREATED, 
       sysdate, 
       :OLD.CONTRACT_ID
    );
  END IF;
END;

GRANT SELECT, DELETE ON GPRS_PHONE_LIMIT TO CORP_MOBILE_ROLE;