CREATE TABLE GPRS_PHONE_LIMIT_LOG
(
  YEAR_MONTH    INTEGER,
  PHONE_NUMBER  VARCHAR2(10 CHAR),
  DATE_CREATED  DATE,
  DATE_DELETE   DATE,
  CONTRACT_ID   INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          9M
            NEXT             8K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE GPRS_PHONE_LIMIT_LOG IS 'Лог с номерами, по которым включаем ограничения по автоподключению пакетов';

COMMENT ON COLUMN GPRS_PHONE_LIMIT_LOG.YEAR_MONTH IS 'Год/месяц';

COMMENT ON COLUMN GPRS_PHONE_LIMIT_LOG.PHONE_NUMBER IS 'Номер';

COMMENT ON COLUMN GPRS_PHONE_LIMIT_LOG.DATE_CREATED IS 'Дата создания записи';

COMMENT ON COLUMN GPRS_PHONE_LIMIT_LOG.DATE_DELETE IS 'Дата удаления записи';

COMMENT ON COLUMN GPRS_PHONE_LIMIT_LOG.CONTRACT_ID IS 'ID контракта';