CREATE TABLE HOT_BILLING_SHABLON_STRING(
  EXT_P_BAN VARCHAR2(9 BYTE),  
  BAN NUMBER(9),
  BEN NUMBER(5), 
  BILL_SEQ_N NUMBER(5),
  SUBSCR_NO VARCHAR2(11 BYTE),
  CH_SEIZ_DT DATE,
  MSG_SWH_ID VARCHAR2 (15 Byte),  
  US_SEQ_N NUMBER(9),
  AT_SOC VARCHAR2(9 Byte),
  AT_SOC_DT DATE,
  SOC_EXP_DT DATE,
  SOC_SEQ_NO NUMBER(9).
  AT_FT_CODE VARCHAR2(6 Byte),
  AT_RTEF_DT DATE,
  AT_RTFR_LV VARCHAR2(1 Byte),
  RT_LVL_CD VARCHAR2(1 Byte),
  PC_PLAN_CD VARCHAR2(9 Byte),
  PC_P_EF_DT DATE,
  S_FTR_SQ_N NUMBER(9), 
  C_ACT_CD VARCHAR2(1 Byte),
  AT_RTAT_CD VARCHAR2(1 Byte),
  FT_SEL_DT DATE,
  AT_C_DR_SC NUMBER(9),
  AT_CDRRD_M NUMBER(11,2),
  AT_NMIN_RT NUMBER(11,2),
  AT_N_OF_IM NUMBER(11,2),
  AT_CHG_AMT NUMBER(11,2),
  AT_C_AT_IU NUMBER(11,2),
  AT_C_ST_PD VARCHAR2(2 Byte),
  IN_PD_CODE VARCHAR2(2 Byte),
  CALL_TO_TN VARCHAR2(18 Byte),
  CALLING_NO VARCHAR2(21 Byte),
  MPS_FIL_NM NUMBER(9),
  SPC_NUM_TP VARCHAR2(1 Byte),
  MESSAGE_TP VARCHAR2(1 Byte),
  AIR_FRE_CD VARCHAR2(2 Byte),
  C_CPRD_IND VARCHAR2(1 Byte),
  C_CSTP_IND VARCHAR2(1 Byte),
  CYCLE_CODE NUMBER(2),
  CYL_R_YR NUMBER(4),
  CYL_R_MTH NUMBER(2),
  BL_RERT_CD VARCHAR2(1 Byte),
  BL_RERT_DT DATE,
  ACT_RSL_CD VARCHAR2(2 Byte),
  SRV_FT_CD VARCHAR2(6 Byte),
  DURATION VARCHAR2(8 Byte),
  FREE_CL_RS VARCHAR2(1 Byte),
  MTRD_UNITS NUMBER(9),
  DATA_VOL NUMBER(11,2),
  WHLSALE_PC NUMBER(9,3),
  N_DCWH_PC NUMBER(9,3),
  ORIG_AMT NUMBER(11,2),
  ORIG_AM_GN NUMBER(11,2),
  NW_CH_ORIG VARCHAR2(16 Byte),
  F_PROC_IND VARCHAR2(1 Byte),
  C_OF_ORIG VARCHAR2(3 Byte),
  AU_EFF_DT DATE,
  C_MN_ST_DT DATE,
  C_STT_DT DATE,
  MPS_RT_IND VARCHAR2(1 Byte),
  SRV_TP VARCHAR2(1 Byte),
  INC_SRV VARCHAR2(8 Byte),
  INC_FT VARCHAR2(8 Byte),
  TF_PLAN_ID VARCHAR2(8 Byte),
  INC_ACC_ID VARCHAR2(8 Byte),
  IMSI VARCHAR2(15 Byte),
  IMEI VARCHAR2(15 Byte),
  M_CGTP_IND VARCHAR2(1 Byte),
  EVENT_TYPE NUMBER(3),
  THSHLD_CLS VARCHAR2(2 Byte),
  AT_GRS_AMT NUMBER(11,2).
  AC_AMT NUMBER(11,2),
  CL_FWD_IND VARCHAR2(1 Byte),
  CELL_ID VARCHAR2(6 Byte),
  DEF_BEN NUMBER(5),
  USG_PAC_CD VARCHAR2(5 Byte),
  LOC_AREA VARCHAR2(6 Byte),
  GUIDE_BY VARCHAR2(1 Byte),
  OUTCOL_IND VARCHAR2(1 Byte),
  PROV_ID VARCHAR2(8 Byte),
  R_TAMT_AIR NUMBER(11,2),
  WAVD_CL_IN VARCHAR2(1 Byte),
  BSC_SRV_CD VARCHAR2(2 Byte),
  BSC_SRV_TP VARCHAR2(1 Byte),
  DIALED_DIG VARCHAR2(21 Byte),
  C_COUNT_CD VARCHAR2(3 Byte),
  CALL_SRC VARCHAR2(1 Byte),
  CALL_DEST VARCHAR2(1 Byte),
  RECORD_ID VARCHAR2(5 Byte),
  INIT_F_IND VARCHAR2(1 Byte),
  C_CRDT_IND VARCHAR2(1 Byte),
  C_CRIU_IND VARCHAR2(1 Byte),
  MT_FTR_IND VARCHAR2(1 Byte),
  PRODUCT_TP VARCHAR2(1 Byte),
  CALL_SERV VARCHAR2(1 Byte),
  TAX_IND VARCHAR2(1 Byte),
  RATE_CODE1 VARCHAR2(9 Byte),
  RATE_CODE2 VARCHAR2(9 Byte),
  RATE_CODE3 VARCHAR2(9 Byte),
  RATE_CODE4 VARCHAR2(9 Byte),
  RATE_CODE5 VARCHAR2(9 Byte),
  RT_CD_IND1 VARCHAR2(1 Byte),
  RT_CD_IND2 VARCHAR2(1 Byte),
  RT_CD_IND3 VARCHAR2(1 Byte),
  RT_CD_IND4 VARCHAR2(1 Byte),
  RT_CD_IND5 VARCHAR2(1 Byte),
  LOGCL_DATE DATE,
  IU_LVL_CD VARCHAR2(1 Byte),
  ALLOCN_IND VARCHAR2(1 Byte),
  PF_SHRT_CD VARCHAR2(7 Byte),
  AT_CAI_SGR NUMBER(11,2),
  UOM VARCHAR2(2 Byte),
  C_UC_RT_IN VARCHAR2(1 Byte),
  SDR_AMOUNT NUMBER(12,6),
  SP_SRVC_CD VARCHAR2(10 Byte),
  HOME_CTN VARCHAR2(11 Byte),
  TECHNOLOGY VARCHAR2(1 Byte),
  NEW_BAL NUMBER(11,2),
  ADV_PM_IND VARCHAR2(1 Byte),
  CALL_DESTN VARCHAR2 (50 Byte),
  SUB_STATUS VARCHAR2(1 Byte),
  CUR_IND VARCHAR2(1 Byte),
  MAIN_CTN VARCHAR2(11 Byte),
  MAIN_SOCNO NUMBER(9),
  COMVRS_AMT NUMBER(15,6),
  AL_PYD_IND VARCHAR2(1 Byte),
  SERVICE_ID VARCHAR2(2 Byte),
  ROAM_FLAG VARCHAR2(1 Byte),
  DIRECTION VARCHAR2(3 Byte),
  SPECIAL_FT VARCHAR2(1 Byte),
  SRVICE_FLG VARCHAR2(3 Byte),
  MPSRT_IND VARCHAR2(1 Byte),
  SUBSCR_ID NUMBER(9),
  DISCT_SOCS VARCHAR2 (100 Byte),
  LOC_ZNE_ID VARCHAR2(8 Byte),
  SES_ST_DT DATE,
  USG_SES_ID VARCHAR2 (10 Byte),
  DR_SOC VARCHAR2(9 Byte),
  DR_SCSQ_NO NUMBER(9),
  DR_STEP NUMBER(9),
  AT_FT_DESC VARCHAR2(100 Byte)
  );

COMMENT ON TABLE HOT_BILLING_SHABLON_STRING IS 'Таблица шаблок без типов(все поля строки)';

COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.EXT_P_BAN IS 'BAN плательщика';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.BAN IS 'BAN сотового номера';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.BEN IS 'BEN сотового номера';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.BILL_SEQ_N IS 'Биллинговый порядковый номер записи о выставлении счета (служебное значение)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.SUBSCR_NO IS 'Сотовый номер';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.CH_SEIZ_DT IS 'Дата_время совершения звонка';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.MSG_SWH_ID IS 'Сетевое устройство (SwitchID)'; 
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.US_SEQ_N IS 'Порядковый номер записи (служебное поле)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AT_SOC IS 'Услуга, по которой определяется тарификация';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AT_SOC_DT IS 'Дата активации тарификационной услуги';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.SOC_EXP_DT IS 'Дата завершения действия тарификационной услуги';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.SOC_SEQ_NO IS 'Порядковый номер записи о подключении услуги (служебное значение)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AT_FT_CODE IS 'Описание типа звонка';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AT_RTEF_DT IS 'Уровень подключения услуги: N – не определно; M – маркет-уровень (уровень Компании); C – уровень сотового номера (прайс-плана, услуги)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.RT_LVL_CD IS 'Уровень тарификации';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.PC_PLAN_CD IS 'Тарифный план';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.PC_P_EF_DT IS 'Дата активации тарифного плана';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.S_FTR_SQ_N IS 'Порядковый номер записи о подключении тарифкационного фичера (служебное значение)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.C_ACT_CD IS 'Тип вызова';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AT_RTAT_CD IS 'Тип рейтинга';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.FT_SEL_DT IS 'Дата определения тарификационного фичера для записи';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AT_C_DR_SC IS 'Длительность (сек.)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AT_CDRRD_M IS 'Длительность (мин., с округлением)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AT_NMIN_RT IS 'Количество минут для тарификации';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AT_N_OF_IM IS 'Количество «включенных» (пакетных) единиц';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AT_CHG_AMT IS 'Стоимость';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AT_C_AT_IU IS 'Стоимость включая «пакетную» длительность';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AT_C_ST_PD IS 'Период совершения звонка';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.IN_PD_CODE IS 'Период совершения входящего звонка';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.CALL_TO_TN IS 'Номер вызываемого абонента';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.CALLING_NO IS 'Номер инициатора звонка';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.MPS_FIL_NM IS 'Идентификатор файла (служебное значение)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.SPC_NUM_TP IS 'Признак впециальной тарификации';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.MESSAGE_TP IS 'Тип записи: домашний или роуминг';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AIR_FRE_CD IS 'Признак не-тарификации';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.C_CPRD_IND IS 'Признак пересечения периода совершения звонка';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.C_CSTP_IND IS 'Признак пересечения порога (для степ-тарификации)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.CYCLE_CODE IS 'Биллинг-цикл';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.CYL_R_YR IS 'Год';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.CYL_R_MTH IS 'Месяц';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.BL_RERT_CD IS 'Признак ререйтинга»';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.BL_RERT_DT IS 'Дата ререйтинга';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.ACT_RSL_CD IS 'Идентификатор ручной модификации записи (для ошибочных записей)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.SRV_FT_CD IS 'Сервис';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.DURATION IS 'Длительность';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.FREE_CL_RS IS 'Причина не-тарификации';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.MTRD_UNITS IS 'Единица измерения.'; 
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.DATA_VOL IS 'Объем (для data)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.WHLSALE_PC IS 'Цена';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.N_DCWH_PC IS 'Цена с учетом возможных скидок';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.ORIG_AMT IS 'Стоимость до применения скидок';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.ORIG_AM_GN IS 'Корректировка (препейд)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.NW_CH_ORIG IS 'Провайдер';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.F_PROC_IND IS 'Индикатор обработки';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.C_OF_ORIG IS 'Страна совершения вызова';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AU_EFF_DT IS 'Дата эффективности аккумулятора';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.C_MN_ST_DT IS 'Месяц начала биллинг-цикла';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.C_STT_DT IS 'Дата начала биллинг-цикла';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.MPS_RT_IND IS 'Пирзнак ререйтинга';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.SRV_TP IS 'Класс сервиса';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.INC_SRV IS 'Признак взодящего взонка';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.INC_FT IS 'Тип входящего звонка';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.TF_PLAN_ID IS 'Тарифный план входящего звонка';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.INC_ACC_ID IS 'Account ID';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.IMSI IS 'IMSI';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.IMEI IS 'IMEI';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.M_CGTP_IND IS 'Тип тарификации (подлежит тарификации или нет)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.EVENT_TYPE IS 'Тип события';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.THSHLD_CLS IS 'Класс порога'; 
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AT_GRS_AMT IS 'Стоимость без учета скидок  тарификационных схем';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AC_AMT IS 'Дополнительная стоимость (например, стоимость соединения)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.CL_FWD_IND IS 'Признак переадресации';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.CELL_ID IS 'Идентификатор соты';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.DEF_BEN IS 'BEN по умолчанию';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.USG_PAC_CD IS 'Служебное поле (не используется)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.LOC_AREA IS 'Код локации';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.GUIDE_BY IS 'Признак тарификации: по IMSI/MSISDN/ дополнительному MSISDN'; 
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.OUTCOL_IND IS 'Признак приезающего роумера';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.PROV_ID IS 'Роуминг-провайдер. Возможные актуальные значения:'; 
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.R_TAMT_AIR IS 'Налоги роуминг-провайдера';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.WAVD_CL_IN IS 'Признак нетарифицируемого вызова';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.BSC_SRV_CD IS 'Код базового сервиса';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.BSC_SRV_TP IS 'Тип базового сервиса';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.DIALED_DIG IS 'Набранный номер';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.C_COUNT_CD IS 'Код страны';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.CALL_SRC IS 'Источник звонка';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.CALL_DEST IS 'Направление звонка';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.RECORD_ID IS 'Идентификатор записи';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.INIT_F_IND IS 'Индикатор стоимости соединения';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.C_CRDT_IND IS 'Признак пересечения даты';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.C_CRIU_IND IS 'Признак превышения пакета «включенных» единиц';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.MT_FTR_IND IS 'Признак наличия множественных тарификацонных фичеров';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.PRODUCT_TP IS 'Тип продукта';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.CALL_SERV IS 'Тип звонкового сервиса';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.TAX_IND IS 'Признак налогообложения';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.RATE_CODE1 IS 'Рейт-код1-5 (определяет схему тарифкации)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.RATE_CODE2 IS 'Рейт-код1-5';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.RATE_CODE3 IS 'Рейт-код1-5';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.RATE_CODE4 IS 'Рейт-код1-5';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.RATE_CODE5 IS 'Рейт-код1-5';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.RT_CD_IND1 IS 'Признак Рейт-кода 1-5';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.RT_CD_IND2 IS 'Признак Рейт-кода 1-5';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.rate_code_ind3 IS 'Признак Рейт-кода 1-5';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.rate_code_ind4 IS 'Признак Рейт-кода 1-5';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.rate_code_ind5 IS 'Признак Рейт-кода 1-5';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.LOGCL_DATE IS 'Логическая дата';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.IU_LVL_CD IS 'Тип «включенных» единиц';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.ALLOCN_IND IS 'Признак применения включенных единиц';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.PF_SHRT_CD IS 'Префикс';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AT_CAI_SGR IS 'Стоимость включая степ';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.UOM IS 'Единица измерения';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.C_UC_RT_IN IS 'Признак расчета тарифа (для роуминговых записей)';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.SDR_AMOUNT IS 'Стоимость в SDR';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.SP_SRVC_CD IS 'Дополнительный сервис';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.HOME_CTN IS 'Номер инициатора';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.TECHNOLOGY IS 'Технология';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.NEW_BAL IS 'Баланс';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.ADV_PM_IND IS 'Признак авансовой системы расчетов';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.CALL_DESTN IS '';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.SUB_STATUS IS 'Статус сотового номера';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.CUR_IND IS 'Валюта';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.MAIN_CTN IS 'Основной сотовый номер';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.MAIN_SOCNO IS 'Тарификационная услуга основаного номера';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.COMVRS_AMT IS 'Признак препейд-абонента';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AL_PYD_IND IS 'Признак оплаченности'; 
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.SERVICE_ID IS 'СервисID';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.ROAM_FLAG IS 'Признак роуминга';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.DIRECTION IS 'направление';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.SPECIAL_FT IS 'Специальный фичер';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.SRVICE_FLG IS '';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.MPSRT_IND IS 'Признак ререйтинга';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.SUBSCR_ID IS 'ID  абонента';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.DISCT_SOCS IS 'Услуга-скидка';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.LOC_ZNE_ID IS 'Признак локальной зоны';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.SES_ST_DT IS 'Дата начала сессии';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.USG_SES_ID IS 'ID сессии';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.DR_SOC 'Услуга динамической скидки';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.DR_SCSQ_NO 'Порядковый номер записи о подключения динамической скидки';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.DR_STEP 'Степ динамической скидки';
COMMENT ON COLUMN HOT_BILLING_SHABLON_STRING.AT_FT_DESC 'Тип звонка (фичер). Возможные актуальные значения :';

