CREATE GLOBAL TEMPORARY TABLE HOT_BILLING_CALLS_SORTED(
  DBF_ID     INTEGER,
  SUBSCR_NO  NUMBER(11),
  CH_SEIZ_DT DATE,
  US_SEQ_N   NUMBER(9),
  AT_SOC     VARCHAR2(9 BYTE),
  AT_FT_CODE VARCHAR2(6 BYTE),
  PC_PLAN_CD VARCHAR2(9 BYTE),
  C_ACT_CD   VARCHAR2(1 BYTE),
  AT_C_DR_SC NUMBER(9),
  AT_CDRRD_M NUMBER(11, 2),
  AT_CHG_AMT NUMBER(11, 2),
  CALLING_NO VARCHAR2(21 BYTE),
  MESSAGE_TP VARCHAR2(1 BYTE),
  SRV_FT_CD  VARCHAR2(6 BYTE),
  DATA_VOL   NUMBER(11, 2),
  IMEI       NUMBER(15),
  CELL_ID    NUMBER(6),
  PROV_ID    VARCHAR2(8 BYTE),
  DIALED_DIG VARCHAR2(21 BYTE),
  UOM        VARCHAR2(2 BYTE),
  DISCT_SOCS VARCHAR2(100 BYTE),
  AT_FT_DESC VARCHAR2(100 CHAR)
  ) ON COMMIT PRESERVE ROWS;

COMMENT ON TABLE HOT_BILLING_CALLS_SORTED IS 'временная таблица для загрузки';

COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.DBF_ID IS 'ID файла источника';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.SUBSCR_NO IS 'Сотовый номер';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.CH_SEIZ_DT IS 'Дата_время совершения звонка';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.US_SEQ_N IS 'Порядковый номер записи (служебное поле)';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.AT_SOC IS 'Услуга, по которой определяется тарификация';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.AT_FT_CODE IS 'Код звонка в билайне';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.PC_PLAN_CD IS 'Тарифный план';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.C_ACT_CD IS 'Тип вызова';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.AT_C_DR_SC IS 'Длительность (сек.)';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.AT_CDRRD_M IS 'Длительность (мин., с округлением)';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.AT_CHG_AMT IS 'Стоимость';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.CALLING_NO IS 'Номер инициатора звонка';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.MESSAGE_TP IS 'Тип записи: домашний или роуминг';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.SRV_FT_CD IS 'Сервис (код)';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.DATA_VOL IS 'Объем (для data)';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.IMEI IS 'IMEI (код)';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.CELL_ID IS 'Идентификатор соты';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.PROV_ID IS 'Роуминг-провайдер';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.DIALED_DIG IS 'Набранный номер';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.UOM IS 'Единица измерения';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.DISCT_SOCS IS 'Услуга-скидка';
COMMENT ON COLUMN HOT_BILLING_CALLS_SORTED.AT_FT_DESC IS 'Тип звонка (фичер).';

CREATE INDEX I_HB_SORTED_CALLS$SUB_AT ON HOT_BILLING_CALLS_SORTED(DBF_ID, SUBSCR_NO, AT_FT_CODE) COMPRESS 3;

CREATE INDEX I_HB_SORTED_CALLS$SUBSCR_NO ON HOT_BILLING_CALLS_SORTED(SUBSCR_NO);

CREATE INDEX I_HB_SORTED_CALLS$DBF_ID$IDX ON HOT_BILLING_CALLS_SORTED(DBF_ID);

CREATE INDEX I_HB_SORTED_CALLS$SUBSCR_NO$CH ON HOT_BILLING_CALLS_SORTED(SUBSCR_NO, CH_SEIZ_DT);

GRANT DELETE, INSERT, SELECT, UPDATE ON HOT_BILLING_CALLS_SORTED TO CORP_MOBILE_ROLE;

GRANT SELECT ON HOT_BILLING_CALLS_SORTED TO CORP_MOBILE_ROLE_RO;