CREATE TABLE HOT_BILLING_CALLS_ERROR(
  DBF_ID     INTEGER,
  SUBSCR_NO  VARCHAR2(11 BYTE),
  CH_SEIZ_DT VARCHAR2(16 BYTE),
  US_SEQ_N   VARCHAR2(9 BYTE),
  AT_SOC     VARCHAR2(9 BYTE),
  AT_FT_CODE VARCHAR2(6 BYTE),
  PC_PLAN_CD VARCHAR2(9 BYTE),
  C_ACT_CD   VARCHAR2(1 BYTE),
  AT_C_DR_SC VARCHAR2(9 BYTE),
  AT_CDRRD_M VARCHAR2(11 BYTE),
  AT_CHG_AMT VARCHAR2(14 BYTE),
  CALLING_NO VARCHAR2(21 BYTE),
  MESSAGE_TP VARCHAR2(1 BYTE),
  SRV_FT_CD  VARCHAR2(6 BYTE),
  DATA_VOL   VARCHAR2(14 BYTE),
  IMEI       VARCHAR2(15 BYTE),
  CELL_ID    VARCHAR2(6 BYTE),
  PROV_ID    VARCHAR2(8 BYTE),
  DIALED_DIG VARCHAR2(21 BYTE),
  UOM        VARCHAR2(2 BYTE),
  DISCT_SOCS VARCHAR2(100 BYTE),
  AT_FT_DESC VARCHAR2(100 CHAR)
  ) TABLESPACE HOT_BILLING;

COMMENT ON TABLE HOT_BILLING_CALLS_ERROR IS 'временная таблица для загрузки(несорт.)';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.DBF_ID IS 'ID файла источника';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.SUBSCR_NO IS 'Сотовый номер';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.CH_SEIZ_DT IS 'Дата_время совершения звонка';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.US_SEQ_N IS 'Порядковый номер записи (служебное поле)';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.AT_SOC IS 'Услуга, по которой определяется тарификация';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.AT_FT_CODE IS 'Код звонка в билайне';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.PC_PLAN_CD IS 'Тарифный план';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.C_ACT_CD IS 'Тип вызова';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.AT_C_DR_SC IS 'Длительность (сек.)';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.AT_CDRRD_M IS 'Длительность (мин., с округлением)';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.AT_CHG_AMT IS 'Стоимость';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.CALLING_NO IS 'Номер инициатора звонка';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.MESSAGE_TP IS 'Тип записи: домашний или роуминг';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.SRV_FT_CD IS 'Сервис (код)';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.DATA_VOL IS 'Объем (для data)';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.IMEI IS 'IMEI (код)';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.CELL_ID IS 'Идентификатор соты';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.PROV_ID IS 'Роуминг-провайдер (таблица ROAMING_PROVIDERS)';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.DIALED_DIG IS 'Набранный номер';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.UOM IS 'Единица измерения';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.DISCT_SOCS IS 'Услуга-скидка';
COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.AT_FT_DESC IS 'Тип звонка (фичер).';

CREATE INDEX I_HB_EC$DBF_ID$SUBSCR_NO$AT_FT ON HOT_BILLING_CALLS_ERROR(DBF_ID, SUBSCR_NO, AT_FT_CODE) COMPRESS 3;

CREATE INDEX I_HB_EC$SUBSCR_NO ON HOT_BILLING_CALLS_ERROR(SUBSCR_NO);

CREATE INDEX I_HB_EC$DBF_ID ON HOT_BILLING_CALLS_ERROR(DBF_ID);

CREATE INDEX I_HB_EC$SUBSCR_NO$CH_SEIZ_DT ON HOT_BILLING_CALLS_ERROR(SUBSCR_NO, CH_SEIZ_DT);

CREATE INDEX I_HB_EC$UOM ON HOT_BILLING_CALLS_ERROR(UOM);

CREATE INDEX I_HB_EC$C_ACT_CD ON HOT_BILLING_CALLS_ERROR(C_ACT_CD);

CREATE INDEX I_HB_EC$MESSAGE_TP ON HOT_BILLING_CALLS_ERROR(MESSAGE_TP);

CREATE INDEX I_HB_EC$SRV_FT_CD ON HOT_BILLING_CALLS_ERROR(SRV_FT_CD);

ALTER TABLE HOT_BILLING_CALLS_ERROR ADD (
  CONSTRAINT HOT_BILLING_E_C$DBF_ID$F 
  FOREIGN KEY (DBF_ID) 
  REFERENCES HOT_BILLING_FILES(HBF_ID));

GRANT DELETE, INSERT, SELECT, UPDATE ON HOT_BILLING_CALLS_ERROR TO CORP_MOBILE_ROLE;

GRANT SELECT ON HOT_BILLING_CALLS_ERROR TO CORP_MOBILE_ROLE_RO;