CREATE TABLE HOT_BILLING_CALL_PROV_ID(
  PROV_ID VARCHAR2(8 BYTE) PRIMARY KEY,
  PROV_DESC VARCHAR2(150 Byte),
  TECHNOLOGY VARCHAR2(1 Byte),
  EFFECTIVE_DATE DATE,
  COUNTRY_CODE INTEGER,
  FILETYPE VARCHAR2(20 Byte),
  DATE_INSERT DATE,
  DATE_LAST_UPDATE DATE    
  ) TABLESPACE HOT_BILLING;

COMMENT ON TABLE HOT_BILLING_CALL_PROV_ID IS 'Provider ID - Роуминг-провайдер.';

COMMENT ON COLUMN HOT_BILLING_CALL_PROV_ID.PROV_ID IS 'Код провайдера';
COMMENT ON COLUMN HOT_BILLING_CALL_PROV_ID.PROV_DESC IS 'Название провайдера, Страна(название партнера)';
COMMENT ON COLUMN HOT_BILLING_CALL_PROV_ID.TECHNOLOGY IS 'Технология';
COMMENT ON COLUMN HOT_BILLING_CALL_PROV_ID.EFFECTIVE_DATE IS 'Дата назначения';
COMMENT ON COLUMN HOT_BILLING_CALL_PROV_ID.COUNTRY_CODE IS 'Код страны пребывания';
COMMENT ON COLUMN HOT_BILLING_CALL_PROV_ID.FILETYPE IS 'Тип файла';
COMMENT ON COLUMN HOT_BILLING_CALL_PROV_ID.DATE_INSERT IS 'Дата вставки';
COMMENT ON COLUMN HOT_BILLING_CALL_PROV_ID.DATE_LAST_UPDATE IS 'Дата обновления';

CREATE OR REPLACE TRIGGER TIU_HB_CALL_PROV_ID
  BEFORE INSERT OR UPDATE ON HOT_BILLING_CALL_PROV_ID FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :NEW.DATE_INSERT:=SYSDATE;
  END IF;
  :NEW.DATE_LAST_UPDATE:=SYSDATE;  
END;  

GRANT DELETE, INSERT, SELECT, UPDATE ON HOT_BILLING_CALL_PROV_ID TO CORP_MOBILE_ROLE;

GRANT SELECT ON HOT_BILLING_CALL_PROV_ID TO CORP_MOBILE_ROLE_RO;