CREATE TABLE HOT_BILLING_CALL_MESSAGE_TP(
  MESSAGE_TP VARCHAR2(1 BYTE) PRIMARY KEY,
  MESSAGE_TP_DESC VARCHAR2(100 CHAR),
  MESSAGE_TP_DESC_RUS VARCHAR2(100 CHAR),
  MESSAGE_TP_DESC_RUS_SHORT VARCHAR2(30 CHAR),
  DATE_INSERT DATE,
  DATE_LAST_UPDATE DATE     
  ) TABLESPACE HOT_BILLING;

COMMENT ON TABLE HOT_BILLING_CALL_MESSAGE_TP IS 'Message Type - Тип записи: домашний или роуминг';

COMMENT ON COLUMN HOT_BILLING_CALL_MESSAGE_TP.MESSAGE_TP IS 'Код';
COMMENT ON COLUMN HOT_BILLING_CALL_MESSAGE_TP.MESSAGE_TP_DESC IS 'Описание';
COMMENT ON COLUMN HOT_BILLING_CALL_MESSAGE_TP.MESSAGE_TP_DESC_RUS IS 'Описание (рус)';
COMMENT ON COLUMN HOT_BILLING_CALL_MESSAGE_TP.DATE_INSERT IS 'Дата вставки';
COMMENT ON COLUMN HOT_BILLING_CALL_MESSAGE_TP.DATE_LAST_UPDATE IS 'Дата обновления';

CREATE OR REPLACE TRIGGER TIU_HB_CALL_MESSAGE_TP
  BEFORE INSERT OR UPDATE ON HOT_BILLING_CALL_MESSAGE_TP FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :NEW.DATE_INSERT:=SYSDATE;
  END IF;
  :NEW.DATE_LAST_UPDATE:=SYSDATE;  
END; 

GRANT DELETE, INSERT, SELECT, UPDATE ON HOT_BILLING_CALL_MESSAGE_TP TO CORP_MOBILE_ROLE;

GRANT SELECT ON HOT_BILLING_CALL_MESSAGE_TP TO CORP_MOBILE_ROLE_RO;

INSERT INTO HOT_BILLING_CALL_MESSAGE_TP(MESSAGE_TP, MESSAGE_TP_DESC, MESSAGE_TP_DESC_RUS)
  VALUES('0', 'Home', 'Домашний');
INSERT INTO HOT_BILLING_CALL_MESSAGE_TP(MESSAGE_TP, MESSAGE_TP_DESC, MESSAGE_TP_DESC_RUS)
  VALUES('1', 'Incollect (Roam) call', 'Роуминг');