CREATE TABLE HOT_BILLING_CALL_SERVICE_TYPE(
  SERVICE_ID NUMBER(1) PRIMARY KEY,  
  SERVICE_NAME VARCHAR2(100 CHAR)
  ) TABLESPACE HOT_BILLING;

COMMENT ON TABLE HOT_BILLING_CALL_SERVICE_TYPE IS 'Типы роуминга';

COMMENT ON COLUMN HOT_BILLING_CALL_SERVICE_TYPE.SERVICE_ID IS 'Код сервиса';
COMMENT ON COLUMN HOT_BILLING_CALL_SERVICE_TYPE.SERVICE_NAME IS 'Описание сервиса';

GRANT DELETE, INSERT, SELECT, UPDATE ON HOT_BILLING_CALL_SERVICE_TYPE TO CORP_MOBILE_ROLE;

GRANT SELECT ON HOT_BILLING_CALL_SERVICE_TYPE TO CORP_MOBILE_ROLE_RO;