CREATE TABLE HOT_BILLING_CALL_IS_ROAMING(
  IS_ROAMING NUMBER(1),
  ROAMING_TYPE_NAME VARCHAR2(100 CHAR)
  ) TABLESPACE HOT_BILLING;

COMMENT ON TABLE HOT_BILLING_CALL_IS_ROAMING IS 'Типы роуминга';

COMMENT ON COLUMN HOT_BILLING_CALL_IS_ROAMING.IS_ROAMING IS 'Код';
COMMENT ON COLUMN HOT_BILLING_CALL_IS_ROAMING.ROAMING_TYPE_NAME IS 'Описание';

GRANT DELETE, INSERT, SELECT, UPDATE ON HOT_BILLING_CALL_IS_ROAMING TO CORP_MOBILE_ROLE;

GRANT SELECT ON HOT_BILLING_CALL_IS_ROAMING TO CORP_MOBILE_ROLE_RO;