CREATE TABLE HOT_BILLING_CALL_SRV_FT_CD(
  SRV_FT_CD VARCHAR2(6 BYTE) PRIMARY KEY,
  SRV_FT_DESC VARCHAR2(100 CHAR),
  DATE_INSERT DATE,
  DATE_LAST_UPDATE DATE   
  ) TABLESPACE HOT_BILLING;

COMMENT ON TABLE HOT_BILLING_CALL_SRV_FT_CD IS 'Service Feature Code - Сервис';

COMMENT ON COLUMN HOT_BILLING_CALL_SRV_FT_CD.SRV_FT_CD IS 'Код сервиса';
COMMENT ON COLUMN HOT_BILLING_CALL_SRV_FT_CD.SRV_FT_DESC IS 'Описание сервиса';
COMMENT ON COLUMN HOT_BILLING_CALL_SRV_FT_CD.DATE_INSERT IS 'Дата вставки';
COMMENT ON COLUMN HOT_BILLING_CALL_SRV_FT_CD.DATE_LAST_UPDATE IS 'Дата обновления';

CREATE OR REPLACE TRIGGER TIU_HOT_BILLING_CALL_SRV_FT_CD
  BEFORE INSERT OR UPDATE ON HOT_BILLING_CALL_SRV_FT_CD FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :NEW.DATE_INSERT:=SYSDATE;
  END IF;
  :NEW.DATE_LAST_UPDATE:=SYSDATE;  
END;  

GRANT DELETE, INSERT, SELECT, UPDATE ON HOT_BILLING_CALL_SRV_FT_CD TO CORP_MOBILE_ROLE;

GRANT SELECT ON HOT_BILLING_CALL_SRV_FT_CD TO CORP_MOBILE_ROLE_RO;