CREATE GLOBAL TEMPORARY TABLE IOT_CURRENT_BALANCE_TEMP(
  PHONE_NUMBER NUMBER NOT NULL,
  LAST_UPDATE DATE NOT NULL,
  UPDATE_TYPE NUMBER NOT NULL,
  BALANCE NUMBER
  ) ON COMMIT PRESERVE ROWS;
  
CREATE UNIQUE INDEX U_IOT_CB_T_PHONE_NUMBER ON IOT_CURRENT_BALANCE_TEMP(PHONE_NUMBER);