CREATE TABLE JOB_GPRS_TURN_OFF_PHN_ERR_LOG
(
  DATE_BEGIN   DATE,
  DATE_END     DATE,
  DATE_INSERT  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE JOB_GPRS_TURN_OFF_PHN_ERR_LOG IS 'лог работы job J_GPRS_TURN_OFF_PHONES_ERROR';

COMMENT ON COLUMN JOB_GPRS_TURN_OFF_PHN_ERR_LOG.DATE_BEGIN IS 'Дата начала';

COMMENT ON COLUMN JOB_GPRS_TURN_OFF_PHN_ERR_LOG.DATE_END IS 'Дата окончания';

COMMENT ON COLUMN JOB_GPRS_TURN_OFF_PHN_ERR_LOG.DATE_INSERT IS 'Дата вставки';