CREATE TABLE LOADER_SETTINGS (
  LOADER_DB_CONNECTION VARCHAR2(50 CHAR),
  LOADER_DB_USER_NAME VARCHAR2(50 CHAR),
  LOADER_DB_PASSWORD VARCHAR2(50 CHAR),
);

ALTER TABLE LOADER_SETTINGS ADD LOAD_DETAIL_POOL_SIZE INTEGER DEFAULT 100;

ALTER TABLE LOADER_SETTINGS ADD LOAD_DETAIL_THREAD_COUNT INTEGER DEFAULT 2;

COMMENT ON COLUMN LOADER_SETTINGS.LOAD_DETAIL_POOL_SIZE IS ' оличество телефонов, дл€ которых детализаци€ загружаетс€ в одной сессии';

COMMENT ON COLUMN LOADER_SETTINGS.LOAD_DETAIL_THREAD_COUNT IS ' оличество параллельных сессий дл€ загрузки детализации';

INSERT INTO LOADER_SETTINGS (
  LOADER_DB_CONNECTION,
  LOADER_DB_USER_NAME,
  LOADER_DB_PASSWORD
) VALUES (
  'beta.tarifer.ru:1521/XE', 
  'db_loader', 
  'db_loader'
);
COMMIT;
