CREATE TABLE LOG_CHECK_PHONE_STATUS
(
  PHONE_NUMBER VARCHAR2(10) NOT NULL,
  DATE_CREATED DATE,
  INSERT_DATE DATE DEFAULT SYSDATE,
  IS_ERROR INTEGER,
  ERROR_TEXT VARCHAR2 (250)
  
);

COMMENT ON TABLE LOG_CHECK_PHONE_STATUS IS 'Очередь для обновления статусов по номеру телефона';
COMMENT ON COLUMN LOG_CHECK_PHONE_STATUS.PHONE_NUMBER IS 'Номер телефона';
COMMENT ON COLUMN LOG_CHECK_PHONE_STATUS.DATE_CREATED IS 'Дата создания записи в очереди (QUEUE_FOR_CHECK_PHONE_STATUS)';
COMMENT ON COLUMN LOG_CHECK_PHONE_STATUS.INSERT_DATE IS 'Дата создания записи в логе (LOG_CHECK_PHONE_STATUS)';
COMMENT ON COLUMN LOG_CHECK_PHONE_STATUS.IS_ERROR IS 'Статус проверки номера (0 -без ошибки, 1 - с ошибкой)';
COMMENT ON COLUMN LOG_CHECK_PHONE_STATUS.ERROR_TEXT IS 'Текст ошибки';