CREATE TABLE LOG_DISCR_SPISANIE_ABON
(
  YEAR_MONTH       NUMBER(38),
  PHONE_NUMBER     VARCHAR2(10 CHAR),
  DATE_INSERT      DATE,
  ABON_SUM         NUMBER(15,2),
  CHARGES_TYPE_ID  NUMBER(38),
  TEXT_COMMENT     VARCHAR2(2000 CHAR),
  BALANCE          NUMBER(15,2),
  TARIFF_ID        NUMBER(38)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE LOG_DISCR_SPISANIE_ABON IS 'Логи дискретного списания абон. плат по тарифам и услугам';

COMMENT ON COLUMN LOG_DISCR_SPISANIE_ABON.TARIFF_ID IS 'Код тарифа';

COMMENT ON COLUMN LOG_DISCR_SPISANIE_ABON.YEAR_MONTH IS 'Год / Месяц';

COMMENT ON COLUMN LOG_DISCR_SPISANIE_ABON.PHONE_NUMBER IS 'Телефон';

COMMENT ON COLUMN LOG_DISCR_SPISANIE_ABON.DATE_INSERT IS 'Дата списания';

COMMENT ON COLUMN LOG_DISCR_SPISANIE_ABON.ABON_SUM IS 'Сумма списания';

COMMENT ON COLUMN LOG_DISCR_SPISANIE_ABON.CHARGES_TYPE_ID IS 'Тип списания';

COMMENT ON COLUMN LOG_DISCR_SPISANIE_ABON.TEXT_COMMENT IS 'Примечание';

COMMENT ON COLUMN LOG_DISCR_SPISANIE_ABON.BALANCE IS 'Величина баланса';

CREATE INDEX I_LOG_DISCR_SPIS_AB_CH_TYPE_ID ON LOG_DISCR_SPISANIE_ABON
(CHARGES_TYPE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX I_LOG_DISCR_SPIS_AB_PHN ON LOG_DISCR_SPISANIE_ABON
(PHONE_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE LOG_DISCR_SPISANIE_ABON ADD (
  CONSTRAINT FK_DISCR_SPIS_AB_CH_TYPE_ID 
  FOREIGN KEY (CHARGES_TYPE_ID) 
  REFERENCES BALANCE_CHARGES_TYPES (CHARGES_TYPE_ID));