CREATE TABLE LOYAL_PHONE_FOR_BLOCK(
  PHONE_NUMBER VARCHAR2(10 CHAR),
  ACCOUNT_ID INTEGER,
  DATE_CHECK DATE,
  DATE_FUTURE_BLOCK DATE,
  BALANCE_BLOCK NUMBER(13, 2),
  FIO VARCHAR2(100 CHAR)
  );
  
GRANT SELECT, INSERT, DELETE, UPDATE ON LOYAL_PHONE_FOR_BLOCK TO LONTANA_ROLE; 
  