CREATE TABLE MOB_PAY_LOG
(
  PHONE        VARCHAR2(11 BYTE),
  SUM_PAY      NUMBER,
  REQ_COUNT    INTEGER,
  DATE_INSERT  DATE,
  RES_CODE     INTEGER,
  ERROR_TEXT   VARCHAR2(2000 BYTE)
);

COMMENT ON TABLE MOB_PAY_LOG IS 'лог платежей через определенный промежуток времени';

COMMENT ON COLUMN MOB_PAY_LOG.PHONE IS 'НОМЕР ТЕЛЕФОНА';

COMMENT ON COLUMN MOB_PAY_LOG.SUM_PAY IS 'СУММА ПЛАТЕЖА';

COMMENT ON COLUMN MOB_PAY_LOG.REQ_COUNT IS 'КОЛИЧЕСТВО ЗАПРОСОВ';

COMMENT ON COLUMN MOB_PAY_LOG.DATE_INSERT IS 'ДАТА ДОБАВЛЕНИЯ';

COMMENT ON COLUMN MOB_PAY_LOG.RES_CODE IS 'КОД ОТВЕТА';

COMMENT ON COLUMN MOB_PAY_LOG.ERROR_TEXT IS 'ТЕКСТ ОШИБКИ';



CREATE OR REPLACE TRIGGER TI_MOB_PAY_LOG
--#Version=1
  BEFORE INSERT ON  MOB_PAY_LOG FOR EACH ROW
BEGIN
     :NEW.date_insert := sysdate;
END;
/

create index I_MOB_PAY_LOG_PHONE on MOB_PAY_LOG (phone);

GRANT DELETE, INSERT, SELECT, UPDATE ON MOB_PAY_LOG TO CORP_MOBILE_ROLE;

GRANT SELECT ON MOB_PAY_LOG TO CORP_MOBILE_ROLE_RO;

Alter table MOB_PAY_LOG add( USER_CREATED varchar2(30));

COMMENT ON COLUMN MOB_PAY_LOG.USER_CREATED IS 'Создавший пользователь';

ALTER TABLE MOB_PAY_LOG ADD(
  REQUEST_TEXT VARCHAR2(1000),
  RESPONSE_ADD_PAY VARCHAR2(1000),
  RESPONSE_CHECK_STATUS_PAY VARCHAR2(1000)
);


COMMENT ON COLUMN MOB_PAY_LOG.REQUEST_TEXT IS 'Текст запроса';

COMMENT ON COLUMN MOB_PAY_LOG.RESPONSE_ADD_PAY IS 'Текст ответа на добавление платежа';


COMMENT ON COLUMN MOB_PAY_LOG.RESPONSE_CHECK_STATUS_PAY IS 'Текст ответа на проверку статуса платежа';