CREATE TABLE MOB_PAY_IN_PROCESSED
(
  PHONE         VARCHAR2(11 BYTE),
  REQUEST_TEXT  VARCHAR2(1000 BYTE),
  DATE_INSERT   DATE,
  USER_CREATED  VARCHAR2(30 BYTE),
  REQ_COUNT     INTEGER
);

COMMENT ON TABLE MOB_PAY_IN_PROCESSED IS 'НВЕПЕДЭ МЕ НАПЮАНРЮММШУ ОКЮРЕФЕИ';

COMMENT ON COLUMN MOB_PAY_IN_PROCESSED.PHONE IS 'мнлеп рекетнмю';

COMMENT ON COLUMN MOB_PAY_IN_PROCESSED.REQUEST_TEXT IS 'рейя гюопняю';

COMMENT ON COLUMN MOB_PAY_IN_PROCESSED.DATE_INSERT IS 'дюрю днаюбкемхъ';

COMMENT ON COLUMN MOB_PAY_IN_PROCESSED.USER_CREATED IS 'янгдюбьхи онкэгнбюрекэ';

COMMENT ON COLUMN MOB_PAY_IN_PROCESSED.REQ_COUNT IS 'йнкхвеярбн гюопнянб';



CREATE INDEX I_MOB_PAY_IN_PROCESSED ON MOB_PAY_IN_PROCESSED
(PHONE);


CREATE OR REPLACE TRIGGER TI_MOB_PAY_IN_PROCESSED
--#Version=1
  BEFORE INSERT ON MOB_PAY_IN_PROCESSED FOR EACH ROW
BEGIN
  :NEW.date_insert := sysdate;
  :NEW.req_count := 0;
END;
/


GRANT DELETE, INSERT, SELECT, UPDATE ON MOB_PAY_IN_PROCESSED TO CORP_MOBILE_ROLE;

GRANT SELECT ON MOB_PAY_IN_PROCESSED TO CORP_MOBILE_ROLE_RO;
