CREATE TABLE NUM_WITHOUT_TRAFFIC_EXCLUSION(
  EXCLUSION_ID INTEGER NOT NULL PRIMARY KEY,
  PHONE_NUMBER VARCHAR(10 CHAR) NOT NULL,
  USER_CREATED VARCHAR2(30 CHAR),
  DATE_CREATED DATE,
  USER_LAST_UPDATED VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED DATE
  );



COMMENT ON TABLE NUM_WITHOUT_TRAFFIC_EXCLUSION IS 'Справочник роуминговых провайдеров';

COMMENT ON COLUMN NUM_WITHOUT_TRAFFIC_EXCLUSION.EXCLUSION_ID IS 'Первичный ключ';
COMMENT ON COLUMN NUM_WITHOUT_TRAFFIC_EXCLUSION.PHONE_NUMBER IS 'Код провайдера';
COMMENT ON COLUMN NUM_WITHOUT_TRAFFIC_EXCLUSION.USER_CREATED IS 'Создавший пользователь';
COMMENT ON COLUMN NUM_WITHOUT_TRAFFIC_EXCLUSION.DATE_CREATED IS 'Дата создания';
COMMENT ON COLUMN NUM_WITHOUT_TRAFFIC_EXCLUSION.USER_LAST_UPDATED IS 'Последний обновивший пользователь';
COMMENT ON COLUMN NUM_WITHOUT_TRAFFIC_EXCLUSION.DATE_LAST_UPDATED IS 'Дата последнего обновления';


CREATE INDEX I_NUM_WITHOUT_TRAFFIC_EXC_PN ON NUM_WITHOUT_TRAFFIC_EXCLUSION(PHONE_NUMBER);

  
CREATE SEQUENCE S_NEW_EXCLUSION_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;  
  
CREATE OR REPLACE FUNCTION NEW_EXCLUSION_ID RETURN NUMBER IS
  vRES NUMBER;
BEGIN
  SELECT S_NEW_EXCLUSION_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;

CREATE OR REPLACE TRIGGER TIU_NUM_WITHOUT_TRAFFIC_EXC
  BEFORE INSERT OR UPDATE ON NUM_WITHOUT_TRAFFIC_EXCLUSION FOR EACH ROW
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.EXCLUSION_ID, 0) = 0 then
      :NEW.EXCLUSION_ID := NEW_EXCLUSION_ID;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
 

grant select,insert, update on num_without_traffic_exclusion to CORP_MOBILE_ROLE;
grant select,insert, update on num_without_traffic_exclusion to CORP_MOBILE_ROLE_RO;

grant execute ON NEW_EXCLUSION_ID to CORP_MOBILE_ROLE;
grant execute ON NEW_EXCLUSION_ID to CORP_MOBILE_ROLE_ro;