CREATE TABLE OPERATORS
(
  OPERATOR_ID         INTEGER                   NOT NULL,
  OPERATOR_NAME       VARCHAR2(100 CHAR),
  USER_CREATED        VARCHAR2(30 CHAR),
  DATE_CREATED        DATE,
  USER_LAST_UPDATED   VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED   DATE,
  LOADER_SCRIPT_NAME  VARCHAR2(30 CHAR),
  ORDER_NUMBER        NUMBER(4)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OPERATORS IS 'Операторы сотовой связи';

COMMENT ON COLUMN OPERATORS.OPERATOR_ID IS 'Первичный ключ';

COMMENT ON COLUMN OPERATORS.OPERATOR_NAME IS 'Наименование оператора сотовой связи';

COMMENT ON COLUMN OPERATORS.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN OPERATORS.DATE_CREATED IS 'Дата/время создания записи';

COMMENT ON COLUMN OPERATORS.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';

COMMENT ON COLUMN OPERATORS.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';


CREATE UNIQUE INDEX PK_OPERATORS ON OPERATORS
(OPERATOR_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

  
  
create index I_OPERATORS_ID_NAME on OPERATORS (OPERATOR_ID, OPERATOR_NAME)
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

  


CREATE OR REPLACE TRIGGER TIU_OPERATORS
  BEFORE INSERT OR UPDATE ON OPERATORS FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.OPERATOR_ID, 0) = 0 then
      :NEW.OPERATOR_ID := NEW_OPERATOR_ID;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/


ALTER TABLE OPERATORS ADD (
  CONSTRAINT PK_OPERATORS
 PRIMARY KEY
 (OPERATOR_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));