CREATE TABLE PHONE_NUMBER_BLOCK_DENIED(
  PHONE_NUMBER  VARCHAR2(10 CHAR)               NOT NULL,
  USER_ADD      VARCHAR2(30 CHAR),
  DATE_ADD      DATE
  );

CREATE OR REPLACE TRIGGER TIU_PHONE_NUMBER_BLOCK_DENIED
  BEFORE INSERT OR UPDATE ON PHONE_NUMBER_BLOCK_DENIED FOR EACH ROW
--#Version=1
BEGIN
  :NEW.USER_ADD := USER;
  :NEW.DATE_ADD := SYSDATE;
END;
/

GRANT DELETE, INSERT, SELECT, UPDATE ON PHONE_NUMBER_BLOCK_DENIED TO CORP_MOBILE_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON PHONE_NUMBER_BLOCK_DENIED TO SIM_TRADE_ROLE;