--drop TABLE PHONE_NUMBER_TYPES

CREATE TABLE PHONE_NUMBER_TYPES (
  PHONE_NUMBER_TYPE NUMBER(1, 0) CONSTRAINT PK_PHONE_NUMBER_TYPES PRIMARY KEY,
  PHONE_NUMBER_TYPE_NAME VARCHAR2(20 CHAR)
  );
  
INSERT INTO PHONE_NUMBER_TYPES 
  (PHONE_NUMBER_TYPE, PHONE_NUMBER_TYPE_NAME)
VALUES
  (0, 'Федеральный');
   
INSERT INTO PHONE_NUMBER_TYPES 
  (PHONE_NUMBER_TYPE, PHONE_NUMBER_TYPE_NAME)
VALUES
  (1, 'Прямой');

COMMIT;
