CREATE TABLE PHONE_CALC_ABON_TP_UNLIM_ON
(
  YEAR_MONTH    INTEGER,
  PHONE_NUMBER  VARCHAR2(10 CHAR)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          9M
            NEXT             8K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PHONE_CALC_ABON_TP_UNLIM_ON IS 'Номера, у которых было недостаточно средств для списания абонки и у которых измененно списание абонки';

COMMENT ON COLUMN PHONE_CALC_ABON_TP_UNLIM_ON.YEAR_MONTH IS 'Год/месяц';

COMMENT ON COLUMN PHONE_CALC_ABON_TP_UNLIM_ON.PHONE_NUMBER IS 'Номер';


CREATE UNIQUE INDEX I_PHONE_YEAR_MONTH ON PHONE_CALC_ABON_TP_UNLIM_ON
(PHONE_NUMBER, YEAR_MONTH)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          4M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
COMPRESS 1;

alter table PHONE_CALC_ABON_TP_UNLIM_ON add (TARIFF_ID INTEGER);
COMMENT ON COLUMN PHONE_CALC_ABON_TP_UNLIM_ON.TARIFF_ID IS 'Код тарифного плана';

ALTER TABLE PHONE_CALC_ABON_TP_UNLIM_ON ADD DATE_CREATED DATE;
COMMENT ON COLUMN PHONE_CALC_ABON_TP_UNLIM_ON.DATE_CREATED IS 'Дата создания записи';


CREATE OR REPLACE TRIGGER CORP_MOBILE.TID_PHONE_CALC_ABON_TP_UNL
BEFORE DELETE OR INSERT
ON CORP_MOBILE.PHONE_CALC_ABON_TP_UNLIM_ON 
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
  vYEAR_MONTH INTEGER; 
  vPHONE_NUMBER VARCHAR2(10 char);
  vTARIFF_ID INTEGER;
  vDATE_INSERT DATE;
  vDATE_DELETE DATE; 
  vNOTE VARCHAR2(50 char);
BEGIN
  --если вставка записи, то указываем дату вставки
  IF INSERTING THEN
    :NEW.DATE_CREATED := SYSDATE;
    
    vYEAR_MONTH := :NEW.YEAR_MONTH;
    vPHONE_NUMBER := :NEW.PHONE_NUMBER;
    vTARIFF_ID := :NEW.TARIFF_ID;
    vDATE_INSERT := :NEW.DATE_CREATED;
    vDATE_DELETE := NULL; 
    vNote := 'Вставка записи';
  ELSIF DELETING THEN  --если удаление, указываем все параметры и дату адаления
    vYEAR_MONTH := :OLD.YEAR_MONTH;
    vPHONE_NUMBER := :OLD.PHONE_NUMBER;
    vTARIFF_ID := :OLD.TARIFF_ID;
    vDATE_INSERT := :OLD.DATE_CREATED;
    vDATE_DELETE := sysdate; 
    vNote := 'Удаление записи';
  END IF;
  
  INSERT INTO PHONE_CALC_ABON_TP_UNLIM_LOG 
    (
      YEAR_MONTH, 
      PHONE_NUMBER, 
      TARIFF_ID, 
      DATE_INSERT, 
      DATE_DELETE, 
      NOTE,
      BALANCE,
      VIRT_BALANCE
    ) 
    VALUES 
    (
      vYEAR_MONTH,
      vPHONE_NUMBER,
      vTARIFF_ID,
      vDATE_INSERT,
      vDATE_DELETE,
      vNote,
      GET_ABONENT_BALANCE(vPHONE_NUMBER),
      GET_ABONENT_BALANCE(vPHONE_NUMBER, null, null, 1)
    );
END TID_PHONE_CALC_ABON_TP_UNL;
