CREATE TABLE PHONE_ACTIV_LOG(
  YEAR_MONTH INTEGER NOT NULL,
  PHONE_NUMBER VARCHAR2(10 CHAR) NOT NULL,
  BAN NUMBER,
  DATE_INSERT DATE
  );
  
CREATE UNIQUE INDEX UNIQUE_PHONE_ACTIV_LOG_YM_P ON PHONE_ACTIV_LOG
(YEAR_MONTH, PHONE_NUMBER);

CREATE OR REPLACE TRIGGER TIU_PHONE_ACTIV_LOG
  BEFORE INSERT OR UPDATE ON PHONE_ACTIV_LOG FOR EACH ROW
--#Version=1
BEGIN
  :NEW.DATE_INSERT:=SYSDATE;
END;

GRANT SELECT, INSERT, UPDATE, DELETE ON PHONE_ACTIV_LOG TO CORP_MOBILE_ROLE;

GRANT SELECT ON PHONE_ACTIV_LOG TO CORP_MOBILE_ROLE_RO;