CREATE TABLE QUEUE_UPDATE_PHONE_HISTORY(
  PHONE_NUMBER VARCHAR2(100 Char),
  BEGIN_DATE DATE,
  END_DATE DATE,
  PHONE_IS_ACTIVE NUMBER(1),
  CELL_PLAN_CODE VARCHAR2(50 Char),
  CONSERVATION NUMBER(1),
  SYSTEM_BLOCK NUMBER(1),
  STATUS_ID INTEGER, 
  DATE_REPORT DATE
  );
  
  
CREATE INDEX I_QUEUE_UPDATE_PHONE_HISTORY ON QUEUE_UPDATE_PHONE_HISTORY(PHONE_NUMBER, DATE_REPORT);


CREATE INDEX I_QUEUE_UPDATE_PHONE_HISTORY2 ON QUEUE_UPDATE_PHONE_HISTORY(PHONE_NUMBER, PHONE_IS_ACTIVE, CELL_PLAN_CODE, STATUS_ID,DATE_REPORT);  
