CREATE TABLE QUEUE_CURRENT_BALANCES(
  QUEUE_ID INTEGER PRIMARY KEY,
  PHONE_NUMBER VARCHAR2(10 CHAR) NOT NULL,
  DATE_INSERT DATE,
  QUEUE_TYPE INTEGER
  );
  
CREATE OR REPLACE TRIGGER TIU_QUEUE_CURRENT_BALANCES
  BEFORE INSERT OR UPDATE ON QUEUE_CURRENT_BALANCES FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    :NEW.DATE_INSERT:=SYSDATE;
   /* SELECT NVL(MAX(QUEUE_ID), 0)+1 INTO :NEW.QUEUE_ID
      FROM QUEUE_CURRENT_BALANCES;*/
  END IF;
END;
/

ALTER TABLE QUEUE_CURRENT_BALANCES ADD (
  CONSTRAINT FK_QCB_TYPES FOREIGN KEY (QUEUE_TYPE) 
  REFERENCES QCB_TYPES (QCB_ID)
  );
  
CREATE INDEX I_QUEUE_CURRENT_BALANCES_PH ON QUEUE_CURRENT_BALANCES(PHONE_NUMBER);

COMMENT ON TABLE CORP_MOBILE.QUEUE_CURRENT_BALANCES IS 'НВЕПЕДЭ МЮ ОЕПЕЯВЕР АЮКЮМЯЮ';

COMMENT ON COLUMN CORP_MOBILE.QUEUE_CURRENT_BALANCES.QUEUE_TYPE IS 'рхо нвепедх';

COMMENT ON COLUMN CORP_MOBILE.QUEUE_CURRENT_BALANCES.QUEUE_ID IS 'ID нвепедх';

COMMENT ON COLUMN CORP_MOBILE.QUEUE_CURRENT_BALANCES.PHONE_NUMBER IS 'мнлеп рекетнмю';

COMMENT ON COLUMN CORP_MOBILE.QUEUE_CURRENT_BALANCES.DATE_INSERT IS 'дюрю днаюбкемхъ';

GRANT INSERT, UPDATE, DELETE, SELECT ON QUEUE_CURRENT_BALANCES TO CORP_MOBILE_ROLE;