CREATE TABLE QUEUE_PHONE_REBLOCK_LOG(
  QUEUE_PHONE_REBLOCK_ID INTEGER,
  PHONE_NUMBER VARCHAR2(10 CHAR),
  DATE_ACTIV DATE,
  DATE_CREATED DATE,
  TICKED_UNLOCK_ID NVARCHAR2(15),
  DATE_UNLOCK DATE,
  TICKED_LOCK_ID NVARCHAR2(15),
  DATE_LOCK DATE, 
  ERROR_STR VARCHAR2(1000 CHAR),
  STREAM_ID INTEGER DEFAULT 0
  );

COMMENT ON TABLE QUEUE_PHONE_REBLOCK_LOG IS 'Лог очереди переблока номеров';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK_LOG.QUEUE_PHONE_REBLOCK_ID IS 'Идентификатор в очереди';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK_LOG.PHONE_NUMBER IS 'Телефон';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK_LOG.DATE_ACTIV IS 'Дата для переблока';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK_LOG.DATE_CREATED IS 'Дата создания';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK_LOG.TICKED_UNLOCK_ID IS 'Номер заявки на разблок';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK_LOG.DATE_UNLOCK IS 'Дата разблока';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK_LOG.TICKED_LOCK_ID IS 'Номер заявки на блок';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK_LOG.DATE_LOCK IS 'Дата блока';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK_LOG.ERROR_STR IS 'Ошибки';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK_LOG.STREAM_ID IS 'Поток обработки';

CREATE INDEX QUEUE_PHONE_REBLOCK_LOG_PHONE ON QUEUE_PHONE_REBLOCK_LOG(PHONE_NUMBER);

CREATE INDEX QUEUE_PHONE_REBLOCK_LOG_TK_LCK ON QUEUE_PHONE_REBLOCK_LOG(TICKED_LOCK_ID);

CREATE INDEX QUEUE_PHONE_REBLOCK_LOG_TK_UNL ON QUEUE_PHONE_REBLOCK_LOG(TICKED_UNLOCK_ID);

--GRANT SELECT, INSERT, UPDATE, DELETE ON QUEUE_PHONE_REBLOCK_LOG TO CORP_MOBILE_ROLE;

--GRANT SELECT ON QUEUE_PHONE_REBLOCK_LOG TO CORP_MOBILE_ROLE_RO;

--GRANT SELECT, INSERT, UPDATE, DELETE ON QUEUE_PHONE_REBLOCK_LOG TO LONTANA_ROLE;

--GRANT SELECT, INSERT, UPDATE, DELETE ON QUEUE_PHONE_REBLOCK_LOG TO SIM_TRADE_ROLE;