CREATE TABLE QUEUE_FOR_CHECK_PHONE_STATUS
(
  PHONE_NUMBER VARCHAR2(10) NOT NULL,
  DATE_CREATED DATE DEFAULT SYSDATE
  
);

COMMENT ON TABLE QUEUE_FOR_CHECK_PHONE_STATUS IS 'Очередь для обновления статусов по номеру телефона';
COMMENT ON COLUMN QUEUE_FOR_CHECK_PHONE_STATUS.PHONE_NUMBER IS 'Номер телефона';
COMMENT ON COLUMN QUEUE_FOR_CHECK_PHONE_STATUS.DATE_CREATED IS 'Дата создания записи';
