CREATE TABLE QUEUE_PHONE_BLOCK_SAVE(
  PHONE_NUMBER NUMBER(11) NOT NULL,
  DATE_INSERT DATE,
  REASON_TYPE_ID INTEGER
  );
  
CREATE OR REPLACE TRIGGER TIU_QUEUE_PHONE_BLOCK_SAVE
  BEFORE INSERT OR UPDATE ON QUEUE_PHONE_BLOCK_SAVE FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :NEW.DATE_INSERT:=SYSDATE;
  END IF;
END;    