CREATE TABLE REF_TEXT_TYPE
--
--Version=1
--
--v.1 19.02.2016 Афросин - добавил таблицу "Справочник типов текстов сообщений"
--
(
  REF_TEXT_TYPE_ID       INTEGER,
  REF_TEXT_TYPE_NAME  VARCHAR2(100),
  DATE_CREATED DATE DEFAULT SYSDATE,
  USER_CREATED VARCHAR2 (20) DEFAULT USER,
  DATE_UPDATED DATE,
  USER_UPDATED VARCHAR2 (20),
  
  CONSTRAINT REF_TEXT_TYPE_ID_PK PRIMARY KEY (REF_TEXT_TYPE_ID)
  
);

COMMENT ON TABLE REF_TEXT_TYPE IS 'Справочник типов текстов сообщений';

COMMENT ON COLUMN REF_TEXT_TYPE.REF_TEXT_TYPE_ID IS 'ID записи';

COMMENT ON COLUMN REF_TEXT_TYPE.REF_TEXT_TYPE_NAME IS 'Тип запроса';

COMMENT ON COLUMN REF_TEXT_TYPE.DATE_CREATED IS 'Дата создания';

COMMENT ON COLUMN REF_TEXT_TYPE.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN REF_TEXT_TYPE.DATE_UPDATED IS 'Дата обновления';

COMMENT ON COLUMN REF_TEXT_TYPE.USER_UPDATED IS 'Пользователь, обновивший запись';

CREATE OR REPLACE TRIGGER TIU_REF_TEXT_TYPE
  BEFORE INSERT OR UPDATE ON REF_TEXT_TYPE FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    :NEW.REF_TEXT_TYPE_ID := S_NEW_REF_TEXT_TYPE_ID.NEXTVAL;
  END IF;
  
  IF UPDATING THEN
    :NEW.USER_UPDATED := USER;
    :NEW.DATE_UPDATED := SYSDATE;
  END IF;
END;


