CREATE TABLE REPORT_PHONE_INACTIVE
(
  LOGIN                 VARCHAR2(30 CHAR),
  PHONE_NUMBER_FEDERAL  VARCHAR2(10 CHAR),
  CONTRACT_DATE         DATE,
  BALANCE               NUMBER(15,2),
  PHONE_IS_ACTIVE       VARCHAR2(25 CHAR),
  DOP_STATUS_NAME       VARCHAR2(100 CHAR),
  LAST_CHECK_DATE_TIME  DATE,
  DATE_CREATED          DATE,
  CURR_TARIFF_ID        NUMBER(38),
  TARIFF_NAME           VARCHAR2(300 CHAR),
  INSERT_DATE           DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE REPORT_PHONE_INACTIVE IS 'Номера с отсутствующей активностью';

COMMENT ON COLUMN REPORT_PHONE_INACTIVE.LOGIN IS 'Л/с (логин)';

COMMENT ON COLUMN REPORT_PHONE_INACTIVE.PHONE_NUMBER_FEDERAL IS 'Номер';

COMMENT ON COLUMN REPORT_PHONE_INACTIVE.CONTRACT_DATE IS 'Дата контракта';

COMMENT ON COLUMN REPORT_PHONE_INACTIVE.BALANCE IS 'Баланс';

COMMENT ON COLUMN REPORT_PHONE_INACTIVE.PHONE_IS_ACTIVE IS 'Статус';

COMMENT ON COLUMN REPORT_PHONE_INACTIVE.DOP_STATUS_NAME IS 'Доп. статус';

COMMENT ON COLUMN REPORT_PHONE_INACTIVE.LAST_CHECK_DATE_TIME IS 'Дата/время последнего обновления';

COMMENT ON COLUMN REPORT_PHONE_INACTIVE.DATE_CREATED IS 'Дата создания записи';

COMMENT ON COLUMN REPORT_PHONE_INACTIVE.CURR_TARIFF_ID IS 'ID тарифа';

COMMENT ON COLUMN REPORT_PHONE_INACTIVE.TARIFF_NAME IS 'Наименование тарифа';

COMMENT ON COLUMN REPORT_PHONE_INACTIVE.INSERT_DATE IS 'Дата вставки записи в таблицу';

GRANT SELECT ON REPORT_PHONE_INACTIVE TO CORP_MOBILE_ROLE;

GRANT SELECT ON REPORT_PHONE_INACTIVE TO CORP_MOBILE_ROLE_RO;

GRANT SELECT ON REPORT_PHONE_INACTIVE TO CRM_USER;