CREATE TABLE ROAMING_TYPE
(
  ROAMING_TYPE_ID                       INTEGER    PRIMARY KEY   NOT NULL,
  ROAMING_TYPE_NAME                     VARCHAR2(50 CHAR),
  USER_CREATED               VARCHAR2(30),
  DATE_CREATED               DATE,
  USER_LAST_UPDATED               VARCHAR2(30),
  DATE_LAST_UPDATED                 DATE
);

COMMENT ON TABLE ROAMING_TYPE IS 'Справочник типов роуминга';

COMMENT ON COLUMN ROAMING_TYPE.ROAMING_TYPE_ID IS 'ID роуминга';
COMMENT ON COLUMN ROAMING_TYPE.ROAMING_TYPE_NAME IS 'Название типа роуминга';
COMMENT ON COLUMN ROAMING_TYPE.USER_CREATED IS 'Создавший пользователь';
COMMENT ON COLUMN ROAMING_TYPE.DATE_CREATED IS 'Дата создания';
COMMENT ON COLUMN ROAMING_TYPE.USER_LAST_UPDATED IS 'Последний обновивший пользователь';
COMMENT ON COLUMN ROAMING_TYPE.DATE_LAST_UPDATED IS 'Дата последнего обновления';

CREATE OR REPLACE TRIGGER TIU_ROAMING_TYPE
  BEFORE INSERT OR UPDATE ON ROAMING_TYPE FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  
  if UPDATING then
    :NEW.USER_LAST_UPDATED := USER;
    :NEW.DATE_LAST_UPDATED := SYSDATE;
  end if;
END;

GRANT SELECT ON ROAMING_TYPE TO  CORP_MOBILE_ROLE;
GRANT SELECT ON ROAMING_TYPE TO CORP_MOBILE_ROLE_RO;