CREATE TABLE ROAMING_PROVIDERS
(
  ROAMING_PROVIDER_ID                       INTEGER       NOT NULL,
  ROAMING_PROVIDER_CODE                     VARCHAR2(8 CHAR),
  TECHNOLOGY                     varchar2(1),
  EFFECTIVE_DATE                  DATE,
  COUNTRY_CODE                       INTEGER,
  DAMPS_PROV_NAME                   VARCHAR2(150),
  FILETYPE                   VARCHAR2(20),
  USER_CREATED               VARCHAR2(30),
  DATE_CREATED               DATE,
  USER_LAST_UPDATED               VARCHAR2(30),
  DATE_LAST_UPDATED                 DATE
);

COMMENT ON TABLE ROAMING_PROVIDERS IS 'Справочник роуминговых провайдеров';

COMMENT ON COLUMN ROAMING_PROVIDERS.ROAMING_PROVIDER_ID IS 'Первичный ключ';
COMMENT ON COLUMN ROAMING_PROVIDERS.ROAMING_PROVIDER_CODE IS 'Код провайдера';
COMMENT ON COLUMN ROAMING_PROVIDERS.TECHNOLOGY IS 'Технология';
COMMENT ON COLUMN ROAMING_PROVIDERS.EFFECTIVE_DATE IS 'Дата назначения';
COMMENT ON COLUMN ROAMING_PROVIDERS.COUNTRY_CODE IS 'Код страны пребывания';
COMMENT ON COLUMN ROAMING_PROVIDERS.DAMPS_PROV_NAME IS 'Название провайдера, Страна(название партнера)';
COMMENT ON COLUMN ROAMING_PROVIDERS.FILETYPE IS 'Тип файла';
COMMENT ON COLUMN ROAMING_PROVIDERS.USER_CREATED IS 'Создавший пользователь';
COMMENT ON COLUMN ROAMING_PROVIDERS.DATE_CREATED IS 'Дата создания';
COMMENT ON COLUMN ROAMING_PROVIDERS.USER_LAST_UPDATED IS 'Последний обновивший пользователь';
COMMENT ON COLUMN ROAMING_PROVIDERS.DATE_LAST_UPDATED IS 'Дата последнего обновления';



CREATE SEQUENCE S_NEW_ROAMING_PROVIDERS_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE OR REPLACE TRIGGER TI_ROAMING_PROVIDERS
  BEFORE INSERT OR UPDATE ON ROAMING_PROVIDERS FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.ROAMING_PROVIDER_ID, 0) = 0 then
      :NEW.ROAMING_PROVIDER_ID := S_NEW_ROAMING_PROVIDERS_ID.NEXTVAL;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  
  if UPDATING then
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
  end if;
END;

Alter table ROAMING_PROVIDERS add (ROAMING_TYPE_ID INTEGER);

COMMENT ON COLUMN ROAMING_PROVIDERS.ROAMING_TYPE_ID IS 'ROAMING_TYPE_ID признака роуминга из таблицы ROAMING_TYPE';
grant select, update on ROAMING_PROVIDERS to CORP_MOBILE_ROLE;
grant select, update on ROAMING_PROVIDERS to CORP_MOBILE_ROLE_RO;

ALTER TABLE ROAMING_PROVIDERS ADD (
  CONSTRAINT ROAMING_PROVIDERS_PK
  PRIMARY KEY
  (ROAMING_PROVIDER_ID)
  USING INDEX ROAMING_PROVIDERS_PK
  ENABLE VALIDATE);
