CREATE TABLE SEND_MAIL_PARAMETRES(
  SMTP_SERVER VARCHAR2(100 CHAR) NOT NULL,
  SMTP_PORT INTEGER DEFAULT 25,
  USER_LOGIN VARCHAR2(100 CHAR) NOT NULL,
  USER_PASSWORD VARCHAR2(100 CHAR)
);

COMMENT ON TABLE SEND_MAIL_PARAMETRES IS 'Параметры e-mail для отправки отчетов';