CREATE TABLE SEND_MAIL_PARAM_BY_ACCOUNT
(
  SMTP_SERVER    VARCHAR2(100 CHAR)             NOT NULL,
  SMTP_PORT      INTEGER,
  USER_LOGIN     VARCHAR2(100 CHAR)             NOT NULL,
  USER_PASSWORD  VARCHAR2(100 CHAR),
  ACCOUNT_ID     INTEGER,
  SMTP_FROM      VARCHAR2(100 CHAR)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             8K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SEND_MAIL_PARAM_BY_ACCOUNT IS 'Ì‡ÒÚÓÈÍË ‡ÍÍ‡ÛÌÚÓ‚ ‰Îˇ ‡ÒÒ˚ÎÍË';

COMMENT ON COLUMN SEND_MAIL_PARAM_BY_ACCOUNT.SMTP_SERVER IS '—≈–¬≈–';

COMMENT ON COLUMN SEND_MAIL_PARAM_BY_ACCOUNT.SMTP_PORT IS 'œŒ–“';

COMMENT ON COLUMN SEND_MAIL_PARAM_BY_ACCOUNT.USER_LOGIN IS 'ÀŒ√»Õ œŒÀ‹«Œ¬¿“≈Àﬂ';

COMMENT ON COLUMN SEND_MAIL_PARAM_BY_ACCOUNT.USER_PASSWORD IS 'œ¿–ŒÀ‹ œŒÀ‹«Œ¬¿“≈Àﬂ';

COMMENT ON COLUMN SEND_MAIL_PARAM_BY_ACCOUNT.ACCOUNT_ID IS 'ID œŒÀ‹«Œ¬¿“≈Àﬂ';

COMMENT ON COLUMN SEND_MAIL_PARAM_BY_ACCOUNT.SMTP_FROM IS 'Œ“  Œ√Œ Œœ–¿¬À≈ÕŒ';



CREATE OR REPLACE SYNONYM CORP_MOBILE_C20141121.SEND_MAIL_PARAM_BY_ACCOUNT FOR SEND_MAIL_PARAM_BY_ACCOUNT;


CREATE OR REPLACE SYNONYM CORP_MOBILE_C20150320.SEND_MAIL_PARAM_BY_ACCOUNT FOR SEND_MAIL_PARAM_BY_ACCOUNT;


CREATE OR REPLACE SYNONYM CORP_MOBILE_C20150327.SEND_MAIL_PARAM_BY_ACCOUNT FOR SEND_MAIL_PARAM_BY_ACCOUNT;


CREATE OR REPLACE SYNONYM CORP_MOBILE_C20150330.SEND_MAIL_PARAM_BY_ACCOUNT FOR SEND_MAIL_PARAM_BY_ACCOUNT;


CREATE OR REPLACE SYNONYM CORP_MOBILE_C20150402.SEND_MAIL_PARAM_BY_ACCOUNT FOR SEND_MAIL_PARAM_BY_ACCOUNT;


CREATE OR REPLACE SYNONYM CORP_MOBILE_C20150403.SEND_MAIL_PARAM_BY_ACCOUNT FOR SEND_MAIL_PARAM_BY_ACCOUNT;


CREATE OR REPLACE SYNONYM CORP_MOBILE_C20150406.SEND_MAIL_PARAM_BY_ACCOUNT FOR SEND_MAIL_PARAM_BY_ACCOUNT;


GRANT DELETE, INSERT, SELECT, UPDATE ON SEND_MAIL_PARAM_BY_ACCOUNT TO CORP_MOBILE_C20141121;

GRANT DELETE, INSERT, SELECT, UPDATE ON SEND_MAIL_PARAM_BY_ACCOUNT TO CORP_MOBILE_C20150320;

GRANT DELETE, INSERT, SELECT, UPDATE ON SEND_MAIL_PARAM_BY_ACCOUNT TO CORP_MOBILE_C20150327;

GRANT DELETE, INSERT, SELECT, UPDATE ON SEND_MAIL_PARAM_BY_ACCOUNT TO CORP_MOBILE_C20150330;

GRANT DELETE, INSERT, SELECT, UPDATE ON SEND_MAIL_PARAM_BY_ACCOUNT TO CORP_MOBILE_C20150402;

GRANT DELETE, INSERT, SELECT, UPDATE ON SEND_MAIL_PARAM_BY_ACCOUNT TO CORP_MOBILE_C20150403;

GRANT DELETE, INSERT, SELECT, UPDATE ON SEND_MAIL_PARAM_BY_ACCOUNT TO CORP_MOBILE_C20150406;

GRANT DELETE, INSERT, SELECT, UPDATE ON SEND_MAIL_PARAM_BY_ACCOUNT TO CORP_MOBILE_ROLE;

GRANT SELECT ON SEND_MAIL_PARAM_BY_ACCOUNT TO CORP_MOBILE_ROLE_RO;
