CREATE TABLE SERVICES_CALL(
  AT_FT_CODE VARCHAR2(6 CHAR) PRIMARY KEY,
  AT_FT_DESC VARCHAR2(200 CHAR),
  AT_FT_DE VARCHAR2(200 CHAR),
  CALL_SOURCE VARCHAR2(3 CHAR) NOT NULL,
  NOT_USE_FOR_CALC NUMBER(1),
  DATE_INSERT DATE,
  DATE_UPDATE DATE,  
  SERVICE_TYPE VARCHAR2(1 CHAR);
  SERVICE_DIRECTION NUMBER(1);
  IS_ROAMING VARCHAR2(1 CHAR);
  ROAMING_ZONE VARCHAR2(6 CHAR);
  );
  
CREATE OR REPLACE TRIGGER TIU_SERVICES_CALL
  BEFORE INSERT OR UPDATE ON SERVICES_CALL FOR EACH ROW
BEGIN
  IF :NEW.CALL_SOURCE IS NULL THEN
    IF :NEW.AT_FT_CODE LIKE 'API%' THEN
      :NEW.CALL_SOURCE := 'API';
    ELSE
      :NEW.CALL_SOURCE := 'HB';
    END IF;
  END IF;
END;  

CREATE INDEX I_SERVICES_CALL_AT_FT_CODE_DE ON SERVICES_CALL
  (AT_FT_CODE, AT_FT_DESC, AT_FT_DE);

CREATE INDEX I_SERVICES_CALL_S ON SERVICES_CALL
  (CALL_SOURCE);

alter table SERVICES_CALL add SERVICE_TYPE VARCHAR2(1 CHAR);
alter table SERVICES_CALL add SERVICE_DIRECTION NUMBER(1);
alter table SERVICES_CALL add IS_ROAMING VARCHAR2(1 CHAR);
alter table SERVICES_CALL add ROAMING_ZONE VARCHAR2(6 CHAR);