CREATE TABLE SH_TARIFF_OPTION_COSTS
(
  TARIFF_OPTION_COST_ID  INTEGER                NOT NULL,
  TARIFF_OPTION_ID       INTEGER                NOT NULL,
  BEGIN_DATE             DATE                   NOT NULL,
  END_DATE               DATE                   NOT NULL,
  TARIFF_ID              INTEGER,
  TURN_ON_COST           NUMBER(12,2),
  MONTHLY_COST           NUMBER(12,2),
  USER_CREATED           VARCHAR2(30 CHAR),
  DATE_CREATED           DATE,
  USER_LAST_UPDATED      VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED      DATE,
  OPERATOR_TURN_ON_COST  NUMBER(12,2),
  OPERATOR_MONTHLY_COST  NUMBER(12,2),
  UPDATE_USER            VARCHAR2(50 BYTE),
  UPDATE_TIME            DATE
)