CREATE TABLE SH_TARIFF_OPTIONS
(
  TARIFF_OPTION_ID    INTEGER                   NOT NULL,
  OPERATOR_ID         INTEGER                   NOT NULL,
  OPTION_CODE         VARCHAR2(30 CHAR)         NOT NULL,
  OPTION_NAME         VARCHAR2(100 CHAR)        NOT NULL,
  USER_CREATED        VARCHAR2(30 CHAR),
  DATE_CREATED        DATE,
  USER_LAST_UPDATED   VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED   DATE,
  KOEF_KOMISS         NUMBER(13,2),
  CALC_UNBLOCK        NUMBER(1),
  DISCR_SPISANIE      NUMBER(1),
  OPTION_NAME_FOR_AB  VARCHAR2(100 CHAR),
  UPDATE_USER         VARCHAR2(50 BYTE),
  UPDATE_TIME         DATE
)