CREATE TABLE SIM
(
  SIM_ID              INTEGER                   NOT NULL,
  AGENT_ID            INTEGER                   NOT NULL,
  SUBAGENT_ID         INTEGER,
  OPERATOR_ID         INTEGER                   NOT NULL,
  DATE_INIT           DATE,
  STATUS_ID           INTEGER,
  DATE_MOVE           DATE,
  ACCOUNT             VARCHAR2(100 BYTE)        NOT NULL,
  CELL_NUMBER         VARCHAR2(10 BYTE)         NOT NULL,
  TARIFF_ID           INTEGER                   NOT NULL,
  SIM_NUMBER          VARCHAR2(100 BYTE),
  ABON_PAY            NUMBER(10,2)              DEFAULT 0,
  DATE_ACTIVATE       DATE,
  DATE_ERASE          DATE,
  BALANCE             NUMBER(10,2)              DEFAULT 0,
  DATE_BALANCE        DATE,
  DATE_LAST_ACTIVITY  DATE,
  SERVICEGID_STATUS   NUMBER(1)                 DEFAULT 0,
  CHECKED             NUMBER(1)                 DEFAULT 0                     NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SIM IS 'Реестр сим-карт';

COMMENT ON COLUMN SIM.SIM_ID IS 'Код сим-карты';

COMMENT ON COLUMN SIM.AGENT_ID IS 'Код агента';

COMMENT ON COLUMN SIM.SUBAGENT_ID IS 'Код субагента';

COMMENT ON COLUMN SIM.OPERATOR_ID IS 'Код оператора';

COMMENT ON COLUMN SIM.DATE_INIT IS 'Дата получения';

COMMENT ON COLUMN SIM.STATUS_ID IS 'Статус1';

COMMENT ON COLUMN SIM.DATE_MOVE IS 'Дата отгрузки субагенту';

COMMENT ON COLUMN SIM.ACCOUNT IS 'Лицевой счет';

COMMENT ON COLUMN SIM.CELL_NUMBER IS 'Номер телефона';

COMMENT ON COLUMN SIM.TARIFF_ID IS 'Тариф';

COMMENT ON COLUMN SIM.SIM_NUMBER IS 'Номер сим-карты';

COMMENT ON COLUMN SIM.ABON_PAY IS 'Абонентская плата';

COMMENT ON COLUMN SIM.DATE_ACTIVATE IS 'Дата активации(передачи абоненту)';

COMMENT ON COLUMN SIM.DATE_ERASE IS 'Дата списания';

COMMENT ON COLUMN SIM.BALANCE IS 'Баланс';

COMMENT ON COLUMN SIM.DATE_BALANCE IS 'Дата проверки баланса';

COMMENT ON COLUMN SIM.DATE_LAST_ACTIVITY IS 'Дата последнего активного действия(заполняется при отправке платного смс)';

COMMENT ON COLUMN SIM.SERVICEGID_STATUS IS 'Статус в сервис-гиде';

COMMENT ON COLUMN SIM.CHECKED IS '0-не проверена, 1-проверена';


CREATE UNIQUE INDEX PK_SIM ON SIM
(SIM_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX UK_SIM_NUM_CELL_ACC ON SIM
(CELL_NUMBER, ACCOUNT, SIM_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX UK_SIM_SIMNUMBER ON SIM
(SIM_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE SEQUENCE S_NEW_SIM_ID;

CREATE OR REPLACE FUNCTION NEW_SIM_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_SIM_ID.NEXTVAL
    INTO vRES
    FROM DUAL;
  RETURN vRES;
END;

CREATE OR REPLACE TRIGGER TI_SIM
  BEFORE INSERT ON SIM FOR EACH ROW
--#Version=1
BEGIN
  IF NVL(:NEW.SIM_ID, 0) = 0 then
    :NEW.SIM_ID := NEW_SIM_ID;
  END IF;  
  IF NVL(:NEW.SERVICEGID_STATUS, -1) = -1 then
    :NEW.SERVICEGID_STATUS:=1;
  END IF;  
END;

CREATE OR REPLACE TRIGGER tibr_sim
  before insert ON SIM   for each row
declare
begin
  select s_sim_id.nextval into :new.sim_id from dual;
end tibr_sim;
/


ALTER TABLE SIM ADD (
  CONSTRAINT PK_SIM
 PRIMARY KEY
 (SIM_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ),
  CONSTRAINT UK_SIM_NUM_CELL_ACC
 UNIQUE (CELL_NUMBER, ACCOUNT, SIM_NUMBER)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ),
  CONSTRAINT UK_SIM_SIMNUMBER
 UNIQUE (SIM_NUMBER)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE SIM ADD (
  CONSTRAINT FK_SIM_REF_AGENT 
 FOREIGN KEY (AGENT_ID) 
 REFERENCES AGENT (AGENT_ID),
  CONSTRAINT FK_SIM_REF_OPERATORS 
 FOREIGN KEY (OPERATOR_ID) 
 REFERENCES OPERATORS (OPERATOR_ID),
  CONSTRAINT FK_SIM_REF_SUBAGENT 
 FOREIGN KEY (SUBAGENT_ID) 
 REFERENCES SUBAGENT (SUBAGENT_ID),
  CONSTRAINT FK_SIM_REF_TARIFFS 
 FOREIGN KEY (TARIFF_ID) 
 REFERENCES TARIFFS (TARIFF_ID));
 
 ALTER TABLE SIM ADD (
  CONSTRAINT FK_SIM_STATUS_ID 
 FOREIGN KEY (STATUS_ID) 
 REFERENCES SIM_STATUSES(SIM_STATUS_ID));
 
ALTER TABLE SIM ADD PHONE_IS_ACTIVE INTEGER; 

COMMENT ON COLUMN SIM.PHONE_IS_ACTIVE IS '0 - Блокирован, 1 - Активен';

GRANT DELETE, INSERT, SELECT, UPDATE ON SIM TO LONTANA_ROLE;