CREATE TABLE SIM_STATUSES
(
  SIM_STATUS_ID      NUMBER,
  SIM_STATUS_NAME    VARCHAR2(100 BYTE),
  USER_CREATED       VARCHAR2(30 BYTE),
  DATE_CREATED       DATE,
  USER_LAST_UPDATED  VARCHAR2(30 BYTE),
  DATE_LAST_UPDATED  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SIM_STATUSES IS 'Статусы sim-карт';

COMMENT ON COLUMN SIM_STATUSES.SIM_STATUS_ID IS 'Первичный ключ';

COMMENT ON COLUMN SIM_STATUSES.SIM_STATUS_NAME IS 'Наименование статуса';

COMMENT ON COLUMN SIM_STATUSES.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN SIM_STATUSES.DATE_CREATED IS 'Дата/время создания записи';

COMMENT ON COLUMN SIM_STATUSES.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';

COMMENT ON COLUMN SIM_STATUSES.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';


CREATE UNIQUE INDEX PK_SIM_STATUSES ON SIM_STATUSES
(SIM_STATUS_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE SEQUENCE S_NEW_SIM_STATUS_ID
  START WITH 101
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  

CREATE OR REPLACE FUNCTION NEW_SIM_STATUS_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_SIM_STATUS_ID.NEXTVAL
    INTO vRES
    FROM DUAL;
  RETURN vRES;
END;

CREATE OR REPLACE TRIGGER TIU_SIM_STATUSES
  BEFORE INSERT OR UPDATE ON SIM_STATUSES FOR EACH ROW
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.SIM_STATUS_ID, 0) = 0 THEN
      :NEW.SIM_STATUS_ID := NEW_SIM_STATUS_ID;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/


ALTER TABLE SIM_STATUSES ADD (
  CONSTRAINT PK_SIM_STATUSES
 PRIMARY KEY
 (SIM_STATUS_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON SIM_STATUSES TO LONTANA_ROLE;
