CREATE TABLE SIM_CURRENT_PHONE_OPTIONS(
  CURRENT_PHONE_OPTION_ID INTEGER PRIMARY KEY,
  PHONE_NUMBER VARCHAR2(10 CHAR) NOT NULL,
  OPTION_CODE NUMBER NOT NULL,
  DATE_OPTION_CHECK DATE
);

CREATE SEQUENCE S_NEW_CURRENT_PHONE_OPTION_ID;

CREATE OR REPLACE FUNCTION NEW_CURRENT_PHONE_OPTION_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_CURRENT_PHONE_OPTION_ID.NEXTVAL
    INTO vRES
    FROM DUAL;
  RETURN vRES;
END;

CREATE OR REPLACE TRIGGER TIU_SIM_CURRENT_PHONE_OPTIONS
  BEFORE INSERT OR UPDATE ON SIM_CURRENT_PHONE_OPTIONS FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.CURRENT_PHONE_OPTION_ID, 0) = 0 then
      :NEW.CURRENT_PHONE_OPTION_ID := NEW_CURRENT_PHONE_OPTION_ID;
    END IF;
    :NEW.DATE_OPTION_CHECK := SYSDATE;   
  END IF;
END;

CREATE INDEX I_SIM_CUR_PH_OPT_PH_NUMBER ON SIM_CURRENT_PHONE_OPTIONS
(PHONE_NUMBER)
LOGGING
NOPARALLEL;

CREATE INDEX I_SIM_CUR_PH_OPT_OPT_CODE ON SIM_CURRENT_PHONE_OPTIONS
(OPTION_CODE)
LOGGING
NOPARALLEL;

GRANT DELETE, INSERT, SELECT, UPDATE ON LONTANA.SIM_CURRENT_PHONE_OPTIONS TO DB_LOADER;

GRANT DELETE, INSERT, SELECT, UPDATE ON LONTANA.SIM_CURRENT_PHONE_OPTIONS TO LONTANA_ROLE;