CREATE TABLE SIM_PHONE_BILL_DETAILS(
  SIM_PHONE_BILL_DETAIL_ID INTEGER PRIMARY KEY,
  YEAR_MONTH INTEGER NOT NULL,
  PHONE_NUMBER VARCHAR2(10 CHAR) NOT NULL,
  FULL_SUM NUMBER(13,2),
  NO_ROUMING_SUM NUMBER(13,2),
  ROUMING_SUM NUMBER(13,2),
  FULL_SUM_CALL NUMBER(13,2),
  NO_ROUMING_SUM_CALL NUMBER(13,2),
  ROUMING_SUM_CALL NUMBER(13,2)
);

COMMENT ON COLUMN SIM_PHONE_BILL_DETAILS.SIM_PHONE_BILL_DETAIL_ID IS 'Первичный ключ'; 

COMMENT ON COLUMN SIM_PHONE_BILL_DETAILS.PHONE_NUMBER IS 'Телефон'; 

COMMENT ON COLUMN SIM_PHONE_BILL_DETAILS.FULL_SUM IS 'Сумма начислений'; 

COMMENT ON COLUMN SIM_PHONE_BILL_DETAILS.NO_ROUMING_SUM IS 'Сумма начислений без роуминга'; 

COMMENT ON COLUMN SIM_PHONE_BILL_DETAILS.ROUMING_SUM IS 'Сумма начислений роуминга'; 

COMMENT ON COLUMN SIM_PHONE_BILL_DETAILS.FULL_SUM_CALL IS 'Сумма начислений за вызовы'; 

COMMENT ON COLUMN SIM_PHONE_BILL_DETAILS.NO_ROUMING_SUM_CALL IS 'Сумма начислений за вызовы без роуминга'; 

COMMENT ON COLUMN SIM_PHONE_BILL_DETAILS.ROUMING_SUM_CALL IS 'Сумма начислений за вызовы роуминга'; 

CREATE UNIQUE INDEX I_SIM_BILL_DET_MONTH_PHONE ON SIM_PHONE_BILL_DETAILS
(YEAR_MONTH, PHONE_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE SEQUENCE S_NEW_SIM_PHONE_BILL_DETAIL_ID;

CREATE OR REPLACE FUNCTION NEW_SIM_PHONE_BILL_DETAIL_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_SIM_PHONE_BILL_DETAIL_ID.NEXTVAL
    INTO vRES
    FROM DUAL;
  RETURN vRES;
END;

CREATE OR REPLACE TRIGGER TIU_SIM_PHONE_BILL_DETAILS
  BEFORE INSERT ON SIM_PHONE_BILL_DETAILS FOR EACH ROW
--#Version=1
BEGIN
  IF NVL(:NEW.SIM_PHONE_BILL_DETAIL_ID, 0) = 0 then
    :NEW.SIM_PHONE_BILL_DETAIL_ID := NEW_SIM_PHONE_BILL_DETAIL_ID;
  END IF;   
  :NEW.DATE_CHECK:=SYSDATE; 
END;

ALTER TABLE SIM_PHONE_BILL_DETAILS ADD DATE_CHECK DATE;

GRANT SELECT, UPDATE, INSERT, DELETE ON SIM_PHONE_BILL_DETAILS TO LONTANA_ROLE;

GRANT SELECT, UPDATE, INSERT, DELETE ON SIM_PHONE_BILL_DETAILS TO DB_LOADER;
