CREATE TABLE SMS_FOR_CONTRACT_PHONE_DRAVE
(
  PHONE_NUMBER   VARCHAR2(10 CHAR),
  TARIFF_ID      NUMBER(38),
  SMS_TYPE       NUMBER(38),
  DATE_CREATED   DATE,
  IS_POSTED      NUMBER(38) DEFAULT 0,
  VALUE_TRAFFIC  NUMBER(38)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SMS_FOR_CONTRACT_PHONE_DRAVE IS 'Номера с тарифом "Драйв", по которым следует отправлять смс на их контактные номера';

COMMENT ON COLUMN SMS_FOR_CONTRACT_PHONE_DRAVE.PHONE_NUMBER IS 'Номер';

COMMENT ON COLUMN SMS_FOR_CONTRACT_PHONE_DRAVE.TARIFF_ID IS 'ID тарифа';

COMMENT ON COLUMN SMS_FOR_CONTRACT_PHONE_DRAVE.SMS_TYPE IS 'Тип смс: 1 - при израсходовании трафика более 80%, 2 - при израсходовании трафика в 0';

COMMENT ON COLUMN SMS_FOR_CONTRACT_PHONE_DRAVE.DATE_CREATED IS 'Дата создания записи';

COMMENT ON COLUMN SMS_FOR_CONTRACT_PHONE_DRAVE.IS_POSTED IS 'Запись уже была отпраленна на сторону клиента';

COMMENT ON COLUMN SMS_FOR_CONTRACT_PHONE_DRAVE.VALUE_TRAFFIC IS 'Количество оставшегося трафика в ГБ, округленный до целого;

GRANT SELECT, UPDATE ON SMS_FOR_CONTRACT_PHONE_DRAVE TO CRM_USER;