CREATE TABLE SOAP_API_SYS_LOG
(
  TYPE_REQ      NUMBER,
  PHONE_NUMBER  VARCHAR2(10 BYTE),
  ACCOUNT_ID    NUMBER,
  BAN           NUMBER,
  RESPONSE      VARCHAR2(2000 BYTE),
  IS_OK         NUMBER,
  DATE_INSERT   DATE
);

COMMENT ON TABLE SOAP_API_SYS_LOG IS 'Протокол всех обращений к апи';

COMMENT ON COLUMN SOAP_API_SYS_LOG.TYPE_REQ IS 'тип запроса';

COMMENT ON COLUMN SOAP_API_SYS_LOG.PHONE_NUMBER IS 'CTN';

COMMENT ON COLUMN SOAP_API_SYS_LOG.BAN IS 'BAN\SUBBAN';

COMMENT ON COLUMN SOAP_API_SYS_LOG.RESPONSE IS 'ответ пакета';

COMMENT ON COLUMN SOAP_API_SYS_LOG.IS_OK IS 'ответ ОК?';

COMMENT ON COLUMN SOAP_API_SYS_LOG.DATE_INSERT IS 'ДАТА ДОБАВЛЕНИЯ';

CREATE INDEX I_SOAP_API_SYS_LOG_PHONE_NUM ON SOAP_API_SYS_LOG(PHONE_NUMBER) COMPRESS;

CREATE INDEX I_SOAP_API_SYS_LOG_DATE_INS ON SOAP_API_SYS_LOG (DATE_INSERT);

begin
  execute immediate 'GRANT ALL SOAP_API_SYS_LOG TO &MAIN_SCHEMA' || '_ROLE';
  execute immediate 'GRANT ALL SOAP_API_SYS_LOG TO &MAIN_SCHEMA' || '_ROLE_RO';
END;
/

ALTER TABLE SOAP_API_SYS_LOG MOVE tablespace TS_SOAP_API_SYS_LOG;

Alter index I_SOAP_API_SYS_LOG_PHONE_NUM rebuild
TABLESPACE TS_SOAP_API_SYS_LOG;

Alter index I_SOAP_API_SYS_LOG_DATE_INS rebuild
TABLESPACE TS_SOAP_API_SYS_LOG;

