CREATE TABLE TARIFER_BILL_FOR_CLIENTS(
  YEAR_MONTH INTEGER NOT NULL,
  PHONE_NUMBER VARCHAR2(10 CHAR) NOT NULL,
  BILL_SUMM NUMBER(15, 4) NOT NULL,
  ABON_TP NUMBER(15, 4) NOT NULL,
  ABON_ADD NUMBER(15, 4) NOT NULL,
  DISCOUNT NUMBER(15, 4) NOT NULL,
  SINGLE_PAYMENTS NUMBER(15, 4) NOT NULL,
  SINGLE_CHANGE_TARIFF NUMBER(15, 4) NOT NULL,
  SINGLE_CORRECTION NUMBER(15, 4) NOT NULL,
  CALLS NUMBER(15, 4) NOT NULL,
  CALLS_COUNTRY NUMBER(15, 4) NOT NULL,
  CALLS_SITY NUMBER(15, 4) NOT NULL,
  CALLS_LOCAL NUMBER(15, 4) NOT NULL,
  CALLS_SMS_MMS NUMBER(15, 4) NOT NULL,
  CALLS_GPRS NUMBER(15, 4) NOT NULL,
  CALLS_RUS_RPP NUMBER(15, 4) NOT NULL,
  CALLS_ALL NUMBER(15, 4) NOT NULL,
  ROUMING_NATIONAL NUMBER(15, 4) NOT NULL,
  ROUMING_INTERNATIONAL NUMBER(15, 4) NOT NULL,
  DATE_CREATED DATE,
  USER_CREATED VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED DATE,
  USER_LAST_UPDATED VARCHAR2(30 CHAR)
  );

COMMENT ON TABLE TARIFER_BILL_FOR_CLIENTS IS 'Счета Тарифера';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.YEAR_MONTH IS 'Месяц';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.PHONE_NUMBER IS 'Номер';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.BILL_SUMM IS 'Итого';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.ABON_TP IS 'Абон пл за тариф';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.ABON_ADD IS 'Абон пл за услуги';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.DISCOUNT IS 'Скидки';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.SINGLE_PAYMENTS IS 'Разовые начисления';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.SINGLE_CHANGE_TARIFF IS 'Смена Тарифного плана';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.SINGLE_CORRECTION IS 'Корректировки';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.CALLS IS 'Все за звонки';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.CALLS_COUNTRY IS 'М/н звонки';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.CALLS_SITY IS 'М/г звонки';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.CALLS_LOCAL IS 'Местные звонки';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.CALLS_SMS_MMS IS 'СМС и ММС';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.CALLS_GPRS IS 'Интернет';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.CALLS_RUS_RPP IS 'Прочие начисления оператора';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.CALLS_ALL IS 'Всего за звонки (без роуминга)';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.ROUMING_NATIONAL IS 'Роуминг национальный';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.ROUMING_INTERNATIONAL IS 'Роуминг международный';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.DATE_CREATED IS 'Когда создали';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.USER_CREATED IS 'Кто создал';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.DATE_LAST_UPDATED IS 'Дата посл обновления';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENTS.USER_LAST_UPDATED IS 'Кто посл обновил';
  
CREATE UNIQUE INDEX I_TARIFER_BILL_PHONE_YM ON TARIFER_BILL_FOR_CLIENTS(PHONE_NUMBER, YEAR_MONTH);
  
CREATE UNIQUE INDEX I_TARIFER_BILL_PHONE_YM_BILL_S ON TARIFER_BILL_FOR_CLIENTS(PHONE_NUMBER, YEAR_MONTH, BILL_SUMM);

CREATE OR REPLACE TRIGGER TIU_TARIFER_BILL_FOR_CLIENTS
  BEFORE INSERT OR UPDATE ON TARIFER_BILL_FOR_CLIENTS FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;

  
GRANT SELECT ON TARIFER_BILL_FOR_CLIENTS TO CORP_MOBILE_ROLE;

GRANT SELECT ON TARIFER_BILL_FOR_CLIENTS TO CORP_MOBILE_ROLE_RO;
  