--ALTER TABLE TARIFFS_ATTRS  DROP PRIMARY KEY CASCADE;

--DROP TABLE TARIFFS_ATTRS CASCADE CONSTRAINTS;

DROP SEQUENCE S_TARIFFS_ATTRS;

CREATE SEQUENCE S_TARIFFS_ATTRS
  START WITH 5
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;
/
  
  
CREATE TABLE TARIFFS_ATTRS
(
  TARIFFS_ATTRIBUTES_ID  INTEGER                NOT NULL,
  ATTRIBUTES_NAME        VARCHAR2(150 CHAR)     NOT NULL,
  MONEY_TYPE             NUMBER(15,2),
  KOEF_TYPE              NUMBER(12,8),
  VARCHAR_TYPE_50        VARCHAR2(50 CHAR),
  INT_TYPE               INTEGER,
  LIFETIME_FROM          DATE                   DEFAULT sysdate               NOT NULL,
  LIFETIME_TO            DATE                   DEFAULT '01-JAN-3000'         NOT NULL,
  USED_TYPE              INTEGER                DEFAULT 1                     NOT NULL,
  date_type              DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


COMMENT ON TABLE  TARIFFS_ATTRS IS 'Расширение таблицы TARIFFS, что б не создавать новые поля';

COMMENT ON COLUMN TARIFFS_ATTRS.TARIFFS_ATTRIBUTES_ID IS 'Первичный ключ';

COMMENT ON COLUMN TARIFFS_ATTRS.ATTRIBUTES_NAME IS 'Имя нового атрибута TARIFFS';

COMMENT ON COLUMN TARIFFS_ATTRS.MONEY_TYPE IS 'Значение атрибута';

COMMENT ON COLUMN TARIFFS_ATTRS.KOEF_TYPE IS 'Значение атрибута';

COMMENT ON COLUMN TARIFFS_ATTRS.VARCHAR_TYPE_50 IS 'Значение атрибута';

COMMENT ON COLUMN TARIFFS_ATTRS.INT_TYPE IS 'Значение атрибута';

COMMENT ON COLUMN TARIFFS_ATTRS.LIFETIME_FROM IS 'Начало действия атрибута';

COMMENT ON COLUMN TARIFFS_ATTRS.LIFETIME_TO IS 'Окончание действия атрибута';

COMMENT ON COLUMN TARIFFS_ATTRS.USED_TYPE IS 'Какой тип будет использован, 1 - MONEY_TYPE, 2 - KOEF_TYPE, 3 - VARCHAR_TYPE_50, 4 - INT_TYPE';

comment on column TARIFFS_ATTRS.date_type is 'Значение атрибута';

CREATE UNIQUE INDEX TARIFFS_ATTRIBUTES_PK ON TARIFFS_ATTRS
(TARIFFS_ATTRIBUTES_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER TI_TARIFFS_ATTRS
BEFORE INSERT
ON TARIFFS_ATTRS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
  vRES NUMBER;
BEGIN
   
   IF INSERTING THEN
     vRES := 0;
     SELECT S_TARIFFS_ATTRS.NEXTVAL INTO vRES FROM DUAL;
   
     :NEW.TARIFFS_ATTRIBUTES_ID := vRES;
   end if;     
   
   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
     null;
   END ;
/


ALTER TABLE TARIFFS_ATTRS ADD (
  CONSTRAINT TARIFFS_ATTRIBUTES_PK
  PRIMARY KEY
  (TARIFFS_ATTRIBUTES_ID)
  USING INDEX TARIFFS_ATTRIBUTES_PK
  ENABLE VALIDATE);

ALTER TABLE TARIFFS_ATTRS ADD NOTE VARCHAR2(150 Char);

COMMENT ON COLUMN TARIFFS_ATTRS.NOTE IS 'Комментарий';  

--
INSERT INTO TARIFFS_ATTRS(ATTRIBUTES_NAME,INT_TYPE,LIFETIME_FROM,LIFETIME_TO,USED_TYPE, NOTE) 
  VALUES('AUTO_CONNECT_MGN500MIN', 1, sysdate, to_date('01.01.3000', 'DD.MM.YYYY'), 4, 'Автоподключение междугороднего пакета');

INSERT INTO TARIFFS_ATTRS(ATTRIBUTES_NAME,MONEY_TYPE,LIFETIME_FROM,LIFETIME_TO,USED_TYPE, NOTE) 
  VALUES('SUM_SPISANIE_4_PHONE_BLOCK_DOP_STATUS', 3, sysdate, to_date('01.01.3000', 'DD.MM.YYYY'), 1, 'Сумма списания за день для номера в блоке с доп. статусом "Добровольная блокировка"');

INSERT INTO TARIFFS_ATTRS(ATTRIBUTES_NAME,INT_TYPE,LIFETIME_FROM,LIFETIME_TO,USED_TYPE, NOTE) 
  VALUES('SCHEME_AUTO_CONNECT_PCKG', 1, sysdate, to_date('01.01.3000', 'DD.MM.YYYY'), 4, 'Схема автоподключеняи пакетов для Безлимит 990 и 1290, 980 и 1280 и их клонов и Безлимит 850');
  
INSERT INTO TARIFFS_ATTRS(ATTRIBUTES_NAME,INT_TYPE,LIFETIME_FROM,LIFETIME_TO,USED_TYPE, NOTE) 
  VALUES('SCHEME_AUTO_CONNECT_PCKG', 2, sysdate, to_date('01.01.3000', 'DD.MM.YYYY'), 4, 'Схема автоподключеняи пакетов для Безлимит 1590');
  
INSERT INTO TARIFFS_ATTRS(ATTRIBUTES_NAME,INT_TYPE,LIFETIME_FROM,LIFETIME_TO,USED_TYPE, NOTE) 
  VALUES('SCHEME_AUTO_CONNECT_PCKG', 3, sysdate, to_date('01.01.3000', 'DD.MM.YYYY'), 4, 'Схема автоподключеняи пакетов для Безлимит 1580 и его клона');

INSERT INTO TARIFFS_ATTRS(ATTRIBUTES_NAME,INT_TYPE,LIFETIME_FROM,LIFETIME_TO,USED_TYPE, NOTE) 
  VALUES('ATR_OPTION', 1357, sysdate, to_date('01.01.3000', 'DD.MM.YYYY'), 4, 'Используется для соответствия тарифа и опции. Опция FSG_TT1');

INSERT INTO TARIFFS_ATTRS(ATTRIBUTES_NAME,INT_TYPE,LIFETIME_FROM,LIFETIME_TO,USED_TYPE, NOTE) 
  VALUES('ATR_OPTION', 1362, sysdate, to_date('01.01.3000', 'DD.MM.YYYY'), 4, 'Используется для соответствия тарифа и опции. Опция FSG_TT2');
  
INSERT INTO TARIFFS_ATTRS(ATTRIBUTES_NAME,INT_TYPE,LIFETIME_FROM,LIFETIME_TO,USED_TYPE, NOTE) 
  VALUES('ATR_OPTION', 1366, sysdate, to_date('01.01.3000', 'DD.MM.YYYY'), 4, 'Используется для соответствия тарифа и опции. Опция FSG_TT3');
  
INSERT INTO TARIFFS_ATTRS(ATTRIBUTES_NAME,INT_TYPE,LIFETIME_FROM,LIFETIME_TO,USED_TYPE, NOTE) 
  VALUES('ATR_OPTION', 68, sysdate, to_date('01.01.3000', 'DD.MM.YYYY'), 4, 'Используется для соответствия тарифа и опции. Опция GPRS_U');

INSERT INTO TARIFFS_ATTRS(ATTRIBUTES_NAME,INT_TYPE,LIFETIME_FROM,LIFETIME_TO,USED_TYPE, NOTE) 
  VALUES('ATR_OPTION', 1419, sysdate, to_date('01.01.3000', 'DD.MM.YYYY'), 4, 'Используется для соответствия тарифа и опции. Опция GPRS_20GB');
  
INSERT INTO TARIFFS_ATTRS(ATTRIBUTES_NAME,INT_TYPE,LIFETIME_FROM,LIFETIME_TO,USED_TYPE, NOTE) 
  VALUES('ATR_OPTION', 1437, sysdate, to_date('01.01.3000', 'DD.MM.YYYY'), 4, 'Используется для соответствия тарифа и опции. Опция GPRS_30GB');
  
INSERT INTO TARIFFS_ATTRS(ATTRIBUTES_NAME,INT_TYPE,LIFETIME_FROM,LIFETIME_TO,USED_TYPE, NOTE) 
  VALUES('ATR_OPTION', 1857, sysdate, to_date('01.01.3000', 'DD.MM.YYYY'), 4, 'Используется для соответствия тарифа и опции. Опция GPRS_20G');
  
INSERT INTO TARIFFS_ATTRS(ATTRIBUTES_NAME,INT_TYPE,LIFETIME_FROM,LIFETIME_TO,USED_TYPE, NOTE) 
  VALUES('ATR_OPTION', 1866, sysdate, to_date('01.01.3000', 'DD.MM.YYYY'), 4, 'Используется для соответствия тарифа и опции. Опция GPRS_30G');

commit;  

