CREATE TABLE VIRTUAL_BALANCE(
  PHONE_NUMBER  VARCHAR2(11 BYTE),
  KR_AV         NUMBER,
  PCHARGES      NUMBER,
  PABON         NUMBER,
  PUSL          NUMBER,
  PBILLS        NUMBER,
  PBILL_AB      NUMBER,
  PBILL_USL     NUMBER,
  PBALANCE      NUMBER,
  PABON_BE      NUMBER,
  PBILL_AB_BE   NUMBER,
  PABON_BL_BE   NUMBER,
  SESSION_ID    NUMBER,
  YEAR_MONTH    NUMBER,
  BALANCE_DATE  DATE,
  DATE_REPORT   DATE
  );

COMMENT ON COLUMN VIRTUAL_BALANCE.PHONE_NUMBER IS 'Номер телефона';

COMMENT ON COLUMN VIRTUAL_BALANCE.KR_AV IS 'Кредит/аванс';

COMMENT ON COLUMN VIRTUAL_BALANCE.PCHARGES IS 'Начисления за период';

COMMENT ON COLUMN VIRTUAL_BALANCE.PABON IS 'Абон.плата за период';

COMMENT ON COLUMN VIRTUAL_BALANCE.PUSL IS 'Услуги за период';

COMMENT ON COLUMN VIRTUAL_BALANCE.PBILLS IS 'Сумма начисления за период из счета';

COMMENT ON COLUMN VIRTUAL_BALANCE.PBILL_AB IS 'Абон.плата за период из счета';

COMMENT ON COLUMN VIRTUAL_BALANCE.PBILL_USL IS 'Услуги за период из счета';

COMMENT ON COLUMN VIRTUAL_BALANCE.PBALANCE IS 'Баланс';

COMMENT ON COLUMN VIRTUAL_BALANCE.PABON_BE IS 'Абон.плата по версии Билайна';

COMMENT ON COLUMN VIRTUAL_BALANCE.PBILL_AB_BE IS 'Абон.плата из счета';

COMMENT ON COLUMN VIRTUAL_BALANCE.PABON_BL_BE IS 'Абон.пл.Билайна за заблок.период';

COMMENT ON COLUMN VIRTUAL_BALANCE.SESSION_ID IS 'Идентификатор сессии';

COMMENT ON COLUMN VIRTUAL_BALANCE.YEAR_MONTH IS 'Период';

COMMENT ON COLUMN VIRTUAL_BALANCE.BALANCE_DATE IS 'Дата баланса';

COMMENT ON COLUMN VIRTUAL_BALANCE.DATE_REPORT IS 'Дата отчета';

GRANT DELETE, INSERT, SELECT, UPDATE ON VIRTUAL_BALANCE TO CORP_MOBILE_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON VIRTUAL_BALANCE TO CORP_MOBILE_ROLE_RO;

ALTER TABLE VIRTUAL_BALANCE ADD SINGLE_CHANGE_TP NUMBER;

COMMENT ON COLUMN VIRTUAL_BALANCE.SINGLE_CHANGE_TP IS 'Смена ТарПл';

ALTER TABLE VIRTUAL_BALANCE ADD SINGLE_OTHER NUMBER;

COMMENT ON COLUMN VIRTUAL_BALANCE.SINGLE_OTHER IS 'Прочие раз. выпл.';

ALTER TABLE VIRTUAL_BALANCE ADD IS_ACTIVE NUMBER;

COMMENT ON COLUMN VIRTUAL_BALANCE.IS_ACTIVE IS 'Акт./Бл.';

ALTER TABLE VIRTUAL_BALANCE ADD IS_CONTRACT VARCHAR2(500 CHAR);

COMMENT ON COLUMN VIRTUAL_BALANCE.IS_CONTRACT IS 'Наличие контракта';

ALTER TABLE VIRTUAL_BALANCE ADD OPTION_CODES NUMBER;

COMMENT ON COLUMN VIRTUAL_BALANCE.OPTION_CODES IS 'Список услуг';

ALTER TABLE VIRTUAL_BALANCE ADD TARIFF_NAME VARCHAR2(500 CHAR);

COMMENT ON COLUMN VIRTUAL_BALANCE.TARIFF_NAME IS 'Список ТП';

ALTER TABLE VIRTUAL_BALANCE ADD PAYMENT_TILL_BILL NUMBER;

COMMENT ON COLUMN VIRTUAL_BALANCE.PAYMENT_TILL_BILL IS 'Пдатежи до счета';