CREATE TABLE ACC_PAYMENTS_FOR_EQUIPMENT
(
  ID_ACC_PAYMENT_EQUIPMENT  NUMBER(38)          NOT NULL,
  ACC_PAYMENT_NUMBER        NUMBER              NOT NULL,
  ACCOUNT_ID                NUMBER(38)          NOT NULL,
  DATE_ISSUING              DATE,
  ACC_PAYMENT_SUM           NUMBER(15,2),
  ACC_PAYMENT_CHECK         NUMBER(38),
  USER_CREATED              VARCHAR2(30 CHAR),
  DATE_CREATED              DATE,
  USER_LAST_UPDATED         VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED         DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ACC_PAYMENTS_FOR_EQUIPMENT IS 'Таблица счетов оплаты за оборудование';

COMMENT ON COLUMN ACC_PAYMENTS_FOR_EQUIPMENT.ACC_PAYMENT_SUM IS 'Сумма по счету оплаты';

COMMENT ON COLUMN ACC_PAYMENTS_FOR_EQUIPMENT.ACC_PAYMENT_CHECK IS 'Проверка санкционирования счета(проверен/непроверен)';

COMMENT ON COLUMN ACC_PAYMENTS_FOR_EQUIPMENT.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN ACC_PAYMENTS_FOR_EQUIPMENT.DATE_CREATED IS 'Дата создания записи';

COMMENT ON COLUMN ACC_PAYMENTS_FOR_EQUIPMENT.USER_LAST_UPDATED IS 'Пользователь, изменивший запись';

COMMENT ON COLUMN ACC_PAYMENTS_FOR_EQUIPMENT.DATE_LAST_UPDATED IS 'Дата последнего изменения записи';

COMMENT ON COLUMN ACC_PAYMENTS_FOR_EQUIPMENT.DATE_ISSUING IS 'Дата выставления счета оплаты';

COMMENT ON COLUMN ACC_PAYMENTS_FOR_EQUIPMENT.ID_ACC_PAYMENT_EQUIPMENT IS 'Код счета оплаты за оборудование';

COMMENT ON COLUMN ACC_PAYMENTS_FOR_EQUIPMENT.ACC_PAYMENT_NUMBER IS 'Номер счета оплаты';

COMMENT ON COLUMN ACC_PAYMENTS_FOR_EQUIPMENT.ACCOUNT_ID IS 'Номер лицевого счета (BAN, номер договора)';


CREATE UNIQUE INDEX ACC_PAYMENTS_FOR_EQUIPMENT_PK ON ACC_PAYMENTS_FOR_EQUIPMENT
(ID_ACC_PAYMENT_EQUIPMENT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX I_ACC_PAYMENTS_EQUIPMENT_AID ON ACC_PAYMENTS_FOR_EQUIPMENT
(ACCOUNT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          9M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE TRIGGER TIU_ACC_PAYMENTS_4_EQUIPMENT
BEFORE INSERT OR UPDATE
ON ACC_PAYMENTS_FOR_EQUIPMENT 
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;  
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;

ALTER TABLE ACC_PAYMENTS_FOR_EQUIPMENT ADD (
  CONSTRAINT ACC_PAYMENTS_FOR_EQUIPMENT_PK
  PRIMARY KEY
  (ID_ACC_PAYMENT_EQUIPMENT)
  USING INDEX ACC_PAYMENTS_FOR_EQUIPMENT_PK);

ALTER TABLE ACC_PAYMENTS_FOR_EQUIPMENT ADD (
  CONSTRAINT ACC_PAYMENTS_FOR_EQUIPMENT_FK1 
  FOREIGN KEY (ACCOUNT_ID) 
  REFERENCES ACCOUNTS (ACCOUNT_ID));

GRANT DELETE, INSERT, SELECT, UPDATE ON ACC_PAYMENTS_FOR_EQUIPMENT TO CORP_MOBILE_ROLE;

GRANT SELECT ON ACC_PAYMENTS_FOR_EQUIPMENT TO CORP_MOBILE_ROLE_RO;
