CREATE TABLE ACCOUNT_LOADED_BILLS(
  ACCOUNT_ID INTEGER NOT NULL,
  YEAR_MONTH INTEGER NOT NULL,
  LOAD_BILL_IN_BALANCE INTEGER NOT NULL,
  DATE_BEGIN DATE NOT NULL,
  DATE_END DATE NOT NULL,
  DATE_CREDIT_END date not null,
  USER_LAST_UPDATE VARCHAR2(30 CHAR),
  DATE_LAST_UPDATE DATE
  );
  
CREATE OR REPLACE TRIGGER TIU_ACCOUNT_LOADED_BILLS
  BEFORE INSERT OR UPDATE ON ACCOUNT_LOADED_BILLS FOR EACH ROW
--#Version=1
BEGIN
  IF (:NEW.LOAD_BILL_IN_BALANCE IS NULL) OR (:NEW.LOAD_BILL_IN_BALANCE <> 1) then
    :NEW.LOAD_BILL_IN_BALANCE := 0;
  END IF;
  IF :NEW.DATE_BEGIN IS NULL then
    :NEW.DATE_BEGIN := TO_DATE(:NEW.YEAR_MONTH||'01', 'YYYYMMDD');
  END IF;
  IF :NEW.DATE_END IS NULL then
    :NEW.DATE_END := LAST_DAY(TO_DATE(:NEW.YEAR_MONTH||'01', 'YYYYMMDD'));
  END IF;
  IF :NEW.DATE_CREDIT_END IS NULL then
    :NEW.DATE_CREDIT_END := CASE
                              WHEN MS_CONSTANTS.GET_CONSTANT_VALUE('CREDIT_SYSTEM_ENABLE') = '1' 
                                THEN ADD_MONTHS(TO_DATE(:NEW.YEAR_MONTH||'15', 'YYYYMMDD'), 1)
                              ELSE lAST_DAY(TO_DATE(:NEW.YEAR_MONTH||'01', 'YYYYMMDD'))
                            END;
  END IF;
  :NEW.USER_LAST_UPDATE := USER;
  :NEW.DATE_LAST_UPDATE := SYSDATE;
END;
  
ALTER TABLE ACCOUNT_LOADED_BILLS ADD (
  CONSTRAINT U_ACCOUNT_LOADED_BILLS_AC_Y_M
  UNIQUE (ACCOUNT_ID, YEAR_MONTH));  

CREATE INDEX I_ACCOUNT_LOADED_BILLS_ACC_Y_M
ON ACCOUNT_LOADED_BILLS (ACCOUNT_ID, YEAR_MONTH);

--GRANT SELECT, INSERT, DELETE, UPDATE ON ACCOUNT_LOADED_BILLS TO CORP_MOBILE_ROLE;
  
--GRANT SELECT, INSERT, DELETE, UPDATE ON ACCOUNT_LOADED_BILLS TO SIM_TRADE_ROLE;
  
--GRANT SELECT, INSERT, DELETE, UPDATE ON ACCOUNT_LOADED_BILLS TO LONTANA_ROLE;