CREATE TABLE ACCOUNT_LOGON_PAUSED (
  ACCOUNT_NAME VARCHAR2(50 CHAR) NOT NULL,
  START_DATE_TIME DATE NOT NULL,
  END_DATE_TIME DATE NOT NULL
  );
  
COMMENT ON TABLE ACCOUNT_LOGON_PAUSED IS 'Таблица паузы входа в личный кабинет (для защиты от блокирования учётной записи)';

COMMENT ON COLUMN ACCOUNT_LOGON_PAUSED.ACCOUNT_NAME IS 'Имя учётной записи';

COMMENT ON COLUMN ACCOUNT_LOGON_PAUSED.START_DATE_TIME IS 'Дата/время начала паузы';

COMMENT ON COLUMN ACCOUNT_LOGON_PAUSED.END_DATE_TIME IS 'Дата/время окончания паузы';
