CREATE TABLE AGENTS
(
  AGENT_ID           NUMBER,
  AGENT_NAME         VARCHAR2(100 BYTE),
  USER_CREATED       VARCHAR2(30 BYTE),
  DATE_CREATED       DATE,
  USER_LAST_UPDATED  VARCHAR2(30 BYTE),
  DATE_LAST_UPDATED  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE AGENTS IS 'Агенты';

COMMENT ON COLUMN AGENTS.AGENT_ID IS 'Первичный ключ';

COMMENT ON COLUMN AGENTS.AGENT_NAME IS 'Наименование агента';

COMMENT ON COLUMN AGENTS.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN AGENTS.DATE_CREATED IS 'Дата/время создания записи';

COMMENT ON COLUMN AGENTS.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';

COMMENT ON COLUMN AGENTS.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';


CREATE UNIQUE INDEX PK_AGENTS ON AGENTS
(AGENT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE SEQUENCE S_NEW_AGENT_ID
  START WITH 101
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE OR REPLACE FUNCTION NEW_AGENT_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_AGENT_ID.NEXTVAL
    INTO vRES
    FROM DUAL;
  RETURN vRES;
END;

CREATE OR REPLACE TRIGGER TIU_AGENTS
  BEFORE INSERT OR UPDATE ON AGENTS FOR EACH ROW
--
--#Version=1
--
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.AGENT_ID, 0) = 0 THEN
      :NEW.AGENT_ID := NEW_AGENT_ID;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/


ALTER TABLE AGENTS ADD (
  CONSTRAINT PK_AGENTS
 PRIMARY KEY
 (AGENT_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON AGENTS TO LONTANA_ROLE;
