DROP TABLE CORP_MOBILE.ALARM_PHONE_LOG_TYPES CASCADE CONSTRAINTS;

CREATE TABLE CORP_MOBILE.ALARM_PHONE_LOG_TYPES
(
  APL_ID  INTEGER                               NOT NULL,
  NAME    VARCHAR2(50 BYTE)                     NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
