CREATE GLOBAL TEMPORARY TABLE API_GET_CTN_INFO_LIST(
  ctn VARCHAR2(15 CHAR),
  statusDate VARCHAR2(25 CHAR),
  status VARCHAR2(15 CHAR),
  pricePlan VARCHAR2(15 CHAR),
  reasonStatus VARCHAR2(15 CHAR),
  lastActivity VARCHAR2(15 CHAR),
  activationDate VARCHAR2(25 CHAR),
  subscriberHLR VARCHAR2(15 CHAR)
  ) ON COMMIT PRESERVE ROWS;
  
COMMENT ON TABLE API_GET_CTN_INFO_LIST IS 'Временная таблица для загрузки API.getCTNInfoList'; 
COMMENT ON COLUMN API_GET_CTN_INFO_LIST.ctn IS 'Номер телефона';
COMMENT ON COLUMN API_GET_CTN_INFO_LIST.statusDate IS 'Дата посл смены статуса';
COMMENT ON COLUMN API_GET_CTN_INFO_LIST.status IS 'Статус, акт/блок';
COMMENT ON COLUMN API_GET_CTN_INFO_LIST.pricePlan IS 'Тарифный план';
COMMENT ON COLUMN API_GET_CTN_INFO_LIST.reasonStatus IS 'Код статуса';
COMMENT ON COLUMN API_GET_CTN_INFO_LIST.lastActivity IS 'Дата посл активности';
COMMENT ON COLUMN API_GET_CTN_INFO_LIST.activationDate IS 'Дата активации';
COMMENT ON COLUMN API_GET_CTN_INFO_LIST.subscriberHLR IS '';

--GRANT SELECT, INSERT, UPDATE, DELETE ON API_GET_CTN_INFO_LIST TO CORP_MOBILE_ROLE;

--GRANT SELECT, INSERT, UPDATE, DELETE ON API_GET_CTN_INFO_LIST TO LONTANA_ROLE;

--GRANT SELECT, INSERT, UPDATE, DELETE ON API_GET_CTN_INFO_LIST TO SIM_TRADE_ROLE;