CREATE TABLE BALANCE_UPD_TYPES(
  UPD_ID       NUMBER,
  UPD_NAME     VARCHAR2(50 BYTE),
  UPD_COMMENT  VARCHAR2(2000 BYTE)
  );

COMMENT ON TABLE BALANCE_UPD_TYPES IS 'Типы обновления балансов';

CREATE UNIQUE INDEX PK_UPDATE_TYPE_ID ON BALANCE_UPD_TYPES
(UPD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE BALANCE_UPD_TYPES ADD (
  CONSTRAINT PK_UPDATE_TYPE_ID
 PRIMARY KEY
 (UPD_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

--GRANT DELETE, INSERT, SELECT, UPDATE ON BALANCE_UPD_TYPES TO CORP_MOBILE_ROLE;

--GRANT SELECT ON BALANCE_UPD_TYPES TO CORP_MOBILE_ROLE_RO;

GRANT DELETE, INSERT, SELECT, UPDATE ON BALANCE_UPD_TYPES TO SIM_TRADE_ROLE;

--GRANT DELETE, INSERT, SELECT, UPDATE ON BALANCE_UPD_TYPES TO LONTANA_ROLE;
