-- DROP TABLE CHECKED_TYPES CASCADE CONSTRAINTS;

    -- 14.11.12 г. А. Пискунов Таблица Код- Статус "Хакера"

CREATE TABLE CHECKED_TYPES
(
  CHECKED_TYPE_ID    NUMBER,
  CHECKED_TYPE_NAME  VARCHAR2(200 BYTE)
)

COMMENT ON COLUMN CHECKED_TYPES.CHECKED_TYPE_ID IS 'Код статуса';

COMMENT ON COLUMN CHECKED_TYPES.CHECKED_TYPE_NAME IS 'Имя Статуса';


INSERT INTO CHECKED_TYPES (CHECKED_TYPE_ID, CHECKED_TYPE_NAME) VALUES (1, 'Не проверен');

INSERT INTO CHECKED_TYPES (CHECKED_TYPE_ID, CHECKED_TYPE_NAME) VALUES (2, 'Проверен: чист');

INSERT INTO CHECKED_TYPES (CHECKED_TYPE_ID, CHECKED_TYPE_NAME) VALUES (3, 'Проверен: мошенник');

INSERT INTO CHECKED_TYPES (CHECKED_TYPE_ID, CHECKED_TYPE_NAME) VALUES (4, 'Другое');


GRANT DELETE, INSERT, SELECT, UPDATE ON CHECKED_TYPES TO CORP_MOBILE_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON CHECKED_TYPES TO LONTANA;

GRANT DELETE, INSERT, SELECT, UPDATE ON CHECKED_TYPES TO SIM_TRADE;

GRANT SELECT ON CHECKED_TYPES TO CORP_MOBILE_ROLE_RO;