--DROP table DB_LOADER_PHONE_STAT;

CREATE TABLE DB_LOADER_PHONE_STAT (
  ACCOUNT_ID INTEGER,
  YEAR_MONTH INTEGER,
  PHONE_NUMBER VARCHAR2(10 CHAR),
  ESTIMATE_SUM NUMBER(15, 2),
  ZEROCOST_OUTCOME_MINUTES NUMBER`(15, 2),
  ZEROCOST_OUTCOME_COUNT NUMBER(15, 2),
  CALLS_COUNT INTEGER,
  CALLS_MINUTES NUMBER(10, 2),
  CALLS_COST NUMBER(15, 2),
  SMS_COUNT INTEGER,
  SMS_COST NUMBER(15, 2),
  MMS_COUNT INTEGER,
  MMS_COST NUMBER(15, 2),
  INTERNET_MB NUMBER(10, 3),
  INTERNET_COST NUMBER(15, 2),
  LAST_CHECK_DATE_TIME DATE,
  SMS_FREE_COUNT INTEGER,
  MMS_FREE_COUNT INTEGER,
  CALLS_FULL_MINUTES INTEGER
);

COMMENT ON TABLE DB_LOADER_PHONE_STAT IS 'Статистика оказанных услуг по телефонному номеру';
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.ACCOUNT_ID IS 'Код лицевого счёта';
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.YEAR_MONTH IS 'Год/месяц в формате 200911';
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.PHONE_NUMBER IS 'Номер телефона';
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.ESTIMATE_SUM IS 'Стоимость услуг (начислено)';
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.ZEROCOST_OUTCOME_MINUTES IS 'Количество бесплатных минут (исходящих)';
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.ZEROCOST_OUTCOME_COUNT IS 'Количество бесплатных звонков (исходящих)';
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.CALLS_COUNT IS 'Количество платных звонков';
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.CALLS_MINUTES IS 'Количество минут платных звонков';
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.CALLS_COST IS 'Стоимость платных звонков';
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.SMS_COUNT IS 'Количество платных SMS';
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.SMS_COST IS 'Стоимость платных SMS';
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.MMS_COUNT IS 'Количество платных MMS';
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.MMS_COST IS 'Стоимость платных MMS';
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.INTERNET_MB IS 'Количество интернета (Мб)';
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.INTERNET_COST IS 'Стоимость интернета (Мб)';
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.LAST_CHECK_DATE_TIME IS 'Дата и время последнего обновления';

CREATE UNIQUE INDEX I_DB_LOADER_PHONE_STAT_Y_M_P
  ON DB_LOADER_PHONE_STAT (PHONE_NUMBER, YEAR_MONTH)
  COMPRESS 1;
  
CREATE OR REPLACE TRIGGER TU_HACKERS_FIND
    BEFORE INSERT OR UPDATE
  ON DB_LOADER_PHONE_STAT    REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
BEGIN  
  IF INSERTING THEN
    IF :new.SMS_COUNT  >= Ms_PARAMs.get_num_var('CRIT_SMS_COUNT')  THEN
      INSERT INTO HACKERS(HACKERS_ID, PHONE_NUMBER, SERVICES_TYPE, DATE_CREATED, CHECKED_TYPE_ID, COUNT_SMS_CHANGE)    
        VALUES (S_NEW_HACKERS_ID.NEXTVAL, :new.PHONE_NUMBER, 2, SYSDATE, 1, :new.SMS_COUNT);    
    END IF;      
    INSERT INTO QUEUE_CURRENT_BALANCES(PHONE_NUMBER)
      VALUES(:NEW.PHONE_NUMBER);   
  ELSIF UPDATING  THEN  
    IF ((:new.SMS_COUNT - :old.SMS_COUNT) >= Ms_PARAMs.get_num_var('CRIT_SMS_COUNT'))  THEN
      INSERT INTO HACKERS(HACKERS_ID, PHONE_NUMBER, SERVICES_TYPE, DATE_CREATED, CHECKED_TYPE_ID, COUNT_SMS_CHANGE)    
        VALUES (S_NEW_HACKERS_ID.NEXTVAL, :new.PHONE_NUMBER, 2, SYSDATE, 1, :new.SMS_COUNT - :old.SMS_COUNT);    
    END IF;
    IF :NEW.ESTIMATE_SUM > :OLD.ESTIMATE_SUM THEN
      INSERT INTO QUEUE_CURRENT_BALANCES(PHONE_NUMBER)
        VALUES(:NEW.PHONE_NUMBER);  
    END IF;
  END IF;          
END;

--#if not ColumnExists("DB_LOADER_PHONE_STAT.SMS_FREE_COUNT") then
ALTER TABLE DB_LOADER_PHONE_STAT ADD SMS_FREE_COUNT INTEGER;
--#end if

--#if GetColumnComment("DB_LOADER_PHONE_STAT.SMS_FREE_COUNT")<>"Количество бесплатных SMS" then
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.SMS_FREE_COUNT IS 'Количество бесплатных SMS';
--#end if

--#if not ColumnExists("DB_LOADER_PHONE_STAT.MMS_FREE_COUNT") then
ALTER TABLE DB_LOADER_PHONE_STAT ADD MMS_FREE_COUNT INTEGER;
--#end if

--#if GetColumnComment("DB_LOADER_PHONE_STAT.MMS_FREE_COUNT")<>"Количество бесплатных MMS" then
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.MMS_FREE_COUNT IS 'Количество бесплатных MMS';
--#end if

--#if not ColumnExists("DB_LOADER_PHONE_STAT.CALLS_FULL_MINUTES") then
ALTER TABLE DB_LOADER_PHONE_STAT ADD CALLS_FULL_MINUTES INTEGER;
--#end if

--#if GetColumnComment("DB_LOADER_PHONE_STAT.CALLS_FULL_MINUTES")<>"Количество полных минут платных звонков" then
COMMENT ON COLUMN DB_LOADER_PHONE_STAT.CALLS_FULL_MINUTES IS 'Количество полных минут платных звонков';
--#end if

GRANT DELETE, INSERT, SELECT, UPDATE ON DB_LOADER_PHONE_STAT TO CORP_MOBILE_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON DB_LOADER_PHONE_STAT TO LONTANA_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON DB_LOADER_PHONE_STAT TO SIM_TRADE;

GRANT SELECT ON DB_LOADER_PHONE_STAT TO CORP_MOBILE_ROLE_RO;