CREATE TABLE DB_LOADER_SERVICE_TYPES (
SERVICE_CODE CHAR(1 CHAR),
SERVICE_NAME VARCHAR2(20 CHAR)
);

INSERT INTO DB_LOADER_SERVICE_TYPES (SERVICE_CODE, SERVICE_NAME) VALUES ('C', 'Звонок');
INSERT INTO DB_LOADER_SERVICE_TYPES (SERVICE_CODE, SERVICE_NAME) VALUES ('S', 'СМС');
INSERT INTO DB_LOADER_SERVICE_TYPES (SERVICE_CODE, SERVICE_NAME) VALUES ('U', 'ММС');
INSERT INTO DB_LOADER_SERVICE_TYPES (SERVICE_CODE, SERVICE_NAME) VALUES ('G', 'Интернет');
INSERT INTO DB_LOADER_SERVICE_TYPES (SERVICE_CODE, SERVICE_NAME) VALUES ('W', 'WAP');
INSERT INTO DB_LOADER_SERVICE_TYPES (SERVICE_CODE, SERVICE_NAME) VALUES ('O', 'Прочие');
COMMIT;
