CREATE TABLE IOT_ACC_REPORT_DATA_TEMP
(
  ACCOUNT_ID      NUMBER,
  YEAR_MONTH      NUMBER,
  NSUM            NUMBER,
  LOAD_DATE_TIME  DATE,
  CAN_LOAD        NUMBER, 
  CONSTRAINT PK_ACC_REPORT_DATA_TEMP
  PRIMARY KEY
  (ACCOUNT_ID, YEAR_MONTH)
)
ORGANIZATION INDEX
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
MONITORING;

COMMENT ON TABLE IOT_ACC_REPORT_DATA_TEMP IS 'Таблица для хранения данных обновления';

COMMENT ON COLUMN IOT_ACC_REPORT_DATA_TEMP.ACCOUNT_ID IS 'Лицевой счёт';

COMMENT ON COLUMN IOT_ACC_REPORT_DATA_TEMP.YEAR_MONTH IS 'Код учётного периода';

COMMENT ON COLUMN IOT_ACC_REPORT_DATA_TEMP.NSUM IS 'Сумма на лицевом счёте';

COMMENT ON COLUMN IOT_ACC_REPORT_DATA_TEMP.LOAD_DATE_TIME IS 'Дата обновления записи';

COMMENT ON COLUMN IOT_ACC_REPORT_DATA_TEMP.CAN_LOAD IS 'Признак разрешения на загрузку';




ALTER TABLE IOT_ACC_REPORT_DATA_TEMP ADD (
  CONSTRAINT FK_ACC_RD_T_ACCOUNTS 
  FOREIGN KEY (ACCOUNT_ID) 
  REFERENCES ACCOUNTS (ACCOUNT_ID));

GRANT DELETE, INSERT, SELECT, UPDATE ON IOT_ACC_REPORT_DATA_TEMP TO CORP_MOBILE_ROLE;

GRANT SELECT ON IOT_ACC_REPORT_DATA_TEMP TO CORP_MOBILE_ROLE_RO;
