--v1
CREATE TABLE MSISDN_REFRESH (
       MSISDN varchar2(11),
       typer number(1)
);


--GRANT DELETE, INSERT, SELECT, UPDATE ON MSISDN_REFRESH TO CORP_MOBILE_ROLE;

--GRANT SELECT ON MSISDN_REFRESH TO CORP_MOBILE_ROLE_RO;  
