--DROP TABLE PHONE_BALANCES;

CREATE SEQUENCE S_NEW_PHONE_BALANCE_ID;

CREATE TABLE PHONE_BALANCES (
  PHONE_BALANCE_ID      INTEGER 
    CONSTRAINT PK_PHONE_BALANCE_ID PRIMARY KEY,
  PHONE_NUMBER VARCHAR2(10) 
    CONSTRAINT NN_PHONE_BALANCE_PHONE NOT NULL,
  BALANCE_DATE          DATE CONSTRAINT NN_PHONE_BALANCE_DATE NOT NULL,
  BALANCE_VALUE         NUMBER(15, 2) NOT NULL,
  USER_CREATED          VARCHAR2(30 CHAR),
  DATE_CREATED          DATE,
  USER_LAST_UPDATED     VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED     DATE
);

COMMENT ON TABLE PHONE_BALANCES IS 'Баланс по телефону';

COMMENT ON COLUMN PHONE_BALANCES.PHONE_BALANCE_ID IS 'Первичный ключ';

COMMENT ON COLUMN PHONE_BALANCES.BALANCE_VALUE  IS 'Баланс';

COMMENT ON COLUMN PHONE_BALANCES.BALANCE_DATE IS 'Дата баланса';

-- Уникальность позволяет сделать только одну запись для телефона на дату
CREATE UNIQUE INDEX UQ_PHONE_BALANCE_PHONE_DATE ON PHONE_BALANCES (
  PHONE_NUMBER, 
  BALANCE_DATE
  );

CREATE OR REPLACE FUNCTION NEW_PHONE_BALANCE_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_PHONE_BALANCE_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;
/

SHOW ERRORS;


CREATE OR REPLACE TRIGGER TIU_PHONE_BALANCES
  BEFORE INSERT OR UPDATE ON PHONE_BALANCES FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.PHONE_BALANCE_ID, 0) = 0 then
      :NEW.PHONE_BALANCE_ID := NEW_PHONE_BALANCE_ID;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/
SHOW ERRORS;

INSERT INTO PHONE_BALANCES
(phone_number, balance_date, balance_value)
select phone_number_federal, balance_date, balance_value
from contract_balances, contracts
where contract_balances.contract_id=contracts.contract_id;

COMMIT;

ALTER TABLE PHONE_BALANCES ADD FIX_YEAR_MONTH_ID INTEGER;

ALTER TABLE PHONE_BALANCES ADD 
CONSTRAINT FK_FIX_YEAR_MONTH_ID
 FOREIGN KEY (FIX_YEAR_MONTH_ID)
 REFERENCES FIX_YEAR_MONTHS (FIX_YEAR_MONTH_ID) ENABLE
 VALIDATE
