CREATE TABLE PHONE_NUMBER_ATTRIBUTES(
  PHONE_NUMBER VARCHAR(10 CHAR) PRIMARY KEY,
  IS_DISCOUNT_OPERATOR NUMBER(1)
  );
 
COMMENT ON TABLE PHONE_NUMBER_ATTRIBUTES IS 'Атрибуты телефонных номеров';
 
COMMENT ON COLUMN PHONE_NUMBER_ATTRIBUTES.PHONE_NUMBER IS 'Номер телефона';  

COMMENT ON COLUMN PHONE_NUMBER_ATTRIBUTES.IS_DISCOUNT_OPERATOR IS 'Наличие годовой скидки оператора 1-есть, иначе-нет';  

GRANT DELETE, INSERT, SELECT, UPDATE ON PHONE_NUMBER_ATTRIBUTES TO LONTANA_ROLE;

ALTER TABLE PHONE_NUMBER_ATTRIBUTES ADD DISCOUNT_BEGIN_DATE DATE;

COMMENT ON COLUMN PHONE_NUMBER_ATTRIBUTES.DISCOUNT_BEGIN_DATE IS 'Дата начала действия скидки';

ALTER TABLE PHONE_NUMBER_ATTRIBUTES ADD DISCOUNT_VALIDITY INTEGER;

COMMENT ON COLUMN PHONE_NUMBER_ATTRIBUTES.DISCOUNT_VALIDITY IS 'Срок действия скидки в месяцах';