CREATE TABLE QUEUE_CURRENT_BALANCES(
  QUEUE_ID INTEGER PRIMARY KEY,
  PHONE_NUMBER VARCHAR2(10 CHAR) NOT NULL,
  DATE_INSERT DATE
  );
  
CREATE OR REPLACE TRIGGER TIU_QUEUE_CURRENT_BALANCES
  BEFORE INSERT OR UPDATE ON QUEUE_CURRENT_BALANCES FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    :NEW.DATE_INSERT:=SYSDATE;
    SELECT NVL(MAX(QUEUE_ID), 0)+1 INTO :NEW.QUEUE_ID
      FROM QUEUE_CURRENT_BALANCES;
  END IF;
END;
/
  
ALTER TABLE QUEUE_CURRENT_BALANCES ADD QUEUE_TYPE INTEGER;
COMMENT ON COLUMN QUEUE_CURRENT_BALANCES.QUEUE_TYPE IS 'рхо нвепедх';

GRANT INSERT, UPDATE, DELETE, SELECT ON QUEUE_CURRENT_BALANCES TO LONTANA_ROLE;