CREATE TABLE REF_TEXT
--
--Version=1
--
--v.1 19.02.2016 Афросин - добавил таблицу "Справочник текстов сообщений"
--
(
  REF_TEXT_ID       INTEGER,
  REF_TEXT_TYPE_ID  INTEGER UNIQUE,
  REF_TEXT_NAME          VARCHAR2(50 BYTE) UNIQUE,
  REF_TEXT_VALUE          VARCHAR2(100 BYTE),
  REF_TEXT_COMMENT  varchar2 (150),
  DATE_CREATED DATE DEFAULT SYSDATE,
  USER_CREATED VARCHAR2 (20) DEFAULT USER,
  DATE_UPDATED DATE,
  USER_UPDATED VARCHAR2 (20),
  
  CONSTRAINT REF_TEXT_ID_PK PRIMARY KEY (REF_TEXT_ID),
  FOREIGN KEY (REF_TEXT_TYPE_ID) REFERENCES REF_TEXT_TYPE(REF_TEXT_TYPE_ID)
);

COMMENT ON TABLE REF_TEXT IS 'Справочник текстов сообщений';

COMMENT ON COLUMN REF_TEXT.REF_TEXT_ID IS 'ID записи';

COMMENT ON COLUMN REF_TEXT.REF_TEXT_TYPE_ID IS 'Тип запроса, для которого возвращается текст (из таблцы REF_TEXT_TYPE)';

COMMENT ON COLUMN REF_TEXT.REF_TEXT_NAME IS 'Имя константы для получения текста';

COMMENT ON COLUMN REF_TEXT.REF_TEXT_VALUE IS 'Текст сообщения';

COMMENT ON COLUMN REF_TEXT.DATE_CREATED IS 'Дата создания';

COMMENT ON COLUMN REF_TEXT.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN REF_TEXT.DATE_UPDATED IS 'Дата обновления';

COMMENT ON COLUMN REF_TEXT.USER_UPDATED IS 'Пользователь, обновивший запись';


CREATE OR REPLACE TRIGGER TIU_REF_TEXT
  BEFORE INSERT OR UPDATE ON REF_TEXT FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    :NEW.REF_TEXT_ID := S_NEW_REF_TEXT_ID.NEXTVAL;
  END IF;
  
  IF UPDATING THEN
    :NEW.USER_UPDATED := USER;
    :NEW.DATE_UPDATED := SYSDATE;
  END IF;
END;
