CREATE TABLE REPORT_TYPES(
  REPORT_TYPE_ID INTEGER PRIMARY KEY,
  TYPE_REPORT VARCHAR2(100 CHAR) NOT NULL, 
  REPORT_NAME VARCHAR2(100 CHAR) NOT NULL
);

COMMENT ON TABLE REPORT_TYPES IS 'Типы отчетов';

CREATE SEQUENCE S_NEW_REPORT_TYPE_ID;

CREATE OR REPLACE FUNCTION NEW_REPORT_TYPE_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_REPORT_TYPE_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;
/

CREATE OR REPLACE TRIGGER TIU_REPORT_TYPES
  BEFORE INSERT OR UPDATE ON REPORT_TYPES FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.REPORT_TYPE_ID, 0) = 0 then
      :NEW.REPORT_TYPE_ID := NEW_REPORT_TYPE_ID;
    END IF;
  END IF;
END;
/

ALTER TABLE REPORT_TYPES ADD SEND_REPORT NUMBER(1);