CREATE TABLE SERVICES_API(
  AT_FT_DE VARCHAR2(240 CHAR),
  AT_FT_DESC VARCHAR2(240 CHAR),
  DATE_INSERT DATE,
  DATE_UPDATE DATE
  );
COMMENT ON TABLE SERVICES_API IS 'Справочник типов услуг и типов звонков по API'; 
COMMENT ON COLUMN SERVICES_API.AT_FT_DE IS 'Тип услуги';
COMMENT ON COLUMN SERVICES_API.AT_FT_DESC IS 'Расшифрвока типа услуги';
COMMENT ON COLUMN SERVICES_API.DATE_INSERT IS 'Дата вставки';
COMMENT ON COLUMN SERVICES_API.DATE_UPDATE IS 'Дата обновления';


--GRANT SELECT, INSERT, UPDATE, DELETE ON SERVICES_API TO CORP_MOBILE_ROLE;

--GRANT SELECT, INSERT, UPDATE, DELETE ON SERVICES_API TO LONTANA_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON SERVICES_API TO SIM_TRADE_ROLE;