CREATE TABLE SH_CONTRACTS
(
  CONTRACT_ID                     INTEGER       NOT NULL,
  CONTRACT_NUM                    INTEGER,
  CONTRACT_DATE                   DATE,
  FILIAL_ID                       INTEGER,
  OPERATOR_ID                     INTEGER,
  PHONE_NUMBER_FEDERAL            VARCHAR2(10 CHAR) NOT NULL,
  PHONE_NUMBER_CITY               VARCHAR2(7 CHAR),
  PHONE_NUMBER_TYPE               NUMBER(1),
  TARIFF_ID                       INTEGER,
  SIM_NUMBER                      VARCHAR2(20 CHAR),
  SERVICE_ID                      INTEGER,
  DISCONNECT_LIMIT                NUMBER,
  CONFIRMED                       NUMBER(1),
  USER_CREATED                    VARCHAR2(30 CHAR),
  DATE_CREATED                    DATE,
  USER_LAST_UPDATED               VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED               DATE,
  ABONENT_ID                      INTEGER,
  RECEIVED_SUM                    NUMBER(15,2),
  START_BALANCE                   NUMBER(15,2)  DEFAULT 0                     NOT NULL,
  GOLD_NUMBER_SUM                 NUMBER(15,2)  DEFAULT 0,
  HAND_BLOCK                      NUMBER        DEFAULT 0,
  CONNECT_LIMIT                   NUMBER(12,2),
  IS_CREDIT_CONTRACT              NUMBER(1),
  COMMENTS                        VARCHAR2(300 CHAR),
  SEND_ACTIV                      NUMBER(1),
  HAND_BLOCK_DATE_END             DATE,
  DOP_STATUS                      NUMBER,
  DEALER_KOD                      INTEGER,
  ABON_TP_DISCOUNT                INTEGER,
  INSTALLMENT_PAYMENT_DATE        DATE,
  INSTALLMENT_PAYMENT_SUM         NUMBER(15,4),
  INSTALLMENT_PAYMENT_MONTHS      INTEGER,
  INSTALLMENT_ADVANCED_REPAYMENT  DATE,
  GROUP_ID                        INTEGER,
  BALANCE_BLOCK_HAND_BLOCK        INTEGER,
  BALANCE_NOTICE_HAND_BLOCK       INTEGER,
  MN_ROAMING                      INTEGER,
  CURR_TARIFF_ID                  INTEGER,
  USER_PASSWORD                   VARCHAR2(30 BYTE),
  OPTION_GROUP_ID                 INTEGER,
  PARAMDISABLE_SMS                VARCHAR2(50 BYTE),
  UPDATE_USER                     VARCHAR2(50 BYTE),
  UPDATE_TIME                     DATE
)