CREATE TABLE SIM_SEND_PAID_SMS_HISTORY(
  SEND_PAID_SMS_HISTORY_ID INTEGER PRIMARY KEY,
  PHONE_NUMBER VARCHAR2(10 CHAR) NOT NULL,
  NOTE VARCHAR2(500 CHAR),
  DATE_SEND DATE
);

CREATE SEQUENCE S_NEW_SEND_PAID_SMS_HISTORY_ID;

CREATE OR REPLACE FUNCTION NEW_SEND_PAID_SMS_HISTORY_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_SEND_PAID_SMS_HISTORY_ID.NEXTVAL
    INTO vRES
    FROM DUAL;
  RETURN vRES;
END;

CREATE OR REPLACE TRIGGER TIU_SIM_SEND_PAID_SMS_HISTORY
  BEFORE INSERT OR UPDATE ON SIM_SEND_PAID_SMS_HISTORY FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.SEND_PAID_SMS_HISTORY_ID, 0) = 0 then
      :NEW.SEND_PAID_SMS_HISTORY_ID := NEW_SEND_PAID_SMS_HISTORY_ID;
    END IF;
    :NEW.DATE_SEND := SYSDATE;   
  END IF;
END;


