CREATE TABLE SIM_PHONE_OPTION_TYPE(
  OPTION_ID INTEGER NOT NULL,
  OPTION_NAME VARCHAR2(200 CHAR) NOT NULL,
  SERVICE_ID INTEGER,
  GROUP_ID INTEGER
);

CREATE UNIQUE INDEX I_SIM_PH_OPT_TYPE_OPT_NAME ON SIM_PHONE_OPTION_TYPE
(OPTION_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;