CREATE TABLE SIM_OPERATION_HISTORY(
  OPERATION_HISTORY_ID INTEGER PRIMARY KEY,
  OPERATION_TYPE VARCHAR(100 CHAR) NOT NULL,
  NOTE VARCHAR2(500 CHAR),
  USER_CREATED VARCHAR2(30 CHAR),
  DATE_BEGIN DATE,
  DATE_END DATE  
);

CREATE SEQUENCE S_NEW_OPERATION_HISTORY_ID;

CREATE OR REPLACE FUNCTION NEW_OPERATION_HISTORY_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_OPERATION_HISTORY_ID.NEXTVAL
    INTO vRES
    FROM DUAL;
  RETURN vRES;
END;

CREATE OR REPLACE TRIGGER TIU_SIM_OPERATION_HISTORY
  BEFORE INSERT OR UPDATE ON SIM_OPERATION_HISTORY FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.OPERATION_HISTORY_ID, 0) = 0 then
      :NEW.OPERATION_HISTORY_ID := NEW_OPERATION_HISTORY_ID;
    END IF;
    IF :NEW.DATE_BEGIN IS NULL then
      :NEW.DATE_BEGIN := SYSDATE;
    END IF;
    IF :NEW.DATE_END IS NULL then
      :NEW.DATE_END := SYSDATE;
    END IF;
    :NEW.USER_CREATED:=USER;
  END IF;
END;

GRANT DELETE, INSERT, SELECT, UPDATE ON SIM_OPERATION_HISTORY TO LONTANA_ROLE;