CREATE TABLE SMS_SEND_PARAMETRS
(
  PROVIDER_ID INTEGER PRIMARY KEY NOT NULL,
  lOGIN VARCHAR2(30 CHAR),
  PASSWORD VARCHAR2(30 CHAR),
  STATUS NUMBER,
  SENDER_NAME VARCHAR2(30 CHAR),
  PROVIDER_NAME VARCHAR2(30 CHAR) NOT NULL
);

SET DEFINE OFF;
Insert into SMS_SEND_PARAMETRS
   (PROVIDER_ID, LOGIN, PASSWORD, STATUS, SENDER_NAME, 
    PROVIDER_NAME)
 Values
   (2, 'simtradeAPI2', 'd4w3gg4', 0, 'SIMtrade', 
    'MobiVision');
Insert into SMS_SEND_PARAMETRS
   (PROVIDER_ID, LOGIN, PASSWORD, STATUS, SENDER_NAME, 
    PROVIDER_NAME)
 Values
   (4, 'simtrade', '123', 0, 'SIMtrade', 
    'TargetSMS');
Insert into SMS_SEND_PARAMETRS
   (PROVIDER_ID, LOGIN, PASSWORD, STATUS, SENDER_NAME, 
    PROVIDER_NAME)
 Values
   (5, 'simtrade', 'sim_trade2015', 0, 'SIMtrade', 
    'sms.e-vostok.ru');
Insert into SMS_SEND_PARAMETRS
   (PROVIDER_ID, LOGIN, PASSWORD, STATUS, SENDER_NAME, 
    PROVIDER_NAME)
 Values
   (3, 'Simtrade', 'f54gvbg', 1, 'SIMtrade', 
    'MyMobyVision');
COMMIT;

COMMENT ON TABLE SMS_SEND_PARAMETRS IS 'ЯОХЯНЙ ЯЛЯ ОПНБЮИДЕПНБ';

COMMENT ON COLUMN SMS_SEND_PARAMETRS.PROVIDER_ID IS 'ID опнбюидепю';

COMMENT ON COLUMN SMS_SEND_PARAMETRS.LOGIN IS 'кнцхм';

COMMENT ON COLUMN SMS_SEND_PARAMETRS.PASSWORD IS 'оюпнкэ';

COMMENT ON COLUMN SMS_SEND_PARAMETRS.STATUS IS 'ярюрся';

COMMENT ON COLUMN SMS_SEND_PARAMETRS.SENDER_NAME IS 'мюхлемнбюмхе нропюбхрекъ';

COMMENT ON COLUMN SMS_SEND_PARAMETRS.PROVIDER_NAME IS 'мюхлемнбюмхе опнбюидепю';
