CREATE SEQUENCE S_NEW_TARIFF_OPTION_NEW_COSTID;

CREATE OR REPLACE FUNCTION NEW_TARIFF_OPTION_NEW_COST_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_TARIFF_OPTION_NEW_COSTID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;
/

CREATE TABLE TARIFF_OPTION_NEW_COST (
  TARIFF_OPTION_NEW_COST_ID INTEGER,
  TARIFF_OPTION_COST_ID INTEGER NOT NULL
    CONSTRAINT FK_TARIFF_OPTION_COST_NEW_COST REFERENCES TARIFF_OPTION_COSTS ON DELETE CASCADE,
  TARIFF_ID INTEGER
    CONSTRAINT FK_TARIFF_OPTION_COST_NEW_TAR REFERENCES TARIFFS ON DELETE CASCADE,
  TURN_ON_COST NUMBER(12, 2),
  MONTHLY_COST NUMBER(12, 2),
  USER_CREATED VARCHAR2(30 CHAR),
  DATE_CREATED DATE,
  USER_LAST_UPDATED VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED DATE
);

COMMENT ON TABLE TARIFF_OPTION_NEW_COST IS 'Стоимость тарифных опций для отдельных тарифов';

COMMENT ON COLUMN TARIFF_OPTION_NEW_COST.TARIFF_OPTION_NEW_COST_ID IS 'Первичный ключ';

COMMENT ON COLUMN TARIFF_OPTION_NEW_COST.TARIFF_OPTION_COST_ID IS 'Код изменямой стоимости опции';

COMMENT ON COLUMN TARIFF_OPTION_NEW_COST.TARIFF_ID IS 'Код тарифного плана';

COMMENT ON COLUMN TARIFF_OPTION_NEW_COST.TURN_ON_COST IS 'Стоимость подключения';

COMMENT ON COLUMN TARIFF_OPTION_NEW_COST.MONTHLY_COST IS 'Ежемесячная стоимость';

COMMENT ON COLUMN TARIFF_OPTION_NEW_COST.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN TARIFF_OPTION_NEW_COST.DATE_CREATED IS 'Дата/время создания записи';

COMMENT ON COLUMN TARIFF_OPTION_NEW_COST.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';

COMMENT ON COLUMN TARIFF_OPTION_NEW_COST.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';

CREATE INDEX I_TARIFF_OPTION_NEW_COST_ID ON TARIFF_OPTION_NEW_COST (TARIFF_ID);

CREATE OR REPLACE TRIGGER TIU_TARIFF_OPTION_NEW_COST
  BEFORE INSERT OR UPDATE ON TARIFF_OPTION_NEW_COST FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.TARIFF_OPTION_NEW_COST_ID, 0) = 0 then
      :NEW.TARIFF_OPTION_NEW_COST_ID := NEW_TARIFF_OPTION_NEW_COST_ID;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/

ALTER TABLE TARIFF_OPTION_NEW_COST ADD TURN_ON_COST_FOR_BILLS NUMBER(15, 4);

COMMENT ON COLUMN TARIFF_OPTION_NEW_COST.TURN_ON_COST_FOR_BILLS IS 'Стоимость подключения в счетах';

ALTER TABLE TARIFF_OPTION_NEW_COST ADD MONTHLY_COST_FOR_BILLS NUMBER(15, 4);

COMMENT ON COLUMN TARIFF_OPTION_NEW_COST.MONTHLY_COST_FOR_BILLS IS 'Ежемесячная стоимость в счетах';