--#if not TableExists("TARIFF_OPTIONS_REQ_LOG") then
CREATE TABLE TARIFF_OPTIONS_REQ_LOG(
  PHONE_NUMBER      VARCHAR2(11),
  OPTION_CODE       VARCHAR2(30 CHAR),
  INCLUSION_TYPE    CHAR(1),
  EFF_DATE          DATE,
  EXP_DATE          DATE,
  REQUEST_ID        VARCHAR2(20),
  REQUEST_INITIATOR VARCHAR2(10),
  USER_NAME         VARCHAR2(30),
  REQUEST_DATE_TIME DATE
  );

COMMENT ON TABLE TARIFF_OPTIONS_REQ_LOG IS 'Журнал заявок на автоматическое подключение и отключение услуг';
COMMENT ON COLUMN TARIFF_OPTIONS_REQ_LOG.PHONE_NUMBER IS 'Номер телефона';
COMMENT ON COLUMN TARIFF_OPTIONS_REQ_LOG.OPTION_CODE IS 'Код опции';
COMMENT ON COLUMN TARIFF_OPTIONS_REQ_LOG.INCLUSION_TYPE IS 'Вид запроса: A - подключение, D - отключение';
COMMENT ON COLUMN TARIFF_OPTIONS_REQ_LOG.EFF_DATE IS 'Дата подключения услуги (NULL - немедленно)';
COMMENT ON COLUMN TARIFF_OPTIONS_REQ_LOG.EXP_DATE IS 'Дата автоматического отключения услуги (NULL - нет)';
COMMENT ON COLUMN TARIFF_OPTIONS_REQ_LOG.REQUEST_ID IS 'Код заявки';
COMMENT ON COLUMN TARIFF_OPTIONS_REQ_LOG.REQUEST_INITIATOR IS 'Инициатор заявки:
RETARIF: блок перетарификации; 
USER: пользователь';
COMMENT ON COLUMN TARIFF_OPTIONS_REQ_LOG.USER_NAME IS 'Имя пользователя, подавшего заявку';
COMMENT ON COLUMN TARIFF_OPTIONS_REQ_LOG.REQUEST_DATE_TIME IS 'Дата и время заявки';
--#end if

CREATE INDEX I_TARIFF_OPTIONS_REQ_LOG_PHONE ON TARIFF_OPTIONS_REQ_LOG(PHONE_NUMBER) COMPRESS;

CREATE INDEX I_TARIFF_OPTIONS_REQ_LOG_REQID ON TARIFF_OPTIONS_REQ_LOG(REQUEST_ID);
