--#if IsClient("CORP_MOBILE") then
--#if not TableExists("TEMP_CALCDETAILSUM") then
CREATE GLOBAL TEMPORARY TABLE TEMP_CALCDETAILSUM
(
  PHONE  VARCHAR2(10 BYTE),
  SDATE DATE
)
ON COMMIT PRESERVE ROWS
NOCACHE;
--#end if

--#if not IndexExists("I_TEMP_CALCDETAILSUM") THEN
CREATE INDEX I_TEMP_CALCDETAILSUM ON TEMP_CALCDETAILSUM
(PHONE);
--#end if

--#end if
