CREATE TABLE USER_NAME_ACCOUNTS
(
  USER_NAME_ID  NUMBER(38)                      NOT NULL,
  ACCOUNT_ID    NUMBER(38)                      NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN USER_NAME_ACCOUNTS.USER_NAME_ID IS 'Пользователь';

COMMENT ON COLUMN USER_NAME_ACCOUNTS.ACCOUNT_ID IS 'Лицевой счет';


CREATE UNIQUE INDEX U_USER_ACCOUNT ON USER_NAME_ACCOUNTS
(USER_NAME_ID, ACCOUNT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE USER_NAME_ACCOUNTS ADD (
  CONSTRAINT U_USER_ACCOUNT
  UNIQUE (USER_NAME_ID, ACCOUNT_ID)
  USING INDEX U_USER_ACCOUNT);

ALTER TABLE USER_NAME_ACCOUNTS ADD (
  CONSTRAINT USER_ACCOUNT_FK1 
  FOREIGN KEY (ACCOUNT_ID) 
  REFERENCES ACCOUNTS (ACCOUNT_ID),
  CONSTRAINT USER_ACCOUNT_FK2 
  FOREIGN KEY (USER_NAME_ID) 
  REFERENCES USER_NAMES (USER_NAME_ID));
