--v1
CREATE TABLE USSD_CURRENT (
       id integer,
       XCPAXAction VARCHAR2(50),
       XCPAMSGID VARCHAR2(50),
       UPDATE_DATE DATE,
       MSISDN varchar2(11),
       XCPAUSSDSession varchar2(3)
);

ALTER TABLE USSD_CURRENT ADD (
  CONSTRAINT FK_USSD_CURRENT_ID
 FOREIGN KEY (ID) 
 REFERENCES USSD_TREE (ID));
 
 ALTER TABLE USSD_CURRENT ADD INSERT_DATE DATE;

CREATE OR REPLACE TRIGGER TIU_USSD_CURRENT
  BEFORE INSERT OR UPDATE ON USSD_CURRENT FOR EACH ROW
--#Version=1
BEGIN
    if INSERTING then
    :NEW.Insert_Date:=sysdate;
  end if;
    :NEW.UPDATE_DATE := sysdate;
END;

--GRANT DELETE, INSERT, SELECT, UPDATE ON USSD_CURRENT TO CORP_MOBILE_ROLE;

--GRANT SELECT ON USSD_CURRENT TO CORP_MOBILE_ROLE_RO;  
