--v1 
CREATE TABLE USSD_TREE (
       ID         INTEGER PRIMARY KEY,
       LEAF_ID INTEGER,
       PARENT_ID  REFERENCES USSD_TREE
);

CREATE INDEX I_USSD_TREE_1 ON USSD_TREE (ID, PARENT_ID);
CREATE INDEX I_USSD_TREE_2 ON USSD_TREE (PARENT_ID, ID);

ALTER TABLE USSD_TREE ADD (
  CONSTRAINT FK_USSD_TREE_LEAF_ID
 FOREIGN KEY (LEAF_ID) 
 REFERENCES USSD_LEAFS (LEAF_ID));
--GRANT DELETE, INSERT, SELECT, UPDATE ON USSD_TREE TO CORP_MOBILE_ROLE;

--GRANT SELECT ON USSD_TREE TO CORP_MOBILE_ROLE_RO;  



