--#IF GETVERSION("DELETE_PROMISED_PAYMENT") < 2 THEN
CREATE OR REPLACE FUNCTION DELETE_PROMISED_PAYMENT(
  pPHONE_NUMBER IN VARCHAR2
  ) RETURN VARCHAR2 IS
--Version = 3
--24.11.2014 Алексеев. Таблица PROMISED_PAYMENTS заменена на вьюху V_ACTIVE_PROMISED_PAYMENTS
CURSOR C(aPHONE_NUMBER VARCHAR2) IS
  SELECT PP.*
    FROM V_ACTIVE_PROMISED_PAYMENTS PP
    WHERE PP.PHONE_NUMBER=aPHONE_NUMBER
      AND PP.PAYMENT_DATE<=SYSDATE;
ITOG VARCHAR2(300 CHAR);
REC_C C%ROWTYPE;
BEGIN
  ITOG:='';
  OPEN C(pPHONE_NUMBER);
  FETCH C INTO REC_C;
  IF C%FOUND THEN 
    UPDATE PROMISED_PAYMENTS PP
      SET PP.PROMISED_DATE = SYSDATE
      WHERE PP.PHONE_NUMBER=pPHONE_NUMBER
        AND PP.PROMISED_DATE>=SYSDATE
        AND PP.PAYMENT_DATE<=SYSDATE;
    COMMIT;
    ITOG:='Остановлен текущий обещанный платеж '||TO_CHAR(REC_C.PROMISED_SUM)||'р до '||TO_CHAR(REC_C.PROMISED_DATE_END, 'DD.MM.YYYY HH24:MI:SS')||' на номер '||REC_C.PHONE_NUMBER||'.';  
  ELSE
    ITOG:='Для номера '||pPHONE_NUMBER||' нет обещанного платежа.';
  END IF;
  CLOSE C;
  RETURN ITOG;
END; 
--#end if

--#Execute MAIN_SCHEMA=IsClient("")

--#if not GrantExists("DELETE_PROMISED_PAYMENT", "ROLE", "EXECUTE") then
begin EXECUTE IMMEDIATE 'GRANT EXECUTE ON DELETE_PROMISED_PAYMENT TO &MAIN_SCHEMA'||'_ROLE'; end;
--#end if

--#if not GrantExists("DELETE_PROMISED_PAYMENT", "ROLE_RO", "EXECUTE") then
begin EXECUTE IMMEDIATE 'GRANT EXECUTE ON DELETE_PROMISED_PAYMENT TO &MAIN_SCHEMA'||'_ROLE_RO'; end;
--#end if

