CREATE OR REPLACE FUNCTION GET_CREDIT_INFO(
  pCONTRACT_ID IN INTEGER
  ) RETURN VARCHAR2 IS
-- v2. Матюнин - 25.05.2015. Механизм получения месяца переделан с использованием CONVERT_PCKG.MONTH_NAME()
                        --   Убрано постоянно срабатывающее условие  IF TO_NUMBER(TO_CHAR(SYSDATE, 'DD'))<=31 THEN
  CURSOR C IS     
    SELECT C.PHONE_NUMBER_FEDERAL,
           NVL(C.IS_CREDIT_CONTRACT, 0) IS_CREDIT_CONTRACT,
           TRUNC(V.BILL_SUMM, 2) BILL_SUM,
           TRUNC(V.ABON_TP + V.ABON_ADD + V.DISCOUNT, 2) ABONKA,
           V.YEAR_MONTH,
           AB.DATE_CREDIT_END
      FROM CONTRACTS C,
           CONTRACT_CANCELS CC,
           TARIFER_BILL_FOR_CLIENTS V,
           (SELECT MAX(DATE_CREDIT_END) DATE_CREDIT_END,
                   MAX(YEAR_MONTH) YEAR_MONTH, ACCOUNT_ID
              FROM ACCOUNT_LOADED_BILLS
              WHERE LOAD_BILL_IN_BALANCE =1
              GROUP BY ACCOUNT_ID ) AB
      WHERE C.CONTRACT_ID=pCONTRACT_ID
        AND NVL(C.IS_CREDIT_CONTRACT, 0)=1
        AND C.CONTRACT_ID = CC.CONTRACT_ID(+)
        AND CC.CONTRACT_CANCEL_DATE IS NULL
        AND C.PHONE_NUMBER_FEDERAL=V.PHONE_NUMBER
        AND V.YEAR_MONTH = AB.YEAR_MONTH(+)
        and ab.account_id = nvl(CONVERT_PCKG.GET_ACCOUNT_ID_BY_PHONE(V.PHONE_NUMBER), 1)
        AND TRUNC(AB.DATE_CREDIT_END) >=TRUNC(SYSDATE)
     /*   AND AB.LOAD_BILL_IN_BALANCE = 1*/;
  DUMMY C%ROWTYPE;      
  ITOG VARCHAR2(300 CHAR);
  BALANCE NUMBER(13, 2);      
  BILL NUMBER(13, 2);
  MONTH_NAME VARCHAR2(20 CHAR);   
  vBILLS NUMBER(13, 2);   
  vABONKA NUMBER(13, 2);   
BEGIN
  --IF TO_NUMBER(TO_CHAR(SYSDATE, 'DD'))<=31 THEN
    vBILLS:=0;
    vABONKA:=0;
    FOR rec IN C 
    LOOP
      vBILLS:=vBILLS+rec.BILL_SUM;
      vABONKA:=vABONKA+rec.ABONKA;
    END LOOP;
    OPEN C;
    FETCH C INTO DUMMY;
    IF (C%FOUND) AND (TRUNC(DUMMY.DATE_CREDIT_END) >= TRUNC(SYSDATE)) THEN
      IF NVL(DUMMY.YEAR_MONTH, 0)>0 THEN
        MONTH_NAME:= CONVERT_PCKG.MONTH_NAME(DUMMY.YEAR_MONTH-100*TRUNC(DUMMY.YEAR_MONTH/100));                    
        BALANCE:=GET_ABONENT_BALANCE(DUMMY.PHONE_NUMBER_FEDERAL) - vABONKA;
        ITOG:='Счет за '||MONTH_NAME||': '||TO_CHAR(vBILLS)||'. Баланс с аб. пл. на '||TO_CHAR(SYSDATE, 'DD.MM.YY')||': '||TO_CHAR(BALANCE);
      END IF;
    END IF;
    CLOSE C;
  --ELSE
  --  ITOG:='';
  --END IF;
  RETURN ITOG;
END;
/
