CREATE OR REPLACE FUNCTION GET_DISCR_ABON_ADD_OPTIONS(
  pPHONE_NUMBER IN VARCHAR2
  ) RETURN VARCHAR2 IS
-- Version = 2
--
--2. 2015.11.30. Крайнов. Поправка для исключения откл услуг.  
  ITOG VARCHAR2(500 CHAR);
  vYEAR_MONTH INTEGER;
  vDATE DATE;
BEGIN
  ITOG:='NULL';
  vDATE:=TRUNC(SYSDATE);
  vYEAR_MONTH:= TO_NUMBER(TO_CHAR(vDATE, 'YYYYMM'));
  FOR rec IN (SELECT D.OPTION_CODE, NVL(NVL(TONC.MONTHLY_COST, TOC.MONTHLY_COST), 0) MONTHLY_COST,
                     NVL(T_O.OPTION_NAME_FOR_AB, T_O.OPTION_NAME) OPTION_NAME
                FROM DB_LOADER_ACCOUNT_PHONE_OPTS D,
                     TARIFF_OPTIONS T_O, 
                     (SELECT * FROM TARIFF_OPTION_COSTS 
                        WHERE BEGIN_DATE <=vDATE AND END_DATE >= vDATE ) TOC,
                     (SELECT * FROM TARIFF_OPTION_NEW_COST
                        WHERE TARIFF_ID = (SELECT TARIFF_ID FROM DB_LOADER_ABONENT_PERIODS AP
                                             WHERE AP.YEAR_MONTH = vYEAR_MONTH AND AP.PHONE_NUMBER = pPHONE_NUMBER 
                                               AND AP.BEGIN_DATE <=vDATE AND AP.END_DATE >= vDATE AND ROWNUM <=1)
                     ) TONC 
                WHERE D.YEAR_MONTH = vYEAR_MONTH
                  AND D.PHONE_NUMBER = pPHONE_NUMBER
                  AND D.TURN_OFF_DATE IS NULL
                  AND D.OPTION_CODE = T_O.OPTION_CODE(+)
                  AND T_O.DISCR_SPISANIE = 1
                  AND T_O.TARIFF_OPTION_ID = TOC.TARIFF_OPTION_ID(+)
                  AND TOC.TARIFF_OPTION_COST_ID = TONC.TARIFF_OPTION_COST_ID(+))
  LOOP
    IF ITOG = 'NULL' THEN
      ITOG:=rec.OPTION_NAME;
    ELSE
      ITOG:=ITOG || ', ' || rec.OPTION_NAME;
    END IF;
  END LOOP;              
  RETURN ITOG;
END;  

GRANT EXECUTE ON GET_DISCR_ABON_ADD_OPTIONS TO CORP_MOBILE_ROLE;

GRANT EXECUTE ON GET_DISCR_ABON_ADD_OPTIONS TO CORP_MOBILE_ROLE_RO;