CREATE OR REPLACE FUNCTION GET_ID_LAST_CONTRACT_BY_PHONE(
  pPHONE_NUMBER IN VARCHAR2, 
  pYEAR_MONTH IN INTEGER DEFAULT NULL
  ) RETURN INTEGER IS
--Version#1
CURSOR C IS
  SELECT CONTRACTS.CONTRACT_ID
    FROM CONTRACTS
    WHERE CONTRACTS.PHONE_NUMBER_FEDERAL=pPHONE_NUMBER
    ORDER BY CONTRACTS.CONTRACT_DATE DESC;
CURSOR C_DATE IS
  SELECT V_CONTRACTS.CONTRACT_ID
    FROM V_CONTRACTS
    WHERE V_CONTRACTS.PHONE_NUMBER_FEDERAL=pPHONE_NUMBER
      AND LAST_DAY(TO_DATE(TO_CHAR(pYEAR_MONTH),'YYYYMM'))>=V_CONTRACTS.CONTRACT_DATE
      AND TO_DATE(TO_CHAR(pYEAR_MONTH*100+1),'YYYYMMDD')<=NVL(V_CONTRACTS.CONTRACT_CANCEL_DATE, TO_DATE(30001231, 'YYYYMMDD'))
    ORDER BY V_CONTRACTS.CONTRACT_DATE DESC;    
    
CONTRACT_ID_C CONTRACTS.CONTRACT_ID%TYPE;   
BEGIN
  IF pYEAR_MONTH IS NULL THEN
    OPEN C;
    FETCH C INTO CONTRACT_ID_C;
    CLOSE C;
    IF CONTRACT_ID_C IS NULL THEN
      RETURN NULL;
    ELSE     
      RETURN CONTRACT_ID_C;
    END IF;
  ELSE
    OPEN C_DATE;
    FETCH C_DATE INTO CONTRACT_ID_C;
    CLOSE C_DATE;
    IF CONTRACT_ID_C IS NULL THEN
      RETURN NULL;
    ELSE     
      RETURN CONTRACT_ID_C;
    END IF;
  END IF;      
END;
/    