CREATE OR REPLACE FUNCTION GET_TIME_IN_STR(
  pTIME IN INTEGER
  ) RETURN VARCHAR2 IS 
  ITOG VARCHAR2(30 CHAR);
  MI INTEGER;
  SS INTEGER;
  HH INTEGER;
  vTIME INTEGER;
BEGIN
  IF pTIME IS NULL THEN
    ITOG:=NULL;
  ELSE
    vTIME:=pTIME;
    SS:=MOD(vTIME, 60);
    vTIME:=(vTIME - SS)/60;
    MI:=MOD(vTIME, 60);
    HH:=(vTIME - MI)/60;
    ITOG:=SUBSTR('00'||MI, -2, 2)||':'||SUBSTR('00'||SS, -2, 2);
    IF HH>0 THEN
      ITOG:=HH||':'||ITOG;
    END IF;
  END IF;
  RETURN ITOG;
END;  

GRANT EXECUTE ON GET_TIME_IN_STR TO CORP_MOBILE_ROLE; 

GRANT EXECUTE ON GET_TIME_IN_STR TO CORP_MOBILE_ROLE_RO;