CREATE OR REPLACE FUNCTION PROG_SELECT_GROUP(
  pPHONE_NUMBER IN VARCHAR2,
  pGROUP_ID out INTEGER, 
  pGROUP_NAME out VARCHAR2
  ) RETURN INTEGER IS
  CURSOR C IS 
    SELECT C.CONTRACT_ID,
       CG.GROUP_ID,
       CG.GROUP_NAME
  FROM CONTRACTS C,
       CONTRACT_GROUPS CG
  WHERE C.PHONE_NUMBER_FEDERAL = pPHONE_NUMBER
    AND C.GROUP_ID = CG.GROUP_ID
    AND NOT EXISTS (SELECT 1
                      FROM CONTRACT_CANCELS CC
                      WHERE CC.CONTRACT_ID = C.CONTRACT_ID);
  C_DUMMY C%ROWTYPE;    
  vCONTRACT_ID INTEGER;    
BEGIN  
  OPEN C;
  FETCH C INTO C_DUMMY;
  IF C%FOUND THEN
   IF C_DUMMY.GROUP_NAME IS NOT NULL THEN
    vCONTRACT_ID:=C_DUMMY.CONTRACT_ID;
    pGROUP_ID := C_DUMMY.GROUP_ID;
    pGROUP_NAME := C_DUMMY.GROUP_NAME;
   END IF;
  ELSE
    vCONTRACT_ID:=0;
  END IF;
  CLOSE C;
  RETURN vCONTRACT_ID;
END;
/
