CREATE OR REPLACE FUNCTION RECALC_CHARGE_COST(
  PHONE_NUMBER IN VARCHAR2,
  COSTS IN NUMBER
  ) RETURN NUMBER IS
-- Version=2
--Начисление некоего процента к стоимости 
--
-- 1.Крайнов. Создание
ITOG NUMBER(15,5);
SERVER_NAME VARCHAR2(30 CHAR);
BEGIN
  SERVER_NAME:=MS_CONSTANTS.GET_CONSTANT_VALUE('SERVER_NAME');
  ITOG:=CASE
          WHEN SERVER_NAME='CORP_MOBILE' THEN COSTS*1.012
          ELSE COSTS
        END;
  RETURN ITOG;
END;
/  