CREATE OR REPLACE FUNCTION COST_TO_CHAR(
  pCOST IN NUMBER
  ) RETURN VARCHAR2 IS
--#Version=1
FLAG BOOLEAN;
OTVET VARCHAR2(22);
ppCOST NUMBER;
LENG INTEGER;
BEGIN
IF (pCOST<0.01)AND(pCOST>-0.01) THEN
  OTVET:='0,00';
ELSE
  ppCOST:=pCOST;
  FLAG:=FALSE;
  IF ppCOST<0 THEN
    FLAG:=TRUE;
    ppCOST:=-1*ppCOST;
  END IF;    
  OTVET:=TO_CHAR(TRUNC(ppCOST,2),'99999999.99');
  LENG:=LENGTH(OTVET);
  IF LENG>6 THEN
    OTVET:=SUBSTR(OTVET,1,LENG-6)||' '||SUBSTR(OTVET,LENG-5,6);
  END IF;
  OTVET:=TRIM(OTVET);
  IF FLAG THEN
    OTVET:='-' || OTVET;
  END IF;
  OTVET:=REPLACE(OTVET,'.',',');
END IF;  
RETURN OTVET;
END COST_TO_CHAR;
/