CREATE OR REPLACE PROCEDURE MAIN(
  X_USERNAME IN VARCHAR2 DEFAULT NULL,
  X_PASSWORD IN VARCHAR2 DEFAULT NULL,
  SESSION_ID IN VARCHAR2 DEFAULT NULL,
  CLOSE_SESSION IN VARCHAR2 DEFAULT NULL
  ) IS
BEGIN
  S_BEGIN(X_USERNAME=>X_USERNAME, X_PASSWORD=>X_PASSWORD, SESSION_ID=>SESSION_ID, CLOSE_SESSION=>CLOSE_SESSION,STRANICA=>1);
  IF G_STATE.USER_ID IS NOT NULL THEN
    IF SESSION_ID IS NULL THEN
      S_SHOW_USER_INFO(TRUE);
    ELSE
      S_SHOW_USER_INFO(FALSE);
    END IF;    
  ELSE 
    IF MS_PARAMS.GET_PARAM_VALUE('SHOW_MESSAGE_ON_SITE')='1' THEN
      --    Всплывающее окошко при 1-ом запуске  
      HTP.PRINT('<SCRIPT type="text/javascript">showMessage()</script>');
    END IF;
    NULL;
  END IF;
  S_END;
EXCEPTION WHEN OTHERS THEN
  OUT_ERROR(SQLERRM);
END MAIN;
/
