CREATE OR REPLACE FUNCTION NEW_D_INSTANT_MESSAGE_ID RETURN NUMBER IS
  
  --#Version=1
  --
  --v1. Алексеев. 03.11.2015. Функция определения последующего SEQUENCE
  
  vRES NUMBER;
BEGIN
  SELECT S_NEW_D_INSTANT_MESSAGE_ID.NEXTVAL
     INTO vRES
    FROM DUAL;
    
  RETURN vRES;
END;

GRANT EXECUTE ON LONTANA_WWW.NEW_D_INSTANT_MESSAGE_ID TO CRM_USER;