CREATE OR REPLACE FUNCTION LONTANA_WWW.S_GET_DATE_TIME_TEXT(
  pDATE_TIME IN DATE
  ) RETURN VARCHAR2 IS
  
  --Version 1
  --
  --v.1 Алексеев. 05.11.2015 Функция показа даты в строковом виде
  
  vRESULT VARCHAR2(100 CHAR);
BEGIN
  IF TRUNC(pDATE_TIME) = TRUNC(SYSDATE) THEN
    vRESULT := 'Сегодня, ' || TO_CHAR(pDATE_TIME, 'HH24:MI');
  ELSIF TRUNC(pDATE_TIME) = TRUNC(SYSDATE)-1 THEN
    vRESULT := 'Вчера, ' || TO_CHAR(pDATE_TIME, 'HH24:MI');
  ELSE
    vRESULT := TO_CHAR(pDATE_TIME, 'DD.MM.YYYY') || ', '|| TO_CHAR(pDATE_TIME, 'HH24:MI');
  END IF;
  RETURN vRESULT;
END;