CREATE OR REPLACE FUNCTION LONTANA_WWW.SQL_GET_USER_PHONE(
  pUSER_ID IN INTEGER
  ) RETURN VARCHAR2 IS
vPHONE_NUMBER VARCHAR2(20 CHAR);
--vCELL_PLAN_NAME VARCHAR2(100 CHAR);
--vUSER_NAME VARCHAR2(100 CHAR);
--vBALANCE NUMBER;
--vDISCONNECT_LIMIT NUMBER;
--vPHONE_STATUS_CODE INTEGER; 
--vACTUAL_DATE DATE;  
ITOG VARCHAR2(200 CHAR);
BEGIN
--version 2 Овсянников Л.В. Оптимизация получения номера телефона.
--  SQL_GET_USER_INFO(
--    pUSER_ID,
--    vPHONE_NUMBER,
--    vCELL_PLAN_NAME,
--    vUSER_NAME,
--    vBALANCE,
--    vDISCONNECT_LIMIT,
--    vPHONE_STATUS_CODE,
--    vACTUAL_DATE
--    );
  WWW_GET_USER_PHONE(pUSER_ID,vPHONE_NUMBER); 
  ITOG:='8-' || SUBSTR(vPHONE_NUMBER,1,3) || '-' || SUBSTR(vPHONE_NUMBER,4,3) || '-' || SUBSTR(vPHONE_NUMBER,7,2) || '-' || SUBSTR(vPHONE_NUMBER,9,2);
  RETURN ITOG;  
END;
/
