CREATE OR REPLACE PROCEDURE SQL_GET_ABONENT_BALANCE_ROWS(
  pUSER_ID IN INTEGER,
  pBALANCE_DATE IN DATE,
  pDATE_ROWS OUT DBMS_SQL.DATE_TABLE, 
  pCOST_ROWS OUT DBMS_SQL.NUMBER_TABLE, 
  pDESCRIPTION_ROWS OUT DBMS_SQL.VARCHAR2_TABLE
  ) IS
  TEMP_DATE DATE;
  TEMP_COST NUMBER;
  TEMP_NOTE VARCHAR2(2000);   
BEGIN
  LONTANA.WWW_GET_ABONENT_BALANCE_ROWS(
    pUSER_ID,
    pBALANCE_DATE,
    pDATE_ROWS,
    pCOST_ROWS,
    pDESCRIPTION_ROWS
    );
  FOR I IN pDATE_ROWS.FIRST..pDATE_ROWS.LAST-1 LOOP
    FOR J IN I+1..pDATE_ROWS.LAST LOOP
      IF pDATE_ROWS(I)>pDATE_ROWS(J) THEN
        NULL;
      ELSE
        TEMP_DATE:=pDATE_ROWS(I);
        TEMP_COST:=pCOST_ROWS(I);
        TEMP_NOTE:=pDESCRIPTION_ROWS(I); 
        pDATE_ROWS(I):=pDATE_ROWS(J);
        pCOST_ROWS(I):=pCOST_ROWS(J);
        pDESCRIPTION_ROWS(I):=pDESCRIPTION_ROWS(J); 
        pDATE_ROWS(J):=TEMP_DATE;
        pCOST_ROWS(J):=TEMP_COST;
        pDESCRIPTION_ROWS(J):=TEMP_NOTE; 
      END IF;
    END LOOP;
  END LOOP;
END;
/
