CREATE OR REPLACE PROCEDURE SQL_GET_ABONENT_BILLS(
  pUSER_ID IN INTEGER,
  pBALANCE_DATE IN DATE,
  pDATESTAMP_ROWS OUT DBMS_SQL.DATE_TABLE, 
  pBILL_SUM_ROWS OUT DBMS_SQL.NUMBER_TABLE
  ) IS
BEGIN
  pDATESTAMP_ROWS(1) := TRUNC(SYSDATE-2); 
  pBILL_SUM_ROWS(1) := 100; 
END;
/
