CREATE OR REPLACE FUNCTION CHECK_LONG_PLUS_BALANCE(
  pPHONE_NUMBER IN VARCHAR2,
  pYEAR_MONTH IN INTEGER
  ) RETURN NUMBER IS
-- Version=2  
  vDATE_START DATE;
  vDATE_END DATE;  
  vCONTRACT_ID INTEGER;  
  CURSOR C IS
    SELECT C1.CONTRACT_ID,
           C1.CONTRACT_DATE,
           NVL(CC1.CONTRACT_CANCEL_DATE, SYSDATE) CONTRACT_CANCEL_DATE
      FROM CONTRACTS C1,
           CONTRACT_CANCELS CC1  
      WHERE C1.PHONE_NUMBER_FEDERAL=pPHONE_NUMBER
        AND C1.CONTRACT_DATE<=LAST_DAY(TO_DATE(pYEAR_MONTH||'01', 'YYYYMMDD'))
        AND C1.CONTRACT_ID=CC1.CONTRACT_ID(+)
      ORDER BY C1.CONTRACT_DATE DESC;  
  CURSOR H(pEND_DATE IN DATE) IS
    SELECT PH.BEGIN_DATE
      FROM DB_LOADER_ACCOUNT_PHONE_HISTS PH
      WHERE PH.PHONE_NUMBER=pPHONE_NUMBER
        AND PH.END_DATE-1>PH.BEGIN_DATE
        AND PH.PHONE_IS_ACTIVE=1
        AND PH.BEGIN_DATE<=pEND_DATE
        AND PH.END_DATE>=LAST_DAY(TO_DATE(pYEAR_MONTH||'01', 'YYYYMMDD'))+1;
  vDUMMY_C C%ROWTYPE;
  vDUMMY_H H%ROWTYPE;
  vTAIL NUMBER(13, 2); 
  vBALANCE NUMBER(13, 2);    
  vCUR_BILL_SUM NUMBER(13, 2);    
  vFLAG NUMBER(1);  
  vCOUNT_DAYS INTEGER;
BEGIN
  OPEN C;
  FETCH C INTO vDUMMY_C;
  IF C%FOUND THEN 
    vCONTRACT_ID:=vDUMMY_C.CONTRACT_ID;
    vDATE_START:=vDUMMY_C.CONTRACT_DATE;
    vDATE_END:=vDUMMY_C.CONTRACT_CANCEL_DATE;
  ELSE
    vCONTRACT_ID:=NULL;
    vDATE_START:=TO_DATE('01.01.2010', 'DD.MM.YYYY');
    vDATE_END:=SYSDATE;
  END IF;
  vFLAG:=0;
  vBALANCE:=GET_ABONENT_BALANCE(pPHONE_NUMBER, LAST_DAY(TO_DATE(pYEAR_MONTH||'01', 'YYYYMMDD')));
  IF vBALANCE>=0 THEN 
    vFLAG:=1;
  ELSE 
    OPEN H(vDATE_END);
    FETCH H INTO vDUMMY_H;
    IF H%FOUND THEN
      vFLAG:=1;
    ELSE
      vFLAG:=0;
    END IF;
    CLOSE H;
  end if;
/*  IF vBALANCE>=0 THEN 
    vFLAG:=1;
  ELSE  
    FOR rec1 IN(
      SELECT B1.YEAR_MONTH
        FROM DB_LOADER_BILLS B1
        WHERE B1.YEAR_MONTH>pYEAR_MONTH
          AND B1.YEAR_MONTH<=TO_NUMBER(TO_CHAR(vDATE_END, 'YYYYMM'))
        GROUP BY B1.YEAR_MONTH
        ORDER BY B1.YEAR_MONTH ASC )
    LOOP
      vCOUNT_DAYS:=TO_CHAR(LAST_DAY(TO_DATE(pYEAR_MONTH||'01', 'YYYYMMDD')), 'DD');     
      vCUR_BILL_SUM:=0;
      FOR rec2 IN(
        SELECT V1.BILL_SUM
          FROM V_BILL_FOR_CLIENT V1
          WHERE V1.PHONE_NUMBER=pPHONE_NUMBER
            AND V1.YEAR_MONTH=rec1.YEAR_MONTH)
      LOOP
        vCUR_BILL_SUM:=vCUR_BILL_SUM+rec2.BILL_SUM;
      END LOOP;
      FOR rec3 IN(
        SELECT P1.PAYMENT_SUM,
               P1.PAYMENT_DATE
          FROM DB_LOADER_PAYMENTS P1
          WHERE P1.PHONE_NUMBER=pPHONE_NUMBER
            AND P1.PAYMENT_DATE>=TO_DATE(rec1.YEAR_MONTH||'01', 'YYYYMMDD')
            AND P1.PAYMENT_DATE<=LAST_DAY(TO_DATE(rec1.YEAR_MONTH||'01', 'YYYYMMDD')))
      LOOP
        vBALANCE:=vBALANCE+rec3.PAYMENT_SUM;
        IF vBALANCE+vCUR_BILL_SUM*TO_NUMBER(TO_CHAR(rec3.PAYMENT_DATE, 'DD'))/vCOUNT_DAYS>=0 THEN
          vFLAG:=1;
          RETURN vFLAG; 
        END IF;
      END LOOP; 
    END LOOP;  
  END IF;*/
  RETURN vFLAG;         
END;  