CREATE OR REPLACE FUNCTION FIND_LOGIN_BY_ACCOUNT_ID(
  pACCOUNT_ID IN number
  ) RETURN VARCHAR2 IS
  RES ACCOUNTS.LOGIN%TYPE;
--#Version=1
BEGIN
  SELECT LOGIN
    INTO RES
    FROM ACCOUNTS
    WHERE ACCOUNT_ID=pACCOUNT_ID;
  RETURN RES;
EXCEPTION WHEN NO_DATA_FOUND THEN
  RAISE_APPLICATION_ERROR(-20500, 'LOGIN NOT FOUND');
END;
