CREATE OR REPLACE FUNCTION GET_DILER_COST_FROM_DETAIL(
  pPHONE_NUMBER IN VARCHAR2,
  pYEAR_MONTH IN NUMBER
  ) RETURN NUMBER IS
  INFA CLOB;
  LENG INTEGER;
  BEGINING INTEGER; 
  ENDING INTEGER;
  I INTEGER; 
  LINE VARCHAR2(2000);
  BE INTEGER;
  EN INTEGER;
  pINFO DBMS_SQL.VARCHAR2_TABLE;
  ITOG NUMBER(15, 4);
  CURSOR C(pTYPE_CALL IN VARCHAR2) IS
    SELECT TYPE_CALL_FOR_DILER.TYPE_DILER
    FROM TYPE_CALL_FOR_DILER
    WHERE TYPE_CALL_FOR_DILER.TYPE_CALL=pTYPE_CALL;
  vDUMMY C%ROWTYPE;
  pCOST VARCHAR2(30 CHAR);
  vNEW_COST NUMBER(15,4);
BEGIN
  INFA:=LOADER3_PCKG.GET_PHONE_DETAIL(TRUNC(pYEAR_MONTH/100),(pYEAR_MONTH-TRUNC(pYEAR_MONTH,-2)),pPHONE_NUMBER);
  LENG:=DBMS_LOB.GETLENGTH(INFA);
  pINFO.delete;
  ITOG:=0;
  IF LENG>0 THEN
    ENDING:=1;
    I:=0;
    --DBMS_LOB.INSTR(INFA,CHR(10),1,1);
    WHILE (DBMS_LOB.INSTR(INFA,CHR(10),ENDING+1,1)<>0) --AND (I<8)
    LOOP
      BEGINING:=ENDING;
      I:=I+1;
      ENDING:=DBMS_LOB.INSTR(INFA,CHR(10),BEGINING+1,1);
      LINE:=DBMS_LOB.SUBSTR(INFA,ENDING-BEGINING-1,BEGINING);
      BE:=INSTR(LINE, CHR(9), 1, 10);
      EN:=INSTR(LINE,CHR(9),BE+1);   
      pINFO(I):=SUBSTR(LINE,BE+1,EN-BE-1);
      OPEN C(pINFO(I));
      FETCH C INTO vDUMMY;
      IF C%FOUND THEN
        IF vDUMMY.TYPE_DILER = 1 THEN          
          BE:=INSTR(LINE, CHR(9), 1, 7);
          EN:=INSTR(LINE,CHR(9),BE+1);
          pCOST:=SUBSTR(LINE,BE+1,EN-BE-1);
          vNEW_COST:=0;
          BEGIN          
            vNEW_COST:=TO_NUMBER(pCOST); 
          EXCEPTION WHEN OTHERS THEN
            vNEW_COST:=0;
          END;    
          ITOG:=ITOG + vNEW_COST;
        END IF;
      ELSE
        INSERT INTO TYPE_CALL_FOR_DILER(TYPE_CALL)
          VALUES(pINFO(I));
        COMMIT;  
      END IF;
      CLOSE C;
    END LOOP;
  END IF;
  RETURN ITOG;
END;
/
