CREATE OR REPLACE PROCEDURE GET_GSM_ABONENT_BALANCE(
  PHONE_NUMBER IN VARCHAR2,
  SECRET_KEY IN VARCHAR2
  ) IS
--#Version=1
--
vBALANCE_VALUE NUMBER;
BEGIN
  IF SECRET_KEY = '12_GSM' THEN
    OWA_UTIL.MIME_HEADER('text/plain', TRUE);
    BEGIN
      SQL_GET_ABONENT_BALANCE(PHONE_NUMBER, vBALANCE_VALUE);
      HTP.PRINT('OK');
      HTP.PRINT(REPLACE(ROUND(vBALANCE_VALUE, 2), ',', '.'));
    EXCEPTION WHEN OTHERS THEN
      HTP.PRINT('ERROR');
      HTP.PRINT(SQLERRM);
    END;
  END IF;
END;
/
