CREATE OR REPLACE PROCEDURE RESTORE_PASSWORD(
  x_username in varchar2 DEFAULT NULL,
  captcha in varchar2 DEFAULT NULL,
  ID IN VARCHAR2 DEFAULT NULL,
  TEST IN VARCHAR2 DEFAULT NULL
  ) IS
--#Version=1
  pDATE_ROWS DBMS_SQL.DATE_TABLE;
  pCOST_ROWS DBMS_SQL.NUMBER_TABLE;
  pDESCRIPTION_ROWS DBMS_SQL.VARCHAR2_TABLE;
  PRIXOD NUMBER;
  RASXOD NUMBER;
BEGIN
  PRIXOD:=0;
  RASXOD:=0;
  S_HEADER;
  S_TOP;
--  S_LEFT;
  IF x_username IS NULL THEN
    S_RESTORE_PASSWORD_FORM;
  ELSE
    S_RESTORE_PASSWORD_FORM(x_username, captcha , ID, TEST);
  END IF;
  S_END;
END;
/
