CREATE OR REPLACE PROCEDURE LONTANA_WWW.SQL_GET_ABONENT_DETAIL_TEXT_B(
  PHONE_NUMBER IN VARCHAR2,
  pYEAR_MONTH IN NUMBER,
  pDATE OUT DBMS_SQL.VARCHAR2_TABLE,
  pTIME OUT DBMS_SQL.VARCHAR2_TABLE,
  pSOBESEDNIK OUT DBMS_SQL.VARCHAR2_TABLE,
  pTYPE OUT DBMS_SQL.VARCHAR2_TABLE,
  pLENGTH OUT DBMS_SQL.VARCHAR2_TABLE,
  pCOST OUT DBMS_SQL.NUMBER_TABLE,
  pROUMING OUT DBMS_SQL.VARCHAR2_TABLE, 
  pZONA_ROUMINGA OUT DBMS_SQL.VARCHAR2_TABLE, 
  pINFO OUT DBMS_SQL.VARCHAR2_TABLE 
  ) IS
  LENG INTEGER;
  BEGINING INTEGER; 
  ENDING INTEGER;
  I INTEGER; 
  LINE VARCHAR2(2000);
  BE INTEGER;
  EN INTEGER;
  TYP VARCHAR2(100);
  LE VARCHAR2(100);
  LEN NUMBER;
  pYear varchar2(4);
  pmonth varchar2(2);
  
BEGIN
 pYear:=substr(to_char(pYEAR_MONTH), 1,4);
 pMonth:=substr(to_char(pYEAR_MONTH), 5,2);

 EXECUTE IMMEDIATE 'SELECT  
to_char(START_TIME,''dd.mm.yyyy'') ,
to_char(START_TIME,''hh:mi:ss'') ,
CALLING_NO,
SERVICETYPE,
DUR,
CALL_COST,
ISROAMING,
ROAMINGZONE,
AT_FT_DE
 from  CALL_'||pMonth||'_'||pYear||' WHERE SUBSCR_NO='''||PHONE_NUMBER||''' ORDER BY START_TIME' bulk collect into   pDATE,
  pTIME,
  pSOBESEDNIK,
  pTYPE,
  pLENGTH,
  pCOST,
  pROUMING, 
  pZONA_ROUMINGA, 
  pINFO;
END;
/
