CREATE OR REPLACE PROCEDURE SQL_GET_TURNED_SERVICES(
  pUSER_ID IN INTEGER,
  pNAME_OPT_ROWS OUT DBMS_SQL.VARCHAR2_TABLE,
  pDATE_ROWS OUT DBMS_SQL.DATE_TABLE 
--  pMONTHLY_COST_ROWS OUT DBMS_SQL.NUMBER_TABLE 
  ) IS
--#Version=1  
BEGIN
LONTANA.WWW_GET_TURNED_SERVICES(
  pUSER_ID,
  pNAME_OPT_ROWS,
  pDATE_ROWS
--  pMONTHLY_COST_ROWS
  );
END;  