CREATE OR REPLACE FUNCTION SQL_GET_USER_ID(
  pPHONE_NUMBER IN VARCHAR2,
  pPASSWORD IN VARCHAR2
  ) RETURN INTEGER IS
-- Тестовая версия
BEGIN
  RETURN LONTANA.WWW_GET_USER_ID(pPHONE_NUMBER,pPASSWORD);   
END;
/