CREATE OR REPLACE PROCEDURE SQL_GET_ABONENT_DETAIL_MONTH(
  pUSER_ID IN INTEGER,
  pDETAIL_DATE IN DATE,
  pYEAR_MONTH OUT DBMS_SQL.NUMBER_TABLE, 
  pSUMMA OUT DBMS_SQL.NUMBER_TABLE 
  ) IS
BEGIN
  lONTANA.WWW_GET_ABONENT_DETAIL_MONTH(
    pUSER_ID,
    pDETAIL_DATE,
    pYEAR_MONTH, 
    pSUMMA
    );
END;
/
