CREATE OR REPLACE PROCEDURE SQL_GET_USER_INFO(
  pUSER_ID IN INTEGER,
  pPHONE_NUMBER OUT VARCHAR2,
  pCELL_PLAN_NAME OUT VARCHAR2,
  pUSER_NAME OUT VARCHAR2,
  pBALANCE OUT NUMBER,
  pDISCONNECT_LIMIT OUT NUMBER,
  pPHONE_STATUS_CODE OUT INTEGER, -- 0 - Заблокирован, 1-Активный
  pACTUAL_DATE OUT DATE -- Дата и время актуальности
  ) IS
BEGIN
  LONTANA.WWW_GET_USER_INFO(
    pUSER_ID,
    pPHONE_NUMBER,
    pCELL_PLAN_NAME,
    pUSER_NAME,
    pBALANCE,
    pDISCONNECT_LIMIT,
    pPHONE_STATUS_CODE,
    pACTUAL_DATE
    );
END;
/
