CREATE OR REPLACE TYPE "TARIFFS_ATTRS_LIST" AS OBJECT
(
 TARIFF_ID        INTEGER,
 TARIFF_CODE      VARCHAR2(30 CHAR),
 OPERATOR_ID      INTEGER,
 FILIAL_ID        INTEGER,
 TARIFF_NAME      VARCHAR2(100 CHAR),
 ATTRIBUTES_ID    INTEGER,
 ATTRIBUTES_NAME  VARCHAR2(150 CHAR), 
 ATTRIBUTES_VALUE VARCHAR2(50 CHAR),
 ATTRIBUTES_TYPE  VARCHAR2(18 CHAR)
)
/