GRANT SELECT ON CONTRACTS TO LONTANA_ROLE_RO;

GRANT SELECT ON CONTRACT_CANCELS TO LONTANA_ROLE_RO;

GRANT SELECT ON ABONENTS TO LONTANA_ROLE_RO;

GRANT SELECT ON OPERATORS TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_ACCOUNT_PHONES TO LONTANA_ROLE_RO;

GRANT EXECUTE ON PROG_SELECT_CONTRACT TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_ABONENT_BALANCE TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_PHONE_STAT TO LONTANA_ROLE_RO;

GRANT SELECT ON TARIFFS TO LONTANA_ROLE_RO;

GRANT SELECT ON V_CONTRACTS TO LONTANA_ROLE_RO; 

GRANT SELECT ON AUTO_BLOCKED_PHONE TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_ACCOUNT_PHONE_HISTS TO LONTANA_ROLE_RO; 

GRANT SELECT ON RIGHTS_TYPE_ACCOUNT_ALLOW TO LONTANA_ROLE_RO;

GRANT SELECT ON V_ACCOUNT_STAT_BY_STATUS_NOW TO LONTANA_ROLE_RO;

GRANT SELECT ON ABONENT_BALANCE_MESSAGES TO LONTANA_ROLE_RO;

GRANT SELECT ON ABONENT_BALANCE_ROWS TO LONTANA_ROLE_RO;

GRANT SELECT ON ABONENTS TO LONTANA_ROLE_RO;

GRANT SELECT ON ACCOUNT_LOAD_LOGS TO LONTANA_ROLE_RO;

GRANT SELECT ON ACCOUNT_LOAD_TYPES TO LONTANA_ROLE_RO;

GRANT SELECT ON ACCOUNT_LOGON_PAUSED TO LONTANA_ROLE_RO;

GRANT EXECUTE ON ACCOUNT_LOGON_PAUSE_PCKG TO LONTANA_ROLE_RO;

GRANT SELECT ON ACCOUNTS TO LONTANA_ROLE_RO;

GRANT EXECUTE ON ADD_DB_LOADER_PHONE_STAT_UPD TO LONTANA_ROLE_RO;

GRANT EXECUTE ON ADD_DEPOSITE_OPER TO LONTANA_ROLE_RO;

GRANT EXECUTE ON ADD_MSISDN_REFRESH_UPD TO LONTANA_ROLE_RO;

GRANT EXECUTE ON ALTER_USER_ENCRYPT_PWD TO LONTANA_ROLE_RO;

GRANT SELECT ON AUTO_BLOCKED_PHONE TO LONTANA_ROLE_RO;

GRANT SELECT ON AUTO_BLOCKED_PHONE_NO_CONTRACT TO LONTANA_ROLE_RO;

GRANT EXECUTE ON AUTO_NUMERATION2 TO LONTANA_ROLE_RO;

GRANT SELECT ON AUTO_NUMERATION2_FREE_VALUES TO LONTANA_ROLE_RO;

GRANT SELECT ON AUTO_NUMERATION2_SEQUENCES TO LONTANA_ROLE_RO;

GRANT SELECT ON AUTO_UNBLOCKED_PHONE TO LONTANA_ROLE_RO;

GRANT SELECT ON BALANCE_CHANGE TO LONTANA_ROLE_RO;

GRANT SELECT ON BALANCE_COMPARE_RESULT TO LONTANA_ROLE_RO;

GRANT EXECUTE ON BEELINE_BS_ZONE_ADD_CODE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON BEELINE_BS_ZONE_CLEAR TO LONTANA_ROLE_RO;

GRANT SELECT ON BEELINE_BS_ZONES TO LONTANA_ROLE_RO;

GRANT DELETE, INSERT, SELECT, UPDATE ON BILL_FINANCE_FOR_CLIENTS_SAVED TO LONTANA_ROLE_RO;

GRANT EXECUTE ON BLOCK_CLIENT_WTH_0_BAL TO LONTANA_ROLE_RO;

GRANT EXECUTE ON BLOCK_CLIENT_WTH_0_BAL2 TO LONTANA_ROLE_RO;

GRANT SELECT ON BLOCK_SEND_SMS TO LONTANA_ROLE_RO;

GRANT EXECUTE ON CALC_BALANCE_ROWS TO LONTANA_ROLE_RO;

GRANT EXECUTE ON CALC_BALANCE_ROWS2 TO LONTANA_ROLE_RO;

GRANT EXECUTE ON CALC_KOMISSIYA_OPTIONS TO LONTANA_ROLE_RO;

GRANT EXECUTE ON CALC2 TO LONTANA_ROLE_RO;

GRANT EXECUTE ON CALC3 TO LONTANA_ROLE_RO;

GRANT SELECT ON CALL_BACK_LOG TO LONTANA_ROLE_RO;

GRANT SELECT ON CALL_BACK_REQUEST TO LONTANA_ROLE_RO;

GRANT SELECT ON CALL_01_2013 TO LONTANA_ROLE_RO;

GRANT SELECT ON CALL_09_2012 TO LONTANA_ROLE_RO;

GRANT SELECT ON CALL_10_2012 TO LONTANA_ROLE_RO;

GRANT SELECT ON CALL_11_2012 TO LONTANA_ROLE_RO;

GRANT SELECT ON CALL_12_2012 TO LONTANA_ROLE_RO;

GRANT EXECUTE ON CHECK_BILLS TO LONTANA_ROLE_RO;

GRANT EXECUTE ON CHECK_CONTRACTS_BY_YEAR_MONTH TO LONTANA_ROLE_RO;

GRANT EXECUTE ON CHECK_CREATE_USER TO LONTANA_ROLE_RO;

GRANT SELECT ON CHECKED_TYPES TO LONTANA_ROLE_RO;

GRANT EXECUTE ON CHECK_LONG_PLUS_BALANCE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON CHECK_PHONE_CREDIT TO LONTANA_ROLE_RO;

GRANT SELECT ON CONSTANTS TO LONTANA_ROLE_RO;

GRANT SELECT ON CONTRACT_BALANCES TO LONTANA_ROLE_RO;

GRANT SELECT ON CONTRACT_CANCELS TO LONTANA_ROLE_RO;

GRANT SELECT ON CONTRACT_CANCEL_TYPES TO LONTANA_ROLE_RO;

GRANT SELECT ON CONTRACT_CHANGES TO LONTANA_ROLE_RO;

GRANT SELECT ON CONTRACT_DEPOSITE_OPER TO LONTANA_ROLE_RO;

GRANT SELECT ON CONTRACT_DEPOSITES TO LONTANA_ROLE_RO;

GRANT SELECT ON CONTRACTS TO LONTANA_ROLE_RO;

GRANT SELECT ON COUNTRIES TO LONTANA_ROLE_RO;

GRANT SELECT ON CREDIT_NOTICE_SEND TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_ACCOUNT_PHONE_HISTS TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_ACCOUNT_PHONE_OPTS TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_ACCOUNT_PHONES TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_BILLS TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_BILLS_ADD TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_FULL_BILL_ABON_PER TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_FULL_BILL_MG_ROUMING TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_FULL_BILL_MN_ROUMING TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_FULL_FINANCE_BILL TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_PAYMENTS TO LONTANA_ROLE_RO;

GRANT EXECUTE ON DB_LOADER_PCKG TO LONTANA_ROLE_RO;

GRANT EXECUTE ON DB_LOADER_PCKG_VARS TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_PHONE_STAT TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_PHONE_STATHB TO LONTANA_ROLE_RO;

GRANT EXECUTE ON DB_LOADER_PHONE_STAT_UPD TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_PHONE_STAT_UPDATE TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_REPORT_DATA TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_SERVICE_TYPES TO LONTANA_ROLE_RO;

GRANT SELECT ON DB_LOADER_TEMPORAR_DO_NOT_LOAD TO LONTANA_ROLE_RO;

GRANT EXECUTE ON DELETE_FIX_MONTH TO LONTANA_ROLE_RO;

GRANT SELECT ON DETAILS_INFO TO LONTANA_ROLE_RO;

GRANT SELECT ON DETAIL_STATS TO LONTANA_ROLE_RO;

GRANT SELECT ON DETAIL_TYPES TO LONTANA_ROLE_RO;

GRANT SELECT ON DOCUM_TYPES TO LONTANA_ROLE_RO;

GRANT SELECT ON FIELD_DETAILS TO LONTANA_ROLE_RO;

GRANT SELECT ON FIELD_DETAIL_TYPES TO LONTANA_ROLE_RO;

GRANT SELECT ON FILIALS TO LONTANA_ROLE_RO;

GRANT EXECUTE ON FIND_ACCOUNT_ID_BY_LOGIN TO LONTANA_ROLE_RO;

GRANT EXECUTE ON FIND_LOGIN_BY_ACCOUNT_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON FIND_LOGIN_BY_ACCOUNT_ID_LPS TO LONTANA_ROLE_RO;

GRANT SELECT ON FORWARDING_PHONE_NUMBER TO LONTANA_ROLE_RO;

GRANT SELECT ON FRAUD_BLOCKED_PHONE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON FREE_CONTRACT_NUMBER TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_ABONENT_BALANCE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_ACCOUNT_ID_BY_PHONE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_ACCOUNT_NUMBER_BY_PHONE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_CREDIT_INFO TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_FIX_YEAR_MONTH_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_ID_LAST_CONTRACT_BY_PHONE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_ID_LAST_TARIFF_BY_CONTRACT TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_MAIL_PHONE_FOR_BL_SAVE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_MAIL_PHONE_FOR_UNBL_SAVE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_MAIL_PHONE_VIOLATIONS TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_MAIL_TARIFF_VIOLATIONS TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_NEXT_CONTRACT_NUMBER TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_PHONE_DETAIL_3 TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_PHONE_TARIFF_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_TARIFF_OPTION_COST TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_TARIFF_OPTION_PERERASCHET TO LONTANA_ROLE_RO;

GRANT EXECUTE ON GET_VOLUME_SERVICE TO LONTANA_ROLE_RO;

GRANT SELECT ON HACKERS TO LONTANA_ROLE_RO;

GRANT SELECT ON HOT_BILLING TO LONTANA_ROLE_RO;

GRANT SELECT ON HOT_BILLING_FILES TO LONTANA_ROLE_RO;

GRANT EXECUTE ON HOT_BILLING_PCKG TO LONTANA_ROLE_RO;

GRANT SELECT ON HOT_BILLING_TEMP_CALL TO LONTANA_ROLE_RO;

GRANT SELECT ON HOT_BILLING_USM_PHONE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON INSERT_FIX_BALANCE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON LOADER_CALL_PCKG TO LONTANA_ROLE_RO;

GRANT SELECT ON LOADER_SETTINGS TO LONTANA_ROLE_RO;

GRANT EXECUTE ON LOADER2_PCKG TO LONTANA_ROLE_RO;

GRANT EXECUTE ON LOADER3_PCKG TO LONTANA_ROLE_RO;

GRANT EXECUTE ON LOADER5_PCKG TO LONTANA_ROLE_RO;

GRANT SELECT ON MESSAGE_TEXTS TO LONTANA_ROLE_RO;

GRANT SELECT ON MN_UNLIM_SERVICES TO LONTANA_ROLE_RO;

GRANT SELECT ON MN_UNLIM_VOLUME TO LONTANA_ROLE_RO;

GRANT SELECT ON MN_UNLIM_VOLUMEHB TO LONTANA_ROLE_RO;

GRANT EXECUTE ON MS_CONSTANTS TO LONTANA_ROLE_RO;

GRANT SELECT ON MSISDN_REFRESH TO LONTANA_ROLE_RO;

GRANT EXECUTE ON MSISDN_REFRESH_UPD TO LONTANA_ROLE_RO;

GRANT EXECUTE ON MS_PARAMS TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_ABONENT_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_ACCOUNT_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_ACCOUNT_LOAD_LOG_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_CONSTANT_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_CONTRACT_BALANCE_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_CONTRACT_CANCEL_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_CONTRACT_CANCEL_TYPE_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_CONTRACT_CHANGE_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_CONTRACT_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_COUNTRY_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_DB_LOADER_ACC_PH_HIST_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_DEPOSITE_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_DEPOSITE_OPER_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_DETAIL_INFO_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_DETAIL_STATS_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_DETAIL_TYPE_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_DOCUM_TYPE_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_FIELD_DETAILS_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_FIELD_DETAIL_TYPES_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_FILIAL_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_FIX_YEAR_MONTH_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_FORWARDING_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_OPERATOR_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_PHONE_BALANCE_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_PHONE_BLOCK_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_RECEIVED_PAYMENT_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_RECORD_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_REGION_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_REPORT_TYPE_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_SERVICE_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_SMS_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_SUBSCRIBE_PAY TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_TARIFF_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_TARIFF_OPTION_COST_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_TARIFF_OPTION_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_TARIFF_OPTION_NEW_COST_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON NEW_USER_NAME_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON OPERATORS TO LONTANA_ROLE_RO;

GRANT SELECT ON PARAMS TO LONTANA_ROLE_RO;

GRANT SELECT ON PHONE_BALANCES TO LONTANA_ROLE_RO;

GRANT SELECT ON PHONE_BLOCKS TO LONTANA_ROLE_RO;

GRANT SELECT ON PHONE_NUMBER_ATTRIBUTES TO LONTANA_ROLE_RO;

GRANT SELECT ON PHONE_NUMBER_TYPES TO LONTANA_ROLE_RO;

GRANT EXECUTE ON PROG_SELECT_CONTRACT TO LONTANA_ROLE_RO;

GRANT EXECUTE ON READ_FIELD_FROM_DETAILS TO LONTANA_ROLE_RO;

GRANT EXECUTE ON READ_LOG TO LONTANA_ROLE_RO;

GRANT EXECUTE ON RECALC_CHARGE_COST TO LONTANA_ROLE_RO;

GRANT SELECT ON RECEIVED_PAYMENTS TO LONTANA_ROLE_RO;

GRANT SELECT ON REGIONS TO LONTANA_ROLE_RO;

GRANT SELECT ON REPORT_MAIL_RECIPIENTS TO LONTANA_ROLE_RO;

GRANT SELECT ON REPORT_TYPES TO LONTANA_ROLE_RO;

GRANT SELECT ON RIGHTS_TYPE_ACCOUNT_ALLOW TO LONTANA_ROLE_RO;

GRANT EXECUTE ON ROBOT_IN_BLOCK TO LONTANA_ROLE_RO;

GRANT EXECUTE ON SAVE_CONTRACT_PAYMENT TO LONTANA_ROLE_RO;

GRANT EXECUTE ON SAVE_DETAILJ TO LONTANA_ROLE_RO;

GRANT EXECUTE ON SEND_ABONENT_BALANCE_MESSAGE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON SEND_MAIL TO LONTANA_ROLE_RO;

GRANT EXECUTE ON SEND_MAIL_OTCHET_PHONE_VIOLS TO LONTANA_ROLE_RO;

GRANT EXECUTE ON SEND_MAIL_OTCHETS TO LONTANA_ROLE_RO;

GRANT EXECUTE ON SEND_MAIL_OTCHET_TAR_VIOLS TO LONTANA_ROLE_RO;

GRANT SELECT ON SEND_MAIL_PARAMETRES TO LONTANA_ROLE_RO;

GRANT EXECUTE ON SEND_MAIL_PHONE_FOR_BL_SAVE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON SEND_MAIL_PHONE_FOR_UNBL_SAVE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON SEND_SMS TO LONTANA_ROLE_RO;

GRANT EXECUTE ON SEND_SMS_CREDIT_NOTICE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON SEND_SMS_NOTICE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON SEND_SMS_NOTICE_END_MONTH TO LONTANA_ROLE_RO;

GRANT SELECT ON SEND_SMS_NOTICE_END_MONTH_LOG TO LONTANA_ROLE_RO;

GRANT SELECT ON SEND_SMS_NOTICE_MN_UNLIM_LOG TO LONTANA_ROLE_RO;

GRANT SELECT ON SEND_SMS_QUERY TO LONTANA_ROLE_RO;

GRANT SELECT ON SERVICES TO LONTANA_ROLE_RO;

GRANT SELECT ON SERVICE_TYPE TO LONTANA_ROLE_RO;

GRANT SELECT ON SERVICE_URL TO LONTANA_ROLE_RO;

GRANT SELECT ON SERVICE_VOLUME TO LONTANA_ROLE_RO;

GRANT EXECUTE ON SET_HAND_BLOCK_END_DATE TO LONTANA_ROLE_RO;

GRANT SELECT ON SMS_SEND_PARAMETRS TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_ABONENT_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_ACCOUNT_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_ACCOUNT_LOAD_LOG_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_CONSTANT_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_CONTRACT_BALANCE_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_CONTRACT_CANCEL_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_CONTRACT_CANCEL_TYPE_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_CONTRACT_CHANGE_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_CONTRACT_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_COUNTRY_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_DB_LOADER_ACC_PH_HIST_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_DEPOSITE_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_DEPOSITE_OPER_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_DETAIL_INFO_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_DETAIL_STATS_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_DETAIL_TYPE_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_DOCUM_TYPE_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_FIELD_DETAILS_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_FIELD_DETAIL_TYPES_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_FILIAL_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_FIX_YEAR_MONTH_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_FORWARDING_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_OPERATOR_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_PHONE_BALANCE_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_PHONE_BLOCK_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_RECEIVED_PAYMENT_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_RECORD_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_REGION_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_REPORT_TYPE_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_SERVICE_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_SMS_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_TARIFF_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_TARIFF_OPTION_COST_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_TARIFF_OPTION_ID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_TARIFF_OPTION_NEW_COSTID TO LONTANA_ROLE_RO;

GRANT SELECT ON S_NEW_USER_NAME_ID TO LONTANA_ROLE_RO;

GRANT EXECUTE ON SOAP_API TO LONTANA_ROLE_RO;

GRANT SELECT ON TARIFF_OPTION_COSTS TO LONTANA_ROLE_RO;

GRANT SELECT ON TARIFF_OPTION_NEW_COST TO LONTANA_ROLE_RO;

GRANT SELECT ON TARIFF_OPTIONS TO LONTANA_ROLE_RO;

GRANT SELECT ON TARIFFS TO LONTANA_ROLE_RO;

GRANT SELECT ON TAR_LOG TO LONTANA_ROLE_RO;

GRANT SELECT ON TEMP_CALL TO LONTANA_ROLE_RO;

GRANT SELECT ON TEMP_VIEW1 TO LONTANA_ROLE_RO;

GRANT SELECT ON TEMP_VIEW2 TO LONTANA_ROLE_RO;

GRANT SELECT ON TEMP_1 TO LONTANA_ROLE_RO;

GRANT SELECT ON TEMP4 TO LONTANA_ROLE_RO;

GRANT SELECT ON TEMP6 TO LONTANA_ROLE_RO;

GRANT EXECUTE ON TRUNCATE_TC TO LONTANA_ROLE_RO;

GRANT EXECUTE ON UNBLOCK_CLIENT_WTH_PLUS_BAL TO LONTANA_ROLE_RO;

GRANT EXECUTE ON UNBLOCK_CLIENT_WTH_PLUS_BAL2 TO LONTANA_ROLE_RO;

GRANT EXECUTE ON UPDATE_TC TO LONTANA_ROLE_RO;

GRANT SELECT ON USER_NAMES TO LONTANA_ROLE_RO;

GRANT EXECUTE ON USER_NAMES_DELETE TO LONTANA_ROLE_RO;

GRANT EXECUTE ON USER_NAMES_INSERT TO LONTANA_ROLE_RO;

GRANT EXECUTE ON USER_NAMES_UPDATE TO LONTANA_ROLE_RO;

GRANT SELECT ON USSD_CURRENT TO LONTANA_ROLE_RO;

GRANT SELECT ON USSD_LEAFS TO LONTANA_ROLE_RO;

GRANT SELECT ON USSD_LOG TO LONTANA_ROLE_RO;

GRANT SELECT ON USSD_TREE TO LONTANA_ROLE_RO;

GRANT SELECT ON V_ABONENT_BALANCES TO LONTANA_ROLE_RO;

GRANT SELECT ON V_ABONENT_BALANCES_WITHOUTSORT TO LONTANA_ROLE_RO;

GRANT SELECT ON V_ABONENT_BALANCES_2 TO LONTANA_ROLE_RO;

GRANT SELECT ON V_ABON_PAYMENT_BY_PHONES TO LONTANA_ROLE_RO;

GRANT SELECT ON V_ABON_PAYMENT_BY_PHONES_YEAR TO LONTANA_ROLE_RO;

GRANT SELECT ON V_ABON_PAYMENT_BY_PHONES_YEAR2 TO LONTANA_ROLE_RO;

GRANT SELECT ON V_ACCOUNT_STAT_BY_STATUS_NOW TO LONTANA_ROLE_RO;

GRANT SELECT ON V_ACTIVE_CONTRACTS TO LONTANA_ROLE_RO;

GRANT SELECT ON V_ACTIVE_NUMBERS_OUT_CONTRACTS TO LONTANA_ROLE_RO;

GRANT SELECT ON V_ALL_NUMBERS_OUT_CONTRACTS TO LONTANA_ROLE_RO;

GRANT SELECT ON V_ALL_PHONE_BALANCES TO LONTANA_ROLE_RO;

GRANT SELECT ON V_BILL_ABON_PER_FOR_CLIENT TO LONTANA_ROLE_RO;

GRANT SELECT ON V_BILL_FINANCE_FOR_CLIENT_DET TO LONTANA_ROLE_RO;

GRANT SELECT ON V_BILL_FOR_CLIENT TO LONTANA_ROLE_RO;

GRANT SELECT ON V_BILL_FOR_CLIENT_DETAILS TO LONTANA_ROLE_RO;

GRANT SELECT ON V_BILL_FOR_DILER TO LONTANA_ROLE_RO;

GRANT SELECT ON V_BILL_FOR_DILER2 TO LONTANA_ROLE_RO;

GRANT SELECT ON V_BILL_FOR_KOMISSIYA TO LONTANA_ROLE_RO;

GRANT SELECT ON V_BILL_FULL_ABON_PER_INCORRECT TO LONTANA_ROLE_RO;

GRANT SELECT ON V_BILL_FULL_FINANCE_DEBUG TO LONTANA_ROLE_RO;

GRANT SELECT ON V_BILL_FULL_ROUMING_INCORRECT TO LONTANA_ROLE_RO;

GRANT SELECT ON V_BILL_ROUMING_FOR_CLIENT TO LONTANA_ROLE_RO;

GRANT SELECT ON V_CONTRACT_CHANGES TO LONTANA_ROLE_RO;

GRANT SELECT ON V_CONTRACT_PRINT TO LONTANA_ROLE_RO;

GRANT SELECT ON V_CONTRACTS TO LONTANA_ROLE_RO;

GRANT SELECT ON V_CONTRACTS_HAND_BLOCK TO LONTANA_ROLE_RO;

GRANT SELECT ON V_COUNT_CLIENT_BY_YEAR_MONTH TO LONTANA_ROLE_RO;

GRANT SELECT ON V_DISCOUNT_REPORT TO LONTANA_ROLE_RO;

GRANT SELECT ON V_FULL_BALANCE_BILLS TO LONTANA_ROLE_RO;

GRANT SELECT ON V_FULL_BALANCE_BILLS2 TO LONTANA_ROLE_RO;

GRANT SELECT ON V_FULL_BALANCE_PAYMENTS TO LONTANA_ROLE_RO;

GRANT SELECT ON V_HOT_BILLING_DELAY TO LONTANA_ROLE_RO;

GRANT SELECT ON V_PAYMENTS_WITHOUT_TRAFFIC TO LONTANA_ROLE_RO;

GRANT SELECT ON V_PHONE_NUMBER_CREDITS TO LONTANA_ROLE_RO;

GRANT SELECT ON V_PHONE_NUMBER_FOR_BLOCK_SAVE TO LONTANA_ROLE_RO;

GRANT SELECT ON V_PHONE_NUMBER_FOR_UNBL_SAVE TO LONTANA_ROLE_RO;

GRANT SELECT ON V_PHONE_NUMBERS_FOR_BLOCK TO LONTANA_ROLE_RO;

GRANT SELECT ON V_PHONE_NUMBERS_FOR_NOTICE_BAL TO LONTANA_ROLE_RO;

GRANT SELECT ON V_PHONE_NUMBERS_FOR_UNLOCK TO LONTANA_ROLE_RO;

GRANT SELECT ON V_PHONE_NUMBER_VIOLATIONS TO LONTANA_ROLE_RO;

GRANT SELECT ON V_PROFIT_BY_PHONES TO LONTANA_ROLE_RO;

GRANT SELECT ON V_PROFIT_BY_PHONES_YEAR TO LONTANA_ROLE_RO;

GRANT SELECT ON V_REPORT_PHONE_STAT TO LONTANA_ROLE_RO;

GRANT SELECT ON V_REPORT_SUMMARY_MINUTES TO LONTANA_ROLE_RO;

GRANT SELECT ON V_SITY_PHONE_NUMBER TO LONTANA_ROLE_RO;

GRANT SELECT ON V_TARIFF_VIOLATIONS TO LONTANA_ROLE_RO;

GRANT SELECT ON V_TURNED_SERVICES TO LONTANA_ROLE_RO;

GRANT SELECT ON V_USER_NAME_ADMINS TO LONTANA_ROLE_RO;

GRANT SELECT ON V_YEAR_MONTH_BALANCE TO LONTANA_ROLE_RO;