--
-- USSD_USER  (User) 
--
-- Овсянников Л.В.
-- Пользователь для отправки USSD запросов
CREATE USER USSD_USER
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 System Privilege for USSD_USER 
  GRANT CREATE SESSION TO USSD_USER;
  -- 1 Tablespace Quota for USSD_USER 
  ALTER USER USSD_USER QUOTA UNLIMITED ON USERS;

GRANT CREATE ANY SYNONYM TO USSD_USER;
GRANT CREATE SESSION TO USSD_USER;


grant execute on USSD_deliver to USSD_USER;
grant execute on USSD_notify to USSD_USER;
CREATE SYNONYM USSD_deliver FOR CORP_MOBILE.USSD_deliver;
CREATE SYNONYM USSD_notify FOR CORP_MOBILE.USSD_notify;


