CREATE OR REPLACE VIEW V_COUNT_CLIENT_BY_YEAR_MONTH AS
--Version=1
SELECT YEAR_MONTH,
       account_id,
       COUNT(*) COUNT_CLIENT
  FROM(SELECT *
         FROM DB_LOADER_PHONE_STAT
           WHERE (DB_LOADER_PHONE_STAT.ZEROCOST_OUTCOME_COUNT<>0
             OR DB_LOADER_PHONE_STAT.ZEROCOST_OUTCOME_MINUTES<>0
             OR DB_LOADER_PHONE_STAT.CALLS_COUNT<>0
             OR DB_LOADER_PHONE_STAT.CALLS_MINUTES<>0
             OR DB_LOADER_PHONE_STAT.CALLS_COST<>0
             OR DB_LOADER_PHONE_STAT.SMS_COUNT<>0
             OR DB_LOADER_PHONE_STAT.SMS_COST<>0
             OR DB_LOADER_PHONE_STAT.MMS_COUNT<>0
             OR DB_LOADER_PHONE_STAT.MMS_COST<>0
             OR DB_LOADER_PHONE_STAT.INTERNET_MB<>0
             OR DB_LOADER_PHONE_STAT.INTERNET_COST<>0))
  GROUP BY YEAR_MONTH, account_id
  ORDER BY YEAR_MONTH, account_id DESC