--DROP TABLE MF_SESSIONS;

-- Сессии (обновляется время последнего обращения при каждой загрузке страницы)
-- ToDo: Нужно периодически вычищать устаревшие сессии.
CREATE TABLE MF_SESSIONS (
  SESSION_ID number(12, 0),
  USER_ID NUMBER(8, 0),
  SESSION_KEY VARCHAR2(37 CHAR),
  START_DATE_TIME DATE,
  LAST_ACCESS_DATE_TIME DATE,
  EXPIRED_FLAG NUMBER(1, 0) DEFAULT 0 CONSTRAINT MF_CHK_SESSION_EXPIRED_FLAG CHECK (EXPIRED_FLAG IN (0, 1)),
  PREV_ACCESS_DATE_TIME DATE, -- дата-время предыдущего соединения
  CONSTRAINT MF_PK_SESSIONS PRIMARY KEY (SESSION_ID)
--  CONSTRAINT MF_FK_SESSIONS_USER_ID FOREIGN KEY (USER_ID) REFERENCES MF_USER_NAMES
  ) /*TABLESPACE MF_DATA*/;
  
CREATE UNIQUE INDEX MF_SESSIONS_SESSION_KEY
  ON MF_SESSIONS (SESSION_KEY) TABLESPACE MF_INDEX;

CREATE SEQUENCE MF_S_NEW_SESSION_ID CACHE 100;

CREATE INDEX I_MF_SESSIONS_USER_ID ON MF_SESSIONS (USER_ID) 
  COMPRESS 1 TABLESPACE MF_INDEX;
