CREATE OR REPLACE PROCEDURE OUT_BLOB(
  pBLOB_NAME IN VARCHAR2,
  pCACHE_EXPIRES IN BINARY_INTEGER) IS
--#Version=2
--
  vBLOB_CONTENT BLOB;
  vCONTENT_TYPE BLOB_DATA.CONTENT_TYPE%TYPE;
BEGIN
  SELECT BLOB_CONTENT, CONTENT_TYPE 
    INTO vBLOB_CONTENT, vCONTENT_TYPE
    FROM BLOB_DATA 
    WHERE BLOB_ID = pBLOB_NAME; 
  OWA_UTIL.MIME_HEADER(vCONTENT_TYPE, FALSE); 
  HTP.P('Content-Length: ' || DBMS_LOB.GETLENGTH(vBLOB_CONTENT)); 
  HTP.P('Expires: ' || to_char(sysdate + 1/24, 'FMDy, DD Mon YYYY HH24:MI:SS', 'NLS_DATE_LANGUAGE = AMERICAN') || ' GMT'); 
  OWA_UTIL.HTTP_HEADER_CLOSE;
-- Initiate Direct BLOB download
  WPG_DOCLOAD.DOWNLOAD_FILE(vBLOB_CONTENT);
  IF G_STATE.STATIC_CACHE_PERIOD > 0 THEN
    OWA_CACHE.SET_EXPIRES(G_STATE.STATIC_CACHE_PERIOD, owa_cache.system_level);
  END IF;
END;
 
/
