CREATE OR REPLACE PROCEDURE SEND_GSM_BALANCE_SMS(
  PHONE_NUMBER IN VARCHAR2,
  SECRET_KEY IN VARCHAR2
  ) IS
--#Version=1
--
vBALANCE_VALUE NUMBER;
vSEND_RESULT VARCHAR2(500 CHAR);
sent_before number;
BEGIN
  IF SECRET_KEY = '12_GSM' THEN
    OWA_UTIL.MIME_HEADER('text/plain', TRUE);
    BEGIN
      SEND_ABONENT_BALANCE_MESSAGE(PHONE_NUMBER, null, vSEND_RESULT, sent_before);
      IF vSEND_RESULT IS NULL THEN
        HTP.PRINT('OK');
      ELSE
        HTP.PRINT('ERROR');
        HTP.PRINT(vSEND_RESULT);
      END IF;
    EXCEPTION WHEN OTHERS THEN
      HTP.PRINT('ERROR');
      HTP.PRINT(SQLERRM);
    END;
  END IF;
END;
/
