CREATE OR REPLACE FUNCTION SQL_GET_USER_BALANCE(
  pUSER_ID IN INTEGER
  ) RETURN NUMBER IS
vPHONE_NUMBER VARCHAR2(20 CHAR);
vCELL_PLAN_NAME VARCHAR2(100 CHAR);
vUSER_NAME VARCHAR2(100 CHAR);
vBALANCE NUMBER;
vDISCONNECT_LIMIT NUMBER;
vPHONE_STATUS_CODE INTEGER; 
vACTUAL_DATE DATE;  
ITOG VARCHAR2(200 CHAR);
BEGIN
  SQL_GET_USER_INFO(
    pUSER_ID,
    vPHONE_NUMBER,
    vCELL_PLAN_NAME,
    vUSER_NAME,
    vBALANCE,
    vDISCONNECT_LIMIT,
    vPHONE_STATUS_CODE,
    vACTUAL_DATE
    );
  RETURN vBALANCE;  
END;
/
