CREATE OR REPLACE PROCEDURE API_LOAD_FAST_PHONE_OPTIONS IS
--#Version=1
  vSTR VARCHAR2(2000 CHAR);
BEGIN
  FOR rec IN (SELECT RRP.PHONE_NUMBER
                FROM ROAMING_RETARIF_PHONES RRP
                WHERE RRP.SERVICE_OFF_CONFIRMED_DATETIME IS NULL)
  LOOP
    vSTR:= BEELINE_API_PCKG.PHONE_OPTIONS(rec.PHONE_NUMBER);
  END LOOP;                  
END;
/
