CREATE OR REPLACE PROCEDURE CHECK_ACCOUNT_PHONES_PERIOD IS
--Version=1
BEGIN
  INSERT INTO DB_LOADER_ACCOUNT_PHONES_PERI(YEAR_MONTH, PHONE_NUMBER)
    SELECT YEAR_MONTH, PHONE_NUMBER
      FROM DB_LOADER_ACCOUNT_PHONES X
      WHERE NOT EXISTS (SELECT 1
                          FROM  DB_LOADER_ACCOUNT_PHONES_PERI Z
                          WHERE Z.YEAR_MONTH = X.YEAR_MONTH
                            AND Z.PHONE_NUMBER = X.PHONE_NUMBER)
      GROUP BY YEAR_MONTH, PHONE_NUMBER;
  INSERT INTO DB_LOADER_ACCOUNT_PHONES_PERI(YEAR_MONTH, PHONE_NUMBER)
    SELECT TO_NUMBER(TO_CHAR(SYSDATE, 'yyyymm')), C.PHONE_NUMBER_FEDERAL
      FROM CONTRACTS C
      WHERE NOT EXISTS (SELECT 1
                          FROM CONTRACT_CANCELS CC
                          WHERE CC.CONTRACT_ID = C.CONTRACT_ID)
        AND NOT EXISTS (SELECT 1
                          FROM DB_LOADER_ACCOUNT_PHONES_PERI X
                          WHERE X.PHONE_NUMBER = C.PHONE_NUMBER_FEDERAL
                            AND X.YEAR_MONTH = TO_NUMBER(TO_CHAR(SYSDATE, 'yyyymm')))
        AND EXISTS (SELECT 1
                      FROM TARIFFS T
                      WHERE T.TARIFF_ID = C.TARIFF_ID
                        AND T.TARIFF_CODE IS NOT NULL);
  COMMIT;
END;

GRANT EXECUTE ON CHECK_ACCOUNT_PHONES_PERIOD TO CORP_MOBILE_ROLE;    

GRANT EXECUTE ON CHECK_ACCOUNT_PHONES_PERIOD TO LONTANA_ROLE;    