CREATE OR REPLACE PROCEDURE READ_FIELD_FROM_DETAILS(
  pFIELD_ID IN INTEGER
  ) IS
RESULT VARCHAR2(200 CHAR);  
YEAR_MONTH INTEGER;
BEGIN
  YEAR_MONTH:=TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMM'));
  FOR rec IN (
    SELECT ACCOUNT_ID
      FROM ACCOUNTS)
  LOOP
    RESULT:=LOADER2_PCKG.READ_FIELD_DETAILS(rec.ACCOUNT_ID, YEAR_MONTH, pFIELD_ID);
  END LOOP;    
END;  

GRANT EXECUTE ON READ_FIELD_FROM_DETAILS TO CORP_MOBILE_ROLE;