CREATE OR REPLACE PROCEDURE REBUILD_ABONENT_ALL_PERIODS IS
BEGIN
  FOR rec IN (SELECT Q.*
                FROM QUEUE_ABONENT_PER_REBILD Q
                ORDER BY Q.DATE_INSERT ASC)
  LOOP
    REBUILD_ABONENT_PERIODS(REC.YEAR_MONTH, REC.PHONE_NUMBER);
    DELETE FROM QUEUE_ABONENT_PER_REBILD Q
      WHERE Q.YEAR_MONTH = REC.YEAR_MONTH
        AND Q.PHONE_NUMBER = REC.PHONE_NUMBER;
    COMMIT;
  END LOOP;
END;