CREATE OR REPLACE PROCEDURE CORP_MOBILE.RESTORE_MISSED_PAYMENTS IS
--Version = 2
--
--v2. 03/09/2015 Соколов. Убрал REPLACE.
BEGIN
  INSERT INTO DB_LOADER_PAYMENTS(ACCOUNT_ID, YEAR_MONTH, PHONE_NUMBER, 
                                 PAYMENT_DATE, PAYMENT_SUM, PAYMENT_STATUS_IS_VALID, 
                                 PAYMENT_NUMBER, PAYMENT_STATUS_TEXT)
    select DISTINCT (SELECT ACCOUNT_ID FROM ACCOUNTS WHERE ACCOUNT_NUMBER = D1.BAN) BAN_OLD, TO_CHAR(convert_pckg.TIMESTAMP_TZ_TO_DATE(d.PAYMENTDATE), 'YYYYMM') YM , D.CTN, 
           convert_pckg.TIMESTAMP_TZ_TO_DATE(d.PAYMENTDATE) P_DATE, TO_NUMBER(D.PAYMENTCURRENTAMT) P_SUM, 1,
           D.BANKPAYMENTID, 'Платеж зачислен'
      from ARCHIVE_API_GET_PAYMENT_LIST d,
           ARCHIVE_API_GET_PAYMENT_LIST d1
      where TO_NUMBER(D.PAYMENTCURRENTAMT) > 0
        AND D.CTN IS NOT NULL
        AND NOT EXISTS (SELECT 1 
                          FROM DB_LOADER_PAYMENTS B
                          WHERE B.PHONE_NUMBER = d.CTN
                            AND B.PAYMENT_DATE = convert_pckg.TIMESTAMP_TZ_TO_DATE(d.PAYMENTDATE)
                            AND B.PAYMENT_NUMBER = D.BANKPAYMENTID)
        AND D.BAN = '152628091'
        AND D1.BAN <> '152628091'
        AND D.CTN = D1.CTN(+)            
        AND D.PAYMENTDATE = D1.PAYMENTDATE(+)            
        AND D.BANKPAYMENTID = D1.BANKPAYMENTID(+)            
        AND D.PAYMENTORIGINALAMT = D1.PAYMENTORIGINALAMT(+)           
        AND TO_NUMBER(D1.PAYMENTCURRENTAMT) = 0;
  commit;        
END;
