CREATE OR REPLACE DIRECTORY 
SNAPSHOT_LOG_BACKUP AS 
'E:\Backup\SNAPSHOT_LOG';

GRANT EXECUTE, READ, WRITE ON DIRECTORY SOAPAPI_BACKUP TO CORP_MOBILE_ROLE;

GRANT EXECUTE, READ, WRITE ON DIRECTORY SOAPAPI_BACKUP TO CORP_MOBILE_ROLE_RO;
