CREATE TABLE CRM_OPERATOR_NOTIFICATIONS(
  CRM_OPERATOR_NOTIFICATION_ID integer NOT NULL PRIMARY KEY,
  ABONENT_NUMBER VARCHAR2(12),
  MESSAGE VARCHAR2(500),
  ACTIVE_FROM DATE,
  ACTIVE_TILL DATE
);

CREATE SEQUENCE CRM_OPERATOR_NOTIFICATIONS_SEQ;

CREATE OR REPLACE TRIGGER CRM_OPERATOR_NOTIFICATIONS_PKT
BEFORE INSERT ON CRM_OPERATOR_NOTIFICATIONS 
FOR EACH ROW
BEGIN
  :new.CRM_OPERATOR_NOTIFICATION_ID := CRM_OPERATOR_NOTIFICATIONS_SEQ.NEXTVAL;
END;
/

COMMENT ON TABLE CRM_OPERATOR_NOTIFICATIONS IS 'Напоминания для абонентов в CRM';
COMMENT ON COLUMN CRM_OPERATOR_NOTIFICATIONS.CRM_OPERATOR_NOTIFICATION_ID IS 'Идентификатор напоминания';
COMMENT ON COLUMN CRM_OPERATOR_NOTIFICATIONS.ABONENT_NUMBER IS 'Номер телефона абонента';
COMMENT ON COLUMN CRM_OPERATOR_NOTIFICATIONS.MESSAGE IS 'Текст напоминания';
COMMENT ON COLUMN CRM_OPERATOR_NOTIFICATIONS.ACTIVE_FROM IS 'Напоминание активно с этой даты';
COMMENT ON COLUMN CRM_OPERATOR_NOTIFICATIONS.ACTIVE_TILL IS 'Напоминание активно по эту дату';

CREATE SYNONYM CRM_USER.CRM_OPERATOR_NOTIFICATIONS FOR CRM_OPERATOR_NOTIFICATIONS;

GRANT SELECT ON CRM_OPERATOR_NOTIFICATIONS_SEQ TO CRM_USER;
GRANT SELECT, INSERT, DELETE, UPDATE ON CRM_OPERATOR_NOTIFICATIONS TO CRM_USER;

ALTER TABLE CRM_OPERATOR_NOTIFICATIONS
MODIFY(MESSAGE VARCHAR2(2000 CHAR));