CREATE TABLE CRM_TICKETS_FILE
(
  CRM_TICKET_FILE_ID int NOT NULL PRIMARY KEY,
  CRM_TICKET_ID int,
  blob_content BLOB
);

COMMENT ON TABLE CRM_TICKETS_FILE IS 'Таблица с файлами для тикетов у CRM_USER';

COMMENT ON COLUMN CRM_TICKETS_FILE.CRM_TICKET_FILE_ID IS 'ID ЗАПИСИ';

COMMENT ON COLUMN CRM_TICKETS_FILE.CRM_TICKET_ID IS 'ID ТИКЕТА';

COMMENT ON COLUMN CRM_TICKETS_FILE.blob_content IS 'БИНАРНОЕ ТЕЛО ФАЙЛА';


CREATE SEQUENCE CRM_TICKETS_FILE_SEQ;

CREATE OR REPLACE TRIGGER CRM_TICKETS_FILE_PKT
BEFORE INSERT ON CRM_TICKETS_FILE 
FOR EACH ROW
BEGIN
  :new.CRM_TICKET_FILE_ID := CRM_TICKETS_FILE_SEQ.NEXTVAL;
END;

CREATE INDEX I_CRM_TICKETS_FILE
ON CRM_TICKETS_FILE (CRM_TICKET_ID);

CREATE SYNONYM CRM_USER.CRM_TICKETS_FILE FOR CRM_TICKETS_FILE;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE on CRM_TICKETS_FILE TO CRM_USER;

Alter table CRM_TICKETS_FILE add( FILE_NAME           VARCHAR2(500 BYTE));
COMMENT ON COLUMN CRM_TICKETS_FILE.FILE_NAME IS 'Имя файла';