CREATE TABLE LEAVING_REASONS 
(
  ID INTEGER NOT NULL 
, TITLE VARCHAR2(255) NOT NULL 
, CONSTRAINT LEAVING_REASONS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON TABLE LEAVING_REASONS IS 'Таблица причин ухода пользователей';

COMMENT ON COLUMN LEAVING_REASONS.ID IS 'Идентификатор записи';

COMMENT ON COLUMN LEAVING_REASONS.TITLE IS 'Заголовок причины ухода';

ALTER TABLE LEAVING_REASONS
ADD (
  IS_ACTIVE NUMBER(1,0) default 1 not null,
  ORDER_POSITION NUMBER(38,0)
);

COMMENT ON COLUMN LEAVING_REASONS.IS_ACTIVE IS 'Флаг используемости причины ухода';
COMMENT ON COLUMN LEAVING_REASONS.ORDER_POSITION IS 'Позиция сортировки причин в списках';

CREATE SYNONYM USER_1C.LEAVING_REASONS for CRM_USER.LEAVING_REASONS;
GRANT SELECT ON CRM_USER.LEAVING_REASONS TO USER_1C; 