CREATE TABLE CORP_MOBILE_LK.ABONENT_ADD_INFO (
  CONTRACT_ID INTEGER CONSTRAINT PK_ABONENT_ADD_INFO PRIMARY KEY,
  EMAIL VARCHAR2(100 CHAR),
  CONTACT_PHONE VARCHAR2(10)
);

COMMENT ON TABLE CORP_MOBILE_LK.ABONENT_ADD_INFO IS 'Дополнительная информация абонента';
