GRANT EXECUTE ON ADD_PROMISED_PAYMENT TO CORP_MOBILE_LK;
 
CREATE OR REPLACE PROCEDURE CORP_MOBILE_LK.ADD_PROMISED_PAYMENT(
  pPHONE_NUMBER IN VARCHAR2, 
  pPROMISED_SUM IN NUMBER
  ) IS
--#Version=1
--
--
  vRESULT VARCHAR2(2000); 
BEGIN
  vRESULT := CORP_MOBILE.ADD_PROMISED_PAYMENT(pPHONE_NUMBER, pPROMISED_SUM, TRUNC(SYSDATE)+4);
END;
/
