GRANT SELECT ON WWW_V_BILLS TO CORP_MOBILE_LK;

CREATE OR REPLACE VIEW CORP_MOBILE_LK.BILLS
AS
   SELECT YEAR_MONTH || PHONE_NUMBER ID,
          YEAR_MONTH,
          PHONE_NUMBER,
          DATE_BEGIN begin_date,
          DATE_END end_date,
          BILL_SUM
     FROM CORP_MOBILE.V_BILL_FOR_CLIENT;



