CREATE OR REPLACE TYPE CORP_MOBILE_LK.BALANCE_ROW_TYPE AS OBJECT
(ROW_DATE DATE,
ROW_COST NUMBER,
DESCRIPTION varchar2(4000)
);


CREATE SYNONYM CORP_MOBILE_LK.CALC_BALANCE_ROWS2 FOR CALC_BALANCE_ROWS2;


GRANT EXECUTE ON CALC_BALANCE_ROWS2 TO CORP_MOBILE_LK;
