GRANT SELECT ON CORP_MOBILE.TARIFFS TO CORP_MOBILE_LK;

CREATE OR REPLACE FUNCTION CORP_MOBILE_LK.GET_TARIFF_CHARGE(
  pTARIFF_ID IN INTEGER
) RETURN NUMBER IS
--
--#Version=1
--
CURSOR C IS
  SELECT MONTHLY_PAYMENT
  FROM CORP_MOBILE.TARIFFS
  WHERE TARIFF_ID=pTARIFF_ID;
--
vRESULT NUMBER;
--
BEGIN
  OPEN C;
  FETCH C INTO vRESULT;
  CLOSE C;
  RETURN vRESULT;
END;
/
