GRANT EXECUTE ON CRM_UNBLOCK_PHONE TO CORP_MOBILE_LK;

CREATE OR REPLACE FUNCTION CORP_MOBILE_LK.UNLOCK_PHONE(pPHONE_NUMBER IN VARCHAR2) RETURN VARCHAR2 IS
BEGIN
  RETURN CORP_MOBILE.CRM_UNBLOCK_PHONE(pPHONE_NUMBER);
END;
/
