CREATE OR REPLACE VIEW CORP_MOBILE_LK.V_ABONENT_CONTACTS AS
SELECT
--#Version=1
--
-- Контактные данные абонентов для выгрузки
--
  ABONENT_ADD_INFO.CONTRACT_ID as ABONENT_CONTACT_ID,
  ABONENT_ADD_INFO.EMAIL,
  ABONENT_ADD_INFO.CONTACT_PHONE,
  CONTRACTS.PHONE_NUMBER_FEDERAL AS LOGIN,
  TO_CHAR(ACCOUNTS.ACCOUNT_NUMBER) AS ACCOUNT_NUMBER,
  ACCOUNTS.COMPANY_NAME
FROM 
  ABONENT_ADD_INFO,
  CORP_MOBILE.CONTRACTS,
  CORP_MOBILE.ACCOUNTS
WHERE
  ABONENT_ADD_INFO.CONTRACT_ID=CORP_MOBILE.CONTRACTS.CONTRACT_ID
  AND ACCOUNTS.ACCOUNT_ID=CORP_MOBILE.GET_ACCOUNT_ID_BY_PHONE(CONTRACTS.PHONE_NUMBER_FEDERAL)
;

GRANT SELECT ON ACCOUNTS TO CORP_MOBILE_LK;