CREATE OR REPLACE VIEW WWW_V_PAYMENTS
AS
SELECT 
--#Version=2
  PAYMENTS.RECEIVED_PAYMENT_ID ID,
  C.CONTRACT_ID USER_ID,
  PAYMENTS.PHONE_NUMBER, 
  PAYMENTS.PAYMENT_SUM, 
  PAYMENTS.PAYMENT_DATE,
  PAYMENTS.PAYMENT_REMARK,
  PAYMENTS.PAYMENT_TYPE_NAME
  --PAYMENTS.PAYMENT_ANNUL_FLAG 
  --PAYMENTS.PAYMENT_ANNUL_DATE_TIME 
  --PAYMENTS.PAYMENT_ANNUL_REASON
FROM 
  CONTRACTS C, 
  CONTRACT_CANCELS CCS, 
  V_FULL_BALANCE_PAYMENTS PAYMENTS 
WHERE C.CONTRACT_ID = CCS.CONTRACT_ID(+) 
  AND CCS.CONTRACT_CANCEL_DATE IS NULL
  AND PAYMENTS.PHONE_NUMBER=C.PHONE_NUMBER_FEDERAL
  -- Суммы платежей с текстом "Компенсация к счету" или "Корректировка к счету" не показываем
  AND NOT REGEXP_LIKE(LOWER(PAYMENTS.PAYMENT_REMARK), 'ко(р)+ектировка к сч[её]ту|компенсация к сч[её]ту')
  AND (
    PAYMENTS.PAYMENT_DATE >= NVL(C.CONTRACT_DATE, TO_DATE('01.01.2000', 'DD.MM.YYYY'))-4
        OR (PAYMENTS.CONTRACT_ID = C.CONTRACT_ID
             and PAYMENTS.PAYMENT_REMARK<>'Стартовый баланс')
        );


GRANT SELECT ON WWW_V_PAYMENTS TO CORP_MOBILE_LK;
GRANT SELECT ON CONTRACTS TO CORP_MOBILE_LK;
GRANT SELECT ON DB_LOADER_PAYMENTS TO CORP_MOBILE_LK;
GRANT SELECT ON RECEIVED_PAYMENTS TO CORP_MOBILE_LK;
GRANT SELECT ON PROMISED_PAYMENTS TO CORP_MOBILE_LK;
GRANT SELECT ON RECEIVED_PAYMENT_TYPES TO CORP_MOBILE_LK;
CREATE SYNONYM CORP_MOBILE_LK.PAYMENTS FOR WWW_V_PAYMENTS;


