CREATE OR REPLACE VIEW CORP_MOBILE.WWW_V_SERVICES
AS
SELECT 
--#Version=3
  C.CONTRACT_ID ID,
  NVL(TARIFF_OPTIONS.OPTION_NAME_FOR_AB, OPTS.OPTION_NAME) OPTION_NAME,
  OPTS.TURN_ON_DATE,
  OPTS.TURN_OFF_DATE,
  TARIFF_OPTIONS.TARIFF_OPTION_ID as OPTION_ID,
  TARIFF_OPTIONS.CAN_BE_TURNED_BY_ABONENT
FROM 
  CONTRACTS C, 
  CONTRACT_CANCELS CCS,
  DB_LOADER_ACCOUNT_PHONE_OPTS OPTS,
  TARIFF_OPTIONS
WHERE C.CONTRACT_ID = CCS.CONTRACT_ID(+) 
  AND CCS.CONTRACT_CANCEL_DATE IS NULL
  AND OPTS.PHONE_NUMBER=C.PHONE_NUMBER_FEDERAL
  AND OPTS.YEAR_MONTH = (SELECT MAX(OPTS2.YEAR_MONTH) 
                        FROM DB_LOADER_ACCOUNT_PHONE_OPTS OPTS2
                        WHERE OPTS2.PHONE_NUMBER=C.PHONE_NUMBER_FEDERAL)
  AND TARIFF_OPTIONS.OPTION_CODE=OPTS.OPTION_CODE
  AND (TARIFF_OPTIONS.OPTION_NAME_FOR_AB IS NULL 
    OR (TARIFF_OPTIONS.OPTION_NAME_FOR_AB <> '-'
      AND UPPER(TARIFF_OPTIONS.OPTION_NAME_FOR_AB) <> '— –€“‹'
      )
    )
  ;


GRANT SELECT ON WWW_V_SERVICES TO CORP_MOBILE_LK;
GRANT SELECT ON CONTRACTS TO CORP_MOBILE_LK;
GRANT SELECT ON CONTRACT_CANCELS TO CORP_MOBILE_LK;
GRANT SELECT ON DB_LOADER_ACCOUNT_PHONE_OPTS TO CORP_MOBILE_LK;
CREATE OR REPLACE SYNONYM CORP_MOBILE_LK.SERVICES FOR WWW_V_SERVICES;

alter table tariff_options disable all triggers;
update tariff_options
set option_name_for_ab = '-'
where option_code in ('INT_05', 'BL_CPA_22', 'RRGUG_0', 'GPBAR_NIN');
alter table tariff_options enable all triggers;


select option_name_for_ab from tariff_options
where option_code in ('INT_05', 'BL_CPA_22', 'RRGUG_0', 'GPBAR_NIN');