CREATE SEQUENCE S_NEW_D_NEW_ID;

CREATE OR REPLACE FUNCTION NEW_D_NEW_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_D_NEW_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;
/

CREATE TABLE D_NEWS
(
  D_NEW_ID           INTEGER,
  DATE_OF_NEW        DATE,
  NEW_HEADER         VARCHAR2(2000 CHAR),
  NEW_ANNOTATION     VARCHAR2(2000 CHAR),
  NEW_TEXT           CLOB,
  NEW_ENABLED  NUMBER(1, 0) CHECK (NEW_ENABLED IN (0, 1)),
  NEW_IS_ON_TOP  NUMBER(1, 0) CHECK (NEW_IS_ON_TOP IN (0, 1)),
  USER_CREATED       VARCHAR2(30 CHAR),
  DATE_CREATED       DATE,
  USER_LAST_UPDATED  VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED  DATE
);

ALTER TABLE D_NEWS ADD  CONSTRAINT PK_D_NEWS PRIMARY KEY (D_NEW_ID);

CREATE OR REPLACE TRIGGER TIU_D_NEWS
  BEFORE INSERT OR UPDATE ON D_NEWS FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.D_NEW_ID, 0) = 0 then
      :NEW.D_NEW_ID := NEW_D_NEW_ID;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/

 

COMMENT ON TABLE D_NEWS IS 'Новости';

COMMENT ON COLUMN D_NEWS.D_NEW_ID IS 'Первичный ключ';

COMMENT ON COLUMN D_NEWS.DATE_OF_NEW IS 'Дата новости';

COMMENT ON COLUMN D_NEWS.NEW_HEADER IS 'Заголовок новости';

COMMENT ON COLUMN D_NEWS.NEW_ANNOTATION IS 'Аннотация';

COMMENT ON COLUMN D_NEWS.NEW_TEXT IS 'Текст новости';

COMMENT ON COLUMN D_NEWS.NEW_ENABLED IS 'Новость включена (разрешена к публикации)';

COMMENT ON COLUMN D_NEWS.NEW_IS_ON_TOP IS 'Новость выделена и показана первой';

COMMENT ON COLUMN D_NEWS.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN D_NEWS.DATE_CREATED IS 'Дата/время создания записи';

COMMENT ON COLUMN D_NEWS.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';

COMMENT ON COLUMN D_NEWS.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';

CREATE INDEX I_D_NEWS_DATE_OF_NEW ON D_NEWS (DATE_OF_NEW);
