CREATE OR REPLACE PROCEDURE S_BEGIN(  
  X_USERNAME IN VARCHAR2 DEFAULT NULL,
  X_PASSWORD IN VARCHAR2 DEFAULT NULL,
  SESSION_ID IN VARCHAR2 DEFAULT NULL,
  CLOSE_SESSION IN VARCHAR2 DEFAULT NULL
  ) is
begin
  S_HEADER(X_USERNAME=>X_USERNAME, X_PASSWORD=>X_PASSWORD, SESSION_ID=>SESSION_ID, CLOSE_SESSION=>CLOSE_SESSION);
  S_TOP;
--  S_LEFT;
  IF (G_STATE.USER_ID IS NULL) /*AND (STRANICA<>5)*/ THEN
    IF G_STATE.LOGIN_ERROR_TEXT IS NOT NULL then
      S_LOGIN_FORM(pPHONE_NUMBER=>X_USERNAME,LOGIN_ERROR_TEXT=>G_STATE.LOGIN_ERROR_TEXT);
    ELSE
      S_LOGIN_FORM(X_USERNAME);
    END IF;
  END IF;
END S_BEGIN;
/
