-- выбирает только по ключам из одного поля

-- если указан параметр R_TABLE_NAME, 
--   то выбираются ссылки только на конкретную таблицу

SELECT T.*, LENGTH(T.TABLE_NAME)+LENGTH(T.COLUMN_NAME)+3 LEN, 
  'CREATE INDEX I_'||T.TABLE_NAME||'_'||T.COLUMN_NAME||' ON '||T.TABLE_NAME||' ('||T.COLUMN_NAME||');' 
FROM 
(
SELECT ACC.TABLE_NAME, ACC.COLUMN_NAME
FROM ALL_CONSTRAINTS AC, ALL_CONS_COLUMNS ACC
WHERE (AC.OWNER = :OWNER)
  AND (ACC.OWNER = :OWNER)
  AND (AC.CONSTRAINT_TYPE = 'R')
  AND (AC.CONSTRAINT_NAME = ACC.CONSTRAINT_NAME)
  AND ((:R_TABLE_NAME IS NULL)
       OR
       EXISTS(
              SELECT 1
              FROM ALL_CONSTRAINTS AC2
              WHERE (AC2.OWNER = :OWNER) AND (AC2.CONSTRAINT_TYPE = 'P')
                AND (AC2.CONSTRAINT_NAME = AC.R_CONSTRAINT_NAME)
                AND AC2.TABLE_NAME = :R_TABLE_NAME
                )
      )
MINUS  
SELECT TABLE_NAME, COLUMN_NAME FROM ALL_IND_COLUMNS 
WHERE INDEX_OWNER = :OWNER
  AND INDEX_NAME IN 
  ( 
    SELECT INDEX_NAME FROM ALL_IND_COLUMNS WHERE INDEX_OWNER = :OWNER
    GROUP BY INDEX_NAME HAVING COUNT(*) = 1
  ) 
) T
ORDER BY COLUMN_NAME;
