DROP TYPE CORP_MOBILE.TPHONEREPORT;

CREATE OR REPLACE TYPE CORP_MOBILE.TPHONEREPORT AS OBJECT
(   ACCOUNT_NUMBER VARCHAR2(20),
    YEARMONTH NUMBER,
    PHONE_NUMBER VARCHAR2(11),
    REPORTDATE DATE,
    CALLS   NUMBER,
    INTERCALL NUMBER,
    CITYCALL NUMBER,
    MEST NUMBER,
    SMS NUMBER,
    INTERNET NUMBER,
    ALLCALLS NUMBER,
    INTERROUMING NUMBER,
    NACROUMING NUMBER)
/
