--ALTER TABLE D_CONTR_TARIFF_PERC_HANDS
-- DROP PRIMARY KEY CASCADE;
--
--DROP TABLE D_CONTR_TARIFF_PERC_HANDS CASCADE CONSTRAINTS;

--
-- D_CONTR_TARIFF_PERC_HANDS  (Table) 
--
CREATE TABLE D_CONTR_TARIFF_PERC_HANDS
(
  CONTR_TARIFF_PRC_HAND_ID  INTEGER             NOT NULL,
  USER_ID                   INTEGER,
  TARIFF_ID                 INTEGER,
  PERCENT                   NUMBER,
  USER_CREATED              VARCHAR2(30 CHAR),
  DATE_CREATED              DATE,
  USER_LAST_UPDATED         VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED         DATE,
  PERIOD                    DATE
)
;

COMMENT ON TABLE D_CONTR_TARIFF_PERC_HANDS IS 'Проценты на тарифы внесенные вручную в привязке к контрагенту (D_CONTR_TARIFF_PERCENTS)';

COMMENT ON COLUMN D_CONTR_TARIFF_PERC_HANDS.CONTR_TARIFF_PRC_HAND_ID IS 'Первичный ключ';

COMMENT ON COLUMN D_CONTR_TARIFF_PERC_HANDS.USER_ID IS 'Код контрагента';

COMMENT ON COLUMN D_CONTR_TARIFF_PERC_HANDS.TARIFF_ID IS 'Код тарифа';

COMMENT ON COLUMN D_CONTR_TARIFF_PERC_HANDS.PERCENT IS 'Процент';

COMMENT ON COLUMN D_CONTR_TARIFF_PERC_HANDS.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN D_CONTR_TARIFF_PERC_HANDS.DATE_CREATED IS 'Дата/время создания записи';

COMMENT ON COLUMN D_CONTR_TARIFF_PERC_HANDS.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';

COMMENT ON COLUMN D_CONTR_TARIFF_PERC_HANDS.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';



--
-- I_D_CONTR_TARIFF_P_H_TRF_ID  (Index) 
--
CREATE INDEX I_D_CONTR_TARIFF_P_H_TRF_ID ON D_CONTR_TARIFF_PERC_HANDS
(TARIFF_ID)
;


--
-- I_D_CONTR_TARIFF_P_H_USER_ID  (Index) 
--
CREATE INDEX I_D_CONTR_TARIFF_P_H_USER_ID ON D_CONTR_TARIFF_PERC_HANDS
(USER_ID)
;


--
-- PK_D_CONTR_TARIFF_PERC_HANDS  (Index) 
--
CREATE UNIQUE INDEX PK_D_CONTR_TARIFF_PERC_HANDS ON D_CONTR_TARIFF_PERC_HANDS
(CONTR_TARIFF_PRC_HAND_ID)
;


CREATE SEQUENCE S_NEW_D_C_TARIFF_PRC_HAND_ID
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE OR REPLACE FUNCTION WWW_DEALER.NEW_CONTR_TARIFF_PRC_HAND_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_D_C_TARIFF_PRC_HAND_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;

--
-- TIU_D_CONTR_TARIFF_PERC_HANDS  (Trigger) 
--
CREATE OR REPLACE TRIGGER TIU_D_CONTR_TARIFF_PERC_HANDS
--#Version=1
  BEFORE INSERT OR UPDATE ON D_CONTR_TARIFF_PERC_HANDS FOR EACH ROW
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.CONTR_TARIFF_PRC_HAND_ID, 0) = 0 then
      :NEW.CONTR_TARIFF_PRC_HAND_ID := NEW_CONTR_TARIFF_PRC_HAND_ID;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/


-- 
-- Non Foreign Key Constraints for Table D_CONTR_TARIFF_PERC_HANDS 
-- 
ALTER TABLE D_CONTR_TARIFF_PERC_HANDS ADD (
  CONSTRAINT PK_D_CONTR_TARIFF_PERC_HANDS
  PRIMARY KEY
  (CONTR_TARIFF_PRC_HAND_ID)
  USING INDEX PK_D_CONTR_TARIFF_PERC_HANDS
  ENABLE VALIDATE);

-- 
-- Foreign Key Constraints for Table D_CONTR_TARIFF_PERC_HANDS 
-- 
ALTER TABLE D_CONTR_TARIFF_PERC_HANDS ADD (
  CONSTRAINT FK_D_CONTR_TARIFF_P_H_TRF_ID 
  FOREIGN KEY (TARIFF_ID) 
  REFERENCES D_TARIFFS (TARIFF_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT FK_D_CONTR_TARIFF_P_H_USER_ID 
  FOREIGN KEY (USER_ID) 
  REFERENCES D_USER_NAMES (USER_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON D_CONTR_TARIFF_PERC_HANDS TO WWW_DEALER_ROLE;
