ALTER TABLE D_DELIVERY_TYPES
 DROP PRIMARY KEY CASCADE;

DROP TABLE D_DELIVERY_TYPES CASCADE CONSTRAINTS;

--
-- D_DELIVERY_TYPES  (Table) 
--
CREATE TABLE D_DELIVERY_TYPES
(
  DELIVERY_TYPE_ID   INTEGER,
  DELIVERY_NAME      VARCHAR2(60 CHAR),
  USER_CREATED       VARCHAR2(30 CHAR),
  DATE_CREATED       DATE,
  USER_LAST_UPDATED  VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED  DATE,
  NEED_ADDRESS       NUMBER(1)                  DEFAULT 1,
  IS_DELETED         NUMBER(1)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE D_DELIVERY_TYPES IS 'Справочник способов доставки';

COMMENT ON COLUMN D_DELIVERY_TYPES.DELIVERY_TYPE_ID IS 'Первичный ключ';

COMMENT ON COLUMN D_DELIVERY_TYPES.DELIVERY_NAME IS 'Наименование способа доставки';

COMMENT ON COLUMN D_DELIVERY_TYPES.NEED_ADDRESS IS 'Признак необходимости указать адрес';

COMMENT ON COLUMN D_DELIVERY_TYPES.IS_DELETED IS 'Признак удаления позиции';



--
-- PK_D_DELIVERY_TYPES  (Index) 
--
CREATE UNIQUE INDEX PK_D_DELIVERY_TYPES ON D_DELIVERY_TYPES
(DELIVERY_TYPE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


--
-- TIU_D_DELIVERY_TYPES  (Trigger) 
--
CREATE OR REPLACE TRIGGER TIU_D_DELIVERY_TYPES
--#Version=1
  BEFORE INSERT OR UPDATE ON D_DELIVERY_TYPES FOR EACH ROW
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.DELIVERY_TYPE_ID, 0) = 0 then
      :NEW.DELIVERY_TYPE_ID := NEW_D_DELIVERY_TYPE_ID;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/


-- 
-- Non Foreign Key Constraints for Table D_DELIVERY_TYPES 
-- 
ALTER TABLE D_DELIVERY_TYPES ADD (
  CONSTRAINT PK_D_DELIVERY_TYPES
  PRIMARY KEY
  (DELIVERY_TYPE_ID)
  USING INDEX PK_D_DELIVERY_TYPES
  ENABLE VALIDATE);
