CREATE SEQUENCE S_NEW_D_FAQ_ID;

CREATE OR REPLACE FUNCTION NEW_D_FAQ_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_D_FAQ_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;
/

CREATE TABLE D_FAQS
(
  D_FAQ_ID           INTEGER,
  ORDER_NUMBER       NUMBER,
  FAQ_HEADER         VARCHAR2(1000 CHAR),
  FAQ_REQUEST        VARCHAR2(4000 CHAR),
  FAQ_RESPONSE       CLOB,
  FAQ_ENABLED  NUMBER(1, 0) CHECK (FAQ_ENABLED IN (0, 1)),
  USER_CREATED       VARCHAR2(30 CHAR),
  DATE_CREATED       DATE,
  USER_LAST_UPDATED  VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED  DATE
);

ALTER TABLE D_FAQS ADD  CONSTRAINT PK_D_FAQS PRIMARY KEY (D_FAQ_ID);

CREATE OR REPLACE TRIGGER TIU_D_FAQS
  BEFORE INSERT OR UPDATE ON D_FAQS FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.D_FAQ_ID, 0) = 0 then
      :NEW.D_FAQ_ID := NEW_D_FAQ_ID;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/

 

COMMENT ON TABLE D_FAQS IS 'Частые вопросы';

COMMENT ON COLUMN D_FAQS.D_FAQ_ID IS 'Первичный ключ';

COMMENT ON COLUMN D_FAQS.ORDER_NUMBER IS 'Порядковый номер';

COMMENT ON COLUMN D_FAQS.FAQ_HEADER IS 'Заголовок';

COMMENT ON COLUMN D_FAQS.FAQ_REQUEST IS 'Текст вопроса';

COMMENT ON COLUMN D_FAQS.FAQ_RESPONSE IS 'Текст ответа';

COMMENT ON COLUMN D_FAQS.FAQ_ENABLED IS 'Вопрос разрешен к показу';

COMMENT ON COLUMN D_FAQS.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN D_FAQS.DATE_CREATED IS 'Дата/время создания записи';

COMMENT ON COLUMN D_FAQS.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';

COMMENT ON COLUMN D_FAQS.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';

--CREATE INDEX I_D_FAQS_DATE_OF_NEW ON D_FAQS (DATE_OF_NEW);
