CREATE OR REPLACE FUNCTION WWW_DEALER.GET_DELIVERY_TYPES_OPTIONS(pSELECTED_DELEVERY_TYPE_ID VARCHAR2) RETURN VARCHAR2 IS
--v2
--V2. - Матюнин И. - При показе способа доставки не учитываем удаленные позиции
--   Возвращает элемент всплывающий список для справочника "Способы доставки" для старницы "Заказ SIM"
    vRES VARCHAR2(32000) := GET_OPTION_ITEM('', '')||CHR(13)||CHR(10);
  BEGIN
    FOR REC IN (SELECT D.* FROM D_DELIVERY_TYPES D WHERE NVL(D.IS_DELETED, 0) = 0 ORDER BY D.DELIVERY_NAME) LOOP
      vRES := SUBSTR(vRES || GET_OPTION_ITEM(REC.DELIVERY_TYPE_ID, pSELECTED_DELEVERY_TYPE_ID, REC.DELIVERY_NAME)||CHR(13)||CHR(10), 1, 32000);
    END LOOP;
    RETURN vRES;
  EXCEPTION WHEN OTHERS THEN OUT_ERROR(pSELECTED_DELEVERY_TYPE_ID);
  END;
/
