CREATE OR REPLACE TYPE K7_LK.AVAILABLE_OPTION_TYPE AS OBJECT
(
  TARIFF_OPTION_ID INTEGER,
  CATEGORY_NAME VARCHAR2(100 CHAR),
  NAME VARCHAR2(100 CHAR),
  TURN_ON_COST NUMBER(15, 2),
  MONTHLY_COST NUMBER(15, 2),
  DESCRIPTION VARCHAR2(4000),
  DISCR_SPISANIE NUMBER(1, 0)
);
/