CREATE OR REPLACE PROCEDURE CALC_BALANCE_ROWS(
  pPHONE_NUMBER IN VARCHAR2,
  pBALANCE_DATE IN DATE DEFAULT NULL
  ) IS
--#Version=14
-- Ќе учитываем историю изменени€ условий тарифов (нет данных)
--
  DATE_ROWS DBMS_SQL.DATE_TABLE; 
  COST_ROWS DBMS_SQL.NUMBER_TABLE; 
  DESCRIPTION_ROWS DBMS_SQL.VARCHAR2_TABLE;
  vRESULT NUMBER(15, 2);
  L BINARY_INTEGER;
  vBALANCE_DATE DATE;
BEGIN
  vBALANCE_DATE:=pBALANCE_DATE;
  DELETE FROM ABONENT_BALANCE_ROWS; -- быстрее чем TRUNCATE
  IF MS_CONSTANTS.GET_CONSTANT_VALUE('SERVER_NAME')='GSM_CORP' THEN
    IF (NVL(pBALANCE_DATE, SYSDATE)>=TO_DATE('28122011', 'DDMMYYYY'))AND(NVL(pBALANCE_DATE, SYSDATE)<=TO_DATE('01012012', 'DDMMYYYY')) THEN  
      vBALANCE_DATE:=TO_DATE('01012012', 'DDMMYYYY');
    END IF;
  END IF;  
  CALC_BALANCE_ROWS2(pPHONE_NUMBER, DATE_ROWS, COST_ROWS, DESCRIPTION_ROWS, TRUE, vBALANCE_DATE);
  L := COST_ROWS.LAST;
  IF L IS NOT NULL THEN
    FORALL I IN COST_ROWS.FIRST..L 
      INSERT INTO ABONENT_BALANCE_ROWS (ROW_DATE, ROW_COST, ROW_COMMENT)
      VALUES (DATE_ROWS(I), COST_ROWS(I), DESCRIPTION_ROWS(I));
  END IF;
END;
/
