CREATE OR REPLACE PROCEDURE CHANGE_CONTRACT_SEND_ACTIV(
  pCONTRACT_NUM IN INTEGER
  ) IS
BEGIN
  UPDATE CONTRACTS
    SET CONTRACTS.SEND_ACTIV=
      CASE
        WHEN CONTRACTS.SEND_ACTIV=1 THEN NULL
        ELSE 1
      END  
    WHERE CONTRACTS.CONTRACT_NUM=pCONTRACT_NUM;
END;
/

grant execute on CHANGE_CONTRACT_SEND_ACTIV to lontana_role;