CREATE OR REPLACE FUNCTION CHECK_DETAIL_EXISTS(
  pYEAR_MONTH IN INTEGER,
  pPHONE_NUMBER IN VARCHAR2
  ) RETURN INTEGER IS
  C CLOB;
BEGIN
  C:=loader3_pckg.get_phone_detail(TRUNC(pYEAR_MONTH/100), pYEAR_MONTH - TRUNC(pYEAR_MONTH/100)*100, pPHONE_NUMBER);
  IF DBMS_LOB.getlength(C) > 100 THEN
    RETURN 1;
  ELSE
    RETURN 0;
  END IF;
EXCEPTION WHEN OTHERS THEN
  RETURN 0;
END;

GRANT EXECUTE ON CHECK_DETAIL_EXISTS TO LONTANA_ROLE;