CREATE OR REPLACE PROCEDURE GET_DETAIL_FIELD(
  pPHONE_NUMBER IN VARCHAR2,
  pYEAR_MONTH IN NUMBER,
  pTYPE_FIELD IN INTEGER, 
  pINFO OUT DBMS_SQL.VARCHAR2_TABLE 
  ) IS
  INFA CLOB;
  LENG INTEGER;
  BEGINING INTEGER; 
  ENDING INTEGER;
  I INTEGER; 
  LINE VARCHAR2(2000);
  BE INTEGER;
  EN INTEGER;
  TYP VARCHAR2(100);
  LE VARCHAR2(100);
  LEN NUMBER;
BEGIN
  INFA:=LOADER3_PCKG.GET_PHONE_DETAIL(TRUNC(pYEAR_MONTH/100),(pYEAR_MONTH-TRUNC(pYEAR_MONTH,-2)),pPHONE_NUMBER);
  LENG:=DBMS_LOB.GETLENGTH(INFA);
  pINFO.delete;
  IF LENG>0 THEN
    ENDING:=1;
    I:=0;
    --DBMS_LOB.INSTR(INFA,CHR(10),1,1);
    WHILE (DBMS_LOB.INSTR(INFA,CHR(10),ENDING+1,1)<>0) --AND (I<8)
    LOOP
      BEGINING:=ENDING;
      I:=I+1;
      ENDING:=DBMS_LOB.INSTR(INFA,CHR(10),BEGINING+1,1);
      LINE:=DBMS_LOB.SUBSTR(INFA,ENDING-BEGINING-1,BEGINING);
      BE:=INSTR(LINE, CHR(9), 1, pTYPE_FIELD - 1);
      EN:=INSTR(LINE,CHR(9),BE+1);   
      pINFO(I):=SUBSTR(LINE,BE+1,EN-BE-1);
    END LOOP;
  END IF;
END;
/

GRANT EXECUTE ON GET_DETAIL_FIELD TO LONTANA_ROLE;
