CREATE OR REPLACE PROCEDURE REBUILD_STACK_ABONENT_PERIODS(
  pSTACK_NUMBER IN INTEGER,
  pSTACK_COUNT IN INTEGER
  ) IS
BEGIN
  FOR rec IN (SELECT Q.*
                FROM QUEUE_ABONENT_PER_REBILD Q
                WHERE mod(TO_NUMBER(Q.PHONE_NUMBER), pSTACK_COUNT)=pSTACK_NUMBER
                ORDER BY Q.DATE_INSERT DESC)
  LOOP
    REBUILD_ABONENT_PERIODS(REC.YEAR_MONTH, REC.PHONE_NUMBER);
    DELETE FROM QUEUE_ABONENT_PER_REBILD Q
      WHERE Q.YEAR_MONTH = REC.YEAR_MONTH
        AND Q.PHONE_NUMBER = REC.PHONE_NUMBER;
    COMMIT;
  END LOOP;
END;