CREATE OR REPLACE PROCEDURE SET_PHONE_ATTR_DISCOUNT(
  pPHONE_NUMBER IN VARCHAR2,
  pCHECK IN INTEGER,
  pDISCOUNT_VALIDITY IN INTEGER,
  pDISCOUNT_BEGIN_DATE IN DATE
  ) IS
--
-- Version=1
--
--13.10.2011 Крайнов Создание.
--
COUNT_INT INTEGER;
BEGIN
  COUNT_INT:=0;
  IF pCHECK=1 THEN
    FOR rec IN(
      SELECT PHONE_NUMBER_ATTRIBUTES.IS_DISCOUNT_OPERATOR
        FROM PHONE_NUMBER_ATTRIBUTES
        WHERE PHONE_NUMBER_ATTRIBUTES.PHONE_NUMBER=pPHONE_NUMBER
      )
    LOOP
      COUNT_INT:=COUNT_INT+1;
    END LOOP;    
    IF COUNT_INT>0 THEN
      UPDATE PHONE_NUMBER_ATTRIBUTES
        SET PHONE_NUMBER_ATTRIBUTES.IS_DISCOUNT_OPERATOR=1,
            PHONE_NUMBER_ATTRIBUTES.DISCOUNT_VALIDITY=pDISCOUNT_VALIDITY,
            PHONE_NUMBER_ATTRIBUTES.DISCOUNT_BEGIN_DATE=pDISCOUNT_BEGIN_DATE
        WHERE PHONE_NUMBER_ATTRIBUTES.PHONE_NUMBER=pPHONE_NUMBER;
    ELSE
      INSERT INTO PHONE_NUMBER_ATTRIBUTES(PHONE_NUMBER, IS_DISCOUNT_OPERATOR, DISCOUNT_BEGIN_DATE, DISCOUNT_VALIDITY)
        VALUES(pPHONE_NUMBER, 1, pDISCOUNT_BEGIN_DATE, pDISCOUNT_VALIDITY);
    END IF;
  ELSE
    DELETE 
      FROM PHONE_NUMBER_ATTRIBUTES
      WHERE PHONE_NUMBER_ATTRIBUTES.PHONE_NUMBER=pPHONE_NUMBER;
  END IF;
END;
/