CREATE OR REPLACE PROCEDURE CALC_BALANCE_STREAM(
  STREAM_ID IN INTEGER
  ) IS  
  vCOUNT_STREAM INTEGER;
  vCURRENT_BALANCE NUMBER(15, 4);
BEGIN
  vCOUNT_STREAM:=TO_NUMBER(MS_PARAMS.GET_PARAM_VALUE('CALC_BALANCE_STREAM_COUNT'));
  FOR rec IN (SELECT PHONE_NUMBER
                FROM QUEUE_CURRENT_BALANCES
                WHERE MOD(QUEUE_ID, vCOUNT_STREAM) = STREAM_ID - 1 
                  AND ROWNUM <=2000)
  LOOP
    vCURRENT_BALANCE:=GET_ABONENT_BALANCE(rec.PHONE_NUMBER);
    DELETE FROM QUEUE_CURRENT_BALANCES
      WHERE PHONE_NUMBER = rec.PHONE_NUMBER;
    COMMIT;  
  END LOOP;                               
END;

GRANT EXECUTE ON CALC_BALANCE_STREAM TO CORP_MOBILE_ROLE;
