CREATE OR REPLACE PROCEDURE CHANGE_ROBOT_ALL_ACCOUNTS(
  pNEW_STATE IN INTEGER
  ) IS
BEGIN
  IF (pNEW_STATE=0) OR (pNEW_STATE = 1) THEN
    UPDATE ACCOUNTS 
      SET ACCOUNTS.DO_AUTO_BLOCK=pNEW_STATE,
          ACCOUNTS.DO_BALANCE_NOTICE=pNEW_STATE;
    COMMIT; 
  END IF; 
END;  

--GRANT EXECUTE ON CHANGE_ROBOT_ALL_ACCOUNTS TO CORP_MOBILE_ROLE;