CREATE OR REPLACE PROCEDURE CHECK_INCORRECT_FINANCE_BILLS IS
--Version = 1
BEGIN
  UPDATE DB_LOADER_FULL_FINANCE_BILL FB
    SET FB.COMPLETE_BILL = 0
    WHERE FB.COMPLETE_BILL = 1
      AND (FB.ACCOUNT_ID, FB.YEAR_MONTH, FB.PHONE_NUMBER) IN
            (SELECT V.ACCOUNT_ID, 
                    V.YEAR_MONTH, 
                    V.PHONE_NUMBER
               FROM V_BILL_FULL_FINANCE_INCORRECT V);
  UPDATE DB_LOADER_FULL_FINANCE_BILL FB
    SET FB.COMPLETE_BILL = 0
    WHERE FB.COMPLETE_BILL = 1
      AND (FB.ACCOUNT_ID, FB.YEAR_MONTH, FB.PHONE_NUMBER) IN
            (SELECT V.ACCOUNT_ID, 
                    V.YEAR_MONTH, 
                    V.PHONE_NUMBER
               FROM V_BILL_FULL_ABON_PER_INCORRECT V);
  COMMIT;             
END;

--GRANT EXECUTE ON CHECK_INCORRECT_FINANCE_BILLS TO SIM_TRADE_ROLE;

--GRANT EXECUTE ON CHECK_INCORRECT_FINANCE_BILLS TO LONTANA_ROLE;

--GRANT EXECUTE ON CHECK_INCORRECT_FINANCE_BILLS TO CORP_MOBILE_ROLE;