CREATE OR REPLACE PROCEDURE SEND_MAIL_OTCHETS IS
--Version=1
BEGIN
  FOR rec IN(
    SELECT *
      FROM REPORT_TYPES
      ORDER BY REPORT_TYPE_ID ASC)
  LOOP
    IF rec.SEND_REPORT=1 THEN
      IF rec.TYPE_REPORT='CONTROL_PHONE_NUMBERS' THEN
        SEND_MAIL_OTCHET_PHONE_VIOLS; 
      END IF;
      IF rec.TYPE_REPORT='CONTROL_TARIFFS' THEN 
        SEND_MAIL_OTCHET_TAR_VIOLS; 
      END IF;
      IF rec.TYPE_REPORT='PHONE_FOR_BLOCK_SAVE' THEN 
        SEND_MAIL_PHONE_FOR_BL_SAVE;
      END IF;
      IF rec.TYPE_REPORT='PHONE_FOR_UNBLOCK_SAVE' THEN 
        SEND_MAIL_PHONE_FOR_UNBL_SAVE;
      END IF;
    END IF;
  END LOOP;
END;
/