CREATE OR REPLACE PROCEDURE SET_PHONE_HISTORY IS
  CURSOR H(PH IN VARCHAR2, CH IN DATE) IS
    SELECT *
      FROM DB_LOADER_ACCOUNT_PHONE_HISTS D
      WHERE D.PHONE_NUMBER = PH
        AND D.BEGIN_DATE <= CH
        AND D.END_DATE >= CH;
  vDUMMY_H H%ROWTYPE;   
BEGIN
  FOR rec IN (SELECT Q.*, Q.ROWID
                FROM QUEUE_UPDATE_PHONE_HISTORY Q
                ORDER BY PHONE_NUMBER ASC, DATE_REPORT ASC)
  LOOP 
    BEGIN      
      SET_PHONE_HISTORY2(rec.PHONE_NUMBER, rec.PHONE_IS_ACTIVE, rec.CELL_PLAN_CODE, 
                         rec.CONSERVATION, rec.SYSTEM_BLOCK, rec.STATUS_ID, rec.DATE_REPORT);
      DELETE FROM QUEUE_UPDATE_PHONE_HISTORY Q
        WHERE Q.ROWID = REC.ROWID;
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN 
      NULL;
      insert into temp7(str2)
      values(rec.PHONE_NUMBER);
      commit;
    END;
  END LOOP;
end;
/

