CREATE OR REPLACE PROCEDURE SET_HAND_BLOCK_END_DATE(
  pCONTRACT_ID IN VARCHAR2,
  pHAND_BLOCK_END_DATE IN DATE,
  pBALANCE_NOTICE_HAND_BLOCK IN INTEGER,
  pBALANCE_BLOCK_HAND_BLOCK IN INTEGER
  ) IS
--
-- Version=3
-- 3. Котенков Добавлена обработка полей BALANCE_NOTICE_HAND_BLOCK и BALANCE_BLOCK_HAND_BLOCK
--
BEGIN
  IF (TRUNC(PHAND_BLOCK_END_DATE)<TRUNC(SYSDATE))OR(pHAND_BLOCK_END_DATE IS NULL) THEN
    UPDATE CONTRACTS
      SET CONTRACTS.HAND_BLOCK=0, CONTRACTS.HAND_BLOCK_DATE_END=NULL,
      CONTRACTS.BALANCE_NOTICE_HAND_BLOCK=NULL, CONTRACTS.BALANCE_BLOCK_HAND_BLOCK=NULL
      WHERE CONTRACTS.CONTRACT_ID=pCONTRACT_ID;
  ELSE
    UPDATE CONTRACTS
      SET CONTRACTS.HAND_BLOCK=1, CONTRACTS.HAND_BLOCK_DATE_END=pHAND_BLOCK_END_DATE,
      CONTRACTS.BALANCE_NOTICE_HAND_BLOCK=pBALANCE_NOTICE_HAND_BLOCK, 
      CONTRACTS.BALANCE_BLOCK_HAND_BLOCK=pBALANCE_BLOCK_HAND_BLOCK
      WHERE CONTRACTS.CONTRACT_ID=pCONTRACT_ID;
  END IF; 
END;
/  

GRANT EXECUTE ON SET_HAND_BLOCK_END_DATE TO CORP_MOBILE_ROLE;
  