CREATE TABLE TARIFER_BILL_FOR_CLIENT_DET
(
  YEAR_MONTH    NUMBER,
  PHONE_NUMBER  VARCHAR2(15 CHAR),
  ROW_DATE      DATE,
  ROW_COST      NUMBER(15,2),
  ROW_COMMENT   VARCHAR2(2000 CHAR),
  ROW_TYPE      INTEGER
);

COMMENT ON TABLE TARIFER_BILL_FOR_CLIENT_DET IS 'Детальная расшифровка выставленного счета';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENT_DET.YEAR_MONTH IS 'Месяц/год за которое выставлен счет';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENT_DET.PHONE_NUMBER IS 'Номер телефона';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENT_DET.ROW_DATE IS 'Дата начисления';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENT_DET.ROW_COST IS 'Сумма начисления';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENT_DET.ROW_COMMENT IS 'Расшиврока начисления';

COMMENT ON COLUMN TARIFER_BILL_FOR_CLIENT_DET.ROW_TYPE IS 'Тип начисления';