CREATE OR REPLACE PROCEDURE USER_NAMES_UPDATE(
  p_OLD_USER_NAME_ID IN NUMBER, 
  p_USER_NAME_ID IN NUMBER, 
  p_USER_FIO IN VARCHAR2, 
  p_USER_NAME IN VARCHAR2, 
  p_PASSWORD IN VARCHAR2, 
  p_FILIAL_ID IN NUMBER, 
  p_RIGHTS_TYPE IN NUMBER,
  p_CHECK_ALLOW_ACCOUNT IN NUMBER,
  p_ENCRYPT_PWD IN NUMBER,
  user_oktel in varchar2 default null,
  p_PASSWORD_OKTEL in varchar2 default null,
  p_MAX_PROMISED_PAYMENT IN NUMBER default null,
  p_SHOW_BLOCK_UNBLOCK_BTN in NUMBER default null,
  p_RIGHT_CANCEL_CONTRACT in NUMBER default null
  ) IS

--#Version=9

-- 9. 12.08.2015 Афросин Добавлена обработка поля RIGHT_CANCEL_CONTRACT
-- 8. 23.06.2015 Афросин Добавлено поле SHOW_BLOCK_UNBLOCK_BTN 
-- 7. Алексеев Добавлена обработка поля MAX_PROMISED_PAYMENT
-- 6. Овсянников Добавлена обработка поля PASSWORD_OKTEL
-- 5. Котенков Добавлена обработка поля ENCRYPT_PWD
-- 4. Котенков Добавлена обработка поля CHECK_ALLOW_ACCOUNT

BEGIN
  CHECK_CREATE_USER(p_USER_NAME, p_PASSWORD, p_USER_NAME_ID, p_RIGHTS_TYPE); 
  --
  UPDATE USER_NAMES
  SET
    USER_NAME_ID = p_USER_NAME_ID,
    USER_FIO = p_USER_FIO,
    USER_NAME = p_USER_NAME,
    --PASSWORD = p_PASSWORD,
    FILIAL_ID = p_FILIAL_ID,
    RIGHTS_TYPE = p_RIGHTS_TYPE,
    CHECK_ALLOW_ACCOUNT = p_CHECK_ALLOW_ACCOUNT,
    ENCRYPT_PWD = p_ENCRYPT_PWD,
    user_name_oktel=user_oktel,
    PASSWORD_OKTEL=p_PASSWORD_OKTEL,
    MAX_PROMISED_PAYMENT = p_MAX_PROMISED_PAYMENT,
    SHOW_BLOCK_UNBLOCK_BTN = p_SHOW_BLOCK_UNBLOCK_BTN,
    RIGHT_CANCEL_CONTRACT = p_RIGHT_CANCEL_CONTRACT
  WHERE
    USER_NAME_ID = p_OLD_USER_NAME_ID;  
END;
/


