CREATE OR REPLACE PROCEDURE WWW_GET_USER_INFO(
  pUSER_ID IN INTEGER,
  pPHONE_NUMBER OUT VARCHAR2,
  pCELL_PLAN_NAME OUT VARCHAR2,
  pUSER_NAME OUT VARCHAR2,
  pBALANCE OUT NUMBER,
  pDISCONNECT_LIMIT OUT NUMBER,
  pPHONE_STATUS_CODE OUT INTEGER, -- 0 - Заблокирован, 1-Активный
  pACTUAL_DATE OUT DATE -- Дата и время актуальности
  ) IS
--#Version=1
CURSOR C IS
  SELECT CONTRACTS.PHONE_NUMBER_FEDERAL,
        V_ABONENT_BALANCES.TARIFF_NAME,
        ABONENTS.SURNAME || ' ' || ABONENTS.NAME || ' ' || ABONENTS.PATRONYMIC FIO,
        GET_ABONENT_BALANCE(CONTRACTS.PHONE_NUMBER_FEDERAL) BALANCE,
        CONTRACTS.DISCONNECT_LIMIT,
        V_ABONENT_BALANCES.PHONE_IS_ACTIVE_CODE,
        DB_LOADER_PHONE_STAT.LAST_CHECK_DATE_TIME
    FROM CONTRACTS,ABONENTS,V_ABONENT_BALANCES,DB_LOADER_PHONE_STAT
    WHERE pUSER_ID=CONTRACTS.CONTRACT_ID
      AND CONTRACTS.ABONENT_ID=ABONENTS.ABONENT_ID
      AND CONTRACTS.PHONE_NUMBER_FEDERAL=V_ABONENT_BALANCES.PHONE_NUMBER_FEDERAL
      AND CONTRACTS.PHONE_NUMBER_FEDERAL=DB_LOADER_PHONE_STAT.PHONE_NUMBER
      ;
vUSER_INFO C%ROWTYPE;      
BEGIN
  vUSER_INFO:=NULL;
  OPEN C;
  FETCH C INTO vUSER_INFO;
  CLOSE C;
  pPHONE_NUMBER:=vUSER_INFO.PHONE_NUMBER_FEDERAL;
  pCELL_PLAN_NAME:=vUSER_INFO.TARIFF_NAME;
  pUSER_NAME:=vUSER_INFO.FIO;
  pBALANCE:=vUSER_INFO.BALANCE;
  pDISCONNECT_LIMIT:=vUSER_INFO.DISCONNECT_LIMIT;
  pPHONE_STATUS_CODE:=vUSER_INFO.PHONE_IS_ACTIVE_CODE;
  pACTUAL_DATE:=vUSER_INFO.LAST_CHECK_DATE_TIME; 
END;
/

GRANT EXECUTE ON WWW_GET_USER_INFO TO LONTANA_WWW;
/       