CREATE OR REPLACE PROCEDURE WWW_GET_ABONENT_BALANCE_ROWS(
  pUSER_ID IN INTEGER,
  pBALANCE_DATE IN DATE,
  pDATE_ROWS OUT DBMS_SQL.DATE_TABLE, 
  pCOST_ROWS OUT DBMS_SQL.NUMBER_TABLE, 
  pDESCRIPTION_ROWS OUT DBMS_SQL.VARCHAR2_TABLE
  ) IS
--#Version=1
CURSOR C IS
  SELECT PHONE_NUMBER_FEDERAL 
    FROM CONTRACTS
    WHERE CONTRACTS.CONTRACT_ID=pUSER_ID
      AND CONTRACTS.CONTRACT_DATE<=NVL(pBALANCE_DATE,SYSDATE);
pPHONE_NUMBER CONTRACTS.PHONE_NUMBER_FEDERAL%TYPE;  
      
BEGIN
  pPHONE_NUMBER:=NULL;
  OPEN C;
  FETCH C INTO pPHONE_NUMBER;
  CLOSE C;
  CALC_BALANCE_ROWS2(
    pPHONE_NUMBER,
    pDATE_ROWS,
    pCOST_ROWS,
    pDESCRIPTION_ROWS,
    TRUE,
    pBALANCE_DATE
    );
END;
/

GRANT EXECUTE ON WWW_GET_ABONENT_BALANCE_ROWS TO LONTANA_WWW;
/       