CREATE OR REPLACE FUNCTION GET_NEW_FULL_FINANCE_ABON_TP1(
  pACCOUNT_ID IN INTEGER,
  pYEAR_MONTH IN INTEGER,
  pPHONE_NUMBER IN VARCHAR2
  ) RETURN NUMBER IS
--Version=2
  CURSOR C IS
    SELECT T1.ACCOUNT_ID,
         T1.YEAR_MONTH,
         T1.PHONE_NUMBER,
         T1.DATE_BEGIN,
         T1.DATE_END,
         T1.TARIFF_CODE,
         T1.ABON_MAIN AS ABON_MAIN_OLD,
         ROUND(T1.ABON_MAIN * NVL(TARIFFS.CALC_KOEFF, 1)
                + T1.COEFF_MONTH * NVL(TARIFFS.TARIFF_ADD_COST, 0), 4) ABON_MAIN,
         T1.ABON_ADD,
         NVL(TARIFFS.CALC_KOEFF, 1) CALC_KOEFF,
         NVL(TARIFFS.TARIFF_ADD_COST, 0) TARIFF_ADD_COST,
         TARIFFS.TARIFF_ID,
         TARIFFS.TARIFF_NAME
    FROM (SELECT AP.*,
                 GET_PHONE_TARIFF_ID(AP.PHONE_NUMBER, AP.TARIFF_CODE, AP.DATE_END) AS TARIFF_ID,
                 (AP.DATE_END - AP.DATE_BEGIN + 1)/(LAST_DAY(AP.DATE_BEGIN) - TO_DATE(TO_CHAR(AP.DATE_BEGIN, 'YYYYMM')||'01', 'YYYYMMDD') + 1) COEFF_MONTH
            FROM DB_LOADER_FULL_BILL_ABON_PER AP
            where  AP.PHONE_NUMBER = pPHONE_NUMBER
             AND AP.YEAR_MONTH = pYEAR_MONTH
            AND AP.ACCOUNT_ID = pACCOUNT_ID) T1,
         TARIFFS
    WHERE  T1.TARIFF_ID=TARIFFS.TARIFF_ID(+)
    and t1.date_begin>=(select min(contr.contract_date) from contracts contr where phone_number_federal=pPHONE_NUMBER);
    
  ITOG NUMBER(15, 4);
BEGIN
  ITOG:=0;
  FOR rec IN C LOOP
    ITOG:=ITOG + rec.ABON_MAIN;
  END LOOP;
  RETURN ITOG;
END;
