CREATE OR REPLACE FUNCTION GET_CREDIT_INFO(
  pCONTRACT_ID IN INTEGER
  ) RETURN VARCHAR2 IS
CURSOR C IS 
  SELECT C.PHONE_NUMBER_FEDERAL,
         NVL(C.IS_CREDIT_CONTRACT, 0) IS_CREDIT_CONTRACT,
         TRUNC(V.BILL_SUM_NEW, 2) BILL_SUM,
         TRUNC(V.ABON_TP_NEW + V.ABON_ADD_NEW + V.DISCOUNT_NEW, 2) ABONKA,
         V.YEAR_MONTH,
         AB.DATE_CREDIT_END
    FROM CONTRACTS C,
         V_BILL_FINANCE_FOR_CLIENTS V,
         ACCOUNT_LOADED_BILLS AB
    WHERE C.CONTRACT_ID=pCONTRACT_ID
      AND NVL(C.IS_CREDIT_CONTRACT, 0)=1
      AND C.PHONE_NUMBER_FEDERAL=V.PHONE_NUMBER
      AND V.ACCOUNT_ID = AB.ACCOUNT_ID
      AND V.YEAR_MONTH = AB.YEAR_MONTH
      AND TRUNC(AB.DATE_CREDIT_END) >=TRUNC(SYSDATE)
      AND AB.LOAD_BILL_IN_BALANCE = 1
      and v.COMPLETE_BILL = 1
  UNION ALL            
  SELECT C.PHONE_NUMBER_FEDERAL,
         NVL(C.IS_CREDIT_CONTRACT, 0) IS_CREDIT_CONTRACT,
         V.BILL_SUM,
         V.SUBSCRIBER_PAYMENT_NEW+V.SUBSCRIBER_PAYMENT_ADD_OLD+V.SUBSCRIBER_PAYMENT_ADD_VOZVRAT ABONKA,
         V.YEAR_MONTH,
         AB.DATE_CREDIT_END
    FROM CONTRACTS C,
         V_BILL_FOR_CLIENT V,
         ACCOUNT_LOADED_BILLS AB,
         V_BILL_FINANCE_FOR_CLIENTS V2
    WHERE C.CONTRACT_ID=pCONTRACT_ID
      AND NVL(C.IS_CREDIT_CONTRACT, 0)=1
      AND C.PHONE_NUMBER_FEDERAL=V.PHONE_NUMBER
      AND V.ACCOUNT_ID = AB.ACCOUNT_ID
      AND V.YEAR_MONTH = AB.YEAR_MONTH
      AND TRUNC(AB.DATE_CREDIT_END) >=TRUNC(SYSDATE)
      AND AB.LOAD_BILL_IN_BALANCE = 1
      AND V.ACCOUNT_ID = V2.ACCOUNT_ID(+)
      AND V.YEAR_MONTH = V2.YEAR_MONTH(+)
      AND V.PHONE_NUMBER = V2.PHONE_NUMBER(+)
      AND V2.PHONE_NUMBER IS NULL;
DUMMY C%ROWTYPE;      
ITOG VARCHAR2(300 CHAR);
BALANCE NUMBER(13, 2);      
BILL NUMBER(13, 2);
MONTH_NAME VARCHAR2(20 CHAR);   
vBILLS NUMBER(13, 2);   
vABONKA NUMBER(13, 2);   
BEGIN
  IF TO_NUMBER(TO_CHAR(SYSDATE, 'DD'))<=31 THEN
    vBILLS:=0;
    vABONKA:=0;
    FOR rec IN C 
    LOOP
      vBILLS:=vBILLS+rec.BILL_SUM;
      vABONKA:=vABONKA+rec.ABONKA;
    END LOOP;
    OPEN C;
    FETCH C INTO DUMMY;
    IF (C%FOUND) AND (TRUNC(DUMMY.DATE_CREDIT_END) >= TRUNC(SYSDATE)) THEN
      IF NVL(DUMMY.YEAR_MONTH, 0)>0 THEN
        MONTH_NAME:=CASE
                      WHEN DUMMY.YEAR_MONTH-100*TRUNC(DUMMY.YEAR_MONTH/100)=1 THEN '€нварь'
                      WHEN DUMMY.YEAR_MONTH-100*TRUNC(DUMMY.YEAR_MONTH/100)=2 THEN 'февраль'
                      WHEN DUMMY.YEAR_MONTH-100*TRUNC(DUMMY.YEAR_MONTH/100)=3 THEN 'март'
                      WHEN DUMMY.YEAR_MONTH-100*TRUNC(DUMMY.YEAR_MONTH/100)=4 THEN 'апрель'
                      WHEN DUMMY.YEAR_MONTH-100*TRUNC(DUMMY.YEAR_MONTH/100)=5 THEN 'май'
                      WHEN DUMMY.YEAR_MONTH-100*TRUNC(DUMMY.YEAR_MONTH/100)=6 THEN 'июнь'
                      WHEN DUMMY.YEAR_MONTH-100*TRUNC(DUMMY.YEAR_MONTH/100)=7 THEN 'июль'
                      WHEN DUMMY.YEAR_MONTH-100*TRUNC(DUMMY.YEAR_MONTH/100)=8 THEN 'август'
                      WHEN DUMMY.YEAR_MONTH-100*TRUNC(DUMMY.YEAR_MONTH/100)=9 THEN 'сент€брь'
                      WHEN DUMMY.YEAR_MONTH-100*TRUNC(DUMMY.YEAR_MONTH/100)=10 THEN 'окт€брь'
                      WHEN DUMMY.YEAR_MONTH-100*TRUNC(DUMMY.YEAR_MONTH/100)=11 THEN 'но€брь'
                      WHEN DUMMY.YEAR_MONTH-100*TRUNC(DUMMY.YEAR_MONTH/100)=12 THEN 'декабрь'
                      ELSE ''
                    END;
        BALANCE:=GET_ABONENT_BALANCE(DUMMY.PHONE_NUMBER_FEDERAL) - vABONKA;
        ITOG:='—чет за '||MONTH_NAME||': '||TO_CHAR(vBILLS)||'. Ѕаланс с аб. пл. на '||TO_CHAR(SYSDATE, 'DD.MM.YY')||': '||TO_CHAR(BALANCE);
      END IF;
    END IF;
    CLOSE C;
  ELSE
    ITOG:='';
  END IF;
  RETURN ITOG;
END;  

GRANT EXECUTE ON GET_CREDIT_INFO TO CORP_MOBILE_ROLE;

GRANT EXECUTE ON GET_CREDIT_INFO TO CORP_MOBILE_ROLE_RO;