CREATE OR REPLACE FUNCTION TO_NUM (pVALUE IN VARCHAR2)
   RETURN NUMBER
IS
   ITOG   NUMBER;
BEGIN
   BEGIN
      ITOG := TO_NUMBER (REPLACE (pVALUE, ',', '.'));
   EXCEPTION
      WHEN OTHERS
      THEN
         ITOG := TO_NUMBER (REPLACE (pVALUE, '.', ','));
   END;

   RETURN ITOG;
END;
/

GRANT EXECUTE ON TO_NUM TO LONTANA_ROLE;

GRANT EXECUTE ON TO_NUM TO LONTANA_ROLE_RO;