CREATE OR REPLACE FUNCTION WWW_GET_PHONE_BY_CONTRACTID(
  pCONTRACT_ID IN INTEGER
  ) RETURN VARCHAR2 IS
  
  --#Version=1
  --
  --v2. Алексеев. Добавил данную функцию в svn
  --v1. Функция определения номера телефона по id контракта.
  
  vPhone varchar2(10);
BEGIN
  SELECT PHONE_NUMBER_FEDERAL
  into vPhone
    FROM CONTRACTS
    WHERE CONTRACT_ID=pCONTRACT_ID ;
  RETURN vPhone; 
END;

CREATE SYNONYM CRM_USER.WWW_GET_PHONE_BY_CONTRACTID FOR LONTANA.WWW_GET_PHONE_BY_CONTRACTID;

GRANT EXECUTE ON LONTANA.WWW_GET_PHONE_BY_CONTRACTID TO CRM_USER;