-- Пользователи
CREATE TABLE MF_USER_NAMES (
  USER_ID NUMBER(8, 0),
  USER_NAME VARCHAR2(30 CHAR),
  PASSWORD_HASH VARCHAR2(50 CHAR),
  IS_LOCKED NUMBER(2, 0),
  DESCRIPTION VARCHAR2(200 CHAR),
  E_MAIL VARCHAR2(100 CHAR),
  IS_ADMIN NUMBER(1, 0),
  CONSTRAINT MF_PK_USER_NAMES PRIMARY KEY (USER_ID)
  );

CREATE SEQUENCE MF_S_NEW_USER_ID NOCACHE;

CREATE UNIQUE INDEX MF_UQ_USER_NAME_PHONE_NUMBER
  ON MF_USER_NAMES (USER_NAME);

-- Администратор
INSERT INTO MF_USER_NAMES (
  USER_ID, 
  USER_NAME, 
  PASSWORD_HASH, 
  IS_LOCKED, 
  DESCRIPTION,
  E_MAIL,
  IS_ADMIN
) VALUES (
  MF_S_NEW_USER_ID.NEXTVAL,
  '000',
  'CC0DCBA79F3CF33191549940C734E486', -- '111',
  0,
  'Администратор',
  'udmitry@mail.ru',
  1 -- Администратор
  );

-- Тестовая запись
INSERT INTO MF_USER_NAMES (
  USER_ID, 
  USER_NAME, 
  PASSWORD_HASH, 
  IS_LOCKED, 
  DESCRIPTION,
  E_MAIL
) VALUES (
  MF_S_NEW_USER_ID.NEXTVAL,
  '9277524741',
  'CC0DCBA79F3CF33191549940C734E486', -- 1
  0,
  'Тестовый пользователь',
  'udmitry@mail.ru'
  );

COMMIT;
