CREATE OR REPLACE PROCEDURE MAIN(
  X_USERNAME IN VARCHAR2 DEFAULT NULL,
  X_PASSWORD IN VARCHAR2 DEFAULT NULL,
  SESSION_ID IN VARCHAR2 DEFAULT NULL,
  CLOSE_SESSION IN VARCHAR2 DEFAULT NULL,
  PAGE IN VARCHAR2 DEFAULT NULL
  ) IS
--
  vPAGE_NUM BINARY_INTEGER;
BEGIN
  IF PAGE IS NULL THEN
    vPAGE_NUM := 1;
  ELSE
  BEGIN
    vPAGE_NUM := TO_NUMBER(PAGE);
    EXCEPTION WHEN OTHERS THEN
      vPAGE_NUM := 1;
    END;
  END IF;
  S_BEGIN(X_USERNAME=>X_USERNAME, X_PASSWORD=>X_PASSWORD, SESSION_ID=>SESSION_ID, CLOSE_SESSION=>CLOSE_SESSION);
  IF G_STATE.USER_ID IS NOT NULL THEN
    IF SESSION_ID IS NULL THEN
      S_SHOW_NEWS_PAGE(TRUE, vPAGE_NUM);
    ELSE
      S_SHOW_NEWS_PAGE(FALSE, vPAGE_NUM);
    END IF;  
  END IF;
  S_END;
EXCEPTION WHEN OTHERS THEN
  OUT_ERROR(SQLERRM);
END MAIN;
/
