CREATE OR REPLACE PROCEDURE MF_CLOSE_SESSION(
  pSESSION_ID IN VARCHAR2
  ) IS
BEGIN
  IF pSESSION_ID IS NOT NULL THEN
    UPDATE MF_SESSIONS
      SET EXPIRED_FLAG = 1
      WHERE MF_SESSIONS.SESSION_KEY=pSESSION_ID;
  END IF;
NULL;
END MF_CLOSE_SESSION;
/
