CREATE TABLE UPLOAD_CONTRAGENT_RESTS (
  CONTRAGENT_DESCRIPTION  VARCHAR2(200 CHAR),
  USER_NAME               VARCHAR2(30 CHAR),
  CONTRAGENT_GUID         VARCHAR2(40 CHAR),
  PHONE_NUMBER            VARCHAR2(20 CHAR),
  OPERATOR                VARCHAR2(30 CHAR),
  TARIFF_NAME             VARCHAR2(200 CHAR),
  TARIFF_GUID             VARCHAR2(40 CHAR),
  IS_DIRECT               NUMBER(1),
  DATE_LOAD               VARCHAR2(20 CHAR)
);
