CREATE TABLE UPLOADED_BALANCE_CHANGE
(
  USER_NAME      VARCHAR2(30 CHAR),
  USER_GUID      VARCHAR2(40 CHAR),
  DATE_TIME      VARCHAR2(20 CHAR),
  SUM_INCOME     NUMBER,
  SUM_OUTCOME    NUMBER,
  BALANCE_AFTER  NUMBER,
  DATE_LOAD      VARCHAR2(20 CHAR),
  PHONE_NUMBER   VARCHAR2(20 CHAR),
  OPERATOR       VARCHAR2(30 CHAR),
  TARIFF_NAME    VARCHAR2(2000 CHAR),
  TARIFF_GUID    VARCHAR2(40 CHAR),
  IS_DIRECT      NUMBER(1),
  TYPE_CHANGE    VARCHAR2(512 CHAR),
  PERIOD         VARCHAR2(20 CHAR)
);

