CREATE TABLE CRM_FAQ(
  QUESTION VARCHAR2(1000 CHAR) NOT NULL,
  ANSWER VARCHAR2(1000 CHAR) NOT NULL
  );

ALTER TABLE CRM_FAQ ADD (FAQ_ID INTEGER NOT NULL);

ALTER TABLE CRM_FAQ ADD (DATE_CREATED DATE);
ALTER TABLE CRM_FAQ ADD (DATE_LAST_UPDATED DATE);
ALTER TABLE CRM_FAQ ADD (PATH VARCHAR2(300 CHAR));


CREATE UNIQUE INDEX PK_CRM_FAQ ON CRM_FAQ(FAQ_ID);

ALTER TABLE CRM_FAQ ADD (
  CONSTRAINT PK_CRM_FAQ
  PRIMARY KEY
  (FAQ_ID)
  USING INDEX PK_CRM_FAQ);

CREATE SEQUENCE S_NEW_FAQ_ID;

CREATE OR REPLACE TRIGGER FAQ_PKT
  BEFORE INSERT OR UPDATE ON CRM_FAQ FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.FAQ_ID, 0) = 0 then
      :NEW.FAQ_ID := S_NEW_FAQ_ID.NEXTVAL;
      :NEW.DATE_CREATED := SYSDATE;
    END IF;
  END IF;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
  
GRANT SELECT, INSERT, DELETE, UPDATE ON CRM_FAQ TO LONTANA_ROLE;
GRANT SELECT, INSERT, DELETE, UPDATE ON CRM_FAQ TO CRM_USER;

CREATE SYNONYM CRM_USER.FAQ FOR CRM_FAQ;
CREATE SYNONYM CRM_USER.S_NEW_FAQ_ID FOR S_NEW_FAQ_ID;
