--#if not ViewExists("V_ACCOUNT_PHONE_STATUSES") then
CREATE OR REPLACE VIEW V_ACCOUNT_PHONE_STATUSES AS
SELECT 
--#Version=1
ACCOUNT_ID, 
  YEAR_MONTH, 
  PHONE_NUMBER, 
  PHONE_IS_ACTIVE, 
  CELL_PLAN_CODE, 
  NEW_CELL_PLAN_CODE, 
  NEW_CELL_PLAN_DATE, 
  LAST_CHECK_DATE_TIME, 
  ORGANIZATION_ID, 
  CONSERVATION, 
  SYSTEM_BLOCK
FROM DB_LOADER_ACCOUNT_PHONES WHERE (PHONE_NUMBER, YEAR_MONTH, ACCOUNT_ID) IN (
  SELECT PHONE_NUMBER, YEAR_MONTH, MAX(ACCOUNT_ID)
  FROM DB_LOADER_ACCOUNT_PHONES
  WHERE (PHONE_NUMBER, YEAR_MONTH) IN (
    SELECT PHONE_NUMBER, MAX(YEAR_MONTH) YEAR_MONTH FROM DB_LOADER_ACCOUNT_PHONES
    WHERE PHONE_NUMBER IS NOT NULL
    AND YEAR_MONTH >= TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE, -1), 'YYYYMM'))
    GROUP BY PHONE_NUMBER
  )
  GROUP BY PHONE_NUMBER, YEAR_MONTH
)
/
--#end if
