CREATE OR REPLACE VIEW V_ACTIVE_PROMISED_PAYMENTS AS
SELECT
--#Version=3
--
-- ƒействующие обещанные платежи
-- 24.11.2014 Алексеев. Добавлено поле PROMISED_DATE_END
  PROMISED_PAYMENTS.PHONE_NUMBER,
  PROMISED_PAYMENTS.PROMISED_SUM,
  TRUNC(PROMISED_PAYMENTS.PAYMENT_DATE) AS PAYMENT_DATE,
  'ќбещанный платеж до ' || TO_CHAR (PROMISED_PAYMENTS.PROMISED_DATE, 'DD.MM.YYYY HH24:MI:SS') AS PAYMENT_REMARK,
  PROMISED_PAYMENTS.DATE_CREATED,
  PROMISED_PAYMENTS.PROMISED_DATE,
  PROMISED_PAYMENTS.PROMISED_DATE_END
FROM 
  PROMISED_PAYMENTS
WHERE 
  PROMISED_PAYMENTS.PROMISED_DATE >= SYSDATE
/