CREATE OR REPLACE VIEW V_BILL_FOR_DILER2 AS
  SELECT 
-- Version=5
         V1.*,
         CASE
           WHEN V1.SUBSCRIBER_PAYMENT_NEW+V1.DILER_PAYMENT+V1.OPTION_COST_DILER < V1.BILL_SUM
             THEN V1.SUBSCRIBER_PAYMENT_NEW+V1.DILER_PAYMENT+V1.OPTION_COST_DILER 
                  + V1.INSTALLMENT_PAYMENT_SUM + V1.DILER_SUMM_OLD_MONTH_IN_MINUS
           ELSE V1.BILL_SUM
         END DILER_FULL_SUM,
         V1.SUBSCRIBER_PAYMENT_OLD+V1.DILER_PAYMENT+V1.OPTION_COST_DILER_BEELINE BEELINE_FULL_SUM,
         CASE
           WHEN V1.SUBSCRIBER_PAYMENT_NEW+V1.DILER_PAYMENT+V1.OPTION_COST_DILER < V1.BILL_SUM
             THEN V1.SUBSCRIBER_PAYMENT_NEW+V1.DILER_PAYMENT+V1.OPTION_COST_DILER
                  + V1.INSTALLMENT_PAYMENT_SUM + V1.DILER_SUMM_OLD_MONTH_IN_MINUS
           ELSE V1.BILL_SUM
         END
          + CASE
              WHEN (V1.CHECK_LONG_PLUS_BALANCE=0 and v1.BILL_SUM_ORIGIN>0) THEN V1.TAIL
              ELSE 0
            END DILER_ITOG_SUM,
         CASE
           WHEN V1.CHECK_LONG_PLUS_BALANCE=0 THEN '-'
           ELSE '+'
         END CHECK_LONG_PLUS_BALANCE2
    FROM V_BILL_FOR_DILER V1;
    
-- GRANT SELECT ON V_BILL_FOR_DILER2 TO CORP_MOBILE_ROLE;      