--#if GetVersion("V_BILL_MN_ROUMING_FOR_GROUP") < 1
CREATE OR REPLACE VIEW V_BILL_MN_ROUMING_FOR_GROUP AS
--#Version=1
SELECT
  MN.ACCOUNT_ID,
  MN.YEAR_MONTH,
  MN.PHONE_NUMBER,
  MN.DATE_BEGIN,
  MN.DATE_END,
  MN.ROUMING_COUNTRY,
  MN.ROUMING_CALLS,
  MN.ROUMING_GPRS,
  MN.ROUMING_SMS,
  MN.COMPANY_TAX,
  MN.ROUMING_SUM,
  C.CONTRACT_ID, 
  C.CONTRACT_NUM, 
  C.CONTRACT_DATE, 
  C.GROUP_ID
FROM DB_LOADER_FULL_BILL_MN_ROUMING MN, V_CONTRACTS C
WHERE MN.PHONE_NUMBER = C.PHONE_NUMBER_FEDERAL
  AND C.CONTRACT_DATE < ADD_MONTHS(TO_DATE(MN.YEAR_MONTH||'01', 'yyyymmdd'), 1)
  AND (C.CONTRACT_CANCEL_DATE IS NULL OR C.CONTRACT_CANCEL_DATE >= TO_DATE(MN.YEAR_MONTH||'01', 'yyyymmdd'))
  AND C.GROUP_ID IS NOT NULL
/
--#end if
               
--GRANT SELECT ON V_BILL_MN_ROUMING_FOR_GROUP TO SIM_TRADE_ROLE;
               
--GRANT SELECT ON V_BILL_MN_ROUMING_FOR_GROUP TO LONTANA_ROLE;
            
--GRANT SELECT ON V_BILL_MN_ROUMING_FOR_GROUP TO CORP_MOBILE_ROLE;
               
--GRANT SELECT ON V_BILL_MN_ROUMING_FOR_GROUP TO CORP_MOBILE_ROLE_RO;    