CREATE OR REPLACE VIEW V_FULL_BALANCE_PAYMENTS AS
SELECT
--#Version=13
-- 13. Уколов. Добавил реальную дату|время создания записи REAL_CREATED_AT
--Овсянников Добавление 2-х колонок PAYMENT_TYPE_NAME,REVERSESCHET
--Nikolaev 20/03/2012 добавил дату загрузки платежа с сайта в базу
-- Платежи по договору
--
-- Стартовый баланс
--
--26 .10 .12 Пискунов создание уникального поля для представления RECEIVED_PAYMENTS.RECEIVED_PAYMENT_ID
--25.11.2014 Алексеев. Таблица PROMISED_PAYMENTS заменена на вьюху V_ACTIVE_PROMISED_PAYMENTS
         CONTRACTS.PHONE_NUMBER_FEDERAL AS PHONE_NUMBER,
         CONTRACTS.START_BALANCE AS PAYMENT_SUM,
         CONTRACTS.CONTRACT_DATE AS PAYMENT_DATE,
         CONTRACTS.CONTRACT_ID AS CONTRACT_ID,
         'Стартовый баланс' AS PAYMENT_REMARK,
         TO_CHAR (NULL) AS PAYMENT_NUMBER,
         0 AS PAYMENT_TYPE,
         CONTRACTS.CONTRACT_DATE AS CREATED_DATE,
         NULL AS RECEIVED_PAYMENT_ID,
         NULL AS PAYMENT_TYPE_NAME,
         NULL AS REVERSESCHET,
         CONTRACTS.DATE_CREATED AS REAL_CREATED_AT
    FROM CONTRACTS
   WHERE CONTRACTS.START_BALANCE <> 0
   -- Принятые платежи
   UNION ALL
   SELECT RECEIVED_PAYMENTS.PHONE_NUMBER,
          RECEIVED_PAYMENTS.PAYMENT_SUM,
          TRUNC (RECEIVED_PAYMENTS.PAYMENT_DATE_TIME),
          RECEIVED_PAYMENTS.CONTRACT_ID,
             'Зарегистрирован в офисе'
          || CASE
                WHEN RECEIVED_PAYMENTS.REMARK IS NULL THEN NULL
                ELSE ': ' || RECEIVED_PAYMENTS.REMARK
             END
             AS PAYMENT_REMARK,
          TO_CHAR (NULL) AS PAYMENT_NUMBER,
          1 AS PAYMENT_TYPE,
          RECEIVED_PAYMENTS.PAYMENT_DATE_TIME AS CREATED_DATE,
          RECEIVED_PAYMENTS.RECEIVED_PAYMENT_ID AS RECEIVED_PAYMENT_ID,
          RECEIVED_PAYMENT_TYPES.RECEIVED_PAYMENT_TYPE_NAME
             AS PAYMENT_TYPE_NAME,
          REVERSESCHET AS REVERSESCHET,
          RECEIVED_PAYMENTS.DATE_CREATED AS REAL_CREATED_AT
     FROM RECEIVED_PAYMENTS, RECEIVED_PAYMENT_TYPES
    WHERE     IS_CONTRACT_PAYMENT = 0 -- Кроме платежей в момент заключения договора
          AND RECEIVED_PAYMENTS.RECEIVED_PAYMENT_TYPE_ID =
                 RECEIVED_PAYMENT_TYPES.RECEIVED_PAYMENT_TYPE_ID(+)
   -- Загруженные платежи с сайта
   UNION ALL
   SELECT DB_LOADER_PAYMENTS.PHONE_NUMBER,
          DB_LOADER_PAYMENTS.PAYMENT_SUM,
          DB_LOADER_PAYMENTS.PAYMENT_DATE,
          DB_LOADER_PAYMENTS.CONTRACT_ID,
             'Платёж оператору'
          || CASE
                WHEN PAYMENT_STATUS_TEXT IS NULL THEN NULL
                ELSE ' (' || PAYMENT_STATUS_TEXT || ')'
             END
             AS PAYMENT_REMARK,
          DB_LOADER_PAYMENTS.PAYMENT_NUMBER,
          2 AS PAYMENT_TYPE,
          DATE_CREATED AS CREATED_DATE,
          NULL AS RECEIVED_PAYMENT_ID,
          NULL AS PAYMENT_TYPE_NAME,
          NULL AS REVERSESCHET,
          DB_LOADER_PAYMENTS.DATE_CREATED AS REAL_CREATED_AT
     FROM DB_LOADER_PAYMENTS
    WHERE (   DB_LOADER_PAYMENTS.YEAR_MONTH =
                 TO_CHAR (DB_LOADER_PAYMENTS.PAYMENT_DATE, 'YYYYMM')
           OR db_loader_payments.year_month =
                 TO_CHAR (db_loader_payments.payment_date + 5, 'yyyymm'))
   --AND DB_LOADER_PAYMENTS.PAYMENT_STATUS_IS_VALID = 1 Отмена платежа тоже важна
   UNION ALL
   -- Обещанные платежи
   SELECT V_ACTIVE_PROMISED_PAYMENTS.PHONE_NUMBER AS PHONE_NUMBER,
          V_ACTIVE_PROMISED_PAYMENTS.PROMISED_SUM AS PAYMENT_SUM,
          V_ACTIVE_PROMISED_PAYMENTS.PAYMENT_DATE,
          NULL AS CONTRACT_ID,
          V_ACTIVE_PROMISED_PAYMENTS.PAYMENT_REMARK,
          TO_CHAR (NULL) PAYMENT_NUMBER,
          3 AS PAYMENT_TYPE,
          V_ACTIVE_PROMISED_PAYMENTS.DATE_CREATED AS CREATED_DATE,
          NULL AS RECEIVED_PAYMENT_ID,
          NULL AS PAYMENT_TYPE_NAME,
          NULL AS REVERSESCHET,
          V_ACTIVE_PROMISED_PAYMENTS.DATE_CREATED AS REAL_CREATED_AT
     FROM V_ACTIVE_PROMISED_PAYMENTS;
/

GRANT SELECT ON CORP_MOBILE.V_FULL_BALANCE_PAYMENTS TO CORP_MOBILE_ROLE;
GRANT SELECT ON CORP_MOBILE.V_FULL_BALANCE_PAYMENTS TO CORP_MOBILE_ROLE_RO;
