--#if GetVersion("V_PHONE_NUMBERS_FOR_BLOCK") < 3
CREATE OR REPLACE VIEW V_PAYMENTS_WITHOUT_TRAFFIC AS


--#Version=3
--
-- Возвращается список номеров телефонов, у которых нет трафика за месяц, 
-- но по которым оператор выставил счёт.
--
-- v.3 Назин Перелал на новую схему счетов.

SELECT DB_LOADER_FULL_FINANCE_BILL.ACCOUNT_ID,
       DB_LOADER_FULL_FINANCE_BILL.YEAR_MONTH,
       DB_LOADER_FULL_FINANCE_BILL.PHONE_NUMBER,
       DB_LOADER_FULL_FINANCE_BILL.BILL_SUM,
       DB_LOADER_FULL_FINANCE_BILL.discounts as DISCOUNT_VALUE
  FROM DB_LOADER_FULL_FINANCE_BILL
  WHERE
    -- Абонплата не = 0
        DB_LOADER_FULL_FINANCE_BILL.BILL_SUM <> 0 -- DB_LOADER_BILLS.DISCOUNT_VALUE
    and DB_LOADER_FULL_FINANCE_BILL.Complete_Bill=1
    AND (DB_LOADER_FULL_FINANCE_BILL.PHONE_NUMBER, DB_LOADER_FULL_FINANCE_BILL.YEAR_MONTH) NOT IN (
      SELECT PHONE_NUMBER, YEAR_MONTH
        FROM DB_LOADER_PHONE_STAT
        WHERE (ZEROCOST_OUTCOME_MINUTES <> 0)
          OR (CALLS_COUNT <> 0)
          OR (CALLS_COST <> 0)
          OR (SMS_COUNT <> 0)
          OR (MMS_COUNT <> 0)
          OR (INTERNET_MB <> 0));
/
--#end if

