CREATE OR REPLACE VIEW V_PHONE_NUMBER_VIOLATIONS AS
--
--Version=2
--
SELECT DB_LOADER_PHONE_STAT.ACCOUNT_ID,
       DB_LOADER_PHONE_STAT.YEAR_MONTH,
       DB_LOADER_PHONE_STAT.PHONE_NUMBER,
       DB_LOADER_PHONE_STAT.ESTIMATE_SUM,
       DB_LOADER_PHONE_STAT.ZEROCOST_OUTCOME_COUNT,
       DB_LOADER_PHONE_STAT.ZEROCOST_OUTCOME_MINUTES,
       DB_LOADER_PHONE_STAT.CALLS_COUNT,
       DB_LOADER_PHONE_STAT.CALLS_MINUTES,
       DB_LOADER_PHONE_STAT.CALLS_COST,
       DB_LOADER_PHONE_STAT.SMS_COUNT,
       DB_LOADER_PHONE_STAT.SMS_COST,
       DB_LOADER_PHONE_STAT.MMS_COUNT,
       DB_LOADER_PHONE_STAT.MMS_COST,
       DB_LOADER_PHONE_STAT.INTERNET_MB,
       DB_LOADER_PHONE_STAT.INTERNET_COST
  FROM 
    DB_LOADER_PHONE_STAT
  WHERE GET_ID_LAST_CONTRACT_BY_PHONE(DB_LOADER_PHONE_STAT.PHONE_NUMBER) IS NULL
    AND (DB_LOADER_PHONE_STAT.ESTIMATE_SUM<>0
        OR DB_LOADER_PHONE_STAT.ZEROCOST_OUTCOME_COUNT<>0
        OR DB_LOADER_PHONE_STAT.ZEROCOST_OUTCOME_MINUTES<>0
        OR DB_LOADER_PHONE_STAT.CALLS_COUNT<>0
        OR DB_LOADER_PHONE_STAT.CALLS_MINUTES<>0
        OR DB_LOADER_PHONE_STAT.CALLS_COST<>0
        OR DB_LOADER_PHONE_STAT.SMS_COUNT<>0
        OR DB_LOADER_PHONE_STAT.SMS_COST<>0
        OR DB_LOADER_PHONE_STAT.MMS_COUNT<>0
        OR DB_LOADER_PHONE_STAT.MMS_COST<>0
        OR DB_LOADER_PHONE_STAT.INTERNET_MB<>0
        OR DB_LOADER_PHONE_STAT.INTERNET_COST<>0)
/    
