CREATE OR REPLACE FUNCTION K7_LK.ADD_PROMISED_PAYMENT(
  pPHONE_NUMBER IN VARCHAR2, 
  pPROMISED_SUM IN NUMBER
  ) RETURN VARCHAR2 IS
--#Version=1
--
--
  vRESULT VARCHAR2(2000); 
BEGIN
  vRESULT := CORP_MOBILE.ADD_PROMISED_PAYMENT(pPHONE_NUMBER, pPROMISED_SUM, TRUNC(SYSDATE)+4);
  Return vRESULT;
END;
/
