CREATE OR REPLACE VIEW V_ABON_PAYMENT_BY_PHONES AS
--
--#Version=4
--
-- Возвращается абонплата в разрезе периодов и телефонных номеров
--
SELECT 
  ACCOUNT_ID,
  YEAR_MONTH,
  PHONE_NUMBER,
  CASE
    WHEN SUBSCRIBER_PAYMENT_NEW<0 THEN 0
    ELSE SUBSCRIBER_PAYMENT_NEW
  END AS SUBSCRIBER_PAYMENT_NEW,
  (
    SELECT NVL(TR.TARIFF_NAME, DB_LOADER_ACCOUNT_PHONES.CELL_PLAN_CODE)  
    FROM DB_LOADER_ACCOUNT_PHONES, TARIFFS TR
    WHERE DB_LOADER_ACCOUNT_PHONES.PHONE_NUMBER = V_BILL_FOR_CLIENT.PHONE_NUMBER
      AND DB_LOADER_ACCOUNT_PHONES.YEAR_MONTH = V_BILL_FOR_CLIENT.YEAR_MONTH
      AND TR.TARIFF_ID(+) = GET_PHONE_TARIFF_ID(
        DB_LOADER_ACCOUNT_PHONES.PHONE_NUMBER,
        DB_LOADER_ACCOUNT_PHONES.CELL_PLAN_CODE,
        DB_LOADER_ACCOUNT_PHONES.LAST_CHECK_DATE_TIME
        )
      AND ROWNUM < 2
  ) as TARIFF_NAME
FROM 
  V_BILL_FOR_CLIENT
WHERE
  (PHONE_NUMBER, YEAR_MONTH) in (
    SELECT PHONE_NUMBER, YEAR_MONTH
    FROM DB_LOADER_PHONE_STAT
    WHERE (ZEROCOST_OUTCOME_MINUTES <> 0)
      OR (CALLS_COUNT <> 0)
      OR (CALLS_COST <> 0)
      OR (SMS_COUNT <> 0)
      OR (MMS_COUNT <> 0)
      OR (INTERNET_MB <> 0)
  )
/
