CREATE OR REPLACE VIEW V_AUTO_UNBLOCKED_PHONE AS
-- Version = 1
--
-- 1. 2015.11.09. Крайнов. Создание.
  SELECT DLAP.ACCOUNT_ID, AUP.PHONE_NUMBER, AUP.ABONENT_FIO, 
         AUP.BALLANCE, AUP.UNBLOCK_DATE_TIME, AUP.NOTE, AUP.TICKET_ID,
         DECODE(AUP.MANUAL_BLOCK, 0, 'Авто', 'Ручная') TYPE_BLOCK, 
         NVL((SELECT USER_FIO FROM USER_NAMES 
                WHERE USER_NAMES.USER_NAME=AUP.USER_NAME
                  AND ROWNUM <= 1), AUP.USER_NAME) USER_NAME,           
         CASE
           WHEN AUP.TICKET_ID IS NULL THEN 'Заявка неизвестна' 
           WHEN BT.TICKET_ID IS NULL THEN 'Заявка не найдена'
           WHEN BT.ANSWER = 1 THEN 'Выполнено'
           WHEN BT.ANSWER = 0 THEN 'Отказано'
           ELSE 'Выполняется'
         END ANSWER
    FROM AUTO_UNBLOCKED_PHONE AUP,
         DB_LOADER_ACCOUNT_PHONES DLAP,
         BEELINE_TICKETS BT 
    WHERE AUP.TICKET_ID = BT.TICKET_ID(+)
      AND AUP.PHONE_NUMBER=DLAP.PHONE_NUMBER(+)
      AND TO_NUMBER(TO_CHAR(AUP.UNBLOCK_DATE_TIME,'YYYYMM'))=DLAP.YEAR_MONTH(+);
    
GRANT SELECT ON V_AUTO_UNBLOCKED_PHONE TO LONTANA_ROLE;    
    
GRANT SELECT ON V_AUTO_UNBLOCKED_PHONE TO LONTANA_ROLE_RO;    