CREATE OR REPLACE VIEW V_BALANCES_ON_END_MONTHS_2 AS
--Version=8
  SELECT VB.YEAR_MONTH,
         VB.PHONE_NUMBER,
         LAST_DAY(TO_DATE(TO_CHAR(VB.YEAR_MONTH)||'01','YYYYMMDD')) AS DATE_CHECK,
         SUM(BILL_SUM_NEW) BILL_SUM_NEW, 
         SUM(BILL_SUM_OLD) BILL_SUM_OLD, 
         SUM(VB.ABON_TP_NEW) ABON_TP_NEW, 
         SUM(BL.CALLS_ALL + BL.ROUMING_NATIONAL + BL.ROUMING_INTERNATIONAL) ALL_CALLS, 
         SUM(st.calls_count + st.mms_count + st.sms_count + st.internet_mb + st.zerocost_outcome_count) STAT_NAL_CALL 
    FROM V_BILL_FINANCE_FOR_CLIENTS VB,
         DB_LOADER_FULL_FINANCE_BILL BL,
         DB_LOADER_PHONE_STAT ST       
    WHERE VB.ACCOUNT_ID = BL.ACCOUNT_ID
      AND VB.YEAR_MONTH = BL.YEAR_MONTH
      AND VB.PHONE_NUMBER = BL.PHONE_NUMBER
      AND VB.ACCOUNT_ID = ST.ACCOUNT_ID(+)
      AND VB.YEAR_MONTH = ST.YEAR_MONTH(+)
      AND VB.PHONE_NUMBER = ST.PHONE_NUMBER(+)
    GROUP BY VB.YEAR_MONTH, VB.PHONE_NUMBER;
    
GRANT SELECT ON V_BALANCES_ON_END_MONTHS_2 TO LONTANA_ROLE;  