CREATE OR REPLACE VIEW V_BILL_FULL_FINANCE_INCORRECT AS
-- Version = 3
  SELECT CASE
           WHEN FB.ABONKA <> FB.ABON_MAIN + FB.ABON_ADD + FB.ABON_OTHER THEN 1
           ELSE 0
         END ER_AB,
         CASE
           WHEN NOT(FB.SINGLE_PAYMENTS = FB.SINGLE_MAIN + FB.SINGLE_ADD + FB.SINGLE_CHANGE_TARIFF + FB.SINGLE_TURN_ON_SERV
                                         + FB.SINGLE_CORRECTION_ROUMING + FB.SINGLE_INTRA_WEB + FB.SINGLE_OTHER
                     OR FB.SINGLE_PAYMENTS = FB.SINGLE_MAIN + FB.SINGLE_ADD + FB.SINGLE_CHANGE_TARIFF + FB.SINGLE_TURN_ON_SERV
                                             + FB.SINGLE_CORRECTION_ROUMING + FB.SINGLE_INTRA_WEB + FB.SINGLE_OTHER
                                             + FB.SINGLE_PENALTI + FB.SINGLE_VIEW_BLACK_LIST) THEN 1
           ELSE 0
         END ER_SIN,
         CASE
           WHEN FB.DISCOUNTS <> FB.DISCOUNT_YEAR + FB.DISCOUNT_SMS_PLUS + FB.DISCOUNT_CALL + FB.DISCOUNT_COUNT_ON_PHONES + FB.DISCOUNT_OTHERS + FB.DISCOUNT_SOVINTEL THEN 1
           ELSE 0
         END ER_DISC,
         CASE
           WHEN FB.CALLS_ALL <> FB.CALLS_COUNTRY + FB.CALLS_SITY + FB.CALLS_LOCAL + FB.CALLS_SMS_MMS + FB.CALLS_GPRS + FB.CALLS_RUS_RPP THEN 1
           ELSE 0
         END ER_CALL,
         CASE
           WHEN FB.CALLS <> FB.CALLS_ALL + FB.ROUMING_INTERNATIONAL + FB.ROUMING_NATIONAL THEN 1
           ELSE 0
         END DBG_ROUM,
         FB.*         
    FROM DB_LOADER_FULL_FINANCE_BILL FB
    WHERE FB.BILL_SUM<>0
      AND (FB.BILL_SUM <> FB.ABONKA + FB.CALLS + FB.SINGLE_PAYMENTS + FB.DISCOUNTS
            OR FB.ABONKA <> FB.ABON_MAIN + FB.ABON_ADD + FB.ABON_OTHER
            OR ( NOT(FB.SINGLE_PAYMENTS = FB.SINGLE_MAIN + FB.SINGLE_ADD + FB.SINGLE_CHANGE_TARIFF + FB.SINGLE_TURN_ON_SERV
                                          + FB.SINGLE_CORRECTION_ROUMING + FB.SINGLE_INTRA_WEB + FB.SINGLE_OTHER
                      OR FB.SINGLE_PAYMENTS = FB.SINGLE_MAIN + FB.SINGLE_ADD + FB.SINGLE_CHANGE_TARIFF + FB.SINGLE_TURN_ON_SERV
                                              + FB.SINGLE_CORRECTION_ROUMING + FB.SINGLE_INTRA_WEB + FB.SINGLE_OTHER
                                              + FB.SINGLE_PENALTI + FB.SINGLE_VIEW_BLACK_LIST))
            OR FB.DISCOUNTS <> FB.DISCOUNT_YEAR + FB.DISCOUNT_SMS_PLUS + FB.DISCOUNT_CALL + FB.DISCOUNT_COUNT_ON_PHONES + FB.DISCOUNT_OTHERS + FB.DISCOUNT_SOVINTEL
            OR FB.CALLS <> FB.CALLS_ALL + FB.ROUMING_INTERNATIONAL + FB.ROUMING_NATIONAL
            OR FB.CALLS_ALL <> FB.CALLS_COUNTRY + FB.CALLS_SITY + FB.CALLS_LOCAL + FB.CALLS_SMS_MMS + FB.CALLS_GPRS + FB.CALLS_RUS_RPP);
               
--GRANT SELECT ON V_BILL_FULL_FINANCE_INCORRECT TO SIM_TRADE_ROLE;
               
--GRANT SELECT ON V_BILL_FULL_FINANCE_INCORRECT TO LONTANA_ROLE;
            
--GRANT SELECT ON V_BILL_FULL_FINANCE_INCORRECT TO CORP_MOBILE_ROLE;
               
--GRANT SELECT ON V_BILL_FULL_FINANCE_INCORRECT TO CORP_MOBILE_ROLE_RO;    