CREATE OR REPLACE VIEW V_BILL_FULL_FINANCE_DEBUG AS
  SELECT *
    FROM DB_LOADER_FULL_FINANCE_BILL FB
    WHERE FB.BILL_SUM<>0
      AND (FB.DISCOUNT_OTHERS <> 0
            OR FB.SINGLE_OTHER <> 0
            OR FB.ABON_OTHER <> 0);
               
--GRANT SELECT ON V_BILL_FULL_FINANCE_DEBUG TO SIM_TRADE_ROLE;
               
--GRANT SELECT ON V_BILL_FULL_FINANCE_DEBUG TO LONTANA_ROLE;
            
--GRANT SELECT ON V_BILL_FULL_FINANCE_DEBUG TO CORP_MOBILE_ROLE;
               
--GRANT SELECT ON V_BILL_FULL_FINANCE_DEBUG TO CORP_MOBILE_ROLE_RO;            