CREATE OR REPLACE VIEW V_BILL_FOR_CLIENT_DETAILS AS 
--Version = 2
SELECT V.ACCOUNT_ID,
       V.YEAR_MONTH,
       V.PHONE_NUMBER,
       TO_DATE(TO_CHAR(V.YEAR_MONTH)||'01', 'YYYYMMDD') DATE_BEGIN,
       LAST_DAY(TO_DATE(TO_CHAR(V.YEAR_MONTH)||'01', 'YYYYMMDD')) DATE_END,
       V.BILL_SUM_NEW BILL_SUM,
       V.ABON_TP_NEW SUBSCRIBER_PAYMENT_NEW,
       V.ABON_ADD_NEW SUBSCRIBER_PAYMENT_ADD_NEW,
       V.CALLS_LOCAL CALLS_LOCAL_COST,
       V.CALLS_SITY CALLS_OTHER_CITY_COST,
       V.CALLS_COUNTRY CALLS_OTHER_COUNTRY_COST,
       V.CALLS_GPRS INTERNET_COST,
       V.CALLS_SMS_MMS MESSAGES_COST,
       FB.ROUMING_NATIONAL NATIONAL_ROAMING_COST,
       FB.ROUMING_INTERNATIONAL OTHER_COUNTRY_ROAMING_COST,
       V.SINGLE_PAYMENTS_NEW SINGLE_PAYMENTS,
       V.DISCOUNT_NEW SUBSCRIBER_PAYMENT_ADD_VOZVRAT
  FROM V_BILL_FINANCE_FOR_CLIENTS V,
       DB_LOADER_FULL_FINANCE_BILL FB
  WHERE V.ACCOUNT_ID = FB.ACCOUNT_ID     
    AND V.YEAR_MONTH = FB.YEAR_MONTH
    AND V.PHONE_NUMBER = FB.PHONE_NUMBER
    AND FB.COMPLETE_BILL = 1
UNION ALL
SELECT B.ACCOUNT_ID,
       B.YEAR_MONTH,
       B.PHONE_NUMBER,
       B.DATE_BEGIN,
       B.DATE_END,
       V.BILL_SUM,
       V.SUBSCRIBER_PAYMENT_NEW,
       TRUNC(RECALC_CHARGE_COST(B.PHONE_NUMBER, B.SUBSCRIBER_PAYMENT_ADD+OPTION_CORRECT_SUM), 2) SUBSCRIBER_PAYMENT_ADD_NEW,
       TRUNC(RECALC_CHARGE_COST(B.PHONE_NUMBER, B.CALLS_LOCAL_COST), 2) CALLS_LOCAL_COST,
       TRUNC(RECALC_CHARGE_COST(B.PHONE_NUMBER, B.CALLS_OTHER_CITY_COST), 2) CALLS_OTHER_CITY_COST,
       TRUNC(RECALC_CHARGE_COST(B.PHONE_NUMBER, B.CALLS_OTHER_COUNTRY_COST), 2) CALLS_OTHER_COUNTRY_COST,
       TRUNC(RECALC_CHARGE_COST(B.PHONE_NUMBER, B.INTERNET_COST), 2) INTERNET_COST,
       TRUNC(RECALC_CHARGE_COST(B.PHONE_NUMBER, B.MESSAGES_COST), 2) MESSAGES_COST,
       TRUNC(RECALC_CHARGE_COST(B.PHONE_NUMBER, B.NATIONAL_ROAMING_COST), 2) NATIONAL_ROAMING_COST,
       TRUNC(RECALC_CHARGE_COST(B.PHONE_NUMBER, B.OTHER_COUNTRY_ROAMING_COST), 2) OTHER_COUNTRY_ROAMING_COST,
       CASE
         WHEN B.SUBSCRIBER_PAYMENT_MAIN + B.SINGLE_PAYMENTS < 0
           THEN TRUNC(RECALC_CHARGE_COST(B.PHONE_NUMBER, B.SINGLE_PAYMENTS * B.SUBSCRIBER_PAYMENT_ADD/(B.SUBSCRIBER_PAYMENT_MAIN + B.SUBSCRIBER_PAYMENT_ADD) ), 2)
         WHEN B.SINGLE_PAYMENTS>0 
           THEN TRUNC(RECALC_CHARGE_COST(B.PHONE_NUMBER, B.SINGLE_PAYMENTS ), 2)
         ELSE 0
       END SINGLE_PAYMENTS,
       V.SUBSCRIBER_PAYMENT_ADD_VOZVRAT
  FROM DB_LOADER_BILLS B,
       V_BILL_FOR_CLIENT V
  WHERE V.ACCOUNT_ID=B.ACCOUNT_ID
    AND V.YEAR_MONTH=B.YEAR_MONTH
    AND V.PHONE_NUMBER=B.PHONE_NUMBER
    AND NOT EXISTS (SELECT 1
                      FROM DB_LOADER_FULL_FINANCE_BILL FB
                      WHERE FB.ACCOUNT_ID = B.ACCOUNT_ID
                        AND FB.YEAR_MONTH = B.YEAR_MONTH
                        AND FB.PHONE_NUMBER = B.PHONE_NUMBER
                        AND FB.COMPLETE_BILL = 1);
    
--GRANT SELECT ON V_BILL_FOR_CLIENT_DETAILS TO CORP_MOBILE_ROLE;
    
--GRANT SELECT ON V_BILL_FOR_CLIENT_DETAILS TO CORP_MOBILE_ROLE_RO;
    
--GRANT SELECT ON V_BILL_FOR_CLIENT_DETAILS TO LONTANA_ROLE;
    
--GRANT SELECT ON V_BILL_FOR_CLIENT_DETAILS TO LONTANA_ROLE_RO;