CREATE OR REPLACE VIEW V_BILL_FINANCE_FOR_CLIENT_DET AS
--Versions = 1
  SELECT ACCOUNTS.LOGIN,
         FB.ACCOUNT_ID,
         FB.YEAR_MONTH,
         FB.PHONE_NUMBER,
         V.BILL_SUM_NEW,
         V.ABON_TP_NEW,
         V.ABON_ADD_NEW,
         V.DISCOUNT_NEW,
         V.SINGLE_PAYMENTS_NEW,
         FB.DISCOUNT_CALL,
         FB.DISCOUNT_SMS_PLUS,
         FB.SINGLE_CHANGE_TARIFF,
         FB.SINGLE_VIEW_BLACK_LIST,
         FB.SINGLE_CORRECTION_ROUMING,
         FB.SINGLE_INTRA_WEB,
         FB.SINGLE_PENALTI, 
         FB.SINGLE_TURN_ON_SERV,
         FB.SINGLE_OTHER,
         FB.CALLS_COUNTRY,
         FB.CALLS_SITY,
         FB.CALLS_LOCAL,
         FB.CALLS_SMS_MMS,
         FB.CALLS_GPRS,
         FB.CALLS_RUS_RPP,
         FB.ROUMING_NATIONAL,
         FB.ROUMING_INTERNATIONAL
    FROM DB_LOADER_FULL_FINANCE_BILL FB,
         V_BILL_FINANCE_FOR_CLIENTS V,
         ACCOUNTS
    WHERE FB.ACCOUNT_ID = V.ACCOUNT_ID(+)
      AND FB.YEAR_MONTH = V.YEAR_MONTH(+)
      AND FB.PHONE_NUMBER = V.PHONE_NUMBER(+)
      AND FB.ACCOUNT_ID = ACCOUNTS.ACCOUNT_ID(+);
    
--GRANT SELECT ON V_BILL_FINANCE_FOR_CLIENT_DET TO SIM_TRADE_ROLE;

--GRANT SELECT ON V_BILL_FINANCE_FOR_CLIENT_DET TO LONTANA_ROLE;

--GRANT SELECT ON V_BILL_FINANCE_FOR_CLIENT_DET TO CORP_MOBILE_ROLE;
     