CREATE OR REPLACE FORCE VIEW V_CALL_STAT_GROUP_BY_TYPES
AS
     SELECT C.YEAR_MONTH,
            C.SUBSCR_NO,
            AFC.IS_ROAMING,
            AFC.SERVICE_ID,
            AFC.C_ACT_CD,
            SUM (C.CALL_SUM) CALL_SUM,
            SUM (AMOUNT) AMOUNT,
            SUM (C.ZERO_COST_AMOUNT) ZERO_COST_AMOUNT,
            SUM (C.DATA_VOL) DATA_VOL,
            SUM (C.ZERO_COST_DATA_VOL) ZERO_COST_DATA_VOL,
            SUM (C.DUR) DUR,
            SUM (C.ZERO_COST_DUR) ZERO_COST_DUR
       FROM CALL_STATISTICS C, HOT_BILLING_CALL_AT_FT_CODE AFC
      WHERE C.AT_FT_CODE = AFC.AT_FT_CODE(+)
   --      AND C.YEAR_MONTH = :YEAR_MONTH
   --      AND C.SUBSCR_NO = :PHONE_NUMBER
   GROUP BY C.YEAR_MONTH,
            C.SUBSCR_NO,
            AFC.IS_ROAMING,
            AFC.SERVICE_ID,
            AFC.C_ACT_CD
   ORDER BY AFC.IS_ROAMING, AFC.SERVICE_ID, AFC.C_ACT_CD;


GRANT SELECT ON V_CALL_STAT_GROUP_BY_TYPES TO LONTANA_ROLE;

GRANT SELECT ON V_CALL_STAT_GROUP_BY_TYPES TO LONTANA_ROLE_RO;
