CREATE OR REPLACE VIEW USER_1C.V_CONTRACT_FOR_DILER AS
  SELECT C.CONTRACT_ID, 
         C.PHONE_NUMBER_FEDERAL, 
         C.CONTRACT_DATE,
         C.DATE_CREATED,
         CC.CONTRACT_CANCEL_DATE
    FROM LONTANA.CONTRACTS C, 
         LONTANA.CONTRACT_CANCELS CC      
    WHERE C.CONTRACT_ID = CC.CONTRACT_ID(+)
    ORDER BY C.CONTRACT_DATE asc, C.CONTRACT_ID ASC, C.PHONE_NUMBER_FEDERAL ASC, CC.CONTRACT_CANCEL_DATE ASC
     -- AND CC.CONTRACT_CANCEL_DATE IS NULL
     /* AND NOT EXISTS (SELECT 1
                        FROM LONTANA.DB_LOADER_ACCOUNT_PHONES DB
                        WHERE DB.PHONE_NUMBER = C.PHONE_NUMBER_FEDERAL
                          AND DB.ACCOUNT_ID = 225)*/;
    
grant select on LONTANA.contract_cancels to www_dealer; 
grant select on LONTANA.contracts to www_dealer; 
grant select on LONTANA.DB_LOADER_ACCOUNT_PHONES to www_dealer;  