CREATE OR REPLACE VIEW V_DISCOUNT_BILLS AS
  SELECT (SELECT MAX(YEAR_MONTH)
            FROM DB_LOADER_FULL_FINANCE_BILL FB2
            WHERE FB2.PHONE_NUMBER = FB.PHONE_NUMBER
              AND FB2.YEAR_MONTH < FB.YEAR_MONTH
              AND FB2.DISCOUNT_YEAR <> 0) AS YEAR_MONTH_DOSCOUNT,
         FB.*
    FROM DB_LOADER_FULL_FINANCE_BILL FB
    WHERE FB.BILL_SUM <> 0
      AND FB.YEAR_MONTH = (SELECT MAX(YEAR_MONTH)
                             FROM DB_LOADER_FULL_FINANCE_BILL)
      AND EXISTS (SELECT 1
                    FROM DB_LOADER_FULL_FINANCE_BILL FB2
                    WHERE FB2.PHONE_NUMBER = FB.PHONE_NUMBER
                      AND FB2.YEAR_MONTH < FB.YEAR_MONTH
                      AND FB2.DISCOUNT_YEAR <> 0)
      AND FB.DISCOUNT_YEAR = 0  
      AND FB.COMPLETE_BILL = 1;
      
--GRANT SELECT ON V_DISCOUNT_BILLS TO SIM_TRADE_ROLE;      