CREATE OR REPLACE VIEW V_DILER_ACCOUNT_DETAL_STAT AS
  SELECT AC.LOGIN, 
         T.YEAR_MONTH, 
         T.ACCOUNT_ID, 
         T.COUNT_PHONE, 
         (SELECT COUNT(*)
            FROM DB_LOADER_FULL_FINANCE_BILL FB
            WHERE FB.ACCOUNT_ID = T.ACCOUNT_ID
              AND FB.YEAR_MONTH = T.YEAR_MONTH
              AND FB.BILL_SUM > 0
              AND FB.COMPLETE_BILL = 1) COUNT_BILLS,
         (SELECT SUM(DS.SUM_COST)
            FROM DETAILS_INFO DI,
                 DETAIL_STATS DS
            WHERE DI.YEAR_MONTH = T.YEAR_MONTH
              AND DI.ACCOUNT_ID = T.ACCOUNT_ID
              AND DI.DETAIL_INFO_ID = DS.DETAIL_INFO_ID) LOAD_SUM_CALLS,
         (SELECT SUM(FB.CALLS_ALL + FB.ROUMING_NATIONAL + FB.ROUMING_INTERNATIONAL)
            FROM DB_LOADER_FULL_FINANCE_BILL FB
            WHERE FB.ACCOUNT_ID = T.ACCOUNT_ID
              AND FB.YEAR_MONTH = T.YEAR_MONTH
              AND FB.BILL_SUM > 0
              AND FB.COMPLETE_BILL = 1) BILL_SUM_CALLS
    FROM ACCOUNTS AC,  
         (SELECT DI.YEAR_MONTH, DI.ACCOUNT_ID, COUNT(1) COUNT_PHONE
            FROM DETAILS_INFO DI
            --WHERE DI.YEAR_MONTH = :YEAR_MONTH
            GROUP BY DI.YEAR_MONTH, DI.ACCOUNT_ID) T
    WHERE T.ACCOUNT_ID = AC.ACCOUNT_ID;
    
GRANT SELECT ON V_DILER_ACCOUNT_DETAL_STAT TO CORP_MOBILE_ROLE;