CREATE OR REPLACE FORCE VIEW V_FULL_BALANCE_BILLS AS
-- Version = 8
-- 10.04.2014. Крайнов. Учет звонков со стороннего CallBack
-- Крайнов. Поправка добавлення деталок, т.к. иногда дата списания деталки выходила за пределы периода списания. 
-- Крайнов. Добавление столбика с Новой абонкой, для учета.
  SELECT V_BILL_FINANCE_FOR_CLIENTS.PHONE_NUMBER,
         ACCOUNT_LOADED_BILLS.DATE_END AS BILL_DATE,
         CASE
           WHEN TRUNC(SYSDATE) <= ACCOUNT_LOADED_BILLS.DATE_CREDIT_END
                  AND (CHECK_PHONE_CREDIT (V_BILL_FINANCE_FOR_CLIENTS.PHONE_NUMBER, ACCOUNT_LOADED_BILLS.DATE_END) = 1)
             THEN V_BILL_FINANCE_FOR_CLIENTS.BILL_SUM_NEW
                   - V_BILL_FINANCE_FOR_CLIENTS.ABON_TP_NEW
                   - V_BILL_FINANCE_FOR_CLIENTS.ABON_ADD_NEW
                   - V_BILL_FINANCE_FOR_CLIENTS.DISCOUNT_NEW
           ELSE V_BILL_FINANCE_FOR_CLIENTS.BILL_SUM_NEW
         END AS BILL_SUM,
         CASE
           WHEN TRUNC(SYSDATE) <= ACCOUNT_LOADED_BILLS.DATE_CREDIT_END
                  AND (CHECK_PHONE_CREDIT (V_BILL_FINANCE_FOR_CLIENTS.PHONE_NUMBER, ACCOUNT_LOADED_BILLS.DATE_END) = 1)
             THEN 'Счёт оператора без аб. пл. с ' || TO_CHAR(ACCOUNT_LOADED_BILLS.DATE_BEGIN, 'DD.MM.YYYY')
                    || ' по ' || TO_CHAR(ACCOUNT_LOADED_BILLS.DATE_END, 'DD.MM.YYYY')
           ELSE 'Счёт оператора с ' || TO_CHAR(ACCOUNT_LOADED_BILLS.DATE_BEGIN, 'DD.MM.YYYY')
                  || ' по ' || TO_CHAR(ACCOUNT_LOADED_BILLS.DATE_END, 'DD.MM.YYYY')
         END AS REMARK,
         V_BILL_FINANCE_FOR_CLIENTS.COMPLETE_BILL AS BILL_CHECKED,
         V_BILL_FINANCE_FOR_CLIENTS.ABON_TP_NEW AS ABON_TP_NEW
    FROM V_BILL_FINANCE_FOR_CLIENTS,
         ACCOUNT_LOADED_BILLS
    WHERE V_BILL_FINANCE_FOR_CLIENTS.ACCOUNT_ID = ACCOUNT_LOADED_BILLS.ACCOUNT_ID
      AND V_BILL_FINANCE_FOR_CLIENTS.YEAR_MONTH = ACCOUNT_LOADED_BILLS.YEAR_MONTH
      AND ACCOUNT_LOADED_BILLS.LOAD_BILL_IN_BALANCE = 1
  UNION ALL
  SELECT V_BILL_FOR_CLIENT.PHONE_NUMBER,
         V_BILL_FOR_CLIENT.DATE_END AS BILL_DATE,
         CASE
           WHEN TRUNC(SYSDATE) <= ACCOUNT_LOADED_BILLS.DATE_CREDIT_END
                 AND (CHECK_PHONE_CREDIT (V_BILL_FOR_CLIENT.PHONE_NUMBER, ACCOUNT_LOADED_BILLS.DATE_END) = 1)
           THEN V_BILL_FOR_CLIENT.BILL_SUM
                 - V_BILL_FOR_CLIENT.SUBSCRIBER_PAYMENT_NEW
                 - V_BILL_FOR_CLIENT.SUBSCRIBER_PAYMENT_ADD_OLD
                 - V_BILL_FOR_CLIENT.SUBSCRIBER_PAYMENT_ADD_VOZVRAT
           ELSE V_BILL_FOR_CLIENT.BILL_SUM
         END AS BILL_SUM,
         CASE
           WHEN TRUNC(SYSDATE) <= ACCOUNT_LOADED_BILLS.DATE_CREDIT_END
                 AND (CHECK_PHONE_CREDIT (V_BILL_FOR_CLIENT.PHONE_NUMBER, ACCOUNT_LOADED_BILLS.DATE_END) = 1)
           THEN 'Счёт оператора без аб. пл. с ' || TO_CHAR (V_BILL_FOR_CLIENT.DATE_BEGIN, 'DD.MM.YYYY')
                 || ' по ' || TO_CHAR (V_BILL_FOR_CLIENT.DATE_END, 'DD.MM.YYYY')
           ELSE 'Счёт оператора с ' || TO_CHAR (V_BILL_FOR_CLIENT.DATE_BEGIN, 'DD.MM.YYYY')
                 || ' по ' || TO_CHAR (V_BILL_FOR_CLIENT.DATE_END, 'DD.MM.YYYY')
         END AS REMARK,
         NVL(V_BILL_FOR_CLIENT.BILL_CHECKED, 0) AS BILL_CHECKED,
         V_BILL_FOR_CLIENT.SUBSCRIBER_PAYMENT_NEW AS ABON_TP_NEW
    FROM V_BILL_FOR_CLIENT, 
         V_BILL_FINANCE_FOR_CLIENTS,
         ACCOUNT_LOADED_BILLS
    WHERE V_BILL_FOR_CLIENT.ACCOUNT_ID = ACCOUNT_LOADED_BILLS.ACCOUNT_ID
      AND V_BILL_FOR_CLIENT.YEAR_MONTH = ACCOUNT_LOADED_BILLS.YEAR_MONTH
      AND ACCOUNT_LOADED_BILLS.LOAD_BILL_IN_BALANCE = 1
      AND V_BILL_FOR_CLIENT.ACCOUNT_ID = V_BILL_FINANCE_FOR_CLIENTS.ACCOUNT_ID(+)
      AND V_BILL_FOR_CLIENT.YEAR_MONTH = V_BILL_FINANCE_FOR_CLIENTS.YEAR_MONTH(+)
      AND V_BILL_FOR_CLIENT.PHONE_NUMBER = V_BILL_FINANCE_FOR_CLIENTS.PHONE_NUMBER(+)
      AND V_BILL_FINANCE_FOR_CLIENTS.PHONE_NUMBER IS NULL
  UNION ALL
  SELECT DB_LOADER_PHONE_STAT.PHONE_NUMBER,
         CASE
           WHEN LAST_DAY(TO_DATE(TO_CHAR(DB_LOADER_PHONE_STAT.YEAR_MONTH || '01'), 'YYYYMMDD')) > DB_LOADER_PHONE_STAT.LAST_CHECK_DATE_TIME THEN 
             CASE
               WHEN TO_DATE(TO_CHAR(DB_LOADER_PHONE_STAT.YEAR_MONTH || '01'), 'YYYYMMDD') > DB_LOADER_PHONE_STAT.LAST_CHECK_DATE_TIME THEN
                 TO_DATE(TO_CHAR(DB_LOADER_PHONE_STAT.YEAR_MONTH || '01'), 'YYYYMMDD')
               ELSE TRUNC(DB_LOADER_PHONE_STAT.LAST_CHECK_DATE_TIME)
             END 
           ELSE LAST_DAY(TO_DATE(TO_CHAR(DB_LOADER_PHONE_STAT.YEAR_MONTH || '01'), 'YYYYMMDD'))
         END AS BILL_DATE,
         RECALC_CHARGE_COST(DB_LOADER_PHONE_STAT.PHONE_NUMBER, DB_LOADER_PHONE_STAT.ESTIMATE_SUM - nvl(DB_LOADER_PHONE_STAT.CALLBACKCOST, 0) ) AS BILL_SUM,
         'Детализация звонков за ' || LOWER(TO_CHAR(TO_DATE(DB_LOADER_PHONE_STAT.YEAR_MONTH, 'YYYYMM'), 'MM.YYYY'))
           || ' (на ' || TO_CHAR(DB_LOADER_PHONE_STAT.LAST_CHECK_DATE_TIME, 'DD.MM.YYYY HH24:MI') || ')',
         1 AS BILL_CHECKED,
         0 AS ABON_TP_NEW
    FROM DB_LOADER_PHONE_STAT
    WHERE NOT EXISTS
                (SELECT 1
                   FROM ACCOUNT_LOADED_BILLS
                  WHERE DB_LOADER_PHONE_STAT.ACCOUNT_ID = ACCOUNT_LOADED_BILLS.ACCOUNT_ID
                    AND DB_LOADER_PHONE_STAT.YEAR_MONTH = ACCOUNT_LOADED_BILLS.YEAR_MONTH
                    AND ACCOUNT_LOADED_BILLS.LOAD_BILL_IN_BALANCE = 1)
  UNION ALL
  SELECT DB_LOADER_PHONE_STAT.PHONE_NUMBER,
         CASE
           WHEN LAST_DAY(TO_DATE(TO_CHAR(DB_LOADER_PHONE_STAT.YEAR_MONTH || '01'), 'YYYYMMDD')) > DB_LOADER_PHONE_STAT.LAST_CHECK_DATE_TIME THEN 
             CASE
               WHEN TO_DATE(TO_CHAR(DB_LOADER_PHONE_STAT.YEAR_MONTH || '01'), 'YYYYMMDD') > DB_LOADER_PHONE_STAT.LAST_CHECK_DATE_TIME THEN
                 TO_DATE(TO_CHAR(DB_LOADER_PHONE_STAT.YEAR_MONTH || '01'), 'YYYYMMDD')
               ELSE TRUNC(DB_LOADER_PHONE_STAT.LAST_CHECK_DATE_TIME)
             END 
           ELSE LAST_DAY(TO_DATE(TO_CHAR(DB_LOADER_PHONE_STAT.YEAR_MONTH || '01'), 'YYYYMMDD'))
         END AS BILL_DATE,
         RECALC_CHARGE_COST(DB_LOADER_PHONE_STAT.PHONE_NUMBER, DB_LOADER_PHONE_STAT.CALLBACKCOST ) AS BILL_SUM,
         'Стоимость звонков по Call Back за ' || LOWER(TO_CHAR(TO_DATE(DB_LOADER_PHONE_STAT.YEAR_MONTH, 'YYYYMM'), 'MM.YYYY'))
           || ' (на ' || TO_CHAR(DB_LOADER_PHONE_STAT.LAST_CHECK_DATE_TIME, 'DD.MM.YYYY HH24:MI') || ')',
         0 AS BILL_CHECKED,
         0 AS ABON_TP_NEW
    FROM DB_LOADER_PHONE_STAT
    WHERE nvl(DB_LOADER_PHONE_STAT.CALLBACKCOST, 0) <> 0;

GRANT SELECT ON V_FULL_BALANCE_BILLS TO CORP_MOBILE_ROLE;

GRANT SELECT ON V_FULL_BALANCE_BILLS TO CORP_MOBILE_ROLE_RO;