CREATE OR REPLACE VIEW V_LAST_ACCOUNT_LOAD_LOGS AS
SELECT 
--#Version=2
  ACCOUNTS.ACCOUNT_ID,
  ACCOUNTS.ACCOUNT_NUMBER,
  ACCOUNT_LOAD_TYPES.ACCOUNT_LOAD_TYPE_NAME,
  GET_LAST_ACC_LOAD_LOGS_ERRORS(ACCOUNTS.account_id, ACCOUNT_LOAD_TYPES.ACCOUNT_LOAD_TYPE_ID) ERROR_TEXTS
FROM ACCOUNTS
, ACCOUNT_LOAD_TYPES
ORDER BY ACCOUNTS.ACCOUNT_ID, ACCOUNT_LOAD_TYPES.ACCOUNT_LOAD_TYPE_ID