CREATE OR REPLACE VIEW V_PHONE_LIMITS AS
-- Version = 1
--
-- 1. 2015.09.28. Крайнов. Создание.
--
  SELECT C.PHONE_NUMBER_FEDERAL,
         C.CONTRACT_ID,
         TR.TARIFF_ID,
         AC.ACCOUNT_ID, 
         NVL(C.DISCONNECT_LIMIT, 0) DISCONNECT_LIMIT,
         NVL(C.DISCONNECT_LIMIT, 0)
         + CASE
             WHEN (NVL(C.HAND_BLOCK,0)=1) THEN NVL(C.BALANCE_BLOCK_HAND_BLOCK, 0)
             ELSE NVL(TR.BALANCE_BLOCK, NVL(AC.BALANCE_BLOCK, 0))
           END BLOCK_LIMIT,
         NVL(C.DISCONNECT_LIMIT, 0) 
         + NVL(C.CONNECT_LIMIT, NVL(TR.BALANCE_UNBLOCK, 0)) UNBLOCK_LIMIT
    FROM V_CONTRACTS C,
         TARIFFS TR,
         ACCOUNTS AC
    WHERE C.CONTRACT_CANCEL_DATE IS NULL
      AND TR.TARIFF_ID(+) = C.TARIFF_ID
      AND AC.ACCOUNT_ID(+) = CONVERT_PCKG.GET_ACCOUNT_ID_BY_PHONE(C.PHONE_NUMBER_FEDERAL)
      AND C.PHONE_NUMBER_FEDERAL IN (SELECT D.PHONE_NUMBER
                                       FROM DB_LOADER_ACCOUNT_PHONES D
                                       WHERE D.YEAR_MONTH = TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMM')) 
                                         AND D.ACCOUNT_ID <> 225);                                 