CREATE OR REPLACE VIEW V_REPORT_SUMMARY_MINUTES
AS
SELECT
--#VERSION=1
  V_REPORT_PHONE_STAT.*
FROM
  V_REPORT_PHONE_STAT,
  TARIFFS
WHERE
  V_REPORT_PHONE_STAT.TARIFF_ID=TARIFFS.TARIFF_ID
  -- Количество бесплатных минут превышает лимит, заданный в справочнике.
  AND V_REPORT_PHONE_STAT.ZEROCOST_OUTCOME_MINUTES > TARIFFS.FREE_MONTH_MINUTES_CNT_FOR_RPT