CREATE OR REPLACE VIEW V_SIM_CURRENT_PHONE_OPTIONS AS
--
-- Vresion=1
--
SELECT SIM_CURRENT_PHONE_OPTIONS.DATE_OPTION_CHECK,
       SIM_CURRENT_PHONE_OPTIONS.PHONE_NUMBER,
       NVL(SIM_PHONE_OPTION_TYPE.OPTION_NAME, SIM_CURRENT_PHONE_OPTIONS.OPTION_CODE) OPTION_NAME
  FROM SIM_CURRENT_PHONE_OPTIONS,
       SIM_PHONE_OPTION_TYPE
  WHERE SIM_CURRENT_PHONE_OPTIONS.OPTION_CODE=SIM_PHONE_OPTION_TYPE.SERVICE_ID(+);