CREATE OR REPLACE VIEW V_YEAR_MONTH_BALANCE AS
--
--Version=1
--
SELECT DB_LOADER_BILLS.ACCOUNT_ID,
       DB_LOADER_BILLS.PHONE_NUMBER,
       DB_LOADER_BILLS.YEAR_MONTH,
       GET_ABONENT_BALANCE(PHONE_NUMBER, ADD_MONTHS(TO_DATE(TO_CHAR(DB_LOADER_BILLS.YEAR_MONTH) || '01','YYYYMMDD')-1/(24*60*60),1)) BALANCE,
       ADD_MONTHS(TO_DATE(TO_CHAR(DB_LOADER_BILLS.YEAR_MONTH) || '01','YYYYMMDD')-1/(24*60*60),1) BALANCE_DATE
  FROM DB_LOADER_BILLS
  WHERE DB_LOADER_BILLS.PHONE_NUMBER<>'0000000000';