CREATE OR REPLACE VIEW V_BALANCES_ON_END_MONTHS_3 AS
--Version=7
  SELECT (SELECT AC.LOGIN
            FROM ACCOUNTS AC,
                 DB_LOADER_ACCOUNT_PHONES AP
            WHERE AP.PHONE_NUMBER = V.PHONE_NUMBER
              AND AP.YEAR_MONTH = TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMM'))
              AND AP.ACCOUNT_ID = AC.ACCOUNT_ID) LOGIN,
         V.YEAR_MONTH,
         V.PHONE_NUMBER,
         V.DATE_CHECK AS DATE_BALANCE,
         GET_ABONENT_BALANCE(V.PHONE_NUMBER, V.DATE_CHECK) AS BALANCE,
         HI.PHONE_IS_ACTIVE,
         HI.BEGIN_DATE,
         V.ABON_TP_NEW SUBSCRIBER_PAYMENT_NEW,
         CASE
           WHEN (V.ALL_CALLS > 0) OR (V.STAT_NAL_CALL > 0) 
             THEN 1
           ELSE  
             CHECK_DETAIL_EXISTS(V.year_month, V.phone_number)
         END ACTIV,
         V.ALL_CALLS,
         DC.DILER_CALLS,
         V.BILL_SUM_NEW,
         V.BILL_SUM_NEW - V.ALL_CALLS + DC.DILER_CALLS DILER_SUM,
         (SELECT TARIFF_NAME
            FROM TARIFFS
            WHERE TARIFF_ID = GET_PHONE_TARIFF_ID(V.PHONE_NUMBER, HI.CELL_PLAN_CODE, V.DATE_CHECK)) TARIFF_NAME
    FROM V_BALANCES_ON_END_MONTHS_2 V,
         DB_LOADER_ACCOUNT_PHONE_HISTS HI,
         CONTRACTS,
         CONTRACT_CANCELS,
         DILER_CALL_FOR_PHONE DC
    WHERE V.PHONE_NUMBER=CONTRACTS.PHONE_NUMBER_FEDERAL(+)
      AND V.YEAR_MONTH>=TO_NUMBER(TO_CHAR(CONTRACTS.CONTRACT_DATE,'YYYYMM'))
      AND CONTRACTS.CONTRACT_ID=CONTRACT_CANCELS.CONTRACT_ID(+)
      AND V.YEAR_MONTH<=NVL(TO_NUMBER(TO_CHAR(CONTRACT_CANCELS.CONTRACT_CANCEL_DATE,'YYYYMM')),205012)
      AND V.PHONE_NUMBER=HI.PHONE_NUMBER(+)
      AND HI.END_DATE>=SYSDATE
      AND V.year_month = DC.YEAR_MONTH (+)
      AND V.phone_number = DC.PHONE_NUMBER (+);  
    
GRANT SELECT ON V_BALANCES_ON_END_MONTHS_3 TO LONTANA_ROLE;    