CREATE OR REPLACE VIEW V_BILL_ABON_PER_FOR_CLIENT AS
  SELECT T1.ACCOUNT_ID,
         T1.YEAR_MONTH,
         T1.PHONE_NUMBER,
         T1.DATE_BEGIN,
         T1.DATE_END,
         T1.TARIFF_CODE,
         T1.ABON_MAIN AS ABON_MAIN_OLD,
         ROUND(T1.ABON_MAIN * NVL(TARIFFS.CALC_KOEFF, 1)
                + T1.COEFF_MONTH * NVL(TARIFFS.TARIFF_ADD_COST, 0), 4) ABON_MAIN,
         T1.ABON_ADD,
         NVL(TARIFFS.CALC_KOEFF, 1) CALC_KOEFF,
         NVL(TARIFFS.TARIFF_ADD_COST, 0) TARIFF_ADD_COST,
         TARIFFS.TARIFF_ID,
         TARIFFS.TARIFF_NAME
    FROM (SELECT AP.*,
                 GET_PHONE_TARIFF_ID(AP.PHONE_NUMBER, AP.TARIFF_CODE, AP.DATE_BEGIN + (AP.DATE_END - AP.DATE_BEGIN + 1) / 2) AS TARIFF_ID,
                 (AP.DATE_END - AP.DATE_BEGIN + 1)/(LAST_DAY(AP.DATE_BEGIN) - TO_DATE(TO_CHAR(AP.DATE_BEGIN, 'YYYYMM')||'01', 'YYYYMMDD') + 1) COEFF_MONTH
            FROM DB_LOADER_FULL_BILL_ABON_PER AP) T1,
         TARIFFS
    WHERE T1.TARIFF_ID=TARIFFS.TARIFF_ID(+);
               
--GRANT SELECT ON V_BILL_ABON_PER_FOR_CLIENT TO SIM_TRADE_ROLE;
               
--GRANT SELECT ON V_BILL_ABON_PER_FOR_CLIENT TO LONTANA_ROLE;
            
--GRANT SELECT ON V_BILL_ABON_PER_FOR_CLIENT TO CORP_MOBILE_ROLE;
               
--GRANT SELECT ON V_BILL_ABON_PER_FOR_CLIENT TO CORP_MOBILE_ROLE_RO;    