CREATE OR REPLACE FORCE VIEW V_BILL_FINANCE_FOR_GROUP_DET AS
--#Version=1

SELECT B.*, C.*
FROM 
  V_BILL_FINANCE_FOR_CLIENT_DET B, V_CONTRACTS C
WHERE B.PHONE_NUMBER = C.PHONE_NUMBER_FEDERAL
  AND C.CONTRACT_DATE < ADD_MONTHS(TO_DATE(b.YEAR_MONTH||'01', 'yyyymmdd'), 1)
  AND (C.CONTRACT_CANCEL_DATE IS NULL OR C.CONTRACT_CANCEL_DATE >= TO_DATE(b.YEAR_MONTH||'01', 'yyyymmdd'))
  AND C.GROUP_ID IS NOT NULL
/

--GRANT SELECT ON V_BILL_FINANCE_FOR_GROUP_DET TO CORP_MOBILE_ROLE;
--GRANT SELECT ON V_BILL_FINANCE_FOR_GROUP_DET TO CORP_MOBILE_ROLE_RO;