CREATE OR REPLACE VIEW V_BILL_FOR_CLIENT_DETAILS AS 
--Version = 3
--
--v3. Афросин 23,04,2015 Переделал вьюху на таблицу TARIFER_BILL_FOR_CLIENTS 
--
SELECT 
 null account_id,
    YEAR_MONTH,
    PHONE_NUMBER,
    TO_DATE(TO_CHAR(YEAR_MONTH)||'01', 'YYYYMMDD') DATE_BEGIN,
    LAST_DAY(TO_DATE(TO_CHAR(YEAR_MONTH)||'01', 'YYYYMMDD')) DATE_END,
    BILL_SUMM  BILL_SUM,
    ABON_TP SUBSCRIBER_PAYMENT_NEW,
    ABON_ADD SUBSCRIBER_PAYMENT_ADD_NEW,
    CALLS_LOCAL CALLS_LOCAL_COST,
    CALLS_SITY CALLS_OTHER_CITY_COST,
    CALLS_COUNTRY CALLS_OTHER_COUNTRY_COST,
    CALLS_GPRS INTERNET_COST,
    CALLS_SMS_MMS MESSAGES_COST,
    ROUMING_NATIONAL NATIONAL_ROAMING_COST,
    ROUMING_INTERNATIONAL OTHER_COUNTRY_ROAMING_COST,
    SINGLE_PAYMENTS,
    0 SUBSCRIBER_PAYMENT_ADD_VOZVRAT
    
  FROM TARIFER_BILL_FOR_CLIENTS

--GRANT SELECT ON V_BILL_FOR_CLIENT_DETAILS TO CORP_MOBILE_ROLE;
    
--GRANT SELECT ON V_BILL_FOR_CLIENT_DETAILS TO CORP_MOBILE_ROLE_RO;
