CREATE OR REPLACE VIEW V_BILL_FULL_ABON_PER_INCORRECT AS
  SELECT *
    FROM DB_LOADER_FULL_FINANCE_BILL FB
    WHERE FB.BILL_SUM <> 0
      AND FB.YEAR_MONTH >= TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE, -4), 'yyyymm'))
      AND FB.ABONKA <> 0
      AND FB.ABONKA <> (SELECT NVL(SUM(AP.ABON_ALL), 0)
                          FROM DB_LOADER_FULL_BILL_ABON_PER AP
                          WHERE AP.ACCOUNT_ID = FB.ACCOUNT_ID
                            AND AP.YEAR_MONTH = FB.YEAR_MONTH
                            AND AP.PHONE_NUMBER = FB.PHONE_NUMBER
                            AND (NVL(AP.BAN, 0) = NVL(FB.BAN, 0) OR FB.BAN = -1));
               
--GRANT SELECT ON V_BILL_FULL_ABON_PER_INCORRECT TO SIM_TRADE_ROLE;
               
--GRANT SELECT ON V_BILL_FULL_ABON_PER_INCORRECT TO LONTANA_ROLE;
            
--GRANT SELECT ON V_BILL_FULL_ABON_PER_INCORRECT TO CORP_MOBILE_ROLE;
               
--GRANT SELECT ON V_BILL_FULL_ABON_PER_INCORRECT TO CORP_MOBILE_ROLE_RO;    