CREATE OR REPLACE VIEW V_CALENDAR AS
  SELECT TRUNC(SYSDATE, 'YYYY') + (LEVEL - 1) AS the_day
    FROM DUAL
    CONNECT BY LEVEL <= TO_NUMBER(TO_CHAR(LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE, 'YYYY'), 11)), 'DDD'))
  UNION
  SELECT TRUNC(ADD_MONTHS(SYSDATE, -12), 'YYYY') + (LEVEL - 1) AS the_day
    FROM DUAL
    CONNECT BY LEVEL <= TO_NUMBER(TO_CHAR(LAST_DAY(ADD_MONTHS(TRUNC(ADD_MONTHS (SYSDATE, -12), 'YYYY'), 11)), 'DDD'));