CREATE OR REPLACE VIEW V_CALL_STAT_GROUP_BY_TYPES AS
  SELECT C.YEAR_MONTH, C.SUBSCR_NO, AFC.IS_ROAMING, 
         AFC.SERVICE_ID, AFC.C_ACT_CD, SUM(C.CALL_SUM) CALL_SUM, 
         SUM(C.DATA_VOL) DATA_VOL, SUM(C.ZERO_COST_DATA_VOL) ZERO_COST_DATA_VOL, 
         SUM(C.AT_C_DR_SC) AT_C_DR_SC,  SUM(C.ZERO_COST_AT_C_DR_SC) ZERO_COST_AT_C_DR_SC,
         SUM(C.AT_CDRRD_M) AT_CDRRD_M,  SUM(C.ZERO_COST_AT_CDRRD_M) ZERO_COST_AT_CDRRD_M,
         SUM(AMOUNT) AMOUNT, SUM(C.ZERO_COST_AMOUNT) ZERO_COST_AMOUNT
    FROM CALL_STATISTICS C,
         HOT_BILLING_CALL_AT_FT_CODE AFC
    WHERE C.AT_FT_CODE = AFC.AT_FT_CODE(+)
    GROUP BY C.YEAR_MONTH, C.SUBSCR_NO, AFC.IS_ROAMING, AFC.SERVICE_ID, AFC.C_ACT_CD
    ORDER BY AFC.IS_ROAMING, AFC.SERVICE_ID, AFC.C_ACT_CD;


GRANT SELECT ON V_CALL_STAT_GROUP_BY_TYPES TO CORP_MOBILE_ROLE; 

GRANT SELECT ON V_CALL_STAT_GROUP_BY_TYPES TO CORP_MOBILE_ROLE_RO; 
