CREATE OR REPLACE VIEW V_CONTRACT_PRINT AS
SELECT
--#Version=1 
      AB.SURNAME, AB.NAME, AB.PATRONYMIC, AB.BDATE
      ,AB.PASSPORT_SER, AB.PASSPORT_NUM, AB.PASSPORT_GET, AB.PASSPORT_DATE
      ,ÑNT_CITIZEN.COUNTRY_NAME COUNTRY_CITIZEN
      ,CN.COUNTRY_NAME
      ,RG.REGION_NAME
      ,AB.CITY_NAME
      ,AB.STREET_NAME
      ,AB.HOUSE
      ,AB.KORPUS
      ,AB.APARTMENT
      ,AB.CODE_WORD
      ,AB.CONTACT_INFO
      ,O.OPERATOR_NAME
      ,TR.TARIFF_NAME
      ,TR.CONNECT_PRICE
      ,TR.ADVANCE_PAYMENT
      ,C.RECEIVED_SUM TOTAL
      ,C.*
  FROM CONTRACTS C
      ,ABONENTS AB
      ,COUNTRIES ÑNT_CITIZEN
      ,COUNTRIES CN
      ,REGIONS RG
      ,OPERATORS O
      ,TARIFFS TR
 WHERE C.ABONENT_ID = AB.ABONENT_ID (+)
   AND AB.CITIZENSHIP = ÑNT_CITIZEN.COUNTRY_ID (+)
   AND AB.COUNTRY_ID = CN.COUNTRY_ID (+) 
   AND AB.REGION_ID = RG.REGION_ID (+)
   AND C.OPERATOR_ID = O.OPERATOR_ID (+)
   AND C.TARIFF_ID = TR.TARIFF_ID (+)
/
