CREATE OR REPLACE VIEW V_HISTORY_ACTIV_PHONE AS
  SELECT H.PHONE_NUMBER,
         TO_CHAR(H.BEGIN_DATE, 'yyyymm' ) BEGIN_YM,
         TO_CHAR(H.END_DATE, 'yyyymm' ) END_YM
    FROM DB_LOADER_ACCOUNT_PHONE_HISTS H
    WHERE H.PHONE_IS_ACTIVE = 1;
    
GRANT SELECT ON V_HISTORY_ACTIV_PHONE TO CORP_MOBILE_ROLE;
    
GRANT SELECT ON V_HISTORY_ACTIV_PHONE TO CORP_MOBILE_ROLE_RO;