CREATE OR REPLACE VIEW V_PHONE_NUMBERS_FOR_UNLOCK AS
--Version=1
SELECT 
    PHONE_NUMBER_FEDERAL,
    BALANCE,
    SURNAME||' '||NAME||' '||PATRONYMIC FIO,
    DISCONNECT_LIMIT   
  FROM v_abonent_balances,TARIFFS
  WHERE loader_script_name is not null
        AND TARIFFS.TARIFF_ID=v_abonent_balances.TARIFF_ID
        and BALANCE-NVL(v_abonent_balances.DISCONNECT_LIMIT, 0)>NVL(v_abonent_balances.CONNECT_LIMIT, NVL(TARIFFS.BALANCE_UNBLOCK,0)) 
        --AND  rownum <= 1 
        and phone_is_active_code=0 
        and Hand_block=0
        AND NOT EXISTS( 
          SELECT 1 FROM AUTO_UNBLOCKED_PHONE WHERE 
          v_abonent_balances.PHONE_NUMBER_FEDERAL=AUTO_UNBLOCKED_PHONE.PHONE_NUMBER
          -- 6 HOUR
          AND  (AUTO_UNBLOCKED_PHONE.UNBLOCK_DATE_TIME > SYSDATE-6/24)
          and AUTO_UNBLOCKED_PHONE.Note IS NULL 
        )
  UNION ALL
  SELECT V_ALL_NUMBERS_OUT_CONTRACTS.PHONE_NUMBER PHONE_NUMBER_FEDERAL,
         GET_ABONENT_BALANCE(V_ALL_NUMBERS_OUT_CONTRACTS.PHONE_NUMBER) BALANCE,
         '' FIO,
         NULL DISCONNECT_LIMIT
    FROM V_ALL_NUMBERS_OUT_CONTRACTS
    WHERE V_ALL_NUMBERS_OUT_CONTRACTS.PHONE_IS_ACTIVE=0
      AND GET_ABONENT_BALANCE(V_ALL_NUMBERS_OUT_CONTRACTS.PHONE_NUMBER)>0
      AND NOT EXISTS( 
          SELECT 1 FROM AUTO_UNBLOCKED_PHONE WHERE 
          V_ALL_NUMBERS_OUT_CONTRACTS.PHONE_NUMBER=AUTO_UNBLOCKED_PHONE.PHONE_NUMBER
          -- 6 HOUR
          AND  (AUTO_UNBLOCKED_PHONE.UNBLOCK_DATE_TIME > SYSDATE-6/24)
          and AUTO_UNBLOCKED_PHONE.Note IS NULL 
        );