CREATE OR REPLACE VIEW V_PHONE_NUMBER_CREDITS AS
  SELECT C.PHONE_NUMBER_FEDERAL,
         A.SURNAME||' '||A.NAME||' '||A.PATRONYMIC FIO,
         C.DISCONNECT_LIMIT,
         T.BALANCE_BLOCK_CREDIT
    FROM CONTRACTS C,
         ABONENTS A,
         TARIFFS T
    WHERE C.IS_CREDIT_CONTRACT=1
      AND C.ABONENT_ID=A.ABONENT_ID(+)
      AND C.TARIFF_ID=T.TARIFF_ID(+)
      AND C.CONTRACT_ID NOT IN (
            SELECT CC.CONTRACT_ID
              FROM CONTRACT_CANCELS CC)
      AND C.PHONE_NUMBER_FEDERAL NOT IN (
            SELECT CNS.PHONE_NUMBER
              FROM CREDIT_NOTICE_SEND CNS
              WHERE TRUNC(CNS.DATE_TIME_CREDIT_NOTICE)=TRUNC(SYSDATE));

--GRANT SELECT ON V_PHONE_NUMBER_CREDITS TO CORP_MOBILE_ROLE;   

--GRANT SELECT ON V_PHONE_NUMBER_CREDITS TO CORP_MOBILE_ROLE_RO;                    