CREATE OR REPLACE VIEW V_PHONE_NUMBERS_FOR_BLOCK AS
--Version=1
SELECT 
    v_abonent_balances.PHONE_NUMBER_FEDERAL,
    v_abonent_balances.BALANCE,
    v_abonent_balances.SURNAME || ' ' || v_abonent_balances.NAME || ' ' || v_abonent_balances.PATRONYMIC FIO,
    v_abonent_balances.DISCONNECT_LIMIT,
    ACCOUNTS.BLOCK_NOTICE_TEXT,
    ACCOUNTS.BALANCE_BLOCK,
    ACCOUNTS.ACCOUNT_ID
  FROM v_abonent_balances,ACCOUNTS,TARIFFS
  WHERE loader_script_name is not null
    AND V_ABONENT_BALANCES.ACCOUNT_ID=ACCOUNTS.ACCOUNT_ID 
    AND TARIFFS.TARIFF_ID=v_abonent_balances.TARIFF_ID
    and (BALANCE-NVL(v_abonent_balances.DISCONNECT_LIMIT, 0) < NVL(TARIFFS.BALANCE_BLOCK, NVL(ACCOUNTS.BALANCE_BLOCK, 0))) 
    and phone_is_active_code=1 
    AND NOT EXISTS( 
    SELECT 1 FROM AUTO_BLOCKED_PHONE WHERE 
    v_abonent_balances.PHONE_NUMBER_FEDERAL=AUTO_BLOCKED_PHONE.PHONE_NUMBER
    -- Не более 6 часов паузы
    AND  (AUTO_BLOCKED_PHONE.BLOCK_DATE_TIME > sysdate-6/24)
    and AUTO_BLOCKED_PHONE.Note IS NULL)
  UNION ALL
  SELECT V_ALL_NUMBERS_OUT_CONTRACTS.PHONE_NUMBER PHONE_NUMBER_FEDERAL,
         GET_ABONENT_BALANCE(V_ALL_NUMBERS_OUT_CONTRACTS.PHONE_NUMBER) BALANCE,
         '' FIO,
         NULL DISCONNECT_LIMIT,
         ACCOUNTS.BLOCK_NOTICE_TEXT,
         ACCOUNTS.BALANCE_BLOCK,
         ACCOUNTS.ACCOUNT_ID
    FROM V_ALL_NUMBERS_OUT_CONTRACTS, ACCOUNTS, DB_LOADER_ACCOUNT_PHONES
    WHERE V_ALL_NUMBERS_OUT_CONTRACTS.PHONE_IS_ACTIVE=1
      AND V_ALL_NUMBERS_OUT_CONTRACTS.PHONE_NUMBER=DB_LOADER_ACCOUNT_PHONES.PHONE_NUMBER
      AND DB_LOADER_ACCOUNT_PHONES.YEAR_MONTH=TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMM'))
      AND DB_LOADER_ACCOUNT_PHONES.ACCOUNT_ID=ACCOUNTS.ACCOUNT_ID
      AND GET_ABONENT_BALANCE(V_ALL_NUMBERS_OUT_CONTRACTS.PHONE_NUMBER)<ACCOUNTS.BALANCE_BLOCK
      AND NOT EXISTS( 
        SELECT 1 FROM AUTO_BLOCKED_PHONE WHERE 
        V_ALL_NUMBERS_OUT_CONTRACTS.PHONE_NUMBER=AUTO_BLOCKED_PHONE.PHONE_NUMBER
        -- ?? ????? 6 ????? ?????
        AND  (AUTO_BLOCKED_PHONE.BLOCK_DATE_TIME > sysdate-6/24)
        and AUTO_BLOCKED_PHONE.Note IS NULL)