CREATE OR REPLACE VIEW V_RECEIVED_PAYMENTS_PROFIT AS
  SELECT TO_NUMBER(TO_CHAR(R.PAYMENT_DATE_TIME, 'YYYYMM')) YEAR_MONTH,
         R.PHONE_NUMBER,
         SUM(R.PAYMENT_SUM) PAYMENT_ALL_SUM
    FROM RECEIVED_PAYMENTS R
    WHERE R.RECEIVED_PAYMENT_TYPE_ID IN (SELECT RT.RECEIVED_PAYMENT_TYPE_ID
                                           FROM RECEIVED_PAYMENT_TYPES RT
                                           WHERE RT.PROFIT_INCLUDING = 1)
      AND NVL(R.REVERSESCHET, 0) <> 1 
    GROUP BY TO_NUMBER(TO_CHAR(R.PAYMENT_DATE_TIME, 'YYYYMM')), R.PHONE_NUMBER;

GRANT SELECT ON V_RECEIVED_PAYMENTS_PROFIT TO CORP_MOBILE_ROLE;               

GRANT SELECT ON V_RECEIVED_PAYMENTS_PROFIT TO CORP_MOBILE_ROLE_RO;                                              
  