--#if GetVersion("V_SIM") < 1 
CREATE OR REPLACE VIEW V_SIM AS
SELECT 
--#Version=1
S.SIM_ID,
         A.AGENT_NAME AGENT_NAME,
         B.SUB_AGENT_NAME SUBAGENT_NAME,
         O.OPERATOR_NAME,
         S.DATE_INIT,
         V.SIM_STATUS_NAME STATUS_NAME,
         S.DATE_MOVE,
         S.ACCOUNT,
         S.CELL_NUMBER,
         T.TARIFF_NAME,
         S.SIM_NUMBER,
         S.ABON_PAY,
         (SELECT FIRST_VALUE(C.DATE_CREATED) OVER (ORDER BY C.DATE_CREATED DESC) 
            FROM CONTRACTS C
            WHERE C.PHONE_NUMBER_FEDERAL=S.CELL_NUMBER) DATE_ACTIVATE,
         S.DATE_ERASE,
         (SELECT Q.SURNAME || ' ' || Q.NAME ||
                 DECODE(Q.PATRONYMIC, NULL, '', ' ' || Q.PATRONYMIC)
            FROM ABONENTS Q, CONTRACTS C
           WHERE Q.ABONENT_ID = C.ABONENT_ID
             AND C.PHONE_NUMBER_FEDERAL = S.CELL_NUMBER) ABONENT_NAME,
         S.BALANCE,
         S.DATE_BALANCE,
         S.DATE_LAST_ACTIVITY,
         SG.SIM_SG_STATUS_NAME GID_STATUS,
         SP.SIM_PHONE_STATUS_NAME PHONE_IS_ACTIVE  
    FROM SIM S, 
         AGENTS A, 
         SUB_AGENTS B, 
         OPERATORS O, 
         TARIFFS T, 
         SIM_STATUSES V, 
         SIM_SERVICE_GID_STATUSES SG,
         SIM_PHONE_STATUSES SP
    WHERE S.AGENT_ID = A.AGENT_ID(+)
      AND S.SUBAGENT_ID = B.SUB_AGENT_ID(+)
      AND O.OPERATOR_ID(+) = S.OPERATOR_ID
      AND T.TARIFF_ID(+) = S.TARIFF_ID
      AND V.SIM_STATUS_ID(+) = S.STATUS_ID
      AND SG.SIM_SG_STATUS_ID(+) = S.SERVICEGID_STATUS
      AND SP.SIM_PHONE_STATUS_ID(+) = S.PHONE_IS_ACTIVE
/
--#end if
