CREATE OR REPLACE VIEW V_TARIFER_BILL_FOR_GROUPS AS
  SELECT B.YEAR_MONTH, C.GROUP_ID, SUM (B.BILL_SUMM) BILL_SUM_NEW
    FROM TARIFER_BILL_FOR_CLIENTS B, 
         V_CONTRACTS C
    WHERE B.PHONE_NUMBER = C.PHONE_NUMBER_FEDERAL
      AND C.CONTRACT_DATE < ADD_MONTHS(TO_DATE(B.YEAR_MONTH || '01', 'yyyymmdd'), 1)
      AND (C.CONTRACT_CANCEL_DATE IS NULL
            OR C.CONTRACT_CANCEL_DATE >= TO_DATE(B.YEAR_MONTH || '01', 'yyyymmdd'))
      AND C.GROUP_ID IS NOT NULL
    GROUP BY B.YEAR_MONTH, C.GROUP_ID;

GRANT SELECT ON V_TARIFER_BILL_FOR_GROUPS TO CORP_MOBILE_ROLE;  

GRANT SELECT ON V_TARIFER_BILL_FOR_GROUPS TO CORP_MOBILE_ROLE_RO;    