CREATE TABLE ABONENT_BALANCE_ROWS_ALL
(
  PHONE_NUMBER  VARCHAR2(15 CHAR),
  ROW_DATE      DATE,
  ROW_COST      NUMBER(15,2),
  ROW_COMMENT   VARCHAR2(2000 CHAR),
  ROW_TYPE      INTEGER
);

COMMENT ON TABLE ABONENT_BALANCE_ROWS_ALL IS 'Расшифровка балансов';

COMMENT ON COLUMN ABONENT_BALANCE_ROWS_ALL.PHONE_NUMBER IS 'Номер телефона';

COMMENT ON COLUMN ABONENT_BALANCE_ROWS_ALL.ROW_DATE IS 'Дата начисления';

COMMENT ON COLUMN ABONENT_BALANCE_ROWS_ALL.ROW_COST IS 'Сумма начисления';

COMMENT ON COLUMN ABONENT_BALANCE_ROWS_ALL.ROW_COMMENT IS 'Расшиврока начисления';

COMMENT ON COLUMN ABONENT_BALANCE_ROWS_ALL.ROW_TYPE IS 'Тип начисления';

CREATE INDEX I_ABON_BAL_ROWS_ALL_BILL ON ABONENT_BALANCE_ROWS_ALL
(PHONE_NUMBER, TO_NUMBER(TO_CHAR(ROW_DATE,'YYYYMM')), ROW_TYPE);
