CREATE TABLE ACCOUNT_INFO
(
  ACCOUNT_ID         INTEGER NOT NULL,
  BALANCE            NUMBER(15,2),
  COUNT_PHONE        INTEGER,
  USER_CREATED       VARCHAR2(30 CHAR),
  DATE_CREATED       DATE,
  USER_LAST_UPDATED  VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ACCOUNT_INFO IS 'Информация по л/с';

COMMENT ON COLUMN ACCOUNT_INFO.ACCOUNT_ID IS 'Код лицевого счёта';

COMMENT ON COLUMN ACCOUNT_INFO.BALANCE IS 'Баланс л/с';

COMMENT ON COLUMN ACCOUNT_INFO.COUNT_PHONE IS 'Кол-во номеров телефонов л/с';

COMMENT ON COLUMN ACCOUNT_INFO.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN ACCOUNT_INFO.DATE_CREATED IS 'Дата/время создания записи';

COMMENT ON COLUMN ACCOUNT_INFO.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';

COMMENT ON COLUMN ACCOUNT_INFO.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';

CREATE OR REPLACE TRIGGER TIU_ACCOUNT_INFO
  BEFORE INSERT OR UPDATE ON ACCOUNT_INFO FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/


GRANT DELETE, INSERT, SELECT, UPDATE ON ACCOUNT_INFO TO CORP_MOBILE_ROLE;
GRANT SELECT ON ACCOUNT_INFO TO CORP_MOBILE_ROLE_RO;
