CREATE TABLE ACCOUNT_LOAD_TYPES
(
  ACCOUNT_LOAD_TYPE_ID         INTEGER         ,
  ACCOUNT_LOAD_TYPE_NAME     VARCHAR2(30 CHAR)
);

ALTER TABLE ACCOUNT_LOAD_TYPES ADD  CONSTRAINT PK_ACCOUNT_LOAD_TYPES PRIMARY KEY (ACCOUNT_LOAD_TYPE_ID); 
 
COMMENT ON TABLE ACCOUNT_LOAD_TYPES IS 'Виды загрузки с сайта оператора';
 
COMMENT ON COLUMN ACCOUNT_LOAD_TYPES.ACCOUNT_LOAD_TYPE_ID IS 'Код';

COMMENT ON COLUMN ACCOUNT_LOAD_TYPES.ACCOUNT_LOAD_TYPE_NAME IS 'Название'; 
 
INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, 
  ACCOUNT_LOAD_TYPE_URL, SOURCE_CHAR_SET_RAW, TARGET_CHAR_SET_RAW, FILES_LOAD_TYPES_ID)
VALUES (1,'Платежи', '/payments?bill=%LOGIN%&pas=%PASSWORD%&start_date=%START_DATE%&end_date=%END_DATE%',
  'UTF8', 'CL8MSWIN1251', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (2,'Детализации', 1); 

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME,
  ACCOUNT_LOAD_TYPE_URL, SOURCE_CHAR_SET_TLOAD, TARGET_CHAR_SET_TLOAD, FILES_LOAD_TYPES_ID)
VALUES (3,'Статусы телефонов', '/phone_states?bill=%LOGIN%&pas=%PASSWORD%&num_rep=%NUM_REP%',
  'CL8MSWIN1251', 'UTF8', 1); 

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME,
  ACCOUNT_LOAD_TYPE_URL, SOURCE_CHAR_SET_TLOAD, TARGET_CHAR_SET_TLOAD, FILES_LOAD_TYPES_ID)
VALUES (4,'Подключенные опции', '/services_and_plans?bill=%LOGIN%&pas=%PASSWORD%',
  'CL8MSWIN1251', 'UTF8', 1); 

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME,
  ACCOUNT_LOAD_TYPE_URL, SOURCE_CHAR_SET_TLOAD, TARGET_CHAR_SET_TLOAD, FILES_LOAD_TYPES_ID)
VALUES (5,'Счета', '/account_bill?bill=%LOGIN%&pas=%PASSWORD%', 
  'CL8MSWIN1251', 'UTF8', 1); 

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME,
  ACCOUNT_LOAD_TYPE_URL, FILES_LOAD_TYPES_ID)
VALUES (6,'Отчеты о текущих начислениях', '/order?bill=%LOGIN%&pas=%PASSWORD%', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME,
  ACCOUNT_LOAD_TYPE_URL, FILES_LOAD_TYPES_ID)
VALUES (7,'Полные счета из "Фин. инфо"', 
  '/detail_bills?bill=%LOGIN%&pas=%PASSWORD%&year_month=%DD_MM_YYYY_-DD_MM_YYYY%&obj=%OBJ%', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (8,'Детальные счета, обр. поток', 1);
  
INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, 
  ACCOUNT_LOAD_TYPE_URL, SOURCE_CHAR_SET_RAW, TARGET_CHAR_SET_RAW, FILES_LOAD_TYPES_ID)
VALUES (9,'Блокировки абонентов', '/lock?bill=%LOGIN%&pas=%PASSWORD%&phone_number=%PHONE_NUMBER%&locking=true',
  'UTF8', 'CL8MSWIN1251', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, 
  ACCOUNT_LOAD_TYPE_URL, SOURCE_CHAR_SET_RAW, TARGET_CHAR_SET_RAW, FILES_LOAD_TYPES_ID)
VALUES (10,'Разблокировки абонентов', '/lock?bill=%LOGIN%&pas=%PASSWORD%&phone_number=%PHONE_NUMBER%&locking=false',
  'UTF8', 'CL8MSWIN1251', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (11,'Разблокировка по API', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (12,'Замена SIM карты абонента', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (14,'Лицевые счета коллектора', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (15,'Подключение/отключение услуг', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, ACCOUNT_LOAD_TYPE_URL, FILES_LOAD_TYPES_ID)
VALUES (17,'Баланс л/с', '/balance?bill=%LOGIN%&pas=%PASSWORD%', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, ACCOUNT_LOAD_TYPE_URL, FILES_LOAD_TYPES_ID)
VALUES (21,'Счета за оборудование', '/equipment_bills?bill=%LOGIN%&pas=%PASSWORD%', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (22,'Смена ТП', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (23,'Получение № SIM карты для BAN', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (24,'Получение инф. о коррек-ах BAN', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (25,'Заказ отчета о детализации сч.', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (26,'Получение отчета о детализ. сч', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (27,'Форм.и отпр. на почту детализ.', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (28,'Получение файла  детализ. PDF', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (29,'Изменение номера', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (30,'Изменение BAN', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, 
  ACCOUNT_LOAD_TYPE_URL, SOURCE_CHAR_SET_RAW, TARGET_CHAR_SET_RAW, FILES_LOAD_TYPES_ID)
VALUES (31,'Статусы телефонов метод 2', '/phone_statuses?bill=%LOGIN%&pas=%PASSWORD%',
  'UTF8', 'CL8MSWIN1251', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (32,'Отмена номера', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, ACCOUNT_LOAD_TYPE_URL, FILES_LOAD_TYPES_ID)
VALUES (51,'Коды ссылок на сайт по CTN', '/bills?bill=%LOGIN%&pas=%PASSWORD%', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, ACCOUNT_LOAD_TYPE_URL, FILES_LOAD_TYPES_ID)
VALUES (52,'Периоды выставленных счетов', '/bills_period_ready?bill=%LOGIN%&pas=%PASSWORD%', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, ACCOUNT_LOAD_TYPE_URL, FILES_LOAD_TYPES_ID)
VALUES (53,'Коды  тарифов для счетов', '/account_tariff?bill=%LOGIN%&pas=%PASSWORD%', 1);

INSERT INTO ACCOUNT_LOAD_TYPES(ACCOUNT_LOAD_TYPE_ID,ACCOUNT_LOAD_TYPE_NAME, FILES_LOAD_TYPES_ID)
VALUES (91,'Блокировка по API', 1);

COMMIT;


--#if not RecordExists("SELECT * FROM ACCOUNT_LOAD_TYPES  WHERE account_load_type_id=80") and isclient("CORP_MOBILE") then
INSERT INTO ACCOUNT_LOAD_TYPES (account_load_type_id,account_load_type_name)
  VALUES ('80', 'Отчет разблокировок на e-mail'); 
--#end if

alter table account_load_types add (account_load_type_url varchar2(200));
COMMENT ON COLUMN ACCOUNT_LOAD_TYPES.account_load_type_url IS 'URL-адрес для перехода';

alter table account_load_types add (SOURCE_CHAR_SET_RAW varchar2(30));
COMMENT ON COLUMN ACCOUNT_LOAD_TYPES.SOURCE_CHAR_SET_RAW IS 'Исходный набор символов для лога (из которого переводим)';

alter table account_load_types add (TARGET_CHAR_SET_RAW varchar2(30));
COMMENT ON COLUMN ACCOUNT_LOAD_TYPES.TARGET_CHAR_SET_RAW IS 'Целевой набор символов для лога (в который переводим)';

alter table account_load_types add (SOURCE_CHAR_SET_TLOAD varchar2(30));
COMMENT ON COLUMN ACCOUNT_LOAD_TYPES.SOURCE_CHAR_SET_TLOAD IS 'Исходный набор символов для массива записей (из которого переводим)';

alter table account_load_types add (TARGET_CHAR_SET_TLOAD varchar2(30));
COMMENT ON COLUMN ACCOUNT_LOAD_TYPES.TARGET_CHAR_SET_TLOAD IS 'Целевой набор символов  для массива записей (в который переводим)';

alter table account_load_types add (FILES_LOAD_TYPES_ID INTEGER);
COMMENT ON COLUMN ACCOUNT_LOAD_TYPES.FILES_LOAD_TYPES_ID IS 'Код типа загружаемого файла';

ALTER TABLE ACCOUNT_LOAD_TYPES ADD (
  CONSTRAINT ACCOUNT_LOAD_TYPES_FK01 
  FOREIGN KEY (FILES_LOAD_TYPES_ID) 
  REFERENCES FILES_LOAD_TYPES (FILES_LOAD_TYPES_ID));

Insert into ACCOUNT_LOAD_TYPES
   (ACCOUNT_LOAD_TYPE_ID, ACCOUNT_LOAD_TYPE_NAME, ACCOUNT_LOAD_TYPE_URL, SOURCE_CHAR_SET_RAW, TARGET_CHAR_SET_RAW, 
    SOURCE_CHAR_SET_TLOAD, TARGET_CHAR_SET_TLOAD, FILES_LOAD_TYPES_ID)
 Values
   (95, 'Гарантийные взносы', '/deposit?bill=%LOGIN%&pas=%PASSWORD%', NULL, NULL, 
    NULL, NULL, 1);

commit;