create table AUTO_UNBLOCKED_PHONE(
  phone_number  varchar2(50),
  Ballance     number,
  Note     varchar2(300 CHAR),
  UNBLOCK_DATE_TIME DATE,
  MANUAL_BLOCK  NUMBER  DEFAULT 0,
  USER_NAME  VARCHAR2(30 CHAR),
  ABONENT_FIO  VARCHAR2(100 CHAR),
  TICKET_ID NUMBER(11)
);

UPDATE AUTO_UNBLOCKED_PHONE
 SET UNBLOCK_DATE_TIME=TO_DATE(DATE_OF_UNBLOCK || ' ' || Time_of_unblock, 'MM/DD/YYYY HH24:MI')
 WHERE UNBLOCK_DATE_TIME IS NULL; 
 
ALTER TABLE AUTO_UNBLOCKED_PHONE ADD (MANUAL_BLOCK NUMBER DEFAULT 0);

ALTER TABLE AUTO_UNBLOCKED_PHONE ADD USER_NAME VARCHAR2(30 CHAR);

ALTER TABLE AUTO_UNBLOCKED_PHONE ADD ABONENT_FIO VARCHAR2(100 CHAR);

UPDATE AUTO_UNBLOCKED_PHONE
 SET ABONENT_FIO=CLIENT_SURNAME || ' ' || CLIENT_NAME
 WHERE ABONENT_FIO IS NULL; 
 
CREATE INDEX I_AUTO_UNBLOCKED_PHONE_P_D_N ON AUTO_UNBLOCKED_PHONE (PHONE_NUMBER, UNBLOCK_DATE_TIME, NOTE)
COMPRESS 1;

ALTER TABLE AUTO_UNBLOCKED_PHONE ADD TICKET_ID NUMBER(11);

update AUTO_UNBLOCKED_PHONE d
  set d.TICKET_ID = replace(d.note, 'Заявка на разблок №', '')
  where d.TICKET_ID is null
    and d.NOTE like 'Заявка на разблок №%';
    
update AUTO_UNBLOCKED_PHONE d
  set d.note = null
 -- select count(*) from AUTO_UNBLOCKED_PHONE d
  where d.TICKET_ID is not null
    and d.NOTE like 'Заявка на разблок №%';   