CREATE TABLE BALANCE_CHANGE
(
  ACCOUNT_ID         INTEGER NOT NULL,
  BALANCE            NUMBER(15,2) NOT NULL,
  DATE_CREATED       DATE NOT NULL,
  DATE_LAST_UPDATED  DATE,
  USER_LAST_UPDATED  VARCHAR2(30 CHAR)
);

COMMENT ON TABLE BALANCE_CHANGE IS 'Изменение балансов л/с';

COMMENT ON COLUMN BALANCE_CHANGE.ACCOUNT_ID IS 'Код лицевого счёта';

COMMENT ON COLUMN BALANCE_CHANGE.BALANCE IS 'Баланс л/с';

COMMENT ON COLUMN BALANCE_CHANGE.DATE_CREATED IS 'Дата/время создания записи';

COMMENT ON COLUMN BALANCE_CHANGE.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';

COMMENT ON COLUMN BALANCE_CHANGE.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';

CREATE INDEX I_BALANCE_CHANGE_ACCOUNT
ON BALANCE_CHANGE (ACCOUNT_ID);

--GRANT SELECT, INSERT, UPDATE, DELETE ON  BALANCE_CHANGE TO CORP_MOBILE_ROLE;
--GRANT SELECT ON BALANCE_CHANGE TO CORP_MOBILE_ROLE_RO;
