
CREATE TABLE BALANCE_HAND_BILLING
(
  DATE_BILLING          DATE                    NOT NULL,
  COST                  NUMBER(17,2),
  PHONE_NUMBER_TARIFER  VARCHAR2(10 CHAR)       NOT NULL,
  PHONE_NUMBER_CLIENT   VARCHAR2(10 CHAR),
  CONTRACT_ID           INTEGER                 NOT NULL,
  SEND_SMS              INTEGER                 DEFAULT 0                     NOT NULL,
  DATA_SEND_SMS         DATE
);

COMMENT ON TABLE  BALANCE_HAND_BILLING IS 'Назначенный биллинг цикл ';

COMMENT ON COLUMN BALANCE_HAND_BILLING.DATE_BILLING IS 'Дата снятия абонентской платы';
COMMENT ON COLUMN BALANCE_HAND_BILLING.COST IS 'Снятая сумма';
COMMENT ON COLUMN BALANCE_HAND_BILLING.PHONE_NUMBER_TARIFER IS 'Номер GSMCorp';
COMMENT ON COLUMN BALANCE_HAND_BILLING.PHONE_NUMBER_CLIENT IS 'Реальный номер клиента';
COMMENT ON COLUMN BALANCE_HAND_BILLING.CONTRACT_ID IS 'Ссылка на CONTRACTS.CONTRACT_ID';
COMMENT ON COLUMN BALANCE_HAND_BILLING.SEND_SMS IS 'Отослано ли СМС :  0 - нет, 1 - да';
COMMENT ON COLUMN BALANCE_HAND_BILLING.DATA_SEND_SMS IS 'Дата и время отправки СМС';

GRANT DELETE, INSERT, SELECT, UPDATE ON BALANCE_HAND_BILLING TO LONTANA_ROLE;