CREATE TABLE BEELINE_TARIFF_CODE
(
  CELL_PLAN_CODE               VARCHAR2(30 BYTE),
  TARIFF_NAME                  VARCHAR2(200 CHAR)
)
TABLESPACE USERS;

COMMENT ON TABLE BEELINE_TARIFF_CODE IS 'Заверенные коды тарифов Билайна для проверки полноты загрузки db_loader_full_bill_abon_per';

COMMENT ON COLUMN BEELINE_TARIFF_CODE.CELL_PLAN_CODE IS 'Заверенный код тарифа';

COMMENT ON COLUMN BEELINE_TARIFF_CODE.TARIFF_NAME IS 'НАИМЕНОВАНИЕ ТАРИФА';

ALTER TABLE BEELINE_TARIFF_CODE ADD PAID_OUTCOMING_ROUMING_CALL NUMBER(1) DEFAULT 0;
COMMENT ON COLUMN BEELINE_TARIFF_CODE.PAID_OUTCOMING_ROUMING_CALL IS 'СТОИМОСТЬ ЗА ИСХОДЯЩИЙ РОУМИНГ';

ALTER TABLE BEELINE_TARIFF_CODE ADD PAID_INCOMING_ROUMING_CALL NUMBER(1) DEFAULT 0;
COMMENT ON COLUMN BEELINE_TARIFF_CODE.PAID_INCOMING_ROUMING_CALL IS 'СТОИМОСТЬ ЗА ВХОДЯЩИЙ РОУМИНГ';
