CREATE TABLE BLOCK_NO_CONTRACTS_SETTINGS(
  CHECK_TIME INTEGER,
  TIME_END NUMBER(13, 4),
  TIME_BEGIN NUMBER(13, 4)
  );
  
GRANT SELECT, INSERT, DELETE, UPDATE ON BLOCK_NO_CONTRACTS_SETTINGS TO CORP_MOBILE_ROLE;
  
GRANT SELECT, INSERT, DELETE, UPDATE ON BLOCK_NO_CONTRACTS_SETTINGS TO SIM_TRADE_ROLE;

ALTER TABLE BLOCK_NO_CONTRACTS_SETTINGS ADD URL_ACCESS_LIST VARCHAR2(500 CHAR);

ALTER TABLE BLOCK_NO_CONTRACTS_SETTINGS ADD PHONE_FOR_NOTICE VARCHAR2(10 CHAR);

ALTER TABLE BLOCK_NO_CONTRACTS_SETTINGS ADD LIST_NO_BLOCK CLOB;