CREATE TABLE CALL_SUMMARY_STAT
(
  CONTRACT_ID                     INTEGER       NOT NULL,
  PHONE_NUMBER_FEDERAL            VARCHAR2(10 CHAR),
  YEAR_MONTH                      NUMBER,
  DURATION_OUT_NO_PAID            NUMBER,
  DURATION_OUT_NO_PAID_ONLY_BEE   NUMBER,
  DURATION_IN_NO_PAID             NUMBER,
  DURATION_IN_NO_PAID_ONLY_BEE    NUMBER,
  DURATION_IN_YES_PAID            NUMBER,
  DURATION_IN_YES_PAID_ONLY_BEE   NUMBER,
  DURATION_OUT_YES_PAID           NUMBER,
  DURATION_OUT_YES_PAID_ONLY_BEE  NUMBER,
  INTERNET_TRAFFIC                NUMBER 
)
;

ALTER TABLE CALL_SUMMARY_STAT ADD SMS_OUT NUMBER;
ALTER TABLE CALL_SUMMARY_STAT ADD MMS_OUT NUMBER; 

ALTER TABLE CALL_SUMMARY_STAT ADD USER_CREATED VARCHAR2(30 CHAR);
ALTER TABLE CALL_SUMMARY_STAT ADD DATE_CREATED DATE;
ALTER TABLE CALL_SUMMARY_STAT ADD USER_LAST_UPDATED VARCHAR2(30 CHAR);
ALTER TABLE CALL_SUMMARY_STAT ADD DATE_LAST_UPDATED DATE;

COMMENT ON TABLE CALL_SUMMARY_STAT IS 'Таблица сводная статистика по таблице CALL_YY_MMMM';
COMMENT ON COLUMN CALL_SUMMARY_STAT.YEAR_MONTH is 'Период';                      
COMMENT ON COLUMN CALL_SUMMARY_STAT.DURATION_OUT_NO_PAID is 'Длительность: все исходящие бесплатные';           
COMMENT ON COLUMN CALL_SUMMARY_STAT.DURATION_OUT_NO_PAID_ONLY_BEE is 'Длительность: все исходящие внутри сети Билайн';   
COMMENT ON COLUMN CALL_SUMMARY_STAT.DURATION_IN_NO_PAID is 'Длительность: все входящие бесплатные';             
COMMENT ON COLUMN CALL_SUMMARY_STAT.DURATION_IN_NO_PAID_ONLY_BEE is 'Длительность: все входящие бесплатные внутри сети Билайн';    
COMMENT ON COLUMN CALL_SUMMARY_STAT.DURATION_IN_YES_PAID is 'Длительность: все входящие платные';             
COMMENT ON COLUMN CALL_SUMMARY_STAT.DURATION_IN_YES_PAID_ONLY_BEE is 'Длительность: все входящие платные внутри сети Билайн';   
COMMENT ON COLUMN CALL_SUMMARY_STAT.DURATION_OUT_YES_PAID is 'Длительность: все исходящие платные';           
COMMENT ON COLUMN CALL_SUMMARY_STAT.DURATION_OUT_YES_PAID_ONLY_BEE is 'Длительность: все исходящие платные внутри сети Билайн';  
COMMENT ON COLUMN CALL_SUMMARY_STAT.INTERNET_TRAFFIC is 'Интернет трафик';                
COMMENT ON COLUMN CALL_SUMMARY_STAT.SMS_OUT is 'Количество исходящих СМС'; 
COMMENT ON COLUMN CALL_SUMMARY_STAT.MMS_OUT is 'Количество исходящих ММС';

CREATE OR REPLACE TRIGGER TIU_CALL_SUMMARY_STAT 
--#Version=1
  BEFORE INSERT OR UPDATE ON CALL_SUMMARY_STAT FOR EACH ROW
BEGIN 
  IF INSERTING THEN 
    :NEW.USER_CREATED := USER; 
    :NEW.DATE_CREATED := SYSDATE;
  END IF; 
  :NEW.USER_LAST_UPDATED := USER; 
  :NEW.DATE_LAST_UPDATED := SYSDATE; 
END;
--#end if
/

GRANT DELETE, SELECT, UPDATE ON CALL_SUMMARY_STAT TO LONTANA_ROLE;

GRANT SELECT ON CALL_SUMMARY_STAT TO LONTANA_ROLE_RO;

create index I_CALL_SUMMARY_STAT_PHONE on CALL_SUMMARY_STAT (PHONE_NUMBER_FEDERAL);
 
create index I_CALL_SUMMARY_STAT_YEAR_MONTH on CALL_SUMMARY_STAT(YEAR_MONTH);

create index I_CALL_SUMMARY_STAT_CONTRAC_ID on CALL_SUMMARY_STAT(CONTRACT_ID);
