CREATE TABLE CALL_STATISTICS
(
  YEAR_MONTH            INTEGER,
  SUBSCR_NO             NUMBER(11),
  AT_FT_CODE            VARCHAR2(6 BYTE),
  CALL_SUM              NUMBER(15,4)            DEFAULT 0                     NOT NULL,
  DATA_VOL              NUMBER(11,2)            DEFAULT 0                     NOT NULL,
  ZERO_COST_DATA_VOL    NUMBER(11,2)            DEFAULT 0                     NOT NULL,
  DUR                   NUMBER(11,2)            DEFAULT 0                     NOT NULL,
  ZERO_COST_DUR         NUMBER(11,2)            DEFAULT 0                     NOT NULL,
  DATE_LAST_UPDATE      DATE                    NOT NULL,
  DATE_LAST_CHANGE_SUM  DATE                    NOT NULL,
  AMOUNT                INTEGER                 DEFAULT 0                     NOT NULL,
  ZERO_COST_AMOUNT      INTEGER                 DEFAULT 0                     NOT NULL, 
  CONSTRAINT PK_CALL_STATISTICS
  PRIMARY KEY
  (YEAR_MONTH, SUBSCR_NO, AT_FT_CODE)
  ENABLE VALIDATE
)
ORGANIZATION INDEX
PCTTHRESHOLD 50
TABLESPACE HOT_BILLING;

COMMENT ON TABLE CALL_STATISTICS IS 'Таблица статистики по CALL_YYYY_MM';

COMMENT ON COLUMN CALL_STATISTICS.YEAR_MONTH IS 'Месяц';

COMMENT ON COLUMN CALL_STATISTICS.SUBSCR_NO IS 'Номер телефона';

COMMENT ON COLUMN CALL_STATISTICS.AT_FT_CODE IS 'Код звонка';

COMMENT ON COLUMN CALL_STATISTICS.CALL_SUM IS 'Сумма звонков';

COMMENT ON COLUMN CALL_STATISTICS.DATA_VOL IS 'Объем интернета(Мб)';

COMMENT ON COLUMN CALL_STATISTICS.ZERO_COST_DATA_VOL IS 'Объем бесплатного интернета(Мб)';

COMMENT ON COLUMN CALL_STATISTICS.DUR IS 'Длительность звонков(сек)';

COMMENT ON COLUMN CALL_STATISTICS.ZERO_COST_DUR IS 'Длительность бесплатных звонков(сек)';

COMMENT ON COLUMN CALL_STATISTICS.DATE_LAST_UPDATE IS 'Дата последнего изменения';

COMMENT ON COLUMN CALL_STATISTICS.DATE_LAST_CHANGE_SUM IS 'Дата последнего изменения суммы';

COMMENT ON COLUMN CALL_STATISTICS.AMOUNT IS 'Количество звонков';

COMMENT ON COLUMN CALL_STATISTICS.ZERO_COST_AMOUNT IS 'Количество бесплатных звонков';



-- Index PK_CALL_STATISTICS is created automatically by Oracle with index organized table CALL_STATISTICS.


CREATE OR REPLACE TRIGGER TI_CALL_STATISTICS
  BEFORE INSERT OR UPDATE ON CALL_STATISTICS 
  REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
  :NEW.DATE_LAST_UPDATE:=SYSDATE;
  IF UPDATING THEN
    IF :NEW.CALL_SUM <> :OLD.CALL_SUM THEN
      :NEW.DATE_LAST_CHANGE_SUM:=SYSDATE;
    END IF;
  ELSE
    :NEW.DATE_LAST_CHANGE_SUM:=SYSDATE;
  END IF;
END;
/

GRANT DELETE, INSERT, SELECT, UPDATE ON CALL_STATISTICS TO LONTANA_ROLE;

GRANT SELECT ON CALL_STATISTICS TO LONTANA_ROLE_RO;
