CREATE TABLE CONTRACT_DEPOSITE_OPER 
  (DEPOSITE_OPER_ID INTEGER PRIMARY KEY,
  CONTRACT_ID INTEGER,
  OPERATION_DATE_TIME DATE,
  DEPOSITE_VALUE NUMBER(12,2)
  );
 
ALTER TABLE CONTRACT_DEPOSITE_OPER ADD OPERATOR_NAME VARCHAR2(30 CHAR);

ALTER TABLE CONTRACT_DEPOSITE_OPER ADD NOTE VARCHAR2(100 CHAR);

CREATE SEQUENCE S_NEW_DEPOSITE_OPER_ID
  START WITH 101
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  

CREATE OR REPLACE FUNCTION NEW_DEPOSITE_OPER_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_DEPOSITE_OPER_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;
/  