CREATE TABLE CONTRACT_DEPOSITES 
  (DEPOSITE_ID INTEGER PRIMARY KEY,
  CONTRACT_ID INTEGER,
  CURRENT_DEPOSITE_VALUE NUMBER(12, 2)
  );
 
CREATE SEQUENCE S_NEW_DEPOSITE_ID
  START WITH 101
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;  

CREATE OR REPLACE FUNCTION NEW_DEPOSITE_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_DEPOSITE_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;

ALTER TABLE CONTRACT_DEPOSITES ADD DATE_DEPOSITE_CHANGE DATE;
/