CREATE TABLE CRM_BEELINE_PAYMENT_LOG_TICKET
(
  ID  INTEGER PRIMARY KEY,
  PHONE_NUMBER_TARIFER    VARCHAR2(10 CHAR) NOT NULL,
  PHONE_NUMBER_CLIENT    VARCHAR2(10 CHAR) NOT NULL,
  OPERATOR_CLIENT        VARCHAR2(20 CHAR),
  PAYMENT_DATE            DATE,
  PAYMENT_SUM             NUMBER(15,2),
  PAYMENT_TYPE            NUMBER(1),
  PAYMENT_NUMBER          VARCHAR2(30 CHAR),
  TYPE_CRM_BEELINE        NUMBER(1),
  ERROR_TEXT              varchar2 (1000 char),
  USER_CREATED            VARCHAR2(30 CHAR),
  DATE_CREATED            DATE,
  USER_LAST_UPDATED       VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED       DATE
);

COMMENT ON TABLE CRM_BEELINE_PAYMENT_LOG_TICKET IS 'Журнал отправки CRM-заявок и корректировочных платежей';

COMMENT ON COLUMN CRM_BEELINE_PAYMENT_LOG_TICKET.ID IS 'Первичный ключ';

COMMENT ON COLUMN CRM_BEELINE_PAYMENT_LOG_TICKET.PHONE_NUMBER_TARIFER IS 'Номер GSMCorp';

COMMENT ON COLUMN CRM_BEELINE_PAYMENT_LOG_TICKET.PHONE_NUMBER_CLIENT IS 'Номер клиетов';

COMMENT ON COLUMN CRM_BEELINE_PAYMENT_LOG_TICKET.OPERATOR_CLIENT IS 'Оператор (Билайн, МТС, Мегафон)';

COMMENT ON COLUMN CRM_BEELINE_PAYMENT_LOG_TICKET.PAYMENT_DATE IS 'Дата платежа';

COMMENT ON COLUMN CRM_BEELINE_PAYMENT_LOG_TICKET.PAYMENT_SUM IS 'Сумма платежа';

COMMENT ON COLUMN CRM_BEELINE_PAYMENT_LOG_TICKET.PAYMENT_NUMBER IS 'Номер платежа';

COMMENT ON COLUMN CRM_BEELINE_PAYMENT_LOG_TICKET.PAYMENT_TYPE IS 'Тип платежа';

COMMENT ON COLUMN CRM_BEELINE_PAYMENT_LOG_TICKET.TYPE_CRM_BEELINE IS 'Признак зерез что делать платеж (TYPES_CRM_BEELINE_ID.ID)';

COMMENT ON COLUMN CRM_BEELINE_PAYMENT_LOG_TICKET.ERROR_TEXT IS 'Ошибки при создании заявки или записи в платежи';

COMMENT ON COLUMN CRM_BEELINE_PAYMENT_LOG_TICKET.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN CRM_BEELINE_PAYMENT_LOG_TICKET.DATE_CREATED IS 'Дата/время создания записи';

COMMENT ON COLUMN CRM_BEELINE_PAYMENT_LOG_TICKET.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';

COMMENT ON COLUMN CRM_BEELINE_PAYMENT_LOG_TICKET.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';


CREATE SEQUENCE S_NEW_CRM_BEE_PAY_LOG_TICK_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE OR REPLACE TRIGGER TIU_CRM_BEE_PAYMENT_LOG_TICKET
  BEFORE INSERT OR UPDATE ON CRM_BEELINE_PAYMENT_LOG_TICKET FOR EACH ROW
--
--#Version=1
--
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.ID, 0) = 0 THEN
      :NEW.ID := S_NEW_CRM_BEE_PAY_LOG_TICK_ID.NEXTVAL;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/
GRANT SELECT ON CRM_BEELINE_PAYMENT_LOG_TICKET TO LONTANA_ROLE;
GRANT SELECT ON CRM_BEELINE_PAYMENT_LOG_TICKET TO LONTANA_ROLE_RO;

alter table CRM_BEELINE_PAYMENT_LOG_TICKET add(CONSTRAINT FK_TYPE_CRM_BEELINE_ID1 FOREIGN KEY (TYPE_CRM_BEELINE)REFERENCES TYPES_CRM_BEELINE   (ID) ENABLE VALIDATE);