CREATE TABLE CRM_BEELINE_CONFORMITY
(
  CONFORMITY_ID        INTEGER PRIMARY KEY,
  PHONE_NUMBER_TARIFER VARCHAR2(10 CHAR) NOT NULL,
  PHONE_NUMBER_CLIENT     VARCHAR2(10 CHAR) NOT NULL,
  OPERATOR_CLIENT         VARCHAR2(20 CHAR),
  USER_CREATED         VARCHAR2(30 CHAR),
  DATE_CREATED         DATE,
  USER_LAST_UPDATED    VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED    DATE,
  CONSTRAINT UC_PHONE_NUMBER_TARIFER UNIQUE (PHONE_NUMBER_TARIFER),
  CONSTRAINT UC_PHONE_NUMBER_CLIENT UNIQUE (PHONE_NUMBER_CLIENT)
);

COMMENT ON TABLE CRM_BEELINE_CONFORMITY IS 'Соответствие номеров Билайн номерам МТС/Мегафон';

COMMENT ON COLUMN CRM_BEELINE_CONFORMITY.CONFORMITY_ID IS 'Первичный ключ';

COMMENT ON COLUMN CRM_BEELINE_CONFORMITY.PHONE_NUMBER_TARIFER IS 'Номер GSMCorp';

COMMENT ON COLUMN CRM_BEELINE_CONFORMITY.PHONE_NUMBER_CLIENT IS 'Реальный номер клиента';

COMMENT ON COLUMN CRM_BEELINE_CONFORMITY.OPERATOR_CLIENT IS 'Оператор (Билайн, МТС, Мегафон)';

COMMENT ON COLUMN CRM_BEELINE_CONFORMITY.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN CRM_BEELINE_CONFORMITY.DATE_CREATED IS 'Дата/время создания записи';

COMMENT ON COLUMN CRM_BEELINE_CONFORMITY.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';

COMMENT ON COLUMN CRM_BEELINE_CONFORMITY.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';


CREATE SEQUENCE S_NEW_CONFORMITY_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE OR REPLACE TRIGGER TIU_CONFORMITY
  BEFORE INSERT OR UPDATE ON CRM_BEELINE_CONFORMITY FOR EACH ROW
--
--#Version=1
--
BEGIN
  
  IF INSERTING THEN
    
    IF NVL(:NEW.CONFORMITY_ID, 0) = 0 THEN
      :NEW.CONFORMITY_ID := S_NEW_CONFORMITY_ID.NEXTVAL;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
  
  if nvl(:NEW.PHONE_NUMBER_CLIENT, '0') <> '0' then 
    :NEW.OPERATOR_CLIENT := substr(GET_OPERATOR_BY_PHONE(:NEW.PHONE_NUMBER_CLIENT), 1, 20);
  end if;
  
END;
/
GRANT SELECT, INSERT, DELETE, UPDATE ON CRM_BEELINE_CONFORMITY TO LONTANA_ROLE;
GRANT SELECT, INSERT, DELETE, UPDATE ON CRM_BEELINE_CONFORMITY TO LONTANA_ROLE_RO;

alter table CRM_BEELINE_CONFORMITY add(TYPE_CRM_BEELINE_ID integer not null);
comment on column CRM_BEELINE_CONFORMITY.TYPE_CRM_BEELINE_ID is 'Признак зерез что делать платеж (TYPES_CRM_BEELINE_ID.ID)';

alter table CRM_BEELINE_CONFORMITY add(CONSTRAINT FK_TYPE_CRM_BEELINE_ID FOREIGN KEY (TYPE_CRM_BEELINE_ID)REFERENCES TYPES_CRM_BEELINE   (ID) ENABLE VALIDATE);