CREATE TABLE CRM_UNBLOCK_PHONE_TYPE
(
  CUP_ID  INTEGER                               NOT NULL,
  NAME    VARCHAR2(100 BYTE)                    NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX I_CRM_UNBL_PHONE_TYPE_CUP_ID ON CRM_UNBLOCK_PHONE_TYPE(CUP_ID);

ALTER TABLE CRM_UNBLOCK_PHONE_TYPE ADD CONSTRAINT PK_CRM_UNBLOCK_PHONE_TYPE_ID
  PRIMARY KEY (CUP_ID);