--drop table DATABASE_COPIES
CREATE TABLE DATABASE_COPIES
(
  ID_DATABASE     NUMBER(38),
  SCHEMA_NAME     VARCHAR2(30 BYTE),
  DATE_CREATED     DATE,
  COMMENT_SCHEMA  VARCHAR2(250 BYTE),
  USER_CREATED    VARCHAR2(30 BYTE)
);


CREATE SEQUENCE S_NEW_ID_DATABASE
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE OR REPLACE TRIGGER TI_DATABASE_COPIES
  BEFORE INSERT ON DATABASE_COPIES FOR EACH ROW
--
--#Version=1
--
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.ID_DATABASE, 0) = 0 THEN
      :NEW.ID_DATABASE := S_NEW_ID_DATABASE.NEXTVAL;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
END;
/


GRANT DELETE, INSERT, SELECT, UPDATE ON DATABASE_COPIES TO CORP_MOBILE_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON DATABASE_COPIES TO LONTANA_ROLE;


