CREATE SEQUENCE DB_LOADER_CFRW_ID
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE TABLE DB_LOADER_CFRW
(
  CFRW_ID    NUMBER(10),
  LOAD_DATE  TIMESTAMP(6),
  REQUESTID  NUMBER(10),
  CFTYPE     VARCHAR2(32 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE OR REPLACE FUNCTION NEW_LOADER_CFRW_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT DB_LOADER_CFRW_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;

ALTER TABLE DB_LOADER_CFRW ADD (
  CONSTRAINT PK_DB_LOADER_CFRW
 PRIMARY KEY
 (CFRW_ID));


COMMENT ON TABLE DB_LOADER_CFRW IS 'Загруженные сообщения о запросах переадресации методом REST';

COMMENT ON COLUMN DB_LOADER_CFRW.CFRW_ID IS 'Первичный ключ';

COMMENT ON COLUMN DB_LOADER_CFRW.LOAD_DATE IS 'Дата/время загрузки';

COMMENT ON COLUMN DB_LOADER_CFRW.REQUESTID IS 'Идентификатор запроса';

COMMENT ON COLUMN DB_LOADER_CFRW.CFTYPE IS 'Тип переадресации';
