ALTER TABLE FILES_LOAD_TYPES
 DROP PRIMARY KEY CASCADE;

DROP TABLE FILES_LOAD_TYPES CASCADE CONSTRAINTS;

CREATE TABLE FILES_LOAD_TYPES
(
  FILES_LOAD_TYPES_ID    NUMBER(38)             NOT NULL,
  FILES_LOAD_TYPES_NAME  VARCHAR2(50 CHAR)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN FILES_LOAD_TYPES.FILES_LOAD_TYPES_ID IS 'Код загружаемого файла';

COMMENT ON COLUMN FILES_LOAD_TYPES.FILES_LOAD_TYPES_NAME IS 'Наименование типа загружаемого файла';


CREATE UNIQUE INDEX FILES_LOAD_TYPES_PK ON FILES_LOAD_TYPES
(FILES_LOAD_TYPES_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE FILES_LOAD_TYPES ADD (
  CONSTRAINT FILES_LOAD_TYPES_PK
  PRIMARY KEY
  (FILES_LOAD_TYPES_ID)
  USING INDEX FILES_LOAD_TYPES_PK);


Insert into FILES_LOAD_TYPES  (FILES_LOAD_TYPES_ID, FILES_LOAD_TYPES_NAME)
 Values   (1, 'Текстовый файл (csv, xml)');
Insert into FILES_LOAD_TYPES   (FILES_LOAD_TYPES_ID, FILES_LOAD_TYPES_NAME)
 Values   (2, 'Бинарный файл (xls)');
COMMIT;
