CREATE TABLE FORWARDING_PHONE_NUMBER(
  FORWARDING_ID INTEGER PRIMARY KEY,
  PHONE_NUMBER VARCHAR2(10 CHAR) UNIQUE,
  PHONE_NUMBER_RECIPIENT VARCHAR2(10 CHAR),
  FORWARDING_ENABLE INTEGER,
  SMS_TEXT_ADD VARCHAR2(100 char),
  DATE_LAST_UPDATE DATE,
  USER_LAST_UPDATE VARCHAR2(30 CHAR)
  );
  
CREATE SEQUENCE S_NEW_FORWARDING_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
CREATE OR REPLACE FUNCTION NEW_FORWARDING_ID RETURN INTEGER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_FORWARDING_ID.NEXTVAL
    INTO vRES
    FROM DUAL;
  RETURN vRES;
END;  

CREATE OR REPLACE TRIGGER TIU_FORWARDING_PHONE_NUMBER
  BEFORE INSERT OR UPDATE ON FORWARDING_PHONE_NUMBER FOR EACH ROW
--#Version=1
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.FORWARDING_ID, 0) = 0 THEN
      :NEW.FORWARDING_ID := NEW_FORWARDING_ID;
    END IF;
    IF :NEW.SMS_TEXT_ADD IS NULL THEN
      :NEW.SMS_TEXT_ADD:='Переадресация от '||:NEW.PHONE_NUMBER||':';
    END IF;
  END IF;
  :NEW.DATE_LAST_UPDATE:=SYSDATE;
  :NEW.USER_LAST_UPDATE:=USER;
END;
/
  
CREATE INDEX I_FORWARDING_P_N_PHONE_RECIP ON FORWARDING_PHONE_NUMBER
  (PHONE_NUMBER_RECIPIENT)
  LOGGING
  NOPARALLEL;
  
GRANT DELETE, INSERT, SELECT, UPDATE ON FORWARDING_PHONE_NUMBER TO CORP_MOBILE_ROLE;

GRANT SELECT ON FORWARDING_PHONE_NUMBER TO CORP_MOBILE_ROLE_RO;  