CREATE TABLE GPRS_TARIFFS
(
  TARIFF_CODE  VARCHAR2(30 CHAR),
  DATE_ON      TIMESTAMP(6),
  DATE_OFF     TIMESTAMP(6)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
/
ALTER TABLE GPRS_TARIFFS ADD (
  CONSTRAINT PK_GPRS_TARIFFS
 PRIMARY KEY
 (TARIFF_CODE));
/
CREATE SEQUENCE GPRS_TARIFFS_ID
  START WITH 201
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
/
CREATE OR REPLACE FUNCTION NEW_GPRS_TARIFFS_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT GPRS_TARIFFS_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;
/
COMMENT ON TABLE GPRS_TARIFFS 							IS 'Список тарифов для которых доступна услуга автоматического подключения пакетов с доп.трафиком INTERNET';

COMMENT ON COLUMN GPRS_TARIFFS.TARIFF_CODE 	IS 'Первичный ключ, код тарифа';

COMMENT ON COLUMN GPRS_TARIFFS.DATE_ON 			IS 'Дата включения тарифа в список доступных для услуги';

COMMENT ON COLUMN GPRS_TARIFFS.DATE_OFF 		IS 'Дата исключения тарифа из списока доступных для услуги';

/