CREATE TABLE GPRS_OPTS
(
  OPT_ID    NUMBER(38),
  OPT_CODE  VARCHAR2(64 CHAR),
  OPT_NAME  VARCHAR2(128 CHAR),
  COST      NUMBER(18,2),
  DATE_ON   TIMESTAMP(6),
  DATE_OFF  TIMESTAMP(6),
  VOL       NUMBER(12)                          DEFAULT 0
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
/
ALTER TABLE GPRS_OPTS ADD (
  CONSTRAINT PK_GPRS_OPTS
 PRIMARY KEY
 (OPT_ID));
/
CREATE SEQUENCE GPRS_OPTS_ID
  START WITH 201
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
/
CREATE OR REPLACE FUNCTION NEW_GPRS_OPTS_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT GPRS_OPTS_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;
/
COMMENT ON TABLE GPRS_OPTS IS 'Список пакетов для автоматического подключения для тарифов с закончившимся INTERNET';

COMMENT ON COLUMN GPRS_OPTS.OPT_ID 		IS 'Первичный ключ';

COMMENT ON COLUMN GPRS_OPTS.OPT_CODE 	IS 'Код опции';

COMMENT ON COLUMN GPRS_OPTS.OPT_NAME 	IS 'Наименование опции';

COMMENT ON COLUMN GPRS_OPTS.COST 			IS 'Стоимость опции';

COMMENT ON COLUMN GPRS_OPTS.DATE_ON 	IS 'Дата создания опции';

COMMENT ON COLUMN GPRS_OPTS.DATE_OFF 	IS 'Дата отключения опции (общая)';

COMMENT ON COLUMN GPRS_OPTS.VOL 			IS 'Объём трафика доступного при подключении опции в МБ';
/
