CREATE TABLE GPRS_TURN_LOG
(
  LOG_ID       NUMBER(38),
  PHONE        VARCHAR2(10 CHAR),
  TARIFF_CODE  VARCHAR2(30 CHAR),
  DATE_ON      TIMESTAMP(6),
  DATE_OFF     TIMESTAMP(6)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
/
ALTER TABLE GPRS_TURN_LOG ADD (
  CONSTRAINT PK_GPRS_TURN_LOG
 PRIMARY KEY
 (LOG_ID));
/
CREATE SEQUENCE GPRS_TURN_LOG_ID
  START WITH 61
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
/
CREATE OR REPLACE FUNCTION NEW_GPRS_TURN_LOG_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT GPRS_TURN_LOG_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;
/
COMMENT ON TABLE GPRS_TURN_LOG							IS 'История подключения доп.пакетов на номер абонента';

COMMENT ON COLUMN GPRS_TURN_LOG.LOG_ID			IS 'Первичный ключ';

COMMENT ON COLUMN GPRS_TURN_LOG.PHONE 			IS 'Номер телефона';

COMMENT ON COLUMN GPRS_TURN_LOG.TARIFF_CODE	IS 'Код тарифа';

COMMENT ON COLUMN GPRS_TURN_LOG.DATE_ON 		IS 'Дата подключения пакета';

COMMENT ON COLUMN GPRS_TURN_LOG.DATE_OFF 		IS 'Дата отключения пакета';

/