CREATE TABLE GUARANTEE_FEES
(
  GUARANTEE_FEES_ID   NUMBER                    primary key,
  ACCOUNT_ID          INTEGER,
  PHONE_NUMBER        VARCHAR2(10 BYTE),
  STATUS_GUARANT_FEE  VARCHAR2(30 CHAR),
  SUM_GUARANT_FEE     NUMBER(15,2),
  PAID                NUMBER(15,2),
  RETURNED            NUMBER(15,2),
  WITHDRAWN           NUMBER(15,2),
  NOT_PAID            NUMBER(15,2),
  BILL_NUMBER      NUMBER,
  YEAR_MONTH          INTEGER,
  DATE_CREATED        DATE,
  USER_CREATED        VARCHAR2(30 CHAR),
  DATE_UPDATE         DATE,
  USER_UPDATE         VARCHAR2(30 CHAR)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE GUARANTEE_FEES IS 'цюпюмрхимше бгмняш';

COMMENT ON COLUMN GUARANTEE_FEES.GUARANTEE_FEES_ID IS 'ID ';

COMMENT ON COLUMN GUARANTEE_FEES.ACCOUNT_ID IS 'ID яверю';

COMMENT ON COLUMN GUARANTEE_FEES.PHONE_NUMBER IS 'мнлеп рекетнмю';

COMMENT ON COLUMN  GUARANTEE_FEES.STATUS_GUARANT_FEE IS 'ярюрся цюпюмрхимнцн бгмняю';

COMMENT ON COLUMN  GUARANTEE_FEES.SUM_GUARANT_FEE IS 'ясллю цюпюмрхимнцн ягбнмю я мдя';

COMMENT ON COLUMN  GUARANTEE_FEES.PAID IS 'нокювемн';

COMMENT ON COLUMN  GUARANTEE_FEES.RETURNED IS 'бнгбпюыемн';

COMMENT ON COLUMN  GUARANTEE_FEES.WITHDRAWN IS 'нрлемемн';

COMMENT ON COLUMN  GUARANTEE_FEES.NOT_PAID IS 'ме нокювемн';

COMMENT ON COLUMN  GUARANTEE_FEES.BILL_NUMBER IS 'мнлеп янгдюмхъ яверю';

COMMENT ON COLUMN  GUARANTEE_FEES.YEAR_MONTH IS 'леяъж цнд';

COMMENT ON COLUMN  GUARANTEE_FEES.DATE_CREATED IS 'дюрю янгдюмхъ';

COMMENT ON COLUMN  GUARANTEE_FEES.USER_CREATED IS 'онкэгнбюрекэ, янгдюбьхи';

COMMENT ON COLUMN  GUARANTEE_FEES.DATE_UPDATE IS 'дюрю хглемемхъ';

COMMENT ON COLUMN  GUARANTEE_FEES.USER_UPDATE IS 'онкэгнбюрекэ, хглемхбьхи';



CREATE OR REPLACE TRIGGER  TIU_GUARANTEE_FEES
BEFORE INSERT OR UPDATE
ON  GUARANTEE_FEES
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN 


  if INSERTING then
    IF NVL(:NEW.GUARANTEE_FEES_ID, 0) = 0 then 
      :NEW.GUARANTEE_FEES_ID := s_NEW_GUARANTEE_FEES_ID.NEXTVAL;
    END IF;  
    
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  end if; 
  
  if updating then     
    :NEW.USER_UPDATE := USER;
    :NEW.DATE_UPDATE := SYSDATE;
  end if;
  
END TIU_GUARANTEE_FEES;
/

CREATE INDEX I_GUARANTEE_FEES_YEAR_MONTH ON GUARANTEE_FEES (YEAR_MONTH);
CREATE INDEX I_GUARANTEE_FEES_ACCOUNT_ID ON GUARANTEE_FEES (ACCOUNT_ID);

ALTER TABLE GUARANTEE_FEES ADD 
CONSTRAINT GUARANTEE_FEES_ACC_ID_ACCOUNT
 FOREIGN KEY (ACCOUNT_ID)
 REFERENCES  ACCOUNTS (ACCOUNT_ID);

