--DROP TABLE HACKERS CASCADE CONSTRAINTS;

CREATE TABLE HACKERS
(
  HACKERS_ID         NUMBER(38)                 NOT NULL,
  SERVICES_TYPE       NUMBER                   NOT NULL,
  DATE_CREATED       DATE                       NOT NULL,
  DATE_LAST_UPDATED  DATE,
  USER_LAST_UPDATED  VARCHAR2(30 CHAR),
  PHONE_NUMBER       VARCHAR2(10 BYTE),
)

ALTER TABLE HACKERS
	ADD CHECKED_TYPE_ID NUMBER

ALTER TABLE HACKERS
	ADD COUNT_SMS_CHANGE NUMBER

CREATE SEQUENCE S_NEW_HACKERS_ID
  START WITH 24
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

COMMENT ON TABLE HACKERS IS 'Учет хакеров';

COMMENT ON COLUMN HACKERS.HACKERS_ID IS 'Код хакера';

COMMENT ON COLUMN HACKERS.DATE_CREATED IS 'Дата/время создания записи';

COMMENT ON COLUMN HACKERS.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';

COMMENT ON COLUMN HACKERS.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';

COMMENT ON COLUMN HACKERS. PHONE_NUMBER IS 'Номер телефона';

COMMENT ON COLUMN HACKERS.CHECKED_TYPE_ID IS 'Тип сообщения';

COMMENT ON COLUMN HACKERS. COUNT_SMS_CHANGE IS 'Значение изменения СМС';



GRANT DELETE, INSERT, SELECT, UPDATE ON HACKERS TO CORP_MOBILE_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON HACKERS TO LONTANA_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON HACKERS TO SIM_TRADE_ROLE;

GRANT SELECT ON HACKERS TO CORP_MOBILE_ROLE_RO;