CREATE TABLE HOT_BILLING_CALL_UOM(
  UOM VARCHAR2(2 BYTE) PRIMARY KEY,
  UOM_DESC VARCHAR2(100 CHAR),
  UOM_DESC_RUS VARCHAR2(100 CHAR),
  DATE_INSERT DATE,
  DATE_LAST_UPDATE DATE  
  ) TABLESPACE HOT_BILLING;

COMMENT ON TABLE HOT_BILLING_CALL_UOM IS 'Units Of Measure - Единица измерения';

COMMENT ON COLUMN HOT_BILLING_CALL_UOM.UOM IS 'Код';
COMMENT ON COLUMN HOT_BILLING_CALL_UOM.UOM_DESC IS 'Описание';
COMMENT ON COLUMN HOT_BILLING_CALL_UOM.UOM_DESC_RUS IS 'Описание (рус)';
COMMENT ON COLUMN HOT_BILLING_CALL_UOM.DATE_INSERT IS 'Дата вставки';
COMMENT ON COLUMN HOT_BILLING_CALL_UOM.DATE_LAST_UPDATE IS 'Дата обновления';

CREATE OR REPLACE TRIGGER TIU_HOT_BILLING_CALL_UOM
  BEFORE INSERT OR UPDATE ON HOT_BILLING_CALL_UOM FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :NEW.DATE_INSERT:=SYSDATE;
  END IF;
  :NEW.DATE_LAST_UPDATE:=SYSDATE;  
END;  

GRANT DELETE, INSERT, SELECT, UPDATE ON HOT_BILLING_CALL_UOM TO LONTANA_ROLE;

GRANT SELECT ON HOT_BILLING_CALL_UOM TO LONTANA_ROLE_RO;

INSERT INTO HOT_BILLING_CALL_UOM(UOM, UOM_DESC, UOM_DESC_RUS)
  VALUES('MB', 'Megabyte', 'Мегабайт');
INSERT INTO HOT_BILLING_CALL_UOM(UOM, UOM_DESC, UOM_DESC_RUS)
  VALUES('SE', 'Second', 'Секунд');
INSERT INTO HOT_BILLING_CALL_UOM(UOM, UOM_DESC, UOM_DESC_RUS)
  VALUES('MI', 'Minute', 'Минут');
INSERT INTO HOT_BILLING_CALL_UOM(UOM, UOM_DESC, UOM_DESC_RUS)
  VALUES('EV', '', 'Разовый');