CREATE GLOBAL TEMPORARY TABLE HOT_BILLING_CALLS_INSERTING
(
  DBF_ID      INTEGER,
  SUBSCR_NO   NUMBER(11),
  CH_SEIZ_DT  DATE,
  US_SEQ_N    NUMBER(9),
  AT_SOC      VARCHAR2(9 BYTE),
  AT_FT_CODE  VARCHAR2(6 BYTE),
  PC_PLAN_CD  VARCHAR2(9 BYTE),
  C_ACT_CD    VARCHAR2(1 BYTE),
  AT_CHG_AMT  NUMBER(11,2),
  CALLING_NO  VARCHAR2(21 BYTE),
  MESSAGE_TP  VARCHAR2(1 BYTE),
  SRV_FT_CD   VARCHAR2(6 BYTE),
  DURATION    VARCHAR2(8 BYTE),
  DATA_VOL    NUMBER(11,2),
  IMEI        NUMBER(15),
  CELL_ID     NUMBER(6),
  PROV_ID     VARCHAR2(8 BYTE),
  DIALED_DIG  VARCHAR2(21 BYTE),
  UOM         VARCHAR2(2 BYTE),
  DISCT_SOCS  VARCHAR2(100 BYTE),
  CALL_COST   NUMBER(11,2),
  DUR         NUMBER(11,2),
  MN_UNLIM    NUMBER(1)
)
ON COMMIT PRESERVE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;

COMMENT ON TABLE HOT_BILLING_CALLS_INSERTING IS 'ГорБиллинг - Тарифицированные звонки';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.DBF_ID IS 'ID файла источника';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.SUBSCR_NO IS 'Сотовый номер';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.CH_SEIZ_DT IS 'Дата_время совершения звонка';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.US_SEQ_N IS 'Порядковый номер записи (служебное поле)';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.AT_SOC IS 'Услуга, по которой определяется тарификация';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.AT_FT_CODE IS 'Код звонка в билайне';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.PC_PLAN_CD IS 'Тарифный план';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.C_ACT_CD IS 'Тип вызова';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.AT_CHG_AMT IS 'Стоимость';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.CALLING_NO IS 'Номер инициатора звонка';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.MESSAGE_TP IS 'Тип записи: домашний или роуминг';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.SRV_FT_CD IS 'Сервис (код)';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.DURATION IS 'Длительность';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.DATA_VOL IS 'Объем (для data)';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.IMEI IS 'IMEI (код)';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.CELL_ID IS 'Идентификатор соты';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.PROV_ID IS 'Роуминг-провайдер';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.DIALED_DIG IS 'Набранный номер';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.UOM IS 'Единица измерения';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.DISCT_SOCS IS 'Услуга-скидка';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.CALL_COST IS 'Стоимость Итоговая';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.DUR IS 'Длительность(сек)';

COMMENT ON COLUMN HOT_BILLING_CALLS_INSERTING.MN_UNLIM IS 'Услуга-скидка';



CREATE INDEX I_HB_INS_CALLS$DBF_ID$IDX ON HOT_BILLING_CALLS_INSERTING
(DBF_ID);


CREATE INDEX I_HB_INS_CALLS$SUB_AT ON HOT_BILLING_CALLS_INSERTING
(DBF_ID, SUBSCR_NO, AT_FT_CODE)
COMPRESS 3;


CREATE UNIQUE INDEX PK_HOT_BILLING_INSERTING_CALLS ON HOT_BILLING_CALLS_INSERTING
(SUBSCR_NO, CH_SEIZ_DT, US_SEQ_N)
COMPRESS 1;


GRANT DELETE, INSERT, SELECT, UPDATE ON HOT_BILLING_CALLS_INSERTING TO LONTANA_ROLE;

GRANT SELECT ON HOT_BILLING_CALLS_INSERTING TO LONTANA_ROLE_RO;
