CREATE TABLE HOT_BILLING_CALL_IS_ROAMING
(
  IS_ROAMING               NUMBER(1),
  ROAMING_TYPE_NAME        VARCHAR2(100 CHAR),
  ROAMING_TYPE_NAME_SHORT  VARCHAR2(30 CHAR)
)
TABLESPACE HOT_BILLING
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE HOT_BILLING_CALL_IS_ROAMING IS 'Типы роуминга';

COMMENT ON COLUMN HOT_BILLING_CALL_IS_ROAMING.IS_ROAMING IS 'Код';

COMMENT ON COLUMN HOT_BILLING_CALL_IS_ROAMING.ROAMING_TYPE_NAME IS 'Описание';



CREATE UNIQUE INDEX HOT_BILLING_CALL_IS_ROAMING_PK ON HOT_BILLING_CALL_IS_ROAMING
(IS_ROAMING);



ALTER TABLE HOT_BILLING_CALL_IS_ROAMING ADD (
  CONSTRAINT HOT_BILLING_CALL_IS_ROAMING_PK
  PRIMARY KEY
  (IS_ROAMING)
  USING INDEX HOT_BILLING_CALL_IS_ROAMING_PK
  ENABLE VALIDATE);


GRANT DELETE, INSERT, SELECT, UPDATE ON HOT_BILLING_CALL_IS_ROAMING TO LONTANA_ROLE;

GRANT SELECT ON HOT_BILLING_CALL_IS_ROAMING TO LONTANA_ROLE_RO;
