CREATE TABLE HOT_BILLING_CALL_C_ACT_CD(
  C_ACT_CD VARCHAR2(1 BYTE) PRIMARY KEY,
  C_ACT_DESC VARCHAR2(100 CHAR),
  C_ACT_DESC_RUS VARCHAR2(100 CHAR),
  C_ACT_DESC_RUS_SHORT VARCHAR2(30 CHAR),
  DATE_INSERT DATE,
  DATE_LAST_UPDATE DATE   
  ) TABLESPACE HOT_BILLING;

COMMENT ON TABLE HOT_BILLING_CALL_C_ACT_CD IS 'Call Action Code - Тип вызова';

COMMENT ON COLUMN HOT_BILLING_CALL_C_ACT_CD.C_ACT_CD IS 'Код';
COMMENT ON COLUMN HOT_BILLING_CALL_C_ACT_CD.C_ACT_DESC IS 'Описание';
COMMENT ON COLUMN HOT_BILLING_CALL_C_ACT_CD.C_ACT_DESC_RUS IS 'Описание (рус)';
COMMENT ON COLUMN HOT_BILLING_CALL_C_ACT_CD.DATE_INSERT IS 'Дата вставки';
COMMENT ON COLUMN HOT_BILLING_CALL_C_ACT_CD.DATE_LAST_UPDATE IS 'Дата обновления';

CREATE OR REPLACE TRIGGER TIU_HOT_BILLING_CALL_C_ACT_CD
  BEFORE INSERT OR UPDATE ON HOT_BILLING_CALL_C_ACT_CD FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :NEW.DATE_INSERT:=SYSDATE;
  END IF;
  :NEW.DATE_LAST_UPDATE:=SYSDATE;  
END;  

GRANT DELETE, INSERT, SELECT, UPDATE ON HOT_BILLING_CALL_C_ACT_CD TO LONTANA_ROLE;

GRANT SELECT ON HOT_BILLING_CALL_C_ACT_CD TO LONTANA_ROLE_RO;

INSERT INTO HOT_BILLING_CALL_C_ACT_CD(C_ACT_CD, C_ACT_DESC, C_ACT_DESC_RUS)
  VALUES('0', 'Both', 'Оба');
INSERT INTO HOT_BILLING_CALL_C_ACT_CD(C_ACT_CD, C_ACT_DESC, C_ACT_DESC_RUS)
  VALUES('1', 'Deposit/ incoming (MT)', 'Входящий');
INSERT INTO HOT_BILLING_CALL_C_ACT_CD(C_ACT_CD, C_ACT_DESC, C_ACT_DESC_RUS)
  VALUES('2', 'Retrieval/ outgoing (MO)', 'Исходящий');
INSERT INTO HOT_BILLING_CALL_C_ACT_CD(C_ACT_CD, C_ACT_DESC, C_ACT_DESC_RUS)
  VALUES('3', 'Activate', 'Активация');
INSERT INTO HOT_BILLING_CALL_C_ACT_CD(C_ACT_CD, C_ACT_DESC, C_ACT_DESC_RUS)
  VALUES('4', 'Deactivate', 'Деактивация');
INSERT INTO HOT_BILLING_CALL_C_ACT_CD(C_ACT_CD, C_ACT_DESC, C_ACT_DESC_RUS)
  VALUES('S', 'Scheme not found', 'Не определено');
INSERT INTO HOT_BILLING_CALL_C_ACT_CD(C_ACT_CD, C_ACT_DESC, C_ACT_DESC_RUS)
  VALUES('6', '', '');
  