CREATE TABLE HOT_BILLING_CALLS_ERROR
(
  DBF_ID      INTEGER,
  SUBSCR_NO   VARCHAR2(11 BYTE),
  CH_SEIZ_DT  VARCHAR2(16 BYTE),
  US_SEQ_N    VARCHAR2(9 BYTE),
  AT_SOC      VARCHAR2(9 BYTE),
  AT_FT_CODE  VARCHAR2(6 BYTE),
  PC_PLAN_CD  VARCHAR2(9 BYTE),
  C_ACT_CD    VARCHAR2(1 BYTE),
  AT_CHG_AMT  VARCHAR2(14 BYTE),
  CALLING_NO  VARCHAR2(21 BYTE),
  MESSAGE_TP  VARCHAR2(1 BYTE),
  SRV_FT_CD   VARCHAR2(6 BYTE),
  DURATION    VARCHAR2(8 BYTE),
  DATA_VOL    VARCHAR2(14 BYTE),
  IMEI        VARCHAR2(15 BYTE),
  CELL_ID     VARCHAR2(6 BYTE),
  PROV_ID     VARCHAR2(8 BYTE),
  DIALED_DIG  VARCHAR2(21 BYTE),
  UOM         VARCHAR2(2 BYTE),
  DISCT_SOCS  VARCHAR2(100 BYTE),
  AT_FT_DESC  VARCHAR2(100 CHAR)
)
TABLESPACE HOT_BILLING
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE HOT_BILLING_CALLS_ERROR IS 'временная таблица для загрузки(несорт.)';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.DBF_ID IS 'ID файла источника';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.SUBSCR_NO IS 'Сотовый номер';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.CH_SEIZ_DT IS 'Дата_время совершения звонка';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.US_SEQ_N IS 'Порядковый номер записи (служебное поле)';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.AT_SOC IS 'Услуга, по которой определяется тарификация';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.AT_FT_CODE IS 'Код звонка в билайне';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.PC_PLAN_CD IS 'Тарифный план';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.C_ACT_CD IS 'Тип вызова';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.AT_CHG_AMT IS 'Стоимость';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.CALLING_NO IS 'Номер инициатора звонка';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.MESSAGE_TP IS 'Тип записи: домашний или роуминг';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.SRV_FT_CD IS 'Сервис (код)';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.DURATION IS 'Длительность';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.DATA_VOL IS 'Объем (для data)';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.IMEI IS 'IMEI (код)';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.CELL_ID IS 'Идентификатор соты';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.PROV_ID IS 'Роуминг-провайдер (таблица ROAMING_PROVIDERS)';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.DIALED_DIG IS 'Набранный номер';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.UOM IS 'Единица измерения';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.DISCT_SOCS IS 'Услуга-скидка';

COMMENT ON COLUMN HOT_BILLING_CALLS_ERROR.AT_FT_DESC IS 'Тип звонка (фичер).';



CREATE INDEX I_HB_EC$C_ACT_CD ON HOT_BILLING_CALLS_ERROR
(C_ACT_CD)
LOGGING
TABLESPACE HOT_BILLING;


CREATE INDEX I_HB_EC$DBF_ID ON HOT_BILLING_CALLS_ERROR
(DBF_ID)
LOGGING
TABLESPACE HOT_BILLING;


CREATE INDEX I_HB_EC$DBF_ID$SUBSCR_NO$AT_FT ON HOT_BILLING_CALLS_ERROR
(DBF_ID, SUBSCR_NO, AT_FT_CODE)
LOGGING
TABLESPACE HOT_BILLING
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
COMPRESS 3;


CREATE INDEX I_HB_EC$MESSAGE_TP ON HOT_BILLING_CALLS_ERROR
(MESSAGE_TP)
LOGGING
TABLESPACE HOT_BILLING;


CREATE INDEX I_HB_EC$SRV_FT_CD ON HOT_BILLING_CALLS_ERROR
(SRV_FT_CD)
LOGGING
TABLESPACE HOT_BILLING
;


CREATE INDEX I_HB_EC$SUBSCR_NO ON HOT_BILLING_CALLS_ERROR
(SUBSCR_NO)
LOGGING
TABLESPACE HOT_BILLING;

CREATE INDEX I_HB_EC$UOM ON HOT_BILLING_CALLS_ERROR
(UOM)
LOGGING
TABLESPACE HOT_BILLING;


ALTER TABLE HOT_BILLING_CALLS_ERROR ADD (
  CONSTRAINT HOT_BILLING_E_C$DBF_ID$F 
  FOREIGN KEY (DBF_ID) 
  REFERENCES HOT_BILLING_FILES (HBF_ID)
  ENABLE VALIDATE);


GRANT DELETE, INSERT, SELECT, UPDATE ON HOT_BILLING_CALLS_ERROR TO LONTANA_ROLE;

GRANT SELECT ON HOT_BILLING_CALLS_ERROR TO LONTANA_ROLE_RO;
