-- Create table
CREATE TABLE IOT_MODEL_YEAR_MONTHS_PHONES(
  PHONE_NUMBER NUMBER NOT NULL,
  YEAR_MONTHS  INTEGER NOT NULL,
  DATE_INSERT  DATE NOT NULL,
  CONSTRAINT PK_CURRENT_BALANCE PRIMARY KEY (PHONE_NUMBER, YEAR_MONTHS)
  ) ORGANIZATION INDEX;
-- Add comments to the table 
COMMENT ON TABLE IOT_MODEL_YEAR_MONTHS_PHONES IS 'Возможные периоды для модуляции баланса номеров';
-- Add comments to the columns 
COMMENT ON COLUMN IOT_MODEL_YEAR_MONTHS_PHONES.PHONE_NUMBER IS 'Номер';
COMMENT ON COLUMN IOT_MODEL_YEAR_MONTHS_PHONES.YEAR_MONTHS IS 'Период';
COMMENT ON COLUMN IOT_MODEL_YEAR_MONTHS_PHONES.DATE_INSERT IS 'Дата вставки';
-- Create/Recreate primary, unique and foreign key constraints 
-- Grant/Revoke object privileges 
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON IOT_MODEL_YEAR_MONTHS_PHONES TO CORP_MOBILE_ROLE;
GRANT SELECT ON IOT_MODEL_YEAR_MONTHS_PHONES TO CORP_MOBILE_ROLE_RO;
--GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON IOT_MODEL_YEAR_MONTHS_PHONES TO SIM_TRADE_ROLE;
--GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON IOT_MODEL_YEAR_MONTHS_PHONES TO LONTANA_ROLE;
