CREATE TABLE LIST_PHONE_UNDELIVERABLE_SMS
(
  LIST_PHONE_SMS_ID  NUMBER(38) NOT NULL,
  PHONE_NUMBER       VARCHAR2(10 CHAR),
  STATUS_SMS         VARCHAR2(200 BYTE),
  SLERROR            VARCHAR2(500 BYTE),
  DATE_INSERT        DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             8K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE LIST_PHONE_UNDELIVERABLE_SMS IS 'Список номеров, по которым имеются недоставленные смс';

COMMENT ON COLUMN LIST_PHONE_UNDELIVERABLE_SMS.LIST_PHONE_SMS_ID IS 'Уникальный код';

COMMENT ON COLUMN LIST_PHONE_UNDELIVERABLE_SMS.PHONE_NUMBER IS 'Номер';

COMMENT ON COLUMN LIST_PHONE_UNDELIVERABLE_SMS.STATUS_SMS IS 'Статус смс';

COMMENT ON COLUMN LIST_PHONE_UNDELIVERABLE_SMS.SLERROR IS 'Ошибка';

COMMENT ON COLUMN LIST_PHONE_UNDELIVERABLE_SMS.DATE_INSERT IS 'Дата вставки';


CREATE UNIQUE INDEX PK_LIST_PHONE_SMS_ID ON LIST_PHONE_UNDELIVERABLE_SMS
(LIST_PHONE_SMS_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE LIST_PHONE_UNDELIVERABLE_SMS ADD (
  CONSTRAINT LIST_PHONE_UNDELIVERABLE_SMSPK
  PRIMARY KEY
  (LIST_PHONE_SMS_ID)
  USING INDEX PK_LIST_PHONE_SMS_ID);