CREATE TABLE LOG_CHECK_OPERATOR_BY_PHONE
(
  YEAR_MONTH    NUMBER(38),
  PHONE_NUMBER  VARCHAR2(10 CHAR),
  DATE_INSERT   DATE,
  TEXT_RESULT   VARCHAR2(2000 CHAR)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE LOG_CHECK_OPERATOR_BY_PHONE IS 'Логи определения оператора';

COMMENT ON COLUMN LOG_CHECK_OPERATOR_BY_PHONE.YEAR_MONTH IS 'Год / Месяц';

COMMENT ON COLUMN LOG_CHECK_OPERATOR_BY_PHONE.PHONE_NUMBER IS 'Телефон';

COMMENT ON COLUMN LOG_CHECK_OPERATOR_BY_PHONE.DATE_INSERT IS 'Дата вставки/дата проверки';

COMMENT ON COLUMN LOG_CHECK_OPERATOR_BY_PHONE.TEXT_RESULT IS 'Результат';


CREATE INDEX I_LOG_CHECK_OPERATOR_PHN ON LOG_CHECK_OPERATOR_BY_PHONE
(PHONE_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;