CREATE TABLE LOYAL_PHONE_FOR_BLOCK(
  PHONE_NUMBER VARCHAR2(10 CHAR),
  ACCOUNT_ID INTEGER,
  DATE_CHECK DATE,
  DATE_FUTURE_BLOCK DATE,
  BALANCE_BLOCK NUMBER(13, 2),
  FIO VARCHAR2(100 CHAR)
  );
  
GRANT SELECT, INSERT, DELETE, UPDATE ON LOYAL_PHONE_FOR_BLOCK TO LONTANA_ROLE;

COMMENT ON TABLE LOYAL_PHONE_FOR_BLOCK IS 'номера для лояльной блокировки';

COMMENT ON COLUMN LOYAL_PHONE_FOR_BLOCK.PHONE_NUMBER IS 'НОМЕР ТЕЛЕФОНА';

COMMENT ON COLUMN LOYAL_PHONE_FOR_BLOCK.ACCOUNT_ID IS 'ID КЛИЕНТА';

COMMENT ON COLUMN LOYAL_PHONE_FOR_BLOCK.DATE_CHECK IS 'ДАТА ВСТАВКИ';

COMMENT ON COLUMN LOYAL_PHONE_FOR_BLOCK.DATE_FUTURE_BLOCK IS 'ДАТА БУДУЩЕЙ БЛОКИРОВКИ';

COMMENT ON COLUMN LOYAL_PHONE_FOR_BLOCK.BALANCE_BLOCK IS 'БАЛАНС БЛОКИРОВКИ';

COMMENT ON COLUMN LOYAL_PHONE_FOR_BLOCK.FIO IS 'ФИО';


ALTER TABLE  LOYAL_PHONE_FOR_BLOCK ADD (BALANCE NUMBER(13, 2));
COMMENT ON COLUMN LOYAL_PHONE_FOR_BLOCK.BALANCE IS 'Баланс на момент проверки в процедуре BLOCK_LOYAL_WITH_0_BALANCE3';
  
ALTER TABLE  LOYAL_PHONE_FOR_BLOCK ADD (SMS_TEMPLATE varchar2(300 char));
COMMENT ON COLUMN LOYAL_PHONE_FOR_BLOCK.SMS_TEMPLATE IS 'Шаблон для смс при повторной отправке устанавливается в  BLOCK_CLIENT_WTH_0_BAL2';

