CREATE TABLE MN_UNLIM_VOLUME(
  PHONE_NUMBER VARCHAR(10 CHAR),
  YEAR_MONTH INTEGER,
  UPDATE_DATE DATE,
  MnUnlimD NUMBER(7,0),
  MnUnlimD_SMS number(1,0),
	MnUnlimT NUMBER(7,0),
  MnUnlimT_SMS number(1,0),
	MnUnlimO NUMBER(7,0),
  MnUnlimO_SMS number(1,0)
  );
 
COMMENT ON TABLE MN_UNLIM_VOLUME IS 'Аккумуляторы по услуге Международный безлимит';
 
COMMENT ON COLUMN MN_UNLIM_VOLUME.PHONE_NUMBER IS 'Номер телефона';  

CREATE OR REPLACE TRIGGER TIU_MN_UNLIM_VOLUME
  BEFORE INSERT OR UPDATE ON MN_UNLIM_VOLUME FOR EACH ROW
--#Version=1
BEGIN
    :NEW.UPDATE_DATE := SYSDATE;
END;

GRANT DELETE, INSERT, SELECT, UPDATE ON MN_UNLIM_VOLUME TO CORP_MOBILE_ROLE;
GRANT SELECT ON MN_UNLIM_VOLUME TO CORP_MOBILE_ROLE_RO;

CREATE INDEX I_MN_UNLIM_VOLUME_YM_PHONE ON MN_UNLIM_VOLUME(YEAR_MONTH, PHONE_NUMBER)
COMPRESS 1;