--drop table PHN_NUMBER_WITH_DAILY_ABON_LOG;
create table PHN_NUMBER_WITH_DAILY_ABON_LOG 
(
  PHONE_NUMBER  VARCHAR2 (10 Char),
  ACTION_TYPE VARCHAR2 (50 char),
  USER_CREATED VARCHAR2 (30 Char),
  DATE_CREATED date,
  USER_LAST_UPDATED VARCHAR2 (30 Char),
  DATE_LAST_UPDATED DATE
);

comment on table PHN_NUMBER_WITH_DAILY_ABON_LOG is 'Лог установки, снятия, обновления признака посуточного списания для номеров';

comment on column PHN_NUMBER_WITH_DAILY_ABON_LOG.PHONE_NUMBER is 'Номер телефона';
comment on column PHN_NUMBER_WITH_DAILY_ABON_LOG.ACTION_TYPE is 'Тип изменения посуточного списания';

CREATE OR REPLACE TRIGGER TIU_PHN_NUM_WITH_DAILY_ABON
  BEFORE INSERT OR UPDATE ON LONTANA.PHN_NUMBER_WITH_DAILY_ABON_LOG FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/