CREATE TABLE QUEUE_PHONE_REBLOCK(
  QUEUE_PHONE_REBLOCK_ID INTEGER,
  PHONE_NUMBER VARCHAR2(10 CHAR),
  DATE_ACTIV DATE,
  DATE_CREATED DATE,
  TICKED_UNLOCK_ID NVARCHAR2(15),
  DATE_UNLOCK DATE,
  TICKED_LOCK_ID NVARCHAR2(15),
  DATE_LOCK DATE, 
  ERROR_STR VARCHAR2(1000 CHAR),
  STREAM_ID INTEGER DEFAULT 0
  );

COMMENT ON TABLE QUEUE_PHONE_REBLOCK IS 'Очередь переблока номеров';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK.QUEUE_PHONE_REBLOCK_ID IS 'Идентификатор в очереди';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK.PHONE_NUMBER IS 'Телефон';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK.DATE_ACTIV IS 'Дата для переблока';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK.DATE_CREATED IS 'Дата создания';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK.TICKED_UNLOCK_ID IS 'Номер заявки на разблок';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK.DATE_UNLOCK IS 'Дата разблока';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK.TICKED_LOCK_ID IS 'Номер заявки на блок';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK.DATE_LOCK IS 'Дата блока';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK.ERROR_STR IS 'Ошибки';
COMMENT ON COLUMN QUEUE_PHONE_REBLOCK.STREAM_ID IS 'Поток обработки';

CREATE SEQUENCE S_NEW_QUEUE_PHONE_REBLOCK_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE OR REPLACE FUNCTION NEW_QUEUE_PHONE_REBLOCK_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_QUEUE_PHONE_REBLOCK_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;

CREATE OR REPLACE TRIGGER TIU_QUEUE_PHONE_REBLOCK
  BEFORE INSERT OR UPDATE ON QUEUE_PHONE_REBLOCK FOR EACH ROW 
--#Version=1
BEGIN 
  IF INSERTING THEN 
    IF NVL(:NEW.QUEUE_PHONE_REBLOCK_ID, 0) = 0 then 
      :NEW.QUEUE_PHONE_REBLOCK_ID := NEW_QUEUE_PHONE_REBLOCK_ID; 
    END IF; 
  END IF;
  :NEW.DATE_ACTIV:=NVL(:NEW.DATE_ACTIV, SYSDATE);
  :NEW.DATE_CREATED:=NVL(:NEW.DATE_CREATED, SYSDATE);
END;
/

--GRANT SELECT, INSERT, UPDATE, DELETE ON QUEUE_PHONE_REBLOCK TO CORP_MOBILE_ROLE;

--GRANT SELECT ON QUEUE_PHONE_REBLOCK TO CORP_MOBILE_ROLE_RO;

--GRANT SELECT, INSERT, UPDATE, DELETE ON QUEUE_PHONE_REBLOCK TO LONTANA_ROLE;

--GRANT SELECT, INSERT, UPDATE, DELETE ON QUEUE_PHONE_REBLOCK TO SIM_TRADE_ROLE;
