--#if not ObjectExists("S_NEW_RECEIVED_PAYMENT_TYPE_ID") then
CREATE SEQUENCE S_NEW_RECEIVED_PAYMENT_TYPE_ID;
--#end if

--#if not TableExists("RECEIVED_PAYMENT_TYPES") then
CREATE TABLE RECEIVED_PAYMENT_TYPES
(
  RECEIVED_PAYMENT_TYPE_ID   INTEGER,
  RECEIVED_PAYMENT_TYPE_NAME     VARCHAR2(50 CHAR)
);

ALTER TABLE RECEIVED_PAYMENT_TYPES
 ADD UNIQUE (RECEIVED_PAYMENT_TYPE_NAME)
  ENABLE VALIDATE;

--#end if

--#if GetVersion("NEW_RECEIVED_PAYMENT_TYPE_ID") < 1 then
CREATE OR REPLACE FUNCTION NEW_RECEIVED_PAYMENT_TYPE_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_RECEIVED_PAYMENT_TYPE_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;
/

SHOW ERRORS;
--#end if

--#if not ConstraintExists("CHK_RECEIVED_PAYMENT_TYPE_ID")
ALTER TABLE RECEIVED_PAYMENT_TYPES ADD 
CONSTRAINT CHK_RECEIVED_PAYMENT_TYPE_ID
 PRIMARY KEY (RECEIVED_PAYMENT_TYPE_ID)
 ENABLE
 VALIDATE;
--#end if

--#if GetVersion("TI_RECEIVED_PAYMENT_TYPES") < 1 then
CREATE OR REPLACE TRIGGER TIU_RECEIVED_PAYMENT_TYPES 
--#Version=1
  BEFORE INSERT  ON RECEIVED_PAYMENT_TYPES FOR EACH ROW
BEGIN 
    IF NVL(:NEW.RECEIVED_PAYMENT_TYPE_ID, 0) = 0 then 
      :NEW.RECEIVED_PAYMENT_TYPE_ID := NEW_RECEIVED_PAYMENT_TYPE_ID;
    END IF; 
END;
/
/
--#end if


--#if GetTableComment("RECEIVED_PAYMENT_TYPES") <> "Типы принятых платежей" then
COMMENT ON TABLE RECEIVED_PAYMENT_TYPES IS 'Типы принятых платежей';
--#end if

--#if GetColumnComment("RECEIVED_PAYMENT_TYPES.RECEIVED_PAYMENT_TYPE_ID") <> "Первичный ключ" then
COMMENT ON COLUMN RECEIVED_PAYMENT_TYPES.RECEIVED_PAYMENT_TYPE_ID IS 'Первичный ключ';
--#end if

--#if GetColumnComment("RECEIVED_PAYMENT_TYPES.RECEIVED_PAYMENT_TYPE_NAME") <> "Тип платежа" then
COMMENT ON COLUMN RECEIVED_PAYMENT_TYPES.RECEIVED_PAYMENT_TYPE_NAME IS 'Тип платежа';
--#end if

--#Execute MAIN_SCHEMA=IsClient("")

--#if not GrantExists("RECEIVED_PAYMENT_TYPES", "ROLE", "SELECT") then
begin EXECUTE IMMEDIATE 'GRANT ALL ON RECEIVED_PAYMENT_TYPES TO &MAIN_SCHEMA'||'_ROLE'; end;
--#end if

--#if not GrantExists("RECEIVED_PAYMENT_TYPES", "ROLE_RO", "SELECT") then
begin EXECUTE IMMEDIATE 'GRANT SELECT ON RECEIVED_PAYMENT_TYPES TO &MAIN_SCHEMA'||'_ROLE_RO'; end;
--#end if

--#if not GrantExists("NEW_RECEIVED_PAYMENT_TYPE_ID", "ROLE", "EXECUTE") then
begin EXECUTE IMMEDIATE 'GRANT EXECUTE ON NEW_RECEIVED_PAYMENT_TYPE_ID TO &MAIN_SCHEMA'||'_ROLE'; end;
--#end if

--#if not GrantExists("NEW_RECEIVED_PAYMENT_TYPE_ID", "ROLE_RO", "EXECUTE") then
begin EXECUTE IMMEDIATE 'GRANT SELECT ON RECEIVED_PAYMENT_TYPES TO &MAIN_SCHEMA'||'_ROLE_RO'; end;
--#end if
