CREATE TABLE REQ_CRM_TARIFF_ERROR_TYPE
(
  ERROR_TYPE_ID    NUMBER(38),
  ERROR_TYPE_NAME  VARCHAR2(100 CHAR),
  ERROR_TYPE_NOTE  VARCHAR2(512 CHAR)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE REQ_CRM_TARIFF_ERROR_TYPE IS 'Типы ошибок при постановке заявки на активацию номера по IVR';

COMMENT ON COLUMN REQ_CRM_TARIFF_ERROR_TYPE.ERROR_TYPE_ID IS 'Код ошибки';

COMMENT ON COLUMN REQ_CRM_TARIFF_ERROR_TYPE.ERROR_TYPE_NAME IS 'Наименование ошибки';

COMMENT ON COLUMN REQ_CRM_TARIFF_ERROR_TYPE.ERROR_TYPE_NOTE IS 'Примечание';


CREATE UNIQUE INDEX PK_REQ_CRM_TARIFF_ERR_TYPE ON REQ_CRM_TARIFF_ERROR_TYPE
(ERROR_TYPE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER TIU_REQ_CRM_TARIFF_ERROR_TYPE
  BEFORE INSERT OR UPDATE ON REQ_CRM_TARIFF_ERROR_TYPE FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.ERROR_TYPE_ID, 0) = 0 then
      :NEW.ERROR_TYPE_ID := S_REQ_CRM_TARIFF_ERROR_TYPE.NEXTVAL;
    END IF;
  END IF;
END;