ALTER TABLE RULE_FOR_CALLS_MONITOR
 DROP PRIMARY KEY CASCADE;

DROP TABLE RULE_FOR_CALLS_MONITOR CASCADE CONSTRAINTS;

CREATE TABLE RULE_FOR_CALLS_MONITOR
(
  RULE_FOR_CALLS_MONITOR_ID  INTEGER,
  TARIFF_ID                  INTEGER,
  LIMIT_OUT_CALL_PAY_ONLY_BEE NUMBER,
  LIMIT_OUT_CALL_NO_PAY_ONLY_BEE NUMBER,
  LIMIT_OUT_CALL_PAY_OTHER      NUMBER,
  LIMIT_OUT_CALL_NO_PAY_OTHER NUMBER,
  LIMIT_OUT_SMS              NUMBER,
  LIMIT_INET_TRAFFIC         NUMBER,
  TURN_ON                    NUMBER(1) DEFAULT 1,
  USER_CREATED               VARCHAR2(30 CHAR),
  DATE_CREATED               DATE,
  USER_LAST_UPDATED          VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED          DATE
)
;

COMMENT ON TABLE RULE_FOR_CALLS_MONITOR IS 'Таблица';

COMMENT ON COLUMN RULE_FOR_CALLS_MONITOR.RULE_FOR_CALLS_MONITOR_ID IS 'Первичный ключ';

COMMENT ON COLUMN RULE_FOR_CALLS_MONITOR.TARIFF_ID IS 'Ссылка на тариф';

COMMENT ON COLUMN RULE_FOR_CALLS_MONITOR.LIMIT_OUT_CALL_PAY_ONLY_BEE IS 'Лимит по платным исходящим звонкам только на Билайн, в минутах';

COMMENT ON COLUMN RULE_FOR_CALLS_MONITOR.LIMIT_OUT_CALL_NO_PAY_ONLY_BEE IS 'Лимит по бесплатным исходящим звонкам только на Билайн, в минутах';

COMMENT ON COLUMN RULE_FOR_CALLS_MONITOR.LIMIT_OUT_CALL_PAY_OTHER IS 'Лимит по платным исходящим звонкам только на других операторов, кроме Билайн, в минутах';

COMMENT ON COLUMN RULE_FOR_CALLS_MONITOR.LIMIT_OUT_CALL_NO_PAY_OTHER IS 'Лимит по бесплатным исходящим звонкам на других операторов, кроме Билайн, в минутах';

COMMENT ON COLUMN RULE_FOR_CALLS_MONITOR.LIMIT_OUT_SMS IS 'Лимит по всем исходящим СМС';

COMMENT ON COLUMN RULE_FOR_CALLS_MONITOR.LIMIT_INET_TRAFFIC IS 'Лимит по интернет трафику, мегабайт';

COMMENT ON COLUMN RULE_FOR_CALLS_MONITOR.TURN_ON IS 'Признак, учитывать ли это правило 1 - да, 0 - нет';



CREATE INDEX I_RULE4CALLS_MONITOR_TARIFF_ID ON RULE_FOR_CALLS_MONITOR
(TARIFF_ID)
;


CREATE UNIQUE INDEX PK_RULE_FOR_CALLS_MONITOR ON RULE_FOR_CALLS_MONITOR
(RULE_FOR_CALLS_MONITOR_ID)
;


CREATE OR REPLACE TRIGGER TIU_RULE_FOR_CALLS_MONITOR 
--#Version=1
  BEFORE INSERT OR UPDATE ON RULE_FOR_CALLS_MONITOR FOR EACH ROW
BEGIN 
  IF INSERTING THEN 
    IF NVL(:NEW.RULE_FOR_CALLS_MONITOR_ID, 0) = 0 then 
      :NEW.RULE_FOR_CALLS_MONITOR_ID := NEW_RULE_FOR_CALL_MONITOR_ID; 
    END IF; 
    :NEW.USER_CREATED := USER; 
    :NEW.DATE_CREATED := SYSDATE;
  END IF; 
  :NEW.USER_LAST_UPDATED := USER; 
  :NEW.DATE_LAST_UPDATED := SYSDATE; 
END;
--#end if
/

ALTER TABLE RULE_FOR_CALLS_MONITOR ADD (
  CONSTRAINT PK_RULE_FOR_CALLS_MONITOR
  PRIMARY KEY
  (RULE_FOR_CALLS_MONITOR_ID)
  USING INDEX PK_RULE_FOR_CALLS_MONITOR
  ENABLE VALIDATE);

ALTER TABLE RULE_FOR_CALLS_MONITOR ADD (
  CONSTRAINT FK_RULE_CALLS_MONITOR_TARIF_ID 
  FOREIGN KEY (TARIFF_ID) 
  REFERENCES TARIFFS (TARIFF_ID)
  ENABLE VALIDATE);

GRANT SELECT ON RULE_FOR_CALLS_MONITOR TO A_KONOVCHUK;

GRANT DELETE, INSERT, SELECT, UPDATE ON RULE_FOR_CALLS_MONITOR TO LONTANA_C20150413;

GRANT DELETE, INSERT, SELECT, UPDATE ON RULE_FOR_CALLS_MONITOR TO LONTANA_C20150413_2;

GRANT DELETE, INSERT, SELECT, UPDATE ON RULE_FOR_CALLS_MONITOR TO LONTANA_C20150506;

GRANT DELETE, INSERT, SELECT, UPDATE ON RULE_FOR_CALLS_MONITOR TO LONTANA_ROLE;

GRANT DELETE, SELECT, UPDATE ON RULE_FOR_CALLS_MONITOR TO LONTANA_ROLE_RO;


ALTER TABLE RULE_FOR_CALLS_MONITOR ADD LIMIT_OUT_CALL_PAY_ALL NUMBER;
COMMENT ON COLUMN RULE_FOR_CALLS_MONITOR.LIMIT_OUT_CALL_PAY_ALL IS 'Лимит по ВСЕМ платным исходящим звонкам (не является суммой билайн и других операторов), в минутах';

ALTER TABLE RULE_FOR_CALLS_MONITOR ADD LIMIT_OUT_CALL_NO_PAY_ALL  NUMBER;
COMMENT ON COLUMN RULE_FOR_CALLS_MONITOR.LIMIT_OUT_CALL_NO_PAY_ALL IS 'Лимит по ВСЕМ бесплатным исходящим звонкам (не является суммой билайн и других операторов), в минутах';
