Create Table SEND_SMS_NOTICE_END_MONTH_LOG
  (phone_number   VARCHAR2(50),
   ABONENT_FIO VARCHAR2(100 CHAR), 
   SEND_DATE_TIME DATE,
   ERROR_TEXT VARCHAR2(2000 CHAR)
  );
CREATE INDEX I_SEND_SMS_NOT_E_M_LOG_PH_M_E ON SEND_SMS_NOTICE_END_MONTH_LOG
(PHONE_NUMBER, SEND_DATE_TIME, ERROR_TEXT);