CREATE TABLE SEND_SMS_QUERY(
  SMS_ID INTEGER PRIMARY KEY,
  PHONE_NUMBER VARCHAR2(10 CHAR) NOT NULL,
  SEND_NAME VARCHAR2(200 CHAR),
  TEXT VARCHAR2(2000 CHAR) NOT NULL,
  NOTE VARCHAR2(200 CHAR),
  DATE_SEND DATE
  );
  
CREATE SEQUENCE S_NEW_SMS_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
CREATE OR REPLACE FUNCTION NEW_SMS_ID RETURN INTEGER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_SMS_ID.NEXTVAL
    INTO vRES
    FROM DUAL;
  RETURN vRES;
END;  


CREATE OR REPLACE TRIGGER TIU_SEND_SMS_QUERY
  BEFORE INSERT OR UPDATE ON SEND_SMS_QUERY FOR EACH ROW
--#Version=1
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.SMS_ID, 0) = 0 THEN
      :NEW.SMS_ID := NEW_SMS_ID;
    END IF;
  END IF;
  :NEW.DATE_SEND := SYSDATE;
END;
/
  
  