--ALTER TABLE SERVICES_BEELINE
-- DROP PRIMARY KEY CASCADE;
--
--DROP TABLE SERVICES_BEELINE CASCADE CONSTRAINTS;
--
-- SERVICES_BEELINE  (Table) 
--
CREATE TABLE SERVICES_BEELINE
(
  AT_FT_CODE   VARCHAR2(6 BYTE),
  AT_FT_DESC   VARCHAR2(100 CHAR),
  SRV_FT_CD    VARCHAR2(6 BYTE),
  SRV_FT_DESC  VARCHAR2(100 CHAR),
  TYPE_CALL    VARCHAR2(100 CHAR)
);

COMMENT ON TABLE SERVICES_BEELINE is 'Справочник FEATURE_CODE Билайна';
comment on column SERVICES_BEELINE.AT_FT_CODE is 'Код вызова';
comment on column SERVICES_BEELINE.AT_FT_DESC is 'Расшифровка вызова';
comment on column SERVICES_BEELINE.SRV_FT_CD is 'Код услуги';
comment on column SERVICES_BEELINE.SRV_FT_DESC is 'Описаниие услуги';
comment on column SERVICES_BEELINE.TYPE_CALL is 'Тип звонка для отчета по платному трафику';
 
--
-- SERVICES_BEELINE_PK  (Index) 
--
CREATE UNIQUE INDEX SERVICES_BEELINE_PK ON SERVICES_BEELINE (AT_FT_CODE);

CREATE INDEX I_SERVICES_BEELINE_TYPE_CALL ON SERVICES_BEELINE (TYPE_CALL);

ALTER TABLE SERVICES_BEELINE ADD (
  CONSTRAINT SERVICES_BEELINE_PK
  PRIMARY KEY
  (AT_FT_CODE)
  USING INDEX SERVICES_BEELINE_PK
  ENABLE VALIDATE);
