CREATE TABLE SIM_PHONE_BILLS(
  BILL_ID INTEGER PRIMARY KEY,
  PHONE_NUMBER VARCHAR2(10 CHAR) NOT NULL,
  BILL_SUM NUMBER(10, 2) NOT NULL,
  DATE_BEGIN DATE NOT NULL,
  DATE_END DATE NOT NULL,
  YEAR_MONTH INTEGER);

COMMENT ON COLUMN SIM_PHONE_BILLS.BILL_ID IS 'Первичный ключ'; 

COMMENT ON COLUMN SIM_PHONE_BILLS.PHONE_NUMBER IS 'Телефон'; 

COMMENT ON COLUMN SIM_PHONE_BILLS.BILL_SUM IS 'Суума счета'; 

COMMENT ON COLUMN SIM_PHONE_BILLS.DATE_BEGIN IS 'Дата начала'; 

COMMENT ON COLUMN SIM_PHONE_BILLS.DATE_END IS 'Дата конца'; 

COMMENT ON COLUMN SIM_PHONE_BILLS.YEAR_MONTH IS 'Месяц'; 

CREATE UNIQUE INDEX PK_BILL ON SIM_PHONE_BILLS
(BILL_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX SIM_BILL_MONTH_PHONE ON SIM_PHONE_BILLS
(YEAR_MONTH, PHONE_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE SEQUENCE S_NEW_BILL_ID;

CREATE OR REPLACE FUNCTION NEW_BILL_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_BILL_ID.NEXTVAL
    INTO vRES
    FROM DUAL;
  RETURN vRES;
END;

CREATE OR REPLACE TRIGGER TI_SIM_PHONE_BILLS
  BEFORE INSERT ON SIM_PHONE_BILLS FOR EACH ROW
--#Version=1
BEGIN
  IF NVL(:NEW.BILL_ID, 0) = 0 then
    :NEW.BILL_ID := NEW_BILL_ID;
  END IF;    
END;
