CREATE TABLE SIM_PHONE_OPTION_SET_HISTORY(
  OPTION_SET_HISTORY_ID INTEGER PRIMARY KEY,
  PHONE_NUMBER VARCHAR2(10 CHAR) NOT NULL,
  OPTION_NAME VARCHAR2(200 CHAR) NOT NULL,
  NOTE VARCHAR2(500 CHAR),
  DATE_OPTION_SET DATE
);

CREATE SEQUENCE S_NEW_OPTION_SET_HISTORY_ID;

CREATE OR REPLACE FUNCTION NEW_OPTION_SET_HISTORY_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_OPTION_SET_HISTORY_ID.NEXTVAL
    INTO vRES
    FROM DUAL;
  RETURN vRES;
END;

CREATE OR REPLACE TRIGGER TIU_SIM_PHONE_OPTION_SET_HIST
  BEFORE INSERT OR UPDATE ON SIM_PHONE_OPTION_SET_HISTORY FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.OPTION_SET_HISTORY_ID, 0) = 0 then
      :NEW.OPTION_SET_HISTORY_ID := NEW_OPTION_SET_HISTORY_ID;
    END IF;
    :NEW.DATE_OPTION_SET := SYSDATE;   
  END IF;
END;

ALTER TABLE SIM_PHONE_OPTION_SET_HISTORY 
  ADD TYPE_SET VARCHAR2(15 CHAR);

GRANT DELETE, INSERT, SELECT, UPDATE ON SIM_PHONE_OPTION_SET_HISTORY TO DB_LOADER;
