CREATE TABLE SIM_SETTINGS(
  SETTINGS_ID INTEGER PRIMARY KEY,
  SETTINGS_NAME VARCHAR2(50 CHAR) NOT NULL,
  LOADER_DB_CONNECTION VARCHAR2(100 CHAR) NOT NULL,
  LOADER_DB_USER_NAME VARCHAR2(100 CHAR) NOT NULL,
  LOADER_DB_PASSWORD VARCHAR2(100 CHAR) NOT NULL,
  MASTER_PASSWORD VARCHAR2(100 CHAR) NOT NULL,
  CORP_PORTAL_LOGIN VARCHAR2(100 CHAR) NOT NULL,
  CORP_PORTAL_PASSWORD VARCHAR2(100 CHAR) NOT NULL,
  SERVICE_GID_PASSWORD VARCHAR2(100 CHAR) NOT NULL
  );

ALTER TABLE SIM_SETTINGS ADD LOADER_NAME VARCHAR2(100 CHAR);

ALTER TABLE SIM_SETTINGS ADD SETTINGS_ACTIVE INTEGER;