CREATE TABLE SMS_SEND_PARAMETRS
(
  PROVIDER_ID INTEGER PRIMARY KEY NOT NULL,
  lOGIN VARCHAR2(30 CHAR),
  PASSWORD VARCHAR2(30 CHAR),
  STATUS NUMBER,
  SENDER_NAME VARCHAR2(30 CHAR),
  PROVIDER_NAME VARCHAR2(30 CHAR) NOT NULL
)