CREATE TABLE TARIFF_OPTION_GROUP(
  OPTION_GROUP_ID INTEGER PRIMARY KEY,
  OPTION_GROUP_NAME VARCHAR2(50 CHAR),
  IS_ACTIVE NUMBER(1),
  USER_CREATED VARCHAR2(30 CHAR),
  DATE_CREATED DATE,
  USER_LAST_UPDATED VARCHAR2(30 CHAR),
  DATE_LAST_UPDATED DATE
  );
  
CREATE SEQUENCE S_NEW_OPTION_GROUP_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;  
  
CREATE OR REPLACE FUNCTION NEW_OPTION_GROUP_ID RETURN NUMBER IS
--#Version=1
  vRES NUMBER;
BEGIN
  SELECT S_NEW_OPTION_GROUP_ID.NEXTVAL
  INTO vRES
  FROM DUAL;
  RETURN vRES;
END;

CREATE OR REPLACE TRIGGER TIU_TARIFF_OPTION_GROUP
  BEFORE INSERT OR UPDATE ON TARIFF_OPTION_GROUP FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.OPTION_GROUP_ID, 0) = 0 then
      :NEW.OPTION_GROUP_ID := NEW_OPTION_GROUP_ID;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
--#end if
 
GRANT SELECT, INSERT, UPDATE, DELETE ON TARIFF_OPTION_GROUP TO CORP_MOBILE_ROLE;
 
GRANT SELECT ON TARIFF_OPTION_GROUP TO CORP_MOBILE_ROLE_RO;

GRANT SELECT, INSERT, UPDATE, DELETE ON TARIFF_OPTION_GROUP TO LONTANA_ROLE;
 
GRANT SELECT ON TARIFF_OPTION_GROUP TO LONTANA_ROLE_RO;