CREATE TABLE TELETIE_CONN_TYPES
(
  CONN_TYPE_ID INTEGER,
  SITE_URL VARCHAR2(200),
  TYPE_COMMENT VARCHAR2(500)

)
TABLESPACE USERS;

COMMENT ON TABLE TELETIE_CONN_TYPES IS 'Типы соединений с сайтом TeleTie';

COMMENT ON COLUMN TELETIE_CONN_TYPES.CONN_TYPE_ID IS 'Идентификатор типа соединения';
COMMENT ON COLUMN TELETIE_CONN_TYPES.SITE_URL IS 'URL - типа соединия';
COMMENT ON COLUMN TELETIE_CONN_TYPES.TYPE_COMMENT IS 'Комментарий';

CREATE UNIQUE INDEX TELETIE_CONN_TYPES_PK ON TELETIE_CONN_TYPES
(CONN_TYPE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE TELETIE_CONN_TYPES ADD (
  CONSTRAINT TELETIE_CONN_TYPES_PK
  PRIMARY KEY
  (CONN_TYPE_ID)
  USING INDEX TELETIE_CONN_TYPES_PK
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON ACCOUNT_LOAD_LOGS TO CORP_MOBILE_ROLE;

GRANT SELECT ON ACCOUNT_LOAD_LOGS TO CORP_MOBILE_ROLE_RO;