CREATE TABLE TELETIE_CONN_LOGS
(
  CONN_LOG_ID INTEGER,
  CONN_TYPE_ID   INTEGER,
  CONN_REQUEST VARCHAR2(200),
  CONN_ANSWER VARCHAR2(200),
  CREATE_DATE_TIME        DATE DEFAULT SYSDATE,
  IS_SUCCESS            NUMBER(1),
  ERROR_TEXT            VARCHAR2(2000 CHAR)
)
TABLESPACE USERS;

COMMENT ON TABLE TELETIE_CONN_LOGS IS 'Журнал загрузок информации с/на сайт TeleTie';

COMMENT ON COLUMN TELETIE_CONN_LOGS.CONN_LOG_ID IS 'Код записи (первичный ключ)';

COMMENT ON COLUMN TELETIE_CONN_LOGS.CONN_TYPE_ID IS 'Идентификатор типа соединения';

COMMENT ON COLUMN TELETIE_CONN_LOGS.CONN_REQUEST IS 'Текст запроса';

COMMENT ON COLUMN TELETIE_CONN_LOGS.CONN_ANSWER IS 'Текст ответа';

COMMENT ON COLUMN TELETIE_CONN_LOGS.CREATE_DATE_TIME IS 'Дата и время загрузки';

COMMENT ON COLUMN TELETIE_CONN_LOGS.IS_SUCCESS IS 'Признак успешной загрузки (1 - успешно, 0 - ошибка)';

COMMENT ON COLUMN TELETIE_CONN_LOGS.ERROR_TEXT IS 'Текст ошибки, если она была';


ALTER TABLE TELETIE_CONN_LOGS ADD (
  CONSTRAINT FK_CONN_TYPE_ID
  FOREIGN KEY (CONN_TYPE_ID) 
  REFERENCES TELETIE_CONN_TYPES (CONN_TYPE_ID)
  ENABLE VALIDATE);
  
  
CREATE SEQUENCE S_TELETILE_CONN_TYPE_LOG
  START WITH 0
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER;
  
  
CREATE OR REPLACE TRIGGER TI_TELETIE_CONN_LOGS
--#Version=1
  BEFORE INSERT ON TELETIE_CONN_LOGS FOR EACH ROW
BEGIN
   :NEW.CONN_LOG_ID :=  S_TELETILE_CONN_TYPE_LOG.NEXTVAL;
END;
/  
  
  

GRANT DELETE, INSERT, SELECT, UPDATE ON ACCOUNT_LOAD_LOGS TO CORP_MOBILE_ROLE;

GRANT SELECT ON ACCOUNT_LOAD_LOGS TO CORP_MOBILE_ROLE_RO;
