--DROP TABLE CORP_MOBILE.TEST_UNLOCK_TABLE CASCADE CONSTRAINTS;

CREATE TABLE TEST_UNLOCK_TABLE
(
  PHONE_NUMBER   VARCHAR2(10 BYTE),
  DATE_CREATION  DATE,
  USER_CREATION  VARCHAR2(20 BYTE)
)

GRANT INSERT ON TEST_UNLOCK_TABLE TO CORP_MOBILE_LK;