--v1
CREATE TABLE USSD_LOG (
       id integer,
       XCPAXAction VARCHAR2(50),
       XCPAMSGID VARCHAR2(50),
       USSD_DATE DATE,
       INSERT_DATE DATE,
       MSISDN varchar2(11),
       XCPAStatus VARCHAR2(20), 
       XCPAError VARCHAR2(3),
       ERROR_TEXT VARCHAR2(2000)
);

ALTER TABLE USSD_LOG ADD (
  CONSTRAINT FK_USSD_LOG_ID
 FOREIGN KEY (ID) 
 REFERENCES USSD_TREE (ID));

CREATE OR REPLACE TRIGGER TI_USSD_LOG
  BEFORE INSERT ON USSD_LOG FOR EACH ROW
--#Version=1
BEGIN
    :NEW.INSERT_DATE := sysdate;
END;

CREATE INDEX I_USSD_LOG_MSISDN_INSERT_DATE ON USSD_LOG (MSISDN, INSERT_DATE) COMPRESS 1;

ALTER TABLE USSD_LOG ADD USSD    VARCHAR2(50);
ALTER TABLE USSD_LOG ADD TEXT_RES varchar2(200);
ALTER TABLE USSD_LOG ADD TYPE_LOG    NUMBER(1);

CREATE INDEX ussd_log_msisdn ON ussd_log
to_number(msisdn);

CREATE INDEX I_USSD_LOG_INSERT_DATE ON USSD_LOG(INSERT_DATE);

--GRANT DELETE, INSERT, SELECT, UPDATE ON USSD_CURRENT TO CORP_MOBILE_ROLE;

--GRANT SELECT ON USSD_CURRENT TO CORP_MOBILE_ROLE_RO;  
