CREATE TABLE AGENTS
(
  AGENT_ID           INTEGER PRIMARY KEY NOT NULL,
  AGENT_NAME         VARCHAR2(100 Char) NOT NULL UNIQUE,
  PAYABLE            INTEGER NOT NULL,
  PHONE_NUMBER_1    VARCHAR2(20 CHAR),
  PHONE_NUMBER_2    VARCHAR2(20 CHAR),
  PHONE_NUMBER_3    VARCHAR2(20 CHAR),
  PHONE_NUMBER_4    VARCHAR2(20 CHAR),
  EMAIL             VARCHAR2 (50 CHAR),
  ADDRESS           VARCHAR2 (250 CHAR),
  USER_CREATED       VARCHAR2(30 Char) NOT NULL,
  DATE_CREATED       DATE NOT NULL,
  USER_LAST_UPDATED  VARCHAR2(30 Char) NOT NULL,
  DATE_LAST_UPDATED  DATE NOT NULL
);

COMMENT ON TABLE AGENTS IS 'Агенты';

COMMENT ON COLUMN AGENTS.AGENT_ID IS 'Первичный ключ';

COMMENT ON COLUMN AGENTS.AGENT_NAME IS 'Наименование агента';

COMMENT ON COLUMN AGENTS.PAYABLE IS 'Признак оплаты (0 - не оплачиваем, 1 - оплачиваем)';

COMMENT ON COLUMN AGENTS.PHONE_NUMBER_1 IS 'Номер телефона агента (первый)';
COMMENT ON COLUMN AGENTS.PHONE_NUMBER_2 IS 'Номер телефона агента (второй)';
COMMENT ON COLUMN AGENTS.PHONE_NUMBER_3 IS 'Номер телефона агента (третий)';
COMMENT ON COLUMN AGENTS.PHONE_NUMBER_4 IS 'Номер телефона агента (четвертый)';

COMMENT ON COLUMN AGENTS.EMAIL IS 'E-mail адрес агента';
COMMENT ON COLUMN AGENTS.ADDRESS IS 'Адрес агента';


COMMENT ON COLUMN AGENTS.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN AGENTS.DATE_CREATED IS 'Дата/время создания записи';

COMMENT ON COLUMN AGENTS.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';

COMMENT ON COLUMN AGENTS.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';


CREATE SEQUENCE S_AGENT_ID
  START WITH 0
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON S_AGENT_ID TO BUSINESS_COMM_ROLE;

CREATE OR REPLACE TRIGGER TIUD_AGENTS
BEFORE DELETE OR INSERT OR UPDATE
ON AGENTS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.AGENT_ID, 0) = 0 THEN
      :NEW.AGENT_ID := S_AGENT_ID.NEXTVAL ;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  IF DELETING THEN
    if (:OLD.AGENT_NAME = 'Агент не задан') THEN
       RAISE_APPLICATION_ERROR(-20001,'Эту запись удалять нельзя!');
    END IF;
  END IF;

  IF INSERTING or updating THEN

   :NEW.USER_LAST_UPDATED := USER;
   :NEW.DATE_LAST_UPDATED := SYSDATE;
  
  --если PAYABLE не 1, то сбрасываем ее значение в 0
   IF NVL(:NEW.PAYABLE, 0) <> 1 THEN
     :NEW.PAYABLE := 0;
   END IF;  
  
  end if;
END;
/

GRANT DELETE, INSERT, SELECT, UPDATE ON AGENTS TO BUSINESS_COMM_ROLE;

GRANT SELECT, UPDATE ON AGENTS TO BUSINESS_COMM_ROLE_RO;

