CREATE TABLE CONTRACTS
(
  CONTRACT_ID           INTEGER                 NOT NULL,
  CONTRACT_NUM          INTEGER                 NOT NULL,
  CONTRACT_DATE         DATE                    NOT NULL,
  PHONE_NUMBER_TYPE     INTEGER                 DEFAULT 0                     NOT NULL,
  VIRTUAL_ACCOUNTS_ID   INTEGER                 NOT NULL,
  PHONE_ON_ACCOUNTS_ID  INTEGER                 NOT NULL,
  FILIAL_ID             INTEGER                 NOT NULL,
  TARIFF_ID             INTEGER                 NOT NULL,
  ABONENT_ID            INTEGER                 NOT NULL,
  SIM_NUMBER            VARCHAR2(30 BYTE),
  USER_CREATED          VARCHAR2(30 CHAR)       NOT NULL,
  DATE_CREATED          DATE                    NOT NULL,
  USER_LAST_UPDATED     VARCHAR2(30 CHAR)       NOT NULL,
  DATE_LAST_UPDATED     DATE                    NOT NULL,
  CONTRACT_DISCOUNT     NUMBER(15,6),
  DESCRIPTION           VARCHAR2(150 CHAR)
);

COMMENT ON TABLE  CONTRACTS IS 'Договора';
COMMENT ON COLUMN CONTRACTS.CONTRACT_ID IS 'Первичный ключ';
COMMENT ON COLUMN CONTRACTS.CONTRACT_NUM IS 'Номер договора';
COMMENT ON COLUMN CONTRACTS.CONTRACT_DATE IS 'Дата договора';
COMMENT ON COLUMN CONTRACTS.PHONE_NUMBER_TYPE IS 'Вид номера (1- городской, иначе федеральный)';
COMMENT ON COLUMN CONTRACTS.VIRTUAL_ACCOUNTS_ID IS 'Идентификтор группового договора VIRTUAL_ACCOUNTS.VIRTUAL_ACCOUNTS_ID';
COMMENT ON COLUMN CONTRACTS.PHONE_ON_ACCOUNTS_ID IS 'Идентификатор находжениея номера на опеределенном счете в текущий момент времени (PHONE_ON_ACCOUNTS.PHONE_ON_ACCOUNTS_ID)';
COMMENT ON COLUMN CONTRACTS.FILIAL_ID IS 'Идентификатор филиала FILIALS.FILIAL_ID';
COMMENT ON COLUMN CONTRACTS.TARIFF_ID IS 'Код тарифного плана (TARIFFS.TARIFF_ID)';
COMMENT ON COLUMN CONTRACTS.ABONENT_ID IS 'Код абонента (из справочника абонентов)';
COMMENT ON COLUMN CONTRACTS.SIM_NUMBER IS 'Номер SIM карты';
COMMENT ON COLUMN CONTRACTS.USER_CREATED IS 'Пользователь, создавший запись';
COMMENT ON COLUMN CONTRACTS.DATE_CREATED IS 'Дата/время создания записи';
COMMENT ON COLUMN CONTRACTS.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';
COMMENT ON COLUMN CONTRACTS.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';
COMMENT ON COLUMN BUSINESS_COMM.CONTRACTS.CONTRACT_DISCOUNT IS 'Скидка на абон.плату в рамках договора';
COMMENT ON COLUMN BUSINESS_COMM.CONTRACTS.DESCRIPTION IS 'Описание - вносим данные при получении данных из 1С';

CREATE UNIQUE INDEX PK_CONTRACTS ON CONTRACTS
(CONTRACT_ID);

ALTER TABLE CONTRACTS ADD (
  CONSTRAINT PK_CONTRACTS
  PRIMARY KEY
  (CONTRACT_ID)
  USING INDEX PK_CONTRACTS
  ENABLE VALIDATE);

ALTER TABLE CONTRACTS ADD (
  CONSTRAINT CONTRACTS_FK_FILIAL_ID 
  FOREIGN KEY (FILIAL_ID) 
  REFERENCES FILIALS (FILIAL_ID)
  ENABLE VALIDATE,

  CONSTRAINT CONTRACTS_FK_PHONE_ON_ACC_ID 
  FOREIGN KEY (PHONE_ON_ACCOUNTS_ID) 
  REFERENCES PHONE_ON_ACCOUNTS (PHONE_ON_ACCOUNTS_ID)
  ENABLE VALIDATE,

  CONSTRAINT CONTRACTS_FK_VIRT_ACC_ID 
  FOREIGN KEY (VIRTUAL_ACCOUNTS_ID) 
  REFERENCES VIRTUAL_ACCOUNTS (VIRTUAL_ACCOUNTS_ID)
  ENABLE VALIDATE,

  CONSTRAINT CONTRACTS_FK_ABONENT_ID 
  FOREIGN KEY (ABONENT_ID) 
  REFERENCES ABONENTS (ABONENT_ID)
  ENABLE VALIDATE,

  CONSTRAINT CONTRACTS_FK_TARIFF_ID 
  FOREIGN KEY (TARIFF_ID) 
  REFERENCES TARIFFS (TARIFF_ID)
  ENABLE VALIDATE);

CREATE SEQUENCE S_NEW_CONTRACTS
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE SEQUENCE S_CONTRACT_NUM
  START WITH 5
  MAXVALUE 9999999999999999999999999999
  MINVALUE 5
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE OR REPLACE TRIGGER TIU_CONTRACTS
  BEFORE INSERT OR UPDATE ON CONTRACTS FOR EACH ROW
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.CONTRACT_ID, 0) = 0 then
      :NEW.CONTRACT_ID :=  S_NEW_CONTRACTS.NEXTVAL;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;

GRANT DELETE, INSERT, SELECT, UPDATE ON CONTRACTS TO BUSINESS_COMM_ROLE;
GRANT SELECT ON S_NEW_CONTRACTS TO BUSINESS_COMM_ROLE;
GRANT SELECT ON S_CONTRACT_NUM TO BUSINESS_COMM_ROLE;
GRANT SELECT, UPDATE ON CONTRACTS TO BUSINESS_COMM_ROLE_RO;

ALTER TABLE CONTRACTS ADD (CONTRACT_DISCOUNT NUMBER(15,6));

COMMENT ON COLUMN CONTRACTS.CONTRACT_DISCOUNT IS 'Скидка на абон.плату в рамках договора';
CREATE OR REPLACE TRIGGER TIU_CONTRACTS
  BEFORE INSERT OR UPDATE ON CONTRACTS FOR EACH ROW
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.CONTRACT_ID, 0) = 0 then
      :NEW.CONTRACT_ID :=  S_NEW_CONTRACTS.NEXTVAL;
    END IF;
    
    IF NVL(:NEW.CONTRACT_NUM, 0) = 0 THEN
      :NEW.CONTRACT_NUM := :NEW.CONTRACT_ID; 
    END IF;
    
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_LAST_UPDATED := USER;
  :NEW.DATE_LAST_UPDATED := SYSDATE;
END;
/
CREATE INDEX I_contracts_varios_id ON contracts  
  (contract_id, tariff_id, abonent_id, filial_id, virtual_accounts_id, phone_on_accounts_id, sim_number);
  
  ALTER TABLE CONTRACTS ADD
(
  OPERATOR_PHONE_STATUSE_ID INTEGER,
  LOCAL_PHONE_STATUSE_ID INTEGER,
  SALE_COST NUMBER(17,2),
  SALE_DATE DATE,
  OPERATOR_ACCOUNT_NAME_ID INTEGER,
  PROJECT_ID INTEGER,
  SUB_ACCOUNT_ID INTEGER,
  AGENT_DATE_DISPATCH DATE,
  AGENT_ID INTEGER,
  
  CONSTRAINT FK_OPERATOR_PHONE_STATUSE_ID
  FOREIGN KEY (OPERATOR_PHONE_STATUSE_ID) 
  REFERENCES OPERATOR_PHONE_STATUSES (OPERATOR_PHONE_STATUSE_ID)
  ENABLE VALIDATE,
  
  CONSTRAINT FK_LOCAL_PHONE_STATUSE_ID
  FOREIGN KEY (LOCAL_PHONE_STATUSE_ID) 
  REFERENCES LOCAL_PHONE_STATUSES (LOCAL_PHONE_STATUSE_ID)
  ENABLE VALIDATE,
  
  CONSTRAINT FK_OPERATOR_ACCOUNT_NAME_ID
  FOREIGN KEY (OPERATOR_ACCOUNT_NAME_ID) 
  REFERENCES OPERATOR_ACCOUNT_NAMES (OPERATOR_ACCOUNT_NAME_ID)
  ENABLE VALIDATE,
  
  CONSTRAINT FK_PROJECT_ID
  FOREIGN KEY (PROJECT_ID) 
  REFERENCES PROJECTS (PROJECT_ID)
  ENABLE VALIDATE,
  
  CONSTRAINT FK_SUB_ACCOUNT_ID
  FOREIGN KEY (SUB_ACCOUNT_ID) 
  REFERENCES OPERATOR_SUB_ACCOUNTS (SUB_ACCOUNT_ID)
  ENABLE VALIDATE,
  
  CONSTRAINT FK_CONTR_AGENT_ID
  FOREIGN KEY (AGENT_ID) 
  REFERENCES AGENTS (AGENT_ID)
  ENABLE VALIDATE
   
);

COMMENT ON COLUMN CONTRACTS.OPERATOR_PHONE_STATUSE_ID IS 'Идентификатор статуса оператора (OPERATOR_PHONE_STATUSES.OPERATOR_PHONE_STATUSE_ID)';
COMMENT ON COLUMN CONTRACTS.LOCAL_PHONE_STATUSE_ID IS 'Идентификатор стутуса в тарифере (LOCAL_PHONE_STATUSES.LOCAL_PHONE_STATUSE_ID)';
COMMENT ON COLUMN CONTRACTS.SALE_COST IS 'Цена продажи';
COMMENT ON COLUMN CONTRACTS.SALE_DATE IS 'Дата продажи';
COMMENT ON COLUMN CONTRACTS.OPERATOR_ACCOUNT_NAME_ID IS 'Идентификатор названия счета у оператора связи (OPERATOR_ACCOUNT_NAMES.OPERATOR_ACCOUNT_NAME_ID)';
COMMENT ON COLUMN CONTRACTS.PROJECT_ID IS 'Идентификатор проекта (PROJECTS.PROJECT_ID)';
COMMENT ON COLUMN CONTRACTS.SUB_ACCOUNT_ID IS 'Идентификатор подбана (OPERATOR_SUB_ACCOUNTS.SUB_ACCOUNT_ID)';
COMMENT ON COLUMN CONTRACTS.AGENT_DATE_DISPATCH IS 'Дата отгрузки агенту';
COMMENT ON COLUMN CONTRACTS.AGENT_ID IS 'Идентификатор агента (AGENTS.AGENT_ID)';

-- подмена filial_id на новые 
update CONTRACTS set filial_id = decode(filial_id,21,15,41,17,filial_id) where filial_id in (21,41); 
commit;