CREATE TABLE FILES_LOAD_TYPES
(
  FILES_LOAD_TYPE_ID    NUMBER(38)             NOT NULL PRIMARY KEY,
  FILES_LOAD_TYPE_NAME  VARCHAR2(50 CHAR)
);

COMMENT ON TABLE FILES_LOAD_TYPES IS 'Типы загружаемых файлов';
COMMENT ON COLUMN FILES_LOAD_TYPES.FILES_LOAD_TYPE_ID IS 'Код загружаемого файла';

COMMENT ON COLUMN FILES_LOAD_TYPES.FILES_LOAD_TYPE_NAME IS 'Наименование типа загружаемого файла';

