CREATE TABLE GET_BLOB_FROM_URL_LOG(
  ID INTEGER PRIMARY KEY,
  LOAD_TYPE_ID INTEGER not null,
  URL VARCHAR2(200 CHAR),
  RESPONSE_BODY BLOB,
  RESPONSE_RESULT VARCHAR2(200) NOT NULL,
  ERROR_TEXT VARCHAR2(1000),
  USER_CREATED VARCHAR2(30 CHAR) NOT NULL,
  DATE_CREATED DATE NOT NULL,
  USER_UPDATED VARCHAR2(30 CHAR) NOT NULL,
  DATE_UPDATED DATE NOT NULL,
  
  CONSTRAINT GET_BLOB_URL_LOAD_TYPE_ID_FK 
  FOREIGN KEY (LOAD_TYPE_ID) 
  REFERENCES LOAD_TYPES (LOAD_TYPE_ID)
  ENABLE VALIDATE
  
  
)
TABLESPACE TS_GET_BLOB_FROM_URL_LOG
LOB (RESPONSE_BODY) STORE AS RESPONSE_BODY_SEG (TABLESPACE TS_GET_BLOB_FROM_URL_LOG);

COMMENT ON TABLE GET_BLOB_FROM_URL_LOG IS 'Лог запросов данных по ссылке';
COMMENT ON COLUMN GET_BLOB_FROM_URL_LOG.ID IS 'Идентификатор записи';
COMMENT ON COLUMN GET_BLOB_FROM_URL_LOG.LOAD_TYPE_ID IS 'Идентификаторо типа загрузки (LOAD_TYPES.LOAD_TYPE_ID)';
COMMENT ON COLUMN GET_BLOB_FROM_URL_LOG.URL IS 'Текст ссылки';
COMMENT ON COLUMN GET_BLOB_FROM_URL_LOG.RESPONSE_BODY IS 'Тело ответа';
COMMENT ON COLUMN GET_BLOB_FROM_URL_LOG.RESPONSE_RESULT IS 'Результат возвращаемого кода ответа';
COMMENT ON COLUMN GET_BLOB_FROM_URL_LOG.ERROR_TEXT IS 'Текст ошибки(если была ошибка)';
COMMENT ON COLUMN GET_BLOB_FROM_URL_LOG.USER_CREATED IS 'Создавший пользователь';
COMMENT ON COLUMN GET_BLOB_FROM_URL_LOG.DATE_CREATED IS 'Дата создания';
COMMENT ON COLUMN GET_BLOB_FROM_URL_LOG.USER_UPDATED IS 'Обновивший пользователь';
COMMENT ON COLUMN GET_BLOB_FROM_URL_LOG.DATE_UPDATED IS 'Дата обновлнеия';

CREATE SEQUENCE S_NEW_GET_BLOB_FROM_URL_LOG_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE OR REPLACE TRIGGER TIU_GET_BLOB_FROM_URL_LOG
  BEFORE INSERT OR UPDATE ON GET_BLOB_FROM_URL_LOG FOR EACH ROW
--#Version=1
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.ID, 0) = 0 then
      :NEW.ID := S_NEW_GET_BLOB_FROM_URL_LOG_ID.NEXTVAL;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
  :NEW.USER_UPDATED := USER;
  :NEW.DATE_UPDATED := SYSDATE;
END;
