CREATE TABLE MOBILE_OPERATOR_NAMES
(
  MOBILE_OPERATOR_NAME_ID  INTEGER              NOT NULL,
  MOBILE_OPERATOR_NAME     VARCHAR2(60 CHAR)    NOT NULL,
  USER_CREATED             VARCHAR2(30 CHAR)    NOT NULL,
  DATE_CREATED             DATE                 NOT NULL,
  USER_LAST_UPDATED        VARCHAR2(30 CHAR)    NOT NULL,
  DATE_LAST_UPDATED        DATE                 NOT NULL
);

COMMENT ON TABLE MOBILE_OPERATOR_NAMES IS 'Справочник оператороов сотовой связи';
COMMENT ON COLUMN MOBILE_OPERATOR_NAMES.MOBILE_OPERATOR_NAME_ID IS 'ИД записи';
COMMENT ON COLUMN MOBILE_OPERATOR_NAMES.MOBILE_OPERATOR_NAME IS 'Наименование оператора сотовой связи';
COMMENT ON COLUMN MOBILE_OPERATOR_NAMES.USER_CREATED IS 'Пользователь, создавший запись';
COMMENT ON COLUMN MOBILE_OPERATOR_NAMES.DATE_CREATED IS 'Дата/время создания записи';
COMMENT ON COLUMN MOBILE_OPERATOR_NAMES.USER_LAST_UPDATED IS 'Пользователь, редактировавший запись последним';
COMMENT ON COLUMN MOBILE_OPERATOR_NAMES.DATE_LAST_UPDATED IS 'Дата/время последней редакции записи';

CREATE UNIQUE INDEX MOBILE_OPERATOR_NAMES_PK ON MOBILE_OPERATOR_NAMES
(MOBILE_OPERATOR_NAME_ID);

ALTER TABLE MOBILE_OPERATOR_NAMES ADD (
  CONSTRAINT MOBILE_OPERATOR_NAMES_PK
  PRIMARY KEY
  (MOBILE_OPERATOR_NAME_ID)
  USING INDEX BUSINESS_COMM.MOBILE_OPERATOR_NAMES_PK
  ENABLE VALIDATE);


CREATE SEQUENCE S_NEW_MOBILE_OPERATOR_NAME_ID
START WITH 0
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;

CREATE OR REPLACE TRIGGER TIU_MOBILE_OPERATOR_NAMES
BEFORE INSERT OR UPDATE
ON MOBILE_OPERATOR_NAMES
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.MOBILE_OPERATOR_NAME_ID, 0) = 0 then
      :NEW.MOBILE_OPERATOR_NAME_ID := S_NEW_MOBILE_OPERATOR_NAME_ID.NEXTVAL;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
    :NEW.USER_LAST_UPDATED := USER;
    :NEW.DATE_LAST_UPDATED := SYSDATE;
  END IF;
  if UPDATING THEN
    :NEW.USER_LAST_UPDATED := USER;
    :NEW.DATE_LAST_UPDATED := SYSDATE;
  end if;
 
   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END;
/

GRANT DELETE, INSERT, SELECT, UPDATE ON MOBILE_OPERATOR_NAMES TO BUSINESS_COMM_ROLE;
GRANT SELECT, UPDATE ON MOBILE_OPERATOR_NAMES TO BUSINESS_COMM_ROLE_RO;

GRANT SELECT ON S_NEW_MOBILE_OPERATOR_NAME_ID TO BUSINESS_COMM_ROLE;

CREATE INDEX I_mobile_operator_names_mn ON   mobile_operator_names
   (MOBILE_OPERATOR_NAME_ID, MOBILE_OPERATOR_NAME);
   
ALTER TABLE MOBILE_OPERATOR_NAMES ADD(MOBILE_OPERATOR_NAME_FOR_URL VARCHAR2(10 CHAR));
COMMENT ON COLUMN MOBILE_OPERATOR_NAMES.MOBILE_OPERATOR_NAME_FOR_URL IS 'Название оператора для ссылки в личный кабинет';   

-- оставляем только "Неопределенный Моб. опер." и "ПАО Мегафон", удаляем избыточные данные
select * from mobile_operator_names; -- проверяем данные
delete from mobile_operator_names mon where mon.mobile_operator_name_id <> 31;
insert into mobile_operator_names mon values (41, 'ПАО МегаФон', USER, sysdate, USER, sysdate, 'Megafon');
commit;