CREATE TABLE MONTH_NAME(
  MONTHS INTEGER PRIMARY KEY,
  RUS_NAME VARCHAR2(10 CHAR),
  ENG_NAME VARCHAR2(10 CHAR)
  );
COMMENT ON TABLE  MONTH_NAME IS 'Названия месяцев';
COMMENT ON COLUMN MONTH_NAME.MONTHS IS 'Номер месяца (1- январь, 2 - феврали и т.д.)';
COMMENT ON COLUMN MONTH_NAME.RUS_NAME IS 'Название месяца рускоязычное';
COMMENT ON COLUMN MONTH_NAME.ENG_NAME IS 'Название месяца англоязычное';


GRANT SELECT ON MONTH_NAME TO BUSINESS_COMM_ROLE;

GRANT SELECT ON MONTH_NAME TO BUSINESS_COMM_ROLE_RO;

CREATE INDEX I_month_name_rus ON    month_name
 (MONTHS, RUS_NAME);