create GLOBAL TEMPORARY TABLE PARSED_FILE_TEMP
(
 
  PHONE_ID INTEGER NOT NULL,
  SERVICE_DATE_TIME DATE,
  OTHER_NUMBER VARCHAR2(20 CHAR),
  SERVICE_DIRECTION INTEGER,
  SERVICE_TYPE VARCHAR2(1 CHAR),
  DURATION_SECONDS NUMBER(15,6),
  COST NUMBER (15,6),
  ORIGIN_COST  NUMBER (15,6),
  COST_WITHOUT_VAT  NUMBER (15,6),
  IS_GROUP INTEGER,
  ROAMING_TYPE INTEGER,
  SELF_ZONE VARCHAR2(150 CHAR),
  OTHER_ZONE VARCHAR2(150 CHAR),
  ADD_INFO VARCHAR2(150 CHAR),
  ACCOUNT_NO VARCHAR2(20 CHAR),
  BILL_NUMBER VARCHAR2(20 CHAR),
  BILL_DATE DATE,
  PHONE_LIMIT  NUMBER (15,6), 
  PHONE_CHARGE_LIMIT  NUMBER (15,6),
  OPTIONS VARCHAR2(150 CHAR),
  CASCADE_NUMBER INTEGER
)
ON COMMIT PRESERVE ROWS;

COMMENT ON TABLE PARSED_FILE_TEMP IS 'Временная таблица для загрузки файлов счетов и детализаций';

COMMENT ON COLUMN PARSED_FILE_TEMP.PHONE_ID IS 'ИД номера телефона из таблицы PHONES';
COMMENT ON COLUMN PARSED_FILE_TEMP.SERVICE_DATE_TIME IS 'Дата и время вызова';
COMMENT ON COLUMN PARSED_FILE_TEMP.OTHER_NUMBER IS 'Номер собеседника';
COMMENT ON COLUMN PARSED_FILE_TEMP.SERVICE_DIRECTION IS 'Направление вызова из таблицы SERVICE_DIRECTION_TYPES';
COMMENT ON COLUMN PARSED_FILE_TEMP.SERVICE_TYPE IS 'Тип вызова из таблицы SERVICE_TYPES';
COMMENT ON COLUMN PARSED_FILE_TEMP.DURATION_SECONDS IS 'Длительность вызова';
COMMENT ON COLUMN PARSED_FILE_TEMP.COST IS 'Стоимость вызова';
COMMENT ON COLUMN PARSED_FILE_TEMP.ORIGIN_COST IS 'Стоимость вызова из исходного файла';
COMMENT ON COLUMN PARSED_FILE_TEMP.COST_WITHOUT_VAT IS 'Стоимость вызова без НДС';
COMMENT ON COLUMN PARSED_FILE_TEMP.IS_GROUP IS 'Признак группового звонка (1- групповой, 0 - не групповой)';
COMMENT ON COLUMN PARSED_FILE_TEMP.ROAMING_TYPE IS 'Тип роуминга из таблицы ROAMING_TYPES';
COMMENT ON COLUMN PARSED_FILE_TEMP.SELF_ZONE IS 'Зона нахождения номера "своего номера"(номера организации)';
COMMENT ON COLUMN PARSED_FILE_TEMP.OTHER_ZONE IS 'Зона находжения номера "чужого номера"';
COMMENT ON COLUMN PARSED_FILE_TEMP.ADD_INFO IS 'Дополнительная информация';
                
COMMENT ON COLUMN PARSED_FILE_TEMP.ACCOUNT_NO IS 'Номер лицевого счета организации';
COMMENT ON COLUMN PARSED_FILE_TEMP.BILL_NUMBER IS 'Номер выставленного счета';
COMMENT ON COLUMN PARSED_FILE_TEMP.BILL_DATE IS 'Дата высталвенного счета';
COMMENT ON COLUMN PARSED_FILE_TEMP.PHONE_LIMIT IS 'Лимит номера из счета/детализации';
COMMENT ON COLUMN PARSED_FILE_TEMP.PHONE_CHARGE_LIMIT IS 'Текущий лимит номера из счета/детализации';
COMMENT ON COLUMN PARSED_FILE_TEMP.OPTIONS IS 'Тарифные опции на номере';

COMMENT ON COLUMN PARSED_FILE_TEMP.CASCADE_NUMBER IS 'Номер каскада из таблицы CASCADE_NUMBER_TYPES';