CREATE GLOBAL TEMPORARY TABLE PAYMENTS_TEMP
(
  VIRTUAL_ACCOUNT_ID INTEGER,
  PHONE_ID INTEGER,
  INN VARCHAR2(12 CHAR),
  DATE_PAY DATE NOT NULL,
  SUM_PAY NUMBER(15,2) NOT NULL,
  DOC_NUMBER VARCHAR2(10 CHAR) NOT NULL,
  PAYMENT_PURPOSE VARCHAR2(500 CHAR),
  PAYER_BIK INTEGER
)
  ON COMMIT PRESERVE ROWS
  RESULT_CACHE (MODE DEFAULT)
  NOCACHE;
  ;

COMMENT ON TABLE PAYMENTS_TEMP IS 'Платежи(временная табличка)';
COMMENT ON COLUMN PAYMENTS_TEMP.VIRTUAL_ACCOUNT_ID IS 'Идентификтор группового договора VIRTUAL_ACCOUNTS.VIRTUAL_ACCOUNTS_ID';
COMMENT ON COLUMN PAYMENTS_TEMP.PHONE_ID IS 'Идентификатор номера телефона PHONES.PHONE_ID';
COMMENT ON COLUMN PAYMENTS_TEMP.INN IS 'ИНН плательщика';
COMMENT ON COLUMN PAYMENTS_TEMP.DATE_PAY IS 'Дата платежа';
COMMENT ON COLUMN PAYMENTS_TEMP.SUM_PAY IS 'Сумма платежа';
COMMENT ON COLUMN PAYMENTS_TEMP.DOC_NUMBER IS 'Номер платежного документа';
COMMENT ON COLUMN PAYMENTS_TEMP.PAYMENT_PURPOSE IS 'Назначение платежа';
COMMENT ON COLUMN PAYMENTS_TEMP.PAYER_BIK is 'Бик плательщика';



GRANT SELECT, INSERT ON PAYMENTS_TEMP TO BUSINESS_COMM_ROLE;

GRANT SELECT, INSERT ON PAYMENTS_TEMP TO BUSINESS_COMM_ROLE_RO;
