CREATE TABLE PERIODS
(
  YEARS       INTEGER                           NOT NULL,
  MONTHS      INTEGER                           NOT NULL,
  YEAR_MONTH  INTEGER                           NOT NULL,
  IS_ACTIVE   INTEGER
);


CREATE UNIQUE INDEX PERIODS_PK ON PERIODS
(YEAR_MONTH);


ALTER TABLE PERIODS ADD (
  CONSTRAINT PERIODS_PK
  PRIMARY KEY
  (YEAR_MONTH)
  USING INDEX PERIODS_PK
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH ON PERIODS TO BUSINESS_COMM_ROLE;
GRANT SELECT, UPDATE ON PERIODS TO BUSINESS_COMM_ROLE_RO;

COMMENT ON TABLE  PERIODS IS 'Список периодов';
COMMENT ON COLUMN PERIODS.YEARS IS 'Год';
COMMENT ON COLUMN PERIODS.MONTHS IS 'Месяц';
COMMENT ON COLUMN PERIODS.YEAR_MONTH IS 'месяц год в формате yyyymm';
COMMENT ON COLUMN PERIODS.IS_ACTIVE IS 'Признак отображения в программе (0- не отображать, 1 - отображать)';

ALTER TABLE PERIODS ADD (
  CONSTRAINT FK_MONTH_NAME_MONTHS
  FOREIGN KEY (MONTHS)
  REFERENCES MONTH_NAME (MONTHS)
  ENABLE VALIDATE);
  
CREATE INDEX I_periods_m_y ON    periods
 (YEAR_MONTH, YEARS,MONTHS);