CREATE TABLE PHONE_ON_ACCOUNTS_HIST
(
  PHONE_ON_ACCOUNTS_HIST_ID  NUMBER             NOT NULL,
  ACCOUNT_ID                 NUMBER             NOT NULL,
  PHONE_ID                   NUMBER             NOT NULL,
  PHONE_IS_ACTIVE            INTEGER            DEFAULT 1                     NOT NULL,
  USER_CREATED               VARCHAR2(30 CHAR)  NOT NULL,
  DATE_CREATED               DATE               NOT NULL,
  STATE                      VARCHAR2(30 CHAR)  NOT NULL,
  PHONE_ON_ACCOUNTS_ID       NUMBER             NOT NULL
);

COMMENT ON TABLE PHONE_ON_ACCOUNTS_HIST IS 'История соотношения телефонных номеров и лицевых счетов оператора связи';

COMMENT ON COLUMN PHONE_ON_ACCOUNTS_HIST.PHONE_ON_ACCOUNTS_HIST_ID IS 'Идентификатор записи';

COMMENT ON COLUMN PHONE_ON_ACCOUNTS_HIST.ACCOUNT_ID IS 'Иденитификатор лицевого счета ACCOUNTS.ACCOUNT_ID';

COMMENT ON COLUMN PHONE_ON_ACCOUNTS_HIST.PHONE_ID IS 'Идентификатор номера телефона PHONES.PHONE_ID';

COMMENT ON COLUMN PHONE_ON_ACCOUNTS_HIST.PHONE_IS_ACTIVE IS 'Признак активности номера(0 - блокирован; 1 - активен)';

COMMENT ON COLUMN PHONE_ON_ACCOUNTS_HIST.USER_CREATED IS 'Пользователь, создавший запись';

COMMENT ON COLUMN PHONE_ON_ACCOUNTS_HIST.DATE_CREATED IS 'Дата/время создания записи';

COMMENT ON COLUMN PHONE_ON_ACCOUNTS_HIST.STATE IS 'Состояние записи';

COMMENT ON COLUMN PHONE_ON_ACCOUNTS_HIST.PHONE_ON_ACCOUNTS_ID IS 'Идентификатор записи phone_on_accounts.phone_on_accounts_id';



CREATE UNIQUE INDEX PHONE_ON_ACCOUNTS_HIST_ID_PK ON PHONE_ON_ACCOUNTS_HIST
(PHONE_ON_ACCOUNTS_HIST_ID);

CREATE SEQUENCE S_NEW_PHONE_ON_ACCOUNTS_H_ID
START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE OR REPLACE TRIGGER TI_PHONE_ON_ACCOUNTS_HIST
BEFORE INSERT
ON PHONE_ON_ACCOUNTS_HIST
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    IF NVL(:NEW.PHONE_ON_ACCOUNTS_HIST_ID, 0) = 0 then
      :NEW.PHONE_ON_ACCOUNTS_HIST_ID := S_NEW_PHONE_ON_ACCOUNTS_H_ID.NEXTVAL;
    END IF;
    :NEW.USER_CREATED := USER;
    :NEW.DATE_CREATED := SYSDATE;
  END IF;
 
   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END;
/


ALTER TABLE PHONE_ON_ACCOUNTS_HIST ADD (
  CONSTRAINT PHONE_ON_ACCOUNTS_HIST_ID_PK
  PRIMARY KEY
  (PHONE_ON_ACCOUNTS_HIST_ID)
  USING INDEX PHONE_ON_ACCOUNTS_HIST_ID_PK
  ENABLE VALIDATE);

RANT DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH ON PHONE_ON_ACCOUNTS_HIST TO BUSINESS_COMM_ROLE;

GRANT SELECT, ON COMMIT REFRESH ON PHONE_ON_ACCOUNTS_HIST TO BUSINESS_COMM_ROLE_RO;

