CREATE TABLE SERVICE_DIRECTION_TYPES(
  SERVICE_DIRECTION_TYPE_ID Integer NOT NULL PRIMARY KEY,
  NAME Varchar2(30 ) NOT NULL
)
/

  
COMMENT ON TABLE SERVICE_DIRECTION_TYPES IS 'Типы направлений вызовов'
/
COMMENT ON COLUMN SERVICE_DIRECTION_TYPES.SERVICE_DIRECTION_TYPE_ID IS 'Идентирфикатор записи'
/
COMMENT ON COLUMN SERVICE_DIRECTION_TYPES.NAME IS 'Название типа направления вызова'
/

SET DEFINE OFF;
Insert into SERVICE_DIRECTION_TYPES (SERVICE_DIRECTION_TYPE_ID, NAME) Values (1, 'Исходящий');
Insert into SERVICE_DIRECTION_TYPES (SERVICE_DIRECTION_TYPE_ID, NAME) Values (2, 'Входящий');
Insert into SERVICE_DIRECTION_TYPES (SERVICE_DIRECTION_TYPE_ID, NAME) Values (3, 'Переадресация');
Insert into SERVICE_DIRECTION_TYPES (SERVICE_DIRECTION_TYPE_ID, NAME) Values (4, 'Неопределено');
COMMIT;
