CREATE TABLE SERVICE_TYPES(
  SERVICE_TYPE_CHAR Varchar2(1 char) NOT NULL PRIMARY KEY,
  NAME Varchar2(30 ) NOT NULL
)
/
  
COMMENT ON TABLE SERVICE_TYPES IS 'Тип вызовов'
/
COMMENT ON COLUMN SERVICE_TYPES.SERVICE_TYPE_CHAR IS 'Тип вызова'
/
COMMENT ON COLUMN SERVICE_TYPES.NAME IS 'Название типа вызова'
/