CREATE TABLE STOP_JOB_EXCEPTION
(
  NAME_STOP_JOB  VARCHAR2(30 CHAR)
);

COMMENT ON TABLE STOP_JOB_EXCEPTION IS 'Список JOB, по которым остановку с помощью STOP_JOB не делаем ';

COMMENT ON COLUMN STOP_JOB_EXCEPTION.NAME_STOP_JOB IS 'Имя job';

CREATE UNIQUE INDEX PK_NAME_STOP_JOB ON STOP_JOB_EXCEPTION
(NAME_STOP_JOB);