DROP TABLE VIRT_ACCOUNT_TEMP CASCADE CONSTRAINTS;

CREATE TABLE VIRT_ACCOUNT_TEMP
(
  INN        INTEGER,
  NAME       VARCHAR2(256 CHAR),
  EMAIL      VARCHAR2(100 CHAR),
  NUMBERS    VARCHAR2(256 CHAR),
  SERVICE01  INTEGER,
  SERVICE02  INTEGER,
  SERVICE03  INTEGER,
  SERVICE04  INTEGER,
  SERVICE05  INTEGER,
  SERVICE06  INTEGER,
  SERVICE07  INTEGER,
  SERVICE08  INTEGER,
  SERVICE09  INTEGER,
  SERVICE10  INTEGER,
  DBF_ID     NUMBER
);

COMMENT ON TABLE  VIRT_ACCOUNT_TEMP IS 'Таблица перемещаемых из dbfданных по виртуальным счетам';
COMMENT ON COLUMN VIRT_ACCOUNT_TEMP.INN IS 'ИНН';
COMMENT ON COLUMN VIRT_ACCOUNT_TEMP.EMAIL IS 'Е-mail адрес для отправки выставленных счетов';
COMMENT ON COLUMN VIRT_ACCOUNT_TEMP.NAME IS 'Название клиента(юр.лица)';
COMMENT ON COLUMN VIRT_ACCOUNT_TEMP.NUMBERS IS 'Список номеров, разделенных по символу Enter (chr(13))';
COMMENT ON COLUMN VIRT_ACCOUNT_TEMP.SERVICE01 IS 'Услуга 1 --  0 - нет услуги, 1 - есть услуга; название услуги смотри в справочнике услуг';
COMMENT ON COLUMN VIRT_ACCOUNT_TEMP.SERVICE02 IS 'Услуга 2';
COMMENT ON COLUMN VIRT_ACCOUNT_TEMP.SERVICE03 IS 'Услуга 3';
COMMENT ON COLUMN VIRT_ACCOUNT_TEMP.SERVICE04 IS 'Услуга 4';
COMMENT ON COLUMN VIRT_ACCOUNT_TEMP.SERVICE05 IS 'Услуга 5';
COMMENT ON COLUMN VIRT_ACCOUNT_TEMP.SERVICE06 IS 'Услуга 6';
COMMENT ON COLUMN VIRT_ACCOUNT_TEMP.SERVICE07 IS 'Услуга 7';
COMMENT ON COLUMN VIRT_ACCOUNT_TEMP.SERVICE08 IS 'Услуга 8';
COMMENT ON COLUMN VIRT_ACCOUNT_TEMP.SERVICE09 IS 'Услуга 9';
COMMENT ON COLUMN VIRT_ACCOUNT_TEMP.SERVICE10 IS 'Услуга 10';
COMMENT ON COLUMN VIRT_ACCOUNT_TEMP.DBF_ID IS 'Ссылка на загружаемый файл';
