CREATE OR REPLACE PROCEDURE CHECK_CREATE_USER(
  p_USER_NAME VARCHAR2, 
  p_PASSWORD VARCHAR2, 
  p_EXCEPT_USER_NAME_ID NUMBER
) IS
  vINT INTEGER;
  vSCHEMA_NAME ALL_USERS.USERNAME%TYPE;
begin
  IF TRIM(p_USER_NAME) IS NULL THEN
    RAISE_APPLICATION_ERROR(-20001, '»м€ пользовател€ Oracle должно быть заполнено.');
  END IF;
  SELECT USERNAME 
    INTO vSCHEMA_NAME 
    FROM ALL_USERS
    WHERE USER_ID = USERENV('SCHEMAID');
  SELECT COUNT(*)
  INTO vINT
  FROM USER_NAMES UN
  WHERE UN.USER_NAME = UPPER(TRIM(p_USER_NAME))
    AND UN.USER_NAME_ID <> NVL(p_EXCEPT_USER_NAME_ID, -1);
  IF vINT > 0 THEN
    RAISE_APPLICATION_ERROR(-20002, 'ѕользователь с именем '||UPPER(TRIM(p_USER_NAME))||' уже зарегистрирован. »змените им€ пользовател€.');
  END IF;
--
  SELECT COUNT(*)
  INTO vINT 
  FROM ALL_USERS AU
  WHERE AU.USERNAME = UPPER(TRIM(p_USER_NAME));
  IF vINT = 0 THEN
    IF TRIM(p_PASSWORD) IS NOT NULL THEN
      EXECUTE IMMEDIATE 'CREATE USER '||UPPER(TRIM(p_USER_NAME))|| ' IDENTIFIED BY "'||TRIM(p_PASSWORD)||'"';
    ELSE
      RAISE_APPLICATION_ERROR(-20002, 'ѕароль должен быть определен.');
    END IF;
  ELSE
  -- может быть изменение параметров пользовател€ без изменени€ парол€
    IF TRIM(p_PASSWORD) IS NOT NULL THEN
      EXECUTE IMMEDIATE 'ALTER USER '||UPPER(TRIM(p_USER_NAME))|| ' IDENTIFIED BY "'||TRIM(p_PASSWORD)||'"';
    END IF;
  END IF;
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO '||UPPER(TRIM(p_USER_NAME));
END;
/

GRANT EXECUTE ON CHECK_CREATE_USER TO BUSINESS_COMM_ROLE;

