CREATE OR REPLACE PROCEDURE DEL_DB_LOADER_BILL_LOAD_LOG 
( p_LOG_BILL_ID IN INTEGER
) IS
begin
  delete from DB_LOADER_BILLS where LOG_BILL_ID = p_LOG_BILL_ID;
  delete from DB_LOADER_BILL_LOAD_LOG where LOG_BILL_ID = p_LOG_BILL_ID;
exception
      when OTHERS then
        rollback;   
END DEL_DB_LOADER_BILL_LOAD_LOG;

/

GRANT EXECUTE ON DEL_DB_LOADER_BILL_LOAD_LOG TO BUSINESS_COMM_ROLE;
GRANT EXECUTE ON DEL_DB_LOADER_BILL_LOAD_LOG TO BUSINESS_COMM_ROLE_RO;