CREATE OR REPLACE PROCEDURE INSERT_PERIOD 
( p_YEARS IN INTEGER, 
  p_MONTHS IN INTEGER, 
  p_YEAR_MONTH IN INTEGER,
  p_IS_ACTIVE IN INTEGER
) IS
begin
  INSERT INTO PERIODS (YEARS, MONTHS, YEAR_MONTH, IS_ACTIVE) 
               VALUES (p_YEARS, p_MONTHS, p_YEAR_MONTH, p_IS_ACTIVE );
exception
      when OTHERS then
        rollback;   
END INSERT_PERIOD;
/

GRANT EXECUTE ON INSERT_PERIOD TO BUSINESS_COMM_ROLE;
GRANT EXECUTE ON INSERT_PERIOD TO BUSINESS_COMM_ROLE_