CREATE OR REPLACE procedure INSERT_T_ACCOUNTS
(
pACCOUNT_ID in integer
) 
is
begin
  insert into  T_ACCOUNTS(ACCOUNT_ID) values  (pACCOUNT_ID);
end;
/

GRANT EXECUTE ON INSERT_T_ACCOUNTS TO BUSINESS_COMM_ROLE;
GRANT EXECUTE ON INSERT_T_ACCOUNTS TO BUSINESS_COMM_ROLE_RO;