CREATE OR REPLACE PROCEDURE USER_NAMES_UPDATE(
  p_OLD_USER_NAME_ID IN NUMBER, 
  p_USER_NAME_ID IN NUMBER, 
  p_USER_FIO IN VARCHAR2, 
  p_USER_NAME IN VARCHAR2, 
  p_PASSWORD IN VARCHAR2, 
  p_CHECK_ALLOW_ACCOUNT IN NUMBER,
  p_ENCRYPT_PWD IN NUMBER
  ) IS


BEGIN
  CHECK_CREATE_USER(p_USER_NAME, p_PASSWORD, p_OLD_USER_NAME_ID); 
  --
  UPDATE USER_NAMES
  SET
    USER_NAME_ID = p_USER_NAME_ID,
    USER_FIO = p_USER_FIO,
    USER_NAME = p_USER_NAME,
    ENCRYPT_PWD = p_ENCRYPT_PWD
  WHERE
    USER_NAME_ID = p_OLD_USER_NAME_ID;  
  
  commit;

END;
/

GRANT EXECUTE ON USER_NAMES_UPDATE TO BUSINESS_COMM_ROLE;