CREATE OR REPLACE PROCEDURE USER_NAMES_DELETE (
  p_USER_NAME_ID IN NUMBER)
is
 v_USER_NAME VARCHAR2(30);

begin

  SELECT UN.USER_NAME into v_USER_NAME
  FROM USER_NAMES UN
  WHERE UN.USER_NAME_ID = p_USER_NAME_ID;
  
  begin
    EXECUTE IMMEDIATE 'DROP USER '||UPPER(TRIM(v_USER_NAME));
  exception
    when others then
    null;
  end; 
  
  DELETE FROM USER_NAMES
  WHERE
    USER_NAME_ID = p_USER_NAME_ID;

  commit;
  
end;
/
GRANT EXECUTE ON USER_NAMES_DELETE TO BUSINESS_COMM_ROLE;