CREATE OR REPLACE PROCEDURE USER_NAMES_INSERT(
  p_USER_FIO IN VARCHAR2, 
  p_USER_NAME IN VARCHAR2, 
  p_PASSWORD IN VARCHAR2, 
  p_ENCRYPT_PWD IN NUMBER
  ) IS

begin
  CHECK_CREATE_USER(p_USER_NAME, p_PASSWORD, NULL); 
  INSERT INTO USER_NAMES
    (USER_FIO, USER_NAME, ENCRYPT_PWD)
  VALUES
    (p_USER_FIO, UPPER(TRIM(p_USER_NAME)), p_ENCRYPT_PWD);
  commit;
end;
/

GRANT EXECUTE ON USER_NAMES_INSERT TO BUSINESS_COMM_ROLE;
