CREATE OR REPLACE package BEELINE_SMPP is
--
  FUNCTION GET_SMS_STATUS(
    pMESSAGE_ID IN VARCHAR2
    ) RETURN VARCHAR2;  
--
  FUNCTION SEND_SMS(
    pPHONE_NUMBER IN VARCHAR2,
    pSMS_TEXT IN VARCHAR2
    ) RETURN VARCHAR2; 
--
END;
/

CREATE OR REPLACE package body BEELINE_SMPP is   
--
  FUNCTION GET_SMS_STATUS(
    pMESSAGE_ID IN VARCHAR2
    ) RETURN VARCHAR2 IS
  ITOG VARCHAR2(2000 CHAR);
  BEGIN
    ITOG:=BEELINE_SMPP_API.GET_SMS_STATUS('217.118.84.12', 3335, '717100', 'O6q^>W)\', 2084, pMESSAGE_ID);
    RETURN ITOG;
  END;
--    
  FUNCTION SEND_SMS(
    pPHONE_NUMBER IN VARCHAR2,
    pSMS_TEXT IN VARCHAR2
    ) RETURN VARCHAR2 IS
  ITOG VARCHAR2(2000 CHAR);
  BEGIN
    --ITOG:=BEELINE_SMPP_API.SEND_SMS('217.118.84.12', 3335, '717100', 'O6q^>W)\', 2084, 'CMT', '7'||pPHONE_NUMBER, pSMS_TEXT);
    ITOG:=BEELINE_SMPP_API.SEND_SMS('217.118.84.12', 3335, '717100', 'O6q^>W)\', '&'||'GSMCorp', 'CMT', '7'||pPHONE_NUMBER, pSMS_TEXT);
    RETURN ITOG;
  END;    
--
END;
/  