CREATE SYNONYM K7_LK.BASE_STATION_ZONES FOR BEELINE_BS_ZONES;
/
GRANT SELECT ON BEELINE_BS_ZONES TO K7_LK;
/
GRANT EXECUTE ON CALC_BALANCE_ROWS2 TO K7_LK;
/
GRANT EXECUTE ON GET_BS_ZONE_NAME TO K7_LK;
/
GRANT EXECUTE ON WWW_GET_PHONE_DETAIL TO K7_LK;
/
GRANT EXECUTE ON GET_PHONE_DETAIL_FROM_CALL TO K7_LK;
/
GRANT EXECUTE ON GET_PHONE_DETAIL_FROM_CALL TO K7_LK;
/
CREATE SYNONYM K7_LK.HOT_BILLING_MONTH FOR HOT_BILLING_MONTH;
/
GRANT SELECT ON HOT_BILLING_MONTH TO K7_LK;
/
CREATE SYNONYM K7_LK.OPTIONS_ENABLED_FOR_TARIFFS FOR OPTIONS_ENABLED_FOR_TARIFFS;
/
GRANT DELETE, INSERT, SELECT ON OPTIONS_ENABLED_FOR_TARIFFS TO K7_LK;
/
CREATE SYNONYM K7_LK.PAYMENTS FOR WWW_V_PAYMENTS;
/
GRANT SELECT ON WWW_V_PAYMENTS TO K7_LK;
/
CREATE SYNONYM K7_LK.SERVICE_TYPES FOR DB_LOADER_SERVICE_TYPES;
/
GRANT SELECT ON DB_LOADER_SERVICE_TYPES TO K7_LK;
/
CREATE SYNONYM K7_LK.SERVICES FOR SERVICES;
/
GRANT SELECT ON SERVICES TO K7_LK;
/
CREATE SYNONYM K7_LK.V_PHONE_DETAIL_DB FOR V_PHONE_DETAIL_DB;
/
GRANT SELECT ON V_PHONE_DETAIL_DB TO K7_LK;
/
GRANT EXECUTE ON GET_PHONE_DETAIL_FROM_CALL TO K7_LK;
/
CREATE SYNONYM K7_LK.GET_PHONE_DETAIL_FROM_CALL FOR GET_PHONE_DETAIL_FROM_CALL;
/
GRANT execute on GET_ABONENT_BALANCE to K7_LK;
/
CREATE SYNONYM K7_LK.GET_ABONENT_BALANCE FOR GET_ABONENT_BALANCE ;
/
GRANT EXECUTE ON SET_DOP_STATUS TO K7_LK;
/
GRANT CREATE TYPE TO K7_LK;
/
GRANT EXECUTE ON CORP_MOBILE.BEELINE_REST_API_PCKG TO K7_LK;
/
GRANT EXECUTE ON CORP_MOBILE.beeline_api_pckg TO K7_LK;
/
GRANT EXECUTE ON CORP_MOBILE.TARIFF_RESTS_TABLE TO K7_LK;
/
GRANT SELECT ON TARIFF_OPTION_COSTS TO K7_LK;
/
GRANT SELECT ON TARIFF_OPTIONS TO K7_LK;
/
GRANT SELECT ON TARIFF_OPTION_NEW_COST TO K7_LK;
/
GRANT EXECUTE ON ADD_PROMISED_PAYMENT TO K7_LK;
/
GRANT SELECT ON DB_LOADER_ACCOUNT_PHONES TO K7_LK;
/
GRANT EXECUTE ON CALC_BALANCE_ROWS_TABLE to K7_LK;
/
CREATE SYNONYM K7_LK.GET_PHONE_DETAIL FOR WWW_GET_PHONE_DETAIL;
/
grant EXECUTE on WWW_GET_PHONE_DETAIL TO k7_lk;
/
GRANT EXECUTE ON GET_BS_ZONE_NAME TO K7_LK;
/
GRANT EXECUTE ON GET_BS_ZONE_NAME TO K7_LK;
/
create synonym K7_LK.GET_BS_ZONE_NAME FOR GET_BS_ZONE_NAME;
/
GRANT execute on corp_mobile.CALC_BALANCE_ROWS_NO_CREDIT to K7_LK;
/
GRANT select on corp_mobile.ABONENT_BALANCE_ROWS to K7_LK;
/